language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.1

addons:
  apt:
    packages:
    - libpcre3-dev

r_packages:
  - Rcpp
  - covr
  - digest

warnings_are_errors: true

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov(token = "26677b57-5e66-44cd-ad0c-49957456a028")'
