language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.1
      brew_packages: pkg-config pcre readline

addons:
  apt:
    packages:
    - libssl-dev
    - libcurl4-openssl-dev

r_packages:
  - Rcpp
  - covr

warnings_are_errors: false

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov(token = "26677b57-5e66-44cd-ad0c-49957456a028")'
