language: r
cache: packages

addons:
  apt:
    packages:
    - libglib2.0-dev
    - libssl-dev
    - libcurl4-openssl-dev

r_packages:
  - Rcpp
  - devtools
  - covr

warnings_are_errors: false

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov(token = "26677b57-5e66-44cd-ad0c-49957456a028")'
