---
title: "Patching the CWB"
author: "Andreas Blaette"
date: "January 7, 2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = path.expand("~/Lab/github/RcppCWB"))
```


## Required libraries

```{r}
library(git2r)
library(fs)
library(magrittr)
```


## Loading and configuring the PatchEngine

```{r load_code_and_data}
source("~/Lab/github/RcppCWB/prep/autopatch/R/PatchEngine.R")

data_files <- list.files("~/Lab/github/RcppCWB/prep/autopatch/data", full.names = TRUE)
for (fname in data_files) source(fname)
```


```{r configure_patch_engine}
P <- PatchEngine$new(
  cwb_dir_svn = "~/Lab/tmp/cwb/trunk",
  repodir = "~/Lab/github/RcppCWB",
  revision = 1069L, # see explanation below
  global_replacements = global_replacements,
  file_patches = file_patches
)
```

The CWB version initially included in the RcppCWB package was 3.4.14 (SVN revision 1069), as can be learned from the file `definitions.mk`.


## Run the PatchEngine

```{r run_patch_engine}
P$patch_all()
```