CWB: cqp/ascii-print.h File Reference
ascii-print.h File Reference
#include <stdio.h>
#include "corpmanag.h"
#include "context_descriptor.h"
#include "print-modes.h"
#include "groups.h"
Functions
const char * ascii_convert_string (const char *s)
Convert string function for ASCII mode; a NOP.
void ascii_print_aligned_line (FILE *dest, int highlighting, char *attribute_name, char *line)
Prints a line of text (which will have been previously exrtracted from a corfpus linked to the present corpus by an a-attribute) with a brief character-mode start-of-line flag ("-->$att_name: ").
void ascii_print_corpus_header (CorpusList *cl, FILE *dest)
Prints a header for a "cat" command.
void ascii_print_output (CorpusList *cl, FILE *dest, int interactive, ContextDescriptor *cd, int first, int last)
Prints out the body of a concordance, ASCII style.
void ascii_print_group (Group *group, FILE *dest)
char * get_colour_escape (char colour, int foreground)
Dummy function for when USE_TERMCAP is not defined.
char * get_typeface_escape (char typeface)
Dummy function for when USE_TERMCAP is not defined.
Variables
PrintDescriptionRecord ASCIIPrintDescriptionRecord
Print description record for ASCII print mode.
Function Documentation
ascii_convert_string()
const char* ascii_convert_string (const char * s)
Convert string function for ASCII mode; a NOP.
This is used for the "printToken" function in the relevant PDR.
Parameters
s The string to convert.
Returns
s (ie no change). 'static' return value of ascii_print_field()
ascii_print_aligned_line()
void ascii_print_aligned_line (FILE * stream, int highlighting, char * attribute_name, char * line)
Prints a line of text (which will have been previously exrtracted from a corfpus linked to the present corpus by an a-attribute) with a brief character-mode start-of-line flag ("-->$att_name: ").
Parameters
stream Destination for the output.
highlighting Boolean: if true, use colour/bold highlighting for the marker at the beginning of the flag.
attribute_name The name of the aligned corpus: printed in the leading indicator
line Character data of the line of aligned-corpus data to print. This is treated as opaque.
References get_colour_escape(), get_typeface_escape(), highlighting, and line.
Referenced by print_all_aligned_lines().
ascii_print_corpus_header()
void ascii_print_corpus_header (CorpusList * cl, FILE * dest)
Prints a header for a "cat" command.
Note that the "corpus" here refers to a subcorpus IE query result.
References CD, char_context, cl::corpus, ContextDescriptor::left_structure_name, ContextDescriptor::left_type, ContextDescriptor::left_width, cl::mother_name, TCorpus::name, cl::name, passwd, cl::query_corpus, cl::query_text, TCorpus::registry_name, ContextDescriptor::right_structure_name, ContextDescriptor::right_type, ContextDescriptor::right_width, cl::size, and word_context.
Referenced by print_corpus_info_header().
ascii_print_group()
void ascii_print_group (Group * group, FILE * dest)
References cl_broken_pipe, _grouptable::count_cells, _id_cnt_mapping::freq, Group_id2str(), _grouptable::is_grouped, _grouptable::nr_cells, pretty_print, _id_cnt_mapping::s, SEPARATOR, _grouptable::source_attribute, and _id_cnt_mapping::t.
Referenced by print_group().
ascii_print_output()
void ascii_print_output (CorpusList * cl, FILE * dest, int interactive, ContextDescriptor * cd, int first, int last)
Prints out the body of a concordance, ASCII style.
See also
print_concordance_body
References ascii_print_concordance_line(), cl_broken_pipe, GlobalPrintOptions, highlighting, PrintOptions::number_lines, ContextDescriptor::printStructureTags, cl::size, and cl::sortidx.
Referenced by print_concordance_body().
get_colour_escape()
char* get_colour_escape (char colour, int foreground)
Dummy function for when USE_TERMCAP is not defined.
Referenced by ascii_print_aligned_line(), ascii_print_field(), and main().
get_typeface_escape()
char* get_typeface_escape (char typeface)
Dummy function for when USE_TERMCAP is not defined.
Referenced by ascii_print_aligned_line(), and main().
Variable Documentation
ASCIIPrintDescriptionRecord
PrintDescriptionRecord ASCIIPrintDescriptionRecord extern
Print description record for ASCII print mode.
Referenced by ascii_print_concordance_line(), and print_all_aligned_lines().