CWB: cqp/ascii-print.c File Reference
ascii-print.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/time.h>
#include <time.h>
#include <pwd.h>
#include "../cl/cl.h"
#include "ascii-print.h"
#include "cqp.h"
#include "output.h"
#include "print_align.h"
#include "options.h"
#include "corpmanag.h"
#include "concordance.h"
#include "attlist.h"
#include "print-modes.h"
Functions
static char * ascii_print_field (FieldType field, int at_end)
Print the string required before or after the representation of a token that is at one of the anchor points (match, matchend, target, keyword).
char * get_colour_escape (char colour, int foreground)
Dummy function for when USE_TERMCAP is not defined.
char * get_typeface_escape (char typeface)
Dummy function for when USE_TERMCAP is not defined.
void get_screen_escapes (void)
Dummy function for when USE_TERMCAP is not defined.
const char * ascii_convert_string (const char *s)
Convert string function for ASCII mode; a NOP.
void ascii_print_aligned_line (FILE *stream, int highlighting, char *attribute_name, char *line)
Prints a line of text (which will have been previously exrtracted from a corfpus linked to the present corpus by an a-attribute) with a brief character-mode start-of-line flag ("-->$att_name: ").
static void ascii_print_concordance_line (FILE *dest, CorpusList *cl, int range_ix, int apply_highlighting, AttributeList *strucs)
Prints a concordance line in ascii mode.
void ascii_print_corpus_header (CorpusList *cl, FILE *dest)
Prints a header for a "cat" command.
void ascii_print_output (CorpusList *cl, FILE *dest, int interactive, ContextDescriptor *cd, int first, int last)
Prints out the body of a concordance, ASCII style.
void ascii_print_group (Group *group, FILE *dest)
Variables
PrintDescriptionRecord ASCIIPrintDescriptionRecord
Print description record for ASCII print mode.
PrintDescriptionRecord ASCIIHighlightedPrintDescriptionRecord
Print description record for Highlighted-ASCII print mode.
static int escapes_initialized = 0
Boolean: have escapes been initialised?
static char * sc_s_in
Enter standout (highlighted) mode.
static char * sc_s_out
Exit standout mode.
static char * sc_u_in
Enter underline mode.
static char * sc_u_out
Exit underline mode.
static char * sc_b_in
Enter bold mode.
static char * sc_b_out
Exit bold mode (doesn't exist; this code turns off all attributes)
static char * sc_bl_in
Enter blink mode.
static char * sc_bl_out
Exit blink mode.
static char * sc_all_out
Turn off all display attributes.
int sc_s_mode = 0
Boolean: following tokens will be shown in standout mode.
int sc_u_mode = 0
Boolean: following tokens will be shown in underline mode.
int sc_b_mode = 0
Boolean: following tokens will be shown in bold mode.
char sc_before_token [256]
Function Documentation
ascii_convert_string()
const char* ascii_convert_string (const char * s)
Convert string function for ASCII mode; a NOP.
This is used for the "printToken" function in the relevant PDR.
Parameters
s The string to convert.
Returns
s (ie no change). 'static' return value of ascii_print_field()
ascii_print_aligned_line()
void ascii_print_aligned_line (FILE * stream, int highlighting, char * attribute_name, char * line)
Prints a line of text (which will have been previously exrtracted from a corfpus linked to the present corpus by an a-attribute) with a brief character-mode start-of-line flag ("-->$att_name: ").
Parameters
stream Destination for the output.
highlighting Boolean: if true, use colour/bold highlighting for the marker at the beginning of the flag.
attribute_name The name of the aligned corpus: printed in the leading indicator
line Character data of the line of aligned-corpus data to print. This is treated as opaque.
References get_colour_escape(), get_typeface_escape(), highlighting, and line.
Referenced by print_all_aligned_lines().
ascii_print_concordance_line()
static void ascii_print_concordance_line (FILE * dest, CorpusList * cl, int range_ix, int apply_highlighting, AttributeList * strucs) static
Prints a concordance line in ascii mode.
References PrintDescriptionRecord::AfterLine, ContextDescriptor::alignedCorpora, ASCIIHighlightedPrintDescriptionRecord, ASCIIPrintDescriptionRecord, CD, cl_free, compose_kwic_line(), cl::corpus, cqpmessage(), Range::end, _ConcLineField::end_position, Error, escapes_initialized, get_screen_escapes(), KeywordField, cl::keywords, left_delimiter, MatchEndField, MatchField, NoField, print_all_aligned_lines(), cl::range, right_delimiter, sc_b_mode, sc_s_mode, sc_u_mode, cl::size, Range::start, _ConcLineField::start_position, TargetField, cl::targets, and _ConcLineField::type.
Referenced by ascii_print_output().
ascii_print_corpus_header()
void ascii_print_corpus_header (CorpusList * cl, FILE * dest)
Prints a header for a "cat" command.
Note that the "corpus" here refers to a subcorpus IE query result.
References CD, char_context, cl::corpus, ContextDescriptor::left_structure_name, ContextDescriptor::left_type, ContextDescriptor::left_width, cl::mother_name, TCorpus::name, cl::name, passwd, cl::query_corpus, cl::query_text, TCorpus::registry_name, ContextDescriptor::right_structure_name, ContextDescriptor::right_type, ContextDescriptor::right_width, cl::size, and word_context.
Referenced by print_corpus_info_header().
ascii_print_field()
static char * ascii_print_field (FieldType field, int at_end) static
Print the string required before or after the representation of a token that is at one of the anchor points (match, matchend, target, keyword).
References get_colour_escape(), KeywordField, MatchField, NoField, sc_all_out, sc_b_in, sc_b_mode, sc_before_token, sc_s_in, sc_s_mode, sc_u_in, sc_u_mode, show_targets, and TargetField.
ascii_print_group()
void ascii_print_group (Group * group, FILE * dest)
References cl_broken_pipe, _grouptable::count_cells, _id_cnt_mapping::freq, Group_id2str(), _grouptable::is_grouped, _grouptable::nr_cells, pretty_print, _id_cnt_mapping::s, SEPARATOR, _grouptable::source_attribute, and _id_cnt_mapping::t.
Referenced by print_group().
ascii_print_output()
void ascii_print_output (CorpusList * cl, FILE * dest, int interactive, ContextDescriptor * cd, int first, int last)
Prints out the body of a concordance, ASCII style.
See also
print_concordance_body
References ascii_print_concordance_line(), cl_broken_pipe, GlobalPrintOptions, highlighting, PrintOptions::number_lines, ContextDescriptor::printStructureTags, cl::size, and cl::sortidx.
Referenced by print_concordance_body().
get_colour_escape()
char* get_colour_escape (char colour, int foreground)
Dummy function for when USE_TERMCAP is not defined.
Referenced by ascii_print_aligned_line(), ascii_print_field(), and main().
get_screen_escapes()
void get_screen_escapes (void)
Dummy function for when USE_TERMCAP is not defined.
References escapes_initialized, sc_all_out, sc_b_in, sc_b_out, sc_bl_in, sc_bl_out, sc_s_in, sc_s_out, sc_u_in, and sc_u_out.
Referenced by ascii_print_concordance_line().
get_typeface_escape()
char* get_typeface_escape (char typeface)
Dummy function for when USE_TERMCAP is not defined.
Referenced by ascii_print_aligned_line(), and main().
Variable Documentation
ASCIIHighlightedPrintDescriptionRecord
PrintDescriptionRecord ASCIIHighlightedPrintDescriptionRecord
Initial value:
= {
  "%9d: ",
  NULL,
  " ",
  ": ",
  "<",
  ">",
  " ",
  "</",
  ">",
  NULL,
  " ",
  "/",
  NULL,
  NULL,
  NULL,
  NULL,
  "\n",
  NULL,
  NULL,
  ascii_convert_string,
  ascii_print_field
}
Print description record for Highlighted-ASCII print mode.
Referenced by ascii_print_concordance_line().
ASCIIPrintDescriptionRecord
PrintDescriptionRecord ASCIIPrintDescriptionRecord
Initial value:
= {
  "%9d: ",
  NULL,
  " ",
  ": ",
  "<",
  ">",
  " ",
  "</",
  ">",
  NULL,
  " ",
  "/",
  NULL,
  NULL,
  NULL,
  NULL,
  "\n",
  NULL,
  NULL,
  ascii_convert_string,
  NULL
}
Print description record for ASCII print mode.
Referenced by ascii_print_concordance_line(), and print_all_aligned_lines().
escapes_initialized
int escapes_initialized = 0 static
Boolean: have escapes been initialised?
Referenced by ascii_print_concordance_line(), and get_screen_escapes().
sc_all_out
char * sc_all_out static
Turn off all display attributes.
Referenced by ascii_print_field(), and get_screen_escapes().
sc_b_in
char * sc_b_in static
Enter bold mode.
Referenced by ascii_print_field(), and get_screen_escapes().
sc_b_mode
int sc_b_mode = 0
Boolean: following tokens will be shown in bold mode.
Referenced by ascii_print_concordance_line(), and ascii_print_field().
sc_b_out
char * sc_b_out static
Exit bold mode (doesn't exist; this code turns off all attributes)
Referenced by get_screen_escapes().
sc_before_token
char sc_before_token[256]
Referenced by ascii_print_field().
sc_bl_in
char * sc_bl_in static
Enter blink mode.
Referenced by get_screen_escapes().
sc_bl_out
char * sc_bl_out static
Exit blink mode.
Referenced by get_screen_escapes().
sc_s_in
char* sc_s_in static
Enter standout (highlighted) mode.
Referenced by ascii_print_field(), and get_screen_escapes().
sc_s_mode
int sc_s_mode = 0
Boolean: following tokens will be shown in standout mode.
Referenced by ascii_print_concordance_line(), and ascii_print_field().
sc_s_out
char * sc_s_out static
Exit standout mode.
Referenced by get_screen_escapes().
sc_u_in
char * sc_u_in static
Enter underline mode.
Referenced by ascii_print_field(), and get_screen_escapes().
sc_u_mode
int sc_u_mode = 0
Boolean: following tokens will be shown in underline mode.
Referenced by ascii_print_concordance_line(), and ascii_print_field().
sc_u_out
char * sc_u_out static
Exit underline mode.
Referenced by get_screen_escapes().