CWB: cqp/attlist.c File Reference
attlist.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../cl/cl.h"
#include "attlist.h"
Functions
AttributeList * NewAttributeList (int element_type)
Creates a new AttributeList.
int DestroyAttributeList (AttributeList **list)
Deletes an AttributeList object.
AttributeInfo * AddNameToAL (AttributeList *list, char *name, int init_show_status, int position)
Adds a new AttributeInfo to an AttributeList object.
int RemoveNameFromAL (AttributeList *list, char *name)
Deletes an AttributeInfo from the AttributeList.
int NrOfElementsWithStatusAL (AttributeList *list, int shown)
Gets the number of entries in an AttributeList which have their "show" status switched on/off.
AttributeInfo * FindInAL (AttributeList *list, char *name)
Finds an entry in an AttributeList.
AttributeList * RecomputeAL (AttributeList *list, Corpus *corpus, int init_status)
Goes through an AttributeList, deletes entries for attributes that don't exist, and adds entries for those that do.
int VerifyList (AttributeList *list, Corpus *corpus, int remove_illegal_entries)
Verifies an AttributeList.
Function Documentation
AddNameToAL()
AttributeInfo* AddNameToAL (AttributeList * list, char * name, int init_show_status, int position)
Adds a new AttributeInfo to an AttributeList object.
Parameters
list The list to add to.
name The name of the Attribute that this AttributeInfo refers to. If the list already contains an att with this name, nothing happens.
init_show_status Initial setting for the status member of the new AttributeInfo (true implies "show +the_att", false implies "show -the_att")
position If this is 1, the new AttributeInfo is added at the beginning of the list. If it is 0, it is added at the end of the list. Otherwise, this specifies a particular insertion position (the given number of steps down the linked list).
Returns
A pointer to the new AttributeInfo, or NULL for error.
References _attrbuf::attribute, cl_malloc(), cl_strdup(), FindInAL(), _attlist::list, _attlist::list_valid, _attrbuf::name, _attrbuf::next, _attrbuf::prev, and _attrbuf::status.
Referenced by compose_kwic_line(), ComputePrintStructures(), and RecomputeAL().
DestroyAttributeList()
int DestroyAttributeList (AttributeList ** list)
Deletes an AttributeList object.
Parameters
list Address of the pointer to the list to delete. NULL-safe.
Returns
Always 1.
References cl_free, _attrbuf::name, and _attrbuf::next.
Referenced by compose_kwic_line(), ComputePrintStructures(), execute_side_effects(), RecomputeAL(), set_current_corpus(), and verify_context_descriptor().
FindInAL()
AttributeInfo* FindInAL (AttributeList * list, char * name)
Finds an entry in an AttributeList.
Parameters
list The list to search.
name The name of the element to search for.
Returns
Pointer to the AttributeInfo with the matching name, or NULL if the name was not found.
References cl_streq, _attlist::list, _attrbuf::name, and _attrbuf::next.
Referenced by AddNameToAL(), compose_kwic_line(), do_attribute_show(), print_all_aligned_lines(), RecomputeAL(), and set_current_corpus().
NewAttributeList()
AttributeList* NewAttributeList (int element_type)
Creates a new AttributeList.
Parameters
element_type What type of attribute is this? ATT_POS, ATT_STRUC, etc.
Returns
Pointer to the new AttributeList object.
References cl_malloc(), _attlist::element_type, _attlist::list, and _attlist::list_valid.
Referenced by compose_kwic_line(), ComputePrintStructures(), RecomputeAL(), and update_context_descriptor().
NrOfElementsWithStatusAL()
int NrOfElementsWithStatusAL (AttributeList * list, int shown)
Gets the number of entries in an AttributeList which have their "show" status switched on/off.
Parameters
list The list to size up.
shown If true, counts "show +" elements. If false, counts "show -" elements.
Returns
The number of elements where status == shown.
References _attlist::list, _attrbuf::next, and _attrbuf::status.
Referenced by compose_kwic_line().
RecomputeAL()
AttributeList* RecomputeAL (AttributeList * list, Corpus * corpus, int init_status)
Goes through an AttributeList, deletes entries for attributes that don't exist, and adds entries for those that do.
Note that all AttributeInfo entries are linked to the actual Attribute objects by this function.
As of CQP v3.4.18, this function re-creates the AttributeList from scratch and copies the current display status of attributes with the same name from the previous list. In this way it ensures that attributes are always displayed in the same order in which they are listed in the registry file.
Parameters
list The AttributeList to recompute.
corpus The corpus in which these attributes are found.
init_status Not currently used.
Returns
The updated AttributeList (which will have been re-allocated)
References AddNameToAL(), _Attribute::any, _attrbuf::attribute, TCorpus::attributes, corpus, DestroyAttributeList(), _attlist::element_type, FindInAL(), _attlist::list_valid, _attrbuf::name, NewAttributeList(), _attrbuf::status, and _Attribute::type.
Referenced by update_context_descriptor().
RemoveNameFromAL()
int RemoveNameFromAL (AttributeList * list, char * name)
Deletes an AttributeInfo from the AttributeList.
Parameters
list The list from which to delete.
name The name of the AttributeInfo to delete.
Returns
True if the attribute info was found and deleted; otherwise false.
References cl_free, cl_streq, _attlist::list, _attrbuf::name, _attrbuf::next, and _attrbuf::prev.
Referenced by update_context_descriptor().
VerifyList()
int VerifyList (AttributeList * list, Corpus * corpus, int remove_illegal_entries)
Verifies an AttributeList.
Each AttributeInfo entry on the list is linked to the actual Attribute object by this function.
If the relevant Attribute cannot be found, the entry is deleted iff remove_illegal_entries.
Parameters
list The list to verify.
corpus The corpus for which this list should be valid.
remove_illegal_entries Boolean: see function description.
Returns
Boolean: true if the list entries are all now vlaid, otherwise false. This result value is also stored in the AtttributeList's "list_valid" member.
References _attrbuf::attribute, cl_free, cl_new_attribute(), corpus, _attlist::element_type, _attlist::list, _attlist::list_valid, TCorpus::name, _attrbuf::next, and _attrbuf::prev.
Referenced by compose_kwic_line(), ComputePrintStructures(), and verify_context_descriptor().