CWB: CQi/auth.h File Reference
auth.h File Reference
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
Functions
void add_user_to_list (char *user, char *passwd)
void add_host_to_list (char *ipaddr)
void add_hosts_in_subnet_to_list (char *ipsubnet)
void add_grant_to_last_user (char *corpus)
int check_host (struct in_addr host)
int authenticate_user (char *user, char *passwd)
returns true if (user, passwd) pair is in list
int check_grant (char *user, char *corpus)
returns true if user may access the specified corpus
void show_grants (void)
prints all hosts/users/grants to stdout for debugging purposes
Function Documentation
add_grant_to_last_user()
void add_grant_to_last_user (char * corpus)
References authorized_users, cl_malloc(), cl_strdup(), Grant::corpus, corpus, UserEntry::grants, and Grant::next.
add_host_to_list()
void add_host_to_list (char * ipaddr)
References HostEntry::accept_any, HostEntry::address, authorized_hosts, cl_free, cl_malloc(), cqpmessage(), Error, and HostEntry::next.
Referenced by add_hosts_in_subnet_to_list(), and main().
add_hosts_in_subnet_to_list()
void add_hosts_in_subnet_to_list (char * ipsubnet)
References add_host_to_list(), cl_free, cl_malloc(), cqpmessage(), and Error.
add_user_to_list()
void add_user_to_list (char * user, char * passwd)
References authorized_users, cl_malloc(), cl_strdup(), cqpmessage(), Error, find_user(), UserEntry::grants, UserEntry::name, UserEntry::next, UserEntry::passwd, passwd, and user.
Referenced by main().
authenticate_user()
int authenticate_user (char * user, char * passwd)
returns true if (user, passwd) pair is in list
References cl_streq, find_user(), passwd, and user.
Referenced by main().
check_grant()
int check_grant (char * user, char * corpus)
returns true if user may access the specified corpus
References cl_streq, Grant::corpus, corpus, find_user(), Grant::next, and user.
Referenced by main().
check_host()
int check_host (struct in_addr host)
References HostEntry::accept_any, HostEntry::address, authorized_hosts, and HostEntry::next.
Referenced by accept_connection().
show_grants()
void show_grants (void)
prints all hosts/users/grants to stdout for debugging purposes
References HostEntry::address, authorized_hosts, authorized_users, Grant::corpus, Grant::next, HostEntry::next, and user.