CWB: CQi/auth.c File Reference
auth.c File Reference
#include <arpa/inet.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "auth.h"
#include "../cl/cl.h"
Data Structures
struct Grant
Internal data structure: name of a corpus to which access is granted.
struct UserEntry
Internal data structure: a username, the user's password, and the top of a linked list of Grants.
struct HostEntry
Internal data structure: member of list of IP addresses from which messages are accepted.
Typedefs
typedef struct Grant Grant
Internal data structure: name of a corpus to which access is granted.
typedef struct UserEntry UserEntry
Internal data structure: a username, the user's password, and the top of a linked list of Grants.
typedef struct HostEntry HostEntry
Internal data structure: member of list of IP addresses from which messages are accepted.
Functions
UserEntry * find_user (char *username)
Finds an entry the user with the specified username on the global user list.
void add_user_to_list (char *user, char *passwd)
void add_grant_to_last_user (char *corpus)
void add_host_to_list (char *ipaddr)
void add_hosts_in_subnet_to_list (char *ipsubnet)
int check_host (struct in_addr host_addr)
int authenticate_user (char *username, char *passwd)
returns true if (user, passwd) pair is in list
int check_grant (char *username, char *corpus)
returns true if user may access the specified corpus
void show_grants (void)
prints all hosts/users/grants to stdout for debugging purposes
Variables
UserEntry * authorized_users = NULL
non-exported global variable for cqpserver's user list
HostEntry * authorized_hosts = NULL
non-exported global variable for cqpserver's host list
Typedef Documentation
Grant
typedef struct Grant Grant
Internal data structure: name of a corpus to which access is granted.
HostEntry
typedef struct HostEntry HostEntry
Internal data structure: member of list of IP addresses from which messages are accepted.
UserEntry
typedef struct UserEntry UserEntry
Internal data structure: a username, the user's password, and the top of a linked list of Grants.
Function Documentation
add_grant_to_last_user()
void add_grant_to_last_user (char * corpus)
References authorized_users, cl_malloc(), cl_strdup(), Grant::corpus, corpus, UserEntry::grants, and Grant::next.
add_host_to_list()
void add_host_to_list (char * ipaddr)
References HostEntry::accept_any, HostEntry::address, authorized_hosts, cl_free, cl_malloc(), and HostEntry::next.
Referenced by add_hosts_in_subnet_to_list(), and main().
add_hosts_in_subnet_to_list()
void add_hosts_in_subnet_to_list (char * ipsubnet)
References add_host_to_list(), cl_free, and cl_malloc().
add_user_to_list()
void add_user_to_list (char * user, char * passwd)
References authorized_users, cl_malloc(), cl_strdup(), find_user(), UserEntry::grants, UserEntry::name, UserEntry::next, UserEntry::passwd, passwd, and user.
Referenced by main().
authenticate_user()
int authenticate_user (char * username, char * passwd)
returns true if (user, passwd) pair is in list
References cl_streq, find_user(), passwd, and user.
Referenced by main().
check_grant()
int check_grant (char * username, char * corpus)
returns true if user may access the specified corpus
References cl_streq, Grant::corpus, corpus, find_user(), Grant::next, and user.
Referenced by main().
check_host()
int check_host (struct in_addr host_addr)
References HostEntry::accept_any, HostEntry::address, authorized_hosts, and HostEntry::next.
Referenced by accept_connection().
find_user()
UserEntry* find_user (char * username)
Finds an entry the user with the specified username on the global user list.
See also
authorized_users
References authorized_users, cl_streq, and user.
Referenced by add_user_to_list(), authenticate_user(), and check_grant().
show_grants()
void show_grants (void)
prints all hosts/users/grants to stdout for debugging purposes
References HostEntry::address, authorized_hosts, authorized_users, Grant::corpus, Grant::next, HostEntry::next, and user.
Variable Documentation
authorized_hosts
HostEntry* authorized_hosts = NULL
non-exported global variable for cqpserver's host list
Referenced by add_host_to_list(), check_host(), and show_grants().
authorized_users
UserEntry* authorized_users = NULL
non-exported global variable for cqpserver's user list
Referenced by add_grant_to_last_user(), add_user_to_list(), find_user(), and show_grants().