CWB: cl/bitfields.h File Reference
bitfields.h File Reference
#include "globals.h"
#include <limits.h>
Data Structures
struct BFBuf
Underlying storage of Bitfield object.
Typedefs
typedef unsigned char BFBaseType
typedef struct BFBuf BFBuf
Underlying storage of Bitfield object.
typedef struct BFBuf * Bitfield
The Bitfield object.
Functions
Bitfield create_bitfield (int nr_of_elements)
Create a new Bitfield object.
Bitfield copy_bitfield (Bitfield source)
Copies a Bitfield.
void destroy_bitfield (Bitfield *bptr)
Deletes a bitfield object.
int set_bit (Bitfield bitfield, int element)
Sets a bit in a Bitfield to 1.
int clear_bit (Bitfield bitfield, int element)
Sets a bit in a Bitfield to 0 (clears it).
int clear_all_bits (Bitfield bitfield)
Clears an entire Bitfield (ie sets all bits to 0).
int set_all_bits (Bitfield bitfield)
Sets an entire Bitfield (ie sets all bits to 1, all bytes to 0xff).
int get_bit (Bitfield bitfield, int element)
Gets the value of the bit at the specified offset in the Bitfield.
int toggle_bit (Bitfield bitfield, int element)
Switches the value of the specified bit in a Bitfield.
int nr_bits_set (Bitfield bitfield)
Gets the number of bits set to 1 in the given Bitfield.
int bf_equal (Bitfield bf1, Bitfield bf2)
Checks two Bitfield objects for equality of all bits.
int bf_compare (Bitfield bf1, Bitfield bf2)
Compares two Bitfield objects.
Typedef Documentation
BFBaseType
typedef unsigned char BFBaseType
BFBuf
typedef struct BFBuf BFBuf
Underlying storage of Bitfield object.
Bitfield
typedef struct BFBuf* Bitfield
The Bitfield object.
Function Documentation
bf_compare()
int bf_compare (Bitfield bf1, Bitfield bf2)
Compares two Bitfield objects.
Comparison is done from the start of the bitfield onwards. The Bitfields compared must have the same number of elements!
Returns
0 if the two are the same; 1 if bf1 is less; -1 if bf2 is less.
References BaseTypeBits, BaseTypeSize, BFBuf::bytes, BFBuf::elements, and BFBuf::field.
bf_equal()
int bf_equal (Bitfield bf1, Bitfield bf2)
Checks two Bitfield objects for equality of all bits.
The Bitfields compared must have the same number of elements!
Returns
Boolean: false if the two bitfields are different, true if they are the same.
References BaseTypeBits, BaseTypeSize, BFBuf::bytes, BFBuf::elements, and BFBuf::field.
clear_all_bits()
int clear_all_bits (Bitfield bitfield)
Clears an entire Bitfield (ie sets all bits to 0).
Returns
False if passed a NULL pointer; otherwise true.
References BFBuf::bytes, BFBuf::field, and BFBuf::nr_bits_set.
Referenced by match_first_pattern().
clear_bit()
int clear_bit (Bitfield bitfield, int element)
Sets a bit in a Bitfield to 0 (clears it).
The number of bits set is decreased by 1 iff the clearing of the specified bit has resulted in a change in the bitfield.
If the offset specified does not exist within this Bitfield, the function returns false (plus an error message is printed). Otherwise it returns true.
Parameters
bitfield The Bitfield object to work with.
element The offset of the bit to set.
Returns
Boolean (see description).
References BaseTypeBits, BFBuf::field, and BFBuf::nr_bits_set.
copy_bitfield()
Bitfield copy_bitfield (Bitfield source)
Copies a Bitfield.
Creates a new bitfield object whihc is an exact duplicate of the source Bitfield.
Parameters
source The Bitfield to copy
Returns
The duplicate Bitfield (or NULL if it was passed NULL).
References BFBuf::bytes, create_bitfield(), BFBuf::elements, BFBuf::field, and BFBuf::nr_bits_set.
create_bitfield()
Bitfield create_bitfield (int nr_of_elements)
Create a new Bitfield object.
Parameters
nr_of_elements The number of bits the field should contain.
Returns
The new Bitfield object.
References BaseTypeBits, BaseTypeSize, BFBuf::bytes, cl_malloc(), BFBuf::elements, BFBuf::field, and BFBuf::nr_bits_set.
Referenced by copy_bitfield(), do_delete_lines(), do_delete_lines_num(), do_reduce(), do_StandardQuery(), and match_first_pattern().
destroy_bitfield()
void destroy_bitfield (Bitfield * bptr)
Deletes a bitfield object.
References cl_free.
Referenced by do_delete_lines(), do_delete_lines_num(), do_reduce(), do_StandardQuery(), and match_first_pattern().
get_bit()
int get_bit (Bitfield bitfield, int element)
Gets the value of the bit at the specified offset in the Bitfield.
Parameters
bitfield The Bitfield to work with.
element Offset of the desired bit.
Returns
1 if the bit is set; 0 if it isn't; -1 if element is not a legal offset (ie if it's outside the bounds of the bitfield).
References BaseTypeBits, and BFBuf::field.
Referenced by apply_range_set_operation(), delete_intervals(), and match_first_pattern().
nr_bits_set()
int nr_bits_set (Bitfield bitfield)
Gets the number of bits set to 1 in the given Bitfield.
References BFBuf::nr_bits_set.
Referenced by do_delete_lines_num().
set_all_bits()
int set_all_bits (Bitfield bitfield)
Sets an entire Bitfield (ie sets all bits to 1, all bytes to 0xff).
Returns
False if passed a NULL pointer; otherwise true.
References BFBuf::bytes, BFBuf::elements, BFBuf::field, and BFBuf::nr_bits_set.
Referenced by match_first_pattern().
set_bit()
int set_bit (Bitfield bitfield, int element)
Sets a bit in a Bitfield to 1.
The number of bits set is increased by 1 iff the setting of the specified bit has resulted in a change in the bitfield.
If the offset specified does not exist within this Bitfield, the function returns false (plus an error message is printed). Otherwise it returns true.
Parameters
bitfield The Bitfield object to work with.
element The offset of the bit to set.
Returns
Boolean (see description).
References BaseTypeBits, BFBuf::field, and BFBuf::nr_bits_set.
Referenced by do_delete_lines(), do_delete_lines_num(), do_reduce(), do_StandardQuery(), and match_first_pattern().
toggle_bit()
int toggle_bit (Bitfield bitfield, int element)
Switches the value of the specified bit in a Bitfield.
The number of set bits is either incremented or decremented, as appropriate.
If the offset specified does not exist within this Bitfield, the function returns false (plus an error message is printed). Otherwise it returns true.
Parameters
bitfield The Bitfield to work with.
element Offset of the bit to flip.
Returns
Boolean (see description).
References BaseTypeBits, BFBuf::field, and BFBuf::nr_bits_set.