CWB: cqp/builtins.c File Reference
builtins.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <glib.h>
#include "../cl/cl.h"
#include "builtins.h"
#include "eval.h"
#include "options.h"
#include "output.h"
Functions
static const char * attat_name (int type)
Gets a pointer to a (static, internal) string containing the name of the specified argument type.
int find_predefined_function (const char *name)
Gets the identifier of a specified predefined function (index into the global array of info about the "builtins").
static int common_prefix_length (char *s, char *t)
Calculates the length of a prefix shared by two strings.
int call_predefined_function (int bf_id, DynCallResult *apl, int nr_args, Constrainttree ctptr, DynCallResult *result)
Calls a predefined function from the builtin_function array.
Variables
int f_args [] = {ATTAT_STRING}
Argument types for builtin function f.
int distance_args [] = {ATTAT_POS, ATTAT_POS}
Argument types for builtin function distance (or dist)
int distabs_args [] = {ATTAT_POS, ATTAT_POS}
Argument types for builtin function distabs.
int bound_args [] = {ATTAT_INT}
Argument types for builtin functions lbound and rbound.
int unify_args [] = {ATTAT_STRING, ATTAT_STRING}
Argument types for builtin functions unify, prefix, is_prefix, minus, normalize.
int ambiguity_args [] = {ATTAT_STRING}
Argument types for builtin function ambiguity.
int string_arg [] = {ATTAT_STRING}
Argument types for builtin functions taking a single string argument.
int arith_args [] = {ATTAT_INT, ATTAT_INT}
Argument types for builtin arithemtical functions.
int ignore_args [] = {ATTAT_POS}
Argument types for builtin function ignore.
BuiltinF builtin_function []
Global array of built-in functions.
Function Documentation
attat_name()
static const char* attat_name (int type) static
Gets a pointer to a (static, internal) string containing the name of the specified argument type.
Parameters
type One of the ATTAT_x constants (an argument type).
Returns
The name of the argument type. Do not modify or free.
References ATTAT_FLOAT, ATTAT_INT, ATTAT_NONE, ATTAT_PAREF, ATTAT_POS, ATTAT_STRING, and ATTAT_VAR.
Referenced by call_predefined_function().
call_predefined_function()
int call_predefined_function (int bf_id, DynCallResult * apl, int nr_args, Constrainttree ctptr, DynCallResult * result)
Calls a predefined function from the builtin_function array.
See also
builtin_function
Parameters
bf_id The function to call, identified as an index to the builtin_function array.
apl Contains the arguments to this function.
nr_args The number of arguments the function takes.
ctptr A constraint tree used in some (but not all) of the builtin functions.
result Where to put the result of calling the function.
Returns
boolean: true on success, otherwise false.
References c_tree::args, ATTAT_INT, attat_name(), ATTAT_NONE, ATTAT_PAREF, ATTAT_POS, ATTAT_STRING, c_tree::attr, builtin_function, _DCR::charres, cl_all_ok, cl_corpus_charset(), cl_cpos2struc2cpos(), CL_DYN_STRING_SIZE, cl_id2freq(), cl_id2str(), cl_set_intersection(), cl_set_size(), cl_str2id(), cl_string_canonical(), common_prefix_length(), cl::corpus, cqpmessage(), _DCR::dynamic_string_buffer, Error, False, c_tree::func, IGNORE_CASE, IGNORE_DIAC, _DCR::intres, _builtinf::name, pa_ref, c_tree::pa_ref, _ActualParamList::param, _DCR::parefres, evalenv::query_corpus, sa_ref, c_tree::sa_ref, True, _DCR::type, c_tree::type, utf8, and _DCR::value.
Referenced by get_leaf_value().
common_prefix_length()
static int common_prefix_length (char * s, char * t) static
Calculates the length of a prefix shared by two strings.
Parameters
s The first string.
t The second string.
Returns
The number of characters from the start of the two strings, that are identical between them. (Or, to put it another way, the index of the first non-identical character.)
Referenced by call_predefined_function().
find_predefined_function()
int find_predefined_function (const char * name)
Gets the identifier of a specified predefined function (index into the global array of info about the "builtins").
Returns -1 if the function is not found.
See also
builtin_function
Parameters
name The name of the function to search for.
Returns
An index into the builtin_function array (or -1 for not found)
References builtin_function, cl_streq, and _builtinf::name.
Referenced by do_FunctionCall().
Variable Documentation
ambiguity_args
int ambiguity_args[] = {ATTAT_STRING}
Argument types for builtin function ambiguity.
arith_args
int arith_args[] = {ATTAT_INT, ATTAT_INT}
Argument types for builtin arithemtical functions.
bound_args
int bound_args[] = {ATTAT_INT}
Argument types for builtin functions lbound and rbound.
builtin_function
BuiltinF builtin_function[]
Initial value:
= {
  {  0, "f",        1, f_args,        ATTAT_INT },
  {  1, "distance", 2, distance_args, ATTAT_INT },
  {  2, "dist",     2, distance_args, ATTAT_INT },
  {  3, "distabs",  2, distabs_args,  ATTAT_INT },
  {  4, "int",      1, string_arg,    ATTAT_INT },
  {  5, "lbound",   1, bound_args,    ATTAT_INT },
  {  6, "rbound",   1, bound_args,    ATTAT_INT },
  {  7, "unify",    2, unify_args,    ATTAT_STRING },
  {  8, "ambiguity",1, ambiguity_args,ATTAT_INT },
  {  9, "add",      2, arith_args,    ATTAT_INT },
  { 10, "sub",      2, arith_args,    ATTAT_INT },
  { 11, "mul",      2, arith_args,    ATTAT_INT },
  { 12, "prefix",   2, unify_args,    ATTAT_STRING },
  { 13, "is_prefix",2, unify_args,    ATTAT_INT },
  { 14, "minus",    2, unify_args,    ATTAT_STRING },
  { 15, "ignore",   1, ignore_args,   ATTAT_INT },
  { 16, "normalize",2, unify_args,    ATTAT_STRING},
  { 17, "lbound_of",2, distance_args, ATTAT_INT },
  { 18, "rbound_of",2, distance_args, ATTAT_INT },
  { 19, "strlen",   1, string_arg,    ATTAT_INT },
  { -1, NULL,       0, NULL,          ATTAT_NONE }
}
Global array of built-in functions.
Referenced by call_predefined_function(), do_FunctionCall(), find_predefined_function(), and print_booltree().
distabs_args
int distabs_args[] = {ATTAT_POS, ATTAT_POS}
Argument types for builtin function distabs.
distance_args
int distance_args[] = {ATTAT_POS, ATTAT_POS}
Argument types for builtin function distance (or dist)
f_args
int f_args[] = {ATTAT_STRING}
Argument types for builtin function f.
ignore_args
int ignore_args[] = {ATTAT_POS}
Argument types for builtin function ignore.
string_arg
int string_arg[] = {ATTAT_STRING}
Argument types for builtin functions taking a single string argument.
unify_args
int unify_args[] = {ATTAT_STRING, ATTAT_STRING}
Argument types for builtin functions unify, prefix, is_prefix, minus, normalize.