CWB: cqp/builtins.h File Reference
builtins.h File Reference
#include "../cl/cl.h"
#include "eval.h"
Data Structures
struct _builtinf
The BuiltinF object represents a built-in function.
Typedefs
typedef struct _builtinf BuiltinF
The BuiltinF object represents a built-in function.
Functions
int find_predefined_function (const char *name)
Gets the identifier of a specified predefined function (index into the global array of info about the "builtins").
int call_predefined_function (int bf_id, DynCallResult *apl, int nr_args, Constrainttree ctptr, DynCallResult *result)
Calls a predefined function from the builtin_function array.
Variables
BuiltinF builtin_function []
Global array of built-in functions.
Typedef Documentation
BuiltinF
typedef struct _builtinf BuiltinF
The BuiltinF object represents a built-in function.
Function Documentation
call_predefined_function()
int call_predefined_function (int bf_id, DynCallResult * apl, int nr_args, Constrainttree ctptr, DynCallResult * result)
Calls a predefined function from the builtin_function array.
See also
builtin_function
Parameters
bf_id The function to call, identified as an index to the builtin_function array.
apl Contains the arguments to this function.
nr_args The number of arguments the function takes.
ctptr A constraint tree used in some (but not all) of the builtin functions.
result Where to put the result of calling the function.
Returns
boolean: true on success, otherwise false.
References c_tree::args, ATTAT_INT, attat_name(), ATTAT_NONE, ATTAT_PAREF, ATTAT_POS, ATTAT_STRING, c_tree::attr, builtin_function, _DCR::charres, cl_all_ok, cl_corpus_charset(), cl_cpos2struc2cpos(), CL_DYN_STRING_SIZE, cl_id2freq(), cl_id2str(), cl_set_intersection(), cl_set_size(), cl_str2id(), cl_string_canonical(), common_prefix_length(), cl::corpus, cqpmessage(), _DCR::dynamic_string_buffer, Error, False, c_tree::func, IGNORE_CASE, IGNORE_DIAC, _DCR::intres, _builtinf::name, pa_ref, c_tree::pa_ref, _ActualParamList::param, _DCR::parefres, evalenv::query_corpus, sa_ref, c_tree::sa_ref, True, _DCR::type, c_tree::type, utf8, and _DCR::value.
Referenced by get_leaf_value().
find_predefined_function()
int find_predefined_function (const char * name)
Gets the identifier of a specified predefined function (index into the global array of info about the "builtins").
Returns -1 if the function is not found.
See also
builtin_function
Parameters
name The name of the function to search for.
Returns
An index into the builtin_function array (or -1 for not found)
References builtin_function, cl_streq, and _builtinf::name.
Referenced by do_FunctionCall().
Variable Documentation
builtin_function
BuiltinF builtin_function[] extern
Global array of built-in functions.
Referenced by call_predefined_function(), do_FunctionCall(), find_predefined_function(), and print_booltree().