CWB: cl/compression.c File Reference
compression.c File Reference
#include <math.h>
#include "globals.h"
#include "compression.h"
Functions
int compute_ba (int ft, int corpus_size)
{I have no idea what this does – AH}
int write_golomb_code (int x, int b, BFile *bf)
Writes an integer to a Golomb-coded bit-file-buffer.
int read_golomb_code_bf (int b, BFile *bf)
Reads an integer from a Golomb-coded bit-file-buffer.
int read_golomb_code_bs (int b, BStream *bs)
Reads an integer from a Golomb-coded bitstream.
Function Documentation
compute_ba()
int compute_ba (int ft, int corpus_size)
{I have no idea what this does – AH}
Parameters
ft ??
corpus_size ??
Returns
??
Referenced by cl_id2cpos_oldstyle(), cl_new_stream(), compress_reversed_index(), and decompress_check_reversed_index().
read_golomb_code_bf()
int read_golomb_code_bf (int b, BFile * bf)
Reads an integer from a Golomb-coded bit-file-buffer.
Parameters
b ???
bf The bit-file to read from.
Returns
The integer that is read.
References BFread(), and log2.
Referenced by decompress_check_reversed_index().
read_golomb_code_bs()
int read_golomb_code_bs (int b, BStream * bs)
Reads an integer from a Golomb-coded bitstream.
Parameters
b ???
bs The bitstream to read from.
Returns
The integer that is read.
References BSread(), and log2.
Referenced by cl_id2cpos_oldstyle(), and cl_read_stream().
write_golomb_code()
int write_golomb_code (int x, int b, BFile * bf)
Writes an integer to a Golomb-coded bit-file-buffer.
Parameters
x Integer to write
b ???
bf The bit-file to read from.
Returns
Always 1.
References BFwrite(), BFwriteWord(), and log2.
Referenced by compress_reversed_index().