CWB: cqp/concordance.h File Reference
concordance.h File Reference
#include "context_descriptor.h"
#include "print-modes.h"
Data Structures
struct _ConcLineField
ConcLineField : a concordance line "field" is one of the four "anchors": that is, match, matchend, target, keyword.
Typedefs
typedef struct _ConcLineField ConcLineField
ConcLineField : a concordance line "field" is one of the four "anchors": that is, match, matchend, target, keyword.
Functions
char * compose_kwic_line (Corpus *corpus, int match_start, int match_end, ContextDescriptor *context, char *left_marker, char *right_marker, ConcLineField *fields, int nr_fields, PrintDescriptionRecord *pdr)
Builds a string for a concordance output line.
void cleanup_kwic_line_memory (void)
Frees the memory used for building a KWIC line for display.
Typedef Documentation
ConcLineField
typedef struct _ConcLineField ConcLineField
ConcLineField : a concordance line "field" is one of the four "anchors": that is, match, matchend, target, keyword.
This object contains a record of the location of one such anchor point and its type. This can be passed to a "field-printing" function to perform special rendering of tokens in the "anchor" within a concordance line.
Function Documentation
cleanup_kwic_line_memory()
void cleanup_kwic_line_memory (void)
Frees the memory used for building a KWIC line for display.
Best used when CQP shuts down.
References cl_autostring_delete(), line, scratch, and token.
Referenced by cqp_cleanup_memory().
compose_kwic_line()
char* compose_kwic_line (Corpus * corpus, int match_start, int match_end, ContextDescriptor * cd, char * left_kwic_delim, char * right_kwic_delim, ConcLineField * fields, int nr_fields, PrintDescriptionRecord * pdr)
Builds a string for a concordance output line.
Parameters
corpus The corpus we're pritning from
match_start A corpus position (start of match)
match_end A corpus position (end of match)
cd ContrextDescriptor to use for printing.
left_kwic_delim String inserted at start of match.
right_kwic_delim String inserted at end of match. THIS AND THE PREVIOUS ARE ONLY USED BY ascii-print./... which passes in global the global options set by LeftKWICDelim and RightKWICDelim So actually, these could be just 1 param: include_global_hit_match_delimiters
fields Array of ConcLineFields object (that is, anchors).
nr_fields Number of items in the "fields" array.
pdr PDR contains the strings to be printed among bits of data from the ciorpus to make the conconrdance.
Returns
String containing the output line.
Use with variables "line", "tok_sep" to insert a separator iff there are already 1+ tokens in the line; macro used only in this function
References a_att_context, add_sep_to_line_if_not_empty, AddNameToAL(), PrintDescriptionRecord::AfterField, PrintDescriptionRecord::AfterToken, ATT_POS, _attrbuf::attribute, ContextDescriptor::attributes, PrintDescriptionRecord::BeforeField, PrintDescriptionRecord::BeforeToken, char_context, TCorpus::charset, cl_alg2cpos(), cl_autostring_concat(), cl_autostring_ptr(), cl_autostring_truncate(), cl_charset_strlen(), cl_cpos2alg(), cl_cpos2struc(), cl_free, cl_max_cpos(), cl_max_struc(), cl_strdup(), cl_string_utf8_continuation_byte(), cl_struc2cpos(), compose_anchor_separators(), compose_kwic_print_structures(), compose_kwic_token(), corpus, CWB_DEFAULT_ATT_NAME, ClAutoString::data, DestroyAttributeList(), FindInAL(), ContextDescriptor::left_structure, ContextDescriptor::left_type, ContextDescriptor::left_width, ClAutoString::len, line, _attlist::list, _attlist::list_valid, MAX, MIN, NewAttributeList(), NrOfElementsWithStatusAL(), ContextDescriptor::print_cpos, ContextDescriptor::right_structure, ContextDescriptor::right_type, ContextDescriptor::right_width, s_att_context, setup_kwic_line_memory(), srev(), _attrbuf::status, text_size, token, token_separator, PrintDescriptionRecord::TokenSeparator, utf8, VerifyList(), and word_context.
Referenced by ascii_print_concordance_line(), html_print_output(), latex_print_output(), print_all_aligned_lines(), and sgml_print_output().