CWB: cqp/concordance.c File Reference
concordance.c File Reference
#include <stdio.h>
#include <glib.h>
#include "../cl/cl.h"
#include "concordance.h"
#include "attlist.h"
#include "options.h"
Data Structures
struct SAttRegion
Represents a single s-attribute region and its annotation.
Macros
#define MAXKWICLINELEN 65535
maximum length of a KWIC line (bytes).
#define MAX_S_ATTRS 1024 /* max. number of s-attribute; same as MAX_ATTRS in <utils/decode.c> and MAXRANGES in <utils/encode.c> */
#define add_sep_to_line_if_not_empty(l, s) {if (l->len > 0) cl_autostring_concat(l, s);}
Functions
static char * srev (char *s)
Reverses the argument string (destructively, that is, in situ).
static void compose_kwic_print_structures (ContextDescriptor *cd, int position, ClAutoString s, int show_cpos, PrintDescriptionRecord *pdr)
Rendering function for the start of a concordance line (before any left-context): implements leading cpos and print-structures.
static void sort_s_att_regions (void)
static void compose_kwic_token (ContextDescriptor *cd, int position, ClAutoString dest, PrintDescriptionRecord *pdr)
Assemble all the bits of a KWIC token (i.e., XML begin/end tags and p-attributes as selected with "show +...") at the given corpus position.
static const char * compose_anchor_separators (int position, ConcLineField *fields, int nr_fields, int at_end, PrintDescriptionRecord *pdr)
This oddly-named function prints a series of separators for "fields" to an internal buffer.
static void setup_kwic_line_memory (void)
Initialises the two empty auto-growing strings used for concordance line concstruction.
void cleanup_kwic_line_memory (void)
Frees the memory used for building a KWIC line for display.
char * compose_kwic_line (Corpus *corpus, int match_start, int match_end, ContextDescriptor *cd, char *left_kwic_delim, char *right_kwic_delim, ConcLineField *fields, int nr_fields, PrintDescriptionRecord *pdr)
Builds a string for a concordance output line.
Variables
SAttRegion s_att_regions [MAX_S_ATTRS]
int sar_sort_index [MAX_S_ATTRS]
int N_sar = 0
static ClAutoString scratch = NULL
Scratch string used by compose_anchor_separators only.
static ClAutoString line = NULL
Used to build the concordance line (main line buffer);.
static ClAutoString token = NULL
Used to build the concordance line (token buffer);.
Macro Definition Documentation
add_sep_to_line_if_not_empty
#define add_sep_to_line_if_not_empty (l, s) {if (l->len > 0) cl_autostring_concat(l, s);}
MAX_S_ATTRS
#define MAX_S_ATTRS 1024 /* max. number of s-attribute; same as MAX_ATTRS in <utils/decode.c> and MAXRANGES in <utils/encode.c> */
MAXKWICLINELEN
#define MAXKWICLINELEN 65535
maximum length of a KWIC line (bytes).
Function Documentation
cleanup_kwic_line_memory()
void cleanup_kwic_line_memory (void)
Frees the memory used for building a KWIC line for display.
Best used when CQP shuts down.
References cl_autostring_delete(), line, scratch, and token.
Referenced by cqp_cleanup_memory().
compose_anchor_separators()
static const char* compose_anchor_separators (int position, ConcLineField * fields, int nr_fields, int at_end, PrintDescriptionRecord * pdr) static
This oddly-named function prints a series of separators for "fields" to an internal buffer.
"Field" in this context means an anchor point (begin, end, target, keyword).
Parameters
position The corpus position (cpos) whose field-separators we want.
fields Pointer to array of ConcLineFields object (each of which specifies one of the 4 anchors).
nr_fields Number of items in the "fields" array.
at_end Boolean: if true, we get the end-separators needed to print at this cpos (after the token printed); if false, we get the beginning-separators needed to print at this cpos (before the token printed).
pdr The PDR for the current concordance printout.
Returns
A pointer to a module-internal static string buffer containing the requested string (sequence of start or end separators for the anchors specified in "fields"). Do not free it or alter it. The buffer's content will change when this function is called again. The function will return NULL if the requested string would have been zero-length.
References cl_autostring_concat(), cl_autostring_new(), cl_autostring_truncate(), ClAutoString::data, ClAutoString::len, PrintDescriptionRecord::printField, scratch, and _ConcLineField::type.
Referenced by compose_kwic_line().
compose_kwic_line()
char* compose_kwic_line (Corpus * corpus, int match_start, int match_end, ContextDescriptor * cd, char * left_kwic_delim, char * right_kwic_delim, ConcLineField * fields, int nr_fields, PrintDescriptionRecord * pdr)
Builds a string for a concordance output line.
Parameters
corpus The corpus we're pritning from
match_start A corpus position (start of match)
match_end A corpus position (end of match)
cd ContrextDescriptor to use for printing.
left_kwic_delim String inserted at start of match.
right_kwic_delim String inserted at end of match. THIS AND THE PREVIOUS ARE ONLY USED BY ascii-print./... which passes in global the global options set by LeftKWICDelim and RightKWICDelim So actually, these could be just 1 param: include_global_hit_match_delimiters
fields Array of ConcLineFields object (that is, anchors).
nr_fields Number of items in the "fields" array.
pdr PDR contains the strings to be printed among bits of data from the ciorpus to make the conconrdance.
Returns
String containing the output line.
Use with variables "line", "tok_sep" to insert a separator iff there are already 1+ tokens in the line; macro used only in this function
References a_att_context, add_sep_to_line_if_not_empty, AddNameToAL(), PrintDescriptionRecord::AfterField, PrintDescriptionRecord::AfterToken, ATT_POS, _attrbuf::attribute, ContextDescriptor::attributes, PrintDescriptionRecord::BeforeField, PrintDescriptionRecord::BeforeToken, char_context, TCorpus::charset, cl_alg2cpos(), cl_autostring_concat(), cl_autostring_ptr(), cl_autostring_truncate(), cl_charset_strlen(), cl_cpos2alg(), cl_cpos2struc(), cl_free, cl_max_cpos(), cl_max_struc(), cl_strdup(), cl_string_utf8_continuation_byte(), cl_struc2cpos(), compose_anchor_separators(), compose_kwic_print_structures(), compose_kwic_token(), corpus, CWB_DEFAULT_ATT_NAME, ClAutoString::data, DestroyAttributeList(), FindInAL(), ContextDescriptor::left_structure, ContextDescriptor::left_type, ContextDescriptor::left_width, ClAutoString::len, line, _attlist::list, _attlist::list_valid, MAX, MIN, NewAttributeList(), NrOfElementsWithStatusAL(), ContextDescriptor::print_cpos, ContextDescriptor::right_structure, ContextDescriptor::right_type, ContextDescriptor::right_width, s_att_context, setup_kwic_line_memory(), srev(), _attrbuf::status, text_size, token, token_separator, PrintDescriptionRecord::TokenSeparator, utf8, VerifyList(), and word_context.
Referenced by ascii_print_concordance_line(), html_print_output(), latex_print_output(), print_all_aligned_lines(), and sgml_print_output().
compose_kwic_print_structures()
static void compose_kwic_print_structures (ContextDescriptor * cd, int position, ClAutoString s, int show_cpos, PrintDescriptionRecord * pdr) static
Rendering function for the start of a concordance line (before any left-context): implements leading cpos and print-structures.
The s-attribute values are put into a ClAutoString, for use at the start of the printed concordance line.
The s-attributes that will be printed are determined by the contents of the ContextDescriptor object; the PrintDescriptionRecord determines what they look like.
The leading material generated here refers to a single given cpos ("position").
Parameters
cd Print settings (context size/type; atts to print)
position The CPOS about which this function renders information.
s Results will be concatenated onto this string.
show_cpos Boolean: whether or not to print the cpos before the PrintStructures.
pdr Print settings (of main mode) to use
References PrintDescriptionRecord::AfterPrintStructures, _Attribute::any, _attrbuf::attribute, PrintDescriptionRecord::BeforePrintStructures, cl_autostring_concat(), cl_cpos2struc2str(), CL_MAX_LINE_LENGTH, PrintDescriptionRecord::CPOSPrintFormat, _attlist::list, _attrbuf::next, PrintDescriptionRecord::PrintStructureSeparator, ContextDescriptor::printStructureTags, PrintDescriptionRecord::printToken, _attrbuf::status, PrintDescriptionRecord::StructureBeginPrefix, and PrintDescriptionRecord::StructureBeginSuffix.
Referenced by compose_kwic_line().
compose_kwic_token()
static void compose_kwic_token (ContextDescriptor * cd, int position, ClAutoString dest, PrintDescriptionRecord * pdr) static
Assemble all the bits of a KWIC token (i.e., XML begin/end tags and p-attributes as selected with "show +...") at the given corpus position.
Parameters
cd ContextDescriptor for the concordance.
position cpos of token to render
dest ClAutoString to place the result in (overwriting any existing content).
pdr PrintDescriptionRecord for the concordance.
References SAttRegion::annot, _Attribute::any, _attrbuf::attribute, attribute_separator, ContextDescriptor::attributes, PrintDescriptionRecord::AttributeSeparator, cl_autostring_concat(), cl_autostring_truncate(), cl_cpos2str(), cl_cpos2struc(), CL_MAX_LINE_LENGTH, cl_strcpy(), cl_struc2cpos(), cl_struc2str(), cl_struc_values(), SAttRegion::end, _attlist::list, N_sar, SAttRegion::name, _attrbuf::next, PrintDescriptionRecord::printToken, s_att_regions, sar_sort_index, show_tag_attributes, sort_s_att_regions(), SAttRegion::start, _attrbuf::status, ContextDescriptor::strucAttributes, structure_delimiter, PrintDescriptionRecord::StructureBeginPrefix, PrintDescriptionRecord::StructureBeginSuffix, PrintDescriptionRecord::StructureEndPrefix, PrintDescriptionRecord::StructureEndSuffix, and word.
Referenced by compose_kwic_line().
setup_kwic_line_memory()
static void setup_kwic_line_memory (void) static
Initialises the two empty auto-growing strings used for concordance line concstruction.
References cl_autostring_new(), cl_autostring_truncate(), line, and token.
Referenced by compose_kwic_line().
sort_s_att_regions()
static void sort_s_att_regions (void) static
References SAttRegion::end, N_sar, s_att_regions, sar_sort_index, and SAttRegion::start.
Referenced by compose_kwic_token().
srev()
static char* srev (char * s) static
Reverses the argument string (destructively, that is, in situ).
Cf. the non-standard (microsoft) function strrev.
This does not respect UTF-8, so anything reversed must be re-reversed before output or there will be invalid byte sequences.
Parameters
s The string to modify.
Returns
A pointer to the modified string (same memory area as the argument string).
References buf.
Referenced by compose_kwic_line().
Variable Documentation
line
ClAutoString line = NULL static
Used to build the concordance line (main line buffer);.
See also
compose_kwic_line
Referenced by alignshow_print_next_region(), alignshow_skip_next_region(), ascii_print_aligned_line(), cleanup_kwic_line_memory(), compose_kwic_line(), cwbci_check_line(), do_undump(), evaluate_subset(), evaluate_target(), html_print_aligned_line(), html_print_output(), latex_print_output(), load_macro_file(), main(), preprocess_input_line(), PrintAttributesPretty(), sencode_parse_line(), setup_kwic_line_memory(), sgml_print_aligned_line(), sgml_print_output(), and SortExternally().
N_sar
int N_sar = 0
Referenced by compose_kwic_token(), and sort_s_att_regions().
s_att_regions
SAttRegion s_att_regions[MAX_S_ATTRS]
Referenced by compose_kwic_token(), and sort_s_att_regions().
sar_sort_index
int sar_sort_index[MAX_S_ATTRS]
Referenced by compose_kwic_token(), and sort_s_att_regions().
scratch
ClAutoString scratch = NULL static
Scratch string used by compose_anchor_separators only.
Global so that Kwic cleanup can catch it!
Referenced by cleanup_kwic_line_memory(), and compose_anchor_separators().
token
ClAutoString token = NULL static
Used to build the concordance line (token buffer);.
See also
compose_kwic_line
Referenced by cl_lexhash_add(), cl_lexhash_del(), cl_lexhash_find(), cl_lexhash_find_i(), cl_lexhash_freq(), cl_lexhash_id(), cleanup_kwic_line_memory(), compose_kwic_line(), ComputePrintStructures(), encode_add_p_attr_line(), expand_macro(), main(), ParsePrintOptions(), s_att_open_range(), setup_kwic_line_memory(), SortExternally(), and SortSubcorpus().