CWB: cl/corpus.c File Reference
corpus.c File Reference
#include <ctype.h>
#include <sys/types.h>
#include <sys/utsname.h>
#include <pwd.h>
#include <grp.h>
#include "globals.h"
#include "attributes.h"
#include "registry.tab.h"
#include "corpus.h"
Data Structures
struct charset_spec
structure for the global list of charset names
Functions
static void FreeIDList (IDList *list)
Deletes an IDList object, and sets the argument pointer to NULL.
static int memberIDList (char *s, IDList l)
Checks whether the specified string occurs in the given IDList.
void cregrestart (FILE *file)
Restarts the registry file parse; function created in output from parsing registry.y.
int cregparse ()
Parse a corpus registry file.
char * cl_standard_registry ()
Gets a string containing the path of the default registry directory.
Corpus * find_corpus (char *registry_dir, char *registry_name)
Gets a pointer to the Corpus object with the specified CWB-name and registry location.
FILE * find_corpus_registry (char *registry_dir, char *registry_name, char **real_registry_dir)
Gets a file handle for the registry file of the corpus with the specified CWB-name and registry location.
static int check_access_conditions (Corpus *corpus, int verbose)
Checks whether the corpus can be accessed.
Corpus * cl_new_corpus (char *registry_dir, char *registry_name)
Creates a Corpus object to represent a given indexed corpus, located in a given directory accessible to the program.
int cl_delete_corpus (Corpus *corpus)
Deletes a Corpus object from memory.
void describe_corpus (Corpus *corpus)
Prints a description of the corpus to STDOUT.
cl_string_list cl_corpus_list_attributes (Corpus *corpus, int attribute_type)
Gets a list of the named attributes that this corpus posesses.
CorpusProperty cl_first_corpus_property (Corpus *corpus)
Gets the first entry in this corpus's list of properties.
CorpusProperty cl_next_corpus_property (CorpusProperty prop)
Gets the next corpus property on the list of properties.
char * cl_corpus_property (Corpus *corpus, char *property)
Gets the value of the specified corpus property.
CorpusCharset cl_corpus_charset (Corpus *corpus)
Retrieves the special 'charset' property from a Corpus object.
const char * cl_charset_name (CorpusCharset id)
Gets a string containing the name of the specified CorpusCharset character set object.
CorpusCharset cl_charset_from_name (const char *name)
Gets a CorpusCharset enumeration with the id code for the given string.
const char * cl_charset_name_canonical (char *name_to_check)
Checks whether a string represents a valid charset, and returns a pointer to the name in canonical form (ie lacking any non-standard case there may be in the input string).
void add_corpus_property (Corpus *corpus, char *property, char *value)
Adds a property to the list of corpus properties.
Variables
FILE * cregin
File pointer for loading corpus registry.
Corpus * cregcorpus
Pointer to a corpus object that is used when loading from the registry.
char * cregin_path = ""
Full path of the registry file currently being parsed (for registry parser error messages)
char * cregin_name = ""
The name of registry file currently being parsed (for registry parser error messages)
char errmsg [CL_MAX_LINE_LENGTH]
Buffer for an error message.
Corpus * loaded_corpora = NULL
Head of a linked list of loaded corpus handles (for memory manager).
const charset_spec charset_names []
a list of charset names as strings paired with CorpusCharset ID values; where there are multiple possible names for one ID, the pair with the CWB-preferred name comes first in the array (and is the same as the identifier used for that charset in the CorpusCharset enumeration).
Function Documentation
add_corpus_property()
void add_corpus_property (Corpus * corpus, char * property, char * value)
Adds a property to the list of corpus properties.
Use this function from registry.y only!
If the property is already defined, ignore and warn. If the property is 'charset', corpus charset is set as well.
Parameters
corpus Corpus object to add property to.
property Name of property to add.
value Value of property to add.
References TCorpus::charset, cl_charset_from_name(), cl_corpus_property(), cl_malloc(), corpus, cregin_name, cregin_path, TCorpusProperty::next, TCorpus::properties, TCorpusProperty::property, and TCorpusProperty::value.
check_access_conditions()
static int check_access_conditions (Corpus * corpus, int verbose) static
Checks whether the corpus can be accessed.
If this corpus has access restriction in the form of a list of users, then this function checks if the current user is on that list.
Then ditto for the list of groups and current group; then ditto for the list of hosts and current host.
Note that this is currently disabled for users/groups. So, if either Corpus::userAccessList or Corpus::groupAccessList are changed from their initial (NULL) setting, this function will return false.
On the other hand, the function does work with hosts. If a list of allows hosts is set, this function will return true iff the current host is on that list.
Finally note: if compiled for Windows, this function returns true without actually checking anything, because windows does not support the POSIX user/group functionality on which all of this relies. Under Windows, access policies have to managed by the cqpserver rather than by the CL simply reading from the registry.
Parameters
corpus The corpus.
verbose A boolean. Currently ignored.
Returns
A boolean: true if access is OK, else false.
References corpus, TCorpus::groupAccessList, TCorpus::hostAccessList, memberIDList(), TCorpus::name, passwd, and TCorpus::userAccessList.
Referenced by cl_new_corpus().
cl_charset_from_name()
CorpusCharset cl_charset_from_name (const char * name)
Gets a CorpusCharset enumeration with the id code for the given string.
References charset_names, charset_spec::name, and unknown_charset.
Referenced by add_corpus_property(), cwbci_parse_options(), main(), and sencode_parse_options().
cl_charset_name()
const char* cl_charset_name (CorpusCharset id)
Gets a string containing the name of the specified CorpusCharset character set object.
Note that returned string cannot be modified.
References charset_names, and charset_spec::name.
Referenced by corpus_info(), describecorpus_show_basic_info(), and do_cqi_corpus_charset().
cl_charset_name_canonical()
const char* cl_charset_name_canonical (char * name_to_check)
Checks whether a string represents a valid charset, and returns a pointer to the name in canonical form (ie lacking any non-standard case there may be in the input string).
Note that the returned string cannot be modified.
Parameters
name_to_check String containing the character set name to be checked
Returns
Pointer to canonical-form string for that charset's name or NULL if name_to_check cannot be linked to a valid charset.
References charset_names, and charset_spec::name.
Referenced by cwbci_parse_options(), encode_parse_options(), and sencode_parse_options().
cl_corpus_charset()
CorpusCharset cl_corpus_charset (Corpus * corpus)
Retrieves the special 'charset' property from a Corpus object.
Parameters
corpus The corpus object from which to retrieve the charset
Returns
The character set (as a CorpusCharset object).
References TCorpus::charset, and corpus.
Referenced by call_predefined_function(), create_feature_maps(), decode_print_xml_declaration(), main(), scancorpus_add_key(), and sencode_parse_options().
cl_corpus_list_attributes()
cl_string_list cl_corpus_list_attributes (Corpus * corpus, int attribute_type)
Gets a list of the named attributes that this corpus posesses.
This function creates a list of strings containing the names of all and only those Attributes in this corpus whose type matches that specified in the second parameter.
Parameters
corpus The corpus whose attributes are to be listed.
attribute_type The type of attributes to be listed. This must be one of the attribute type macros: ATT_POS, ATT_STRUC etc. For all attributes, specify ATT_ALL (natuerlich).
Returns
String list containing names of all the corpus's attributes that have the desired type. All the actual character buffers have been newly allocated, so it is safe to call cl_free_string_list on the returned cl_string_list object once you're done with it.
References _Attribute::any, TCorpus::attributes, cl_new_string_list(), cl_strdup(), cl_string_list_append(), and corpus.
cl_corpus_property()
char* cl_corpus_property (Corpus * corpus, char * property)
Gets the value of the specified corpus property.
Parameters
corpus Pointer to the Corpus object.
property Name of the property to retrieve.
Returns
Pointer to string that contains the value of the property, or NULL if the specified property is undefined for this Corpus object.
References cl_first_corpus_property(), cl_next_corpus_property(), corpus, TCorpusProperty::property, and TCorpusProperty::value.
Referenced by add_corpus_property(), and corpus_info().
cl_delete_corpus()
int cl_delete_corpus (Corpus * corpus)
Deletes a Corpus object from memory.
A Corpus object keeps track of how many times it has been requested via cl_new_corpus(). When cl_delete_corpus() is called, the object is only actually deleted when there is just one outstanding request. Otherwise, the variable tracking the number of requests is decremented.
Parameters
corpus The Corpus to delete.
Returns
Always 1.
References TCorpus::attributes, cl_delete_attribute(), cl_free, corpus, cregcorpus, FreeIDList(), TCorpus::groupAccessList, TCorpus::hostAccessList, TCorpus::id, TCorpus::info_file, loaded_corpora, TCorpus::name, TCorpus::next, TCorpus::nr_of_loads, TCorpus::path, TCorpus::registry_dir, TCorpus::registry_name, and TCorpus::userAccessList.
Referenced by cl_new_corpus(), cleanup_and_exit(), compressrdx_cleanup(), huffcode_usage(), and main().
cl_first_corpus_property()
CorpusProperty cl_first_corpus_property (Corpus * corpus)
Gets the first entry in this corpus's list of properties.
(The corpus properties iterator / property datatype is public.)
Parameters
corpus Pointer to the Corpus object.
Returns
The first property.
References corpus, and TCorpus::properties.
Referenced by cl_corpus_property(), and corpus_info().
cl_new_corpus()
Corpus* cl_new_corpus (char * registry_dir, char * registry_name)
Creates a Corpus object to represent a given indexed corpus, located in a given directory accessible to the program.
Parameters
registry_dir Path to the CWB registry directory from which the corpus is to be loaded. This may be NULL, in which case the default registry directory is used.
registry_name The CWB-name of the indexed corpus to load (in the all-lowercase form)
Returns
Pointer to the resulting Corpus object.
References check_access_conditions(), cl_delete_corpus(), cl_free, cl_id_tolower(), cl_id_validate(), cl_standard_registry(), cl_strdup(), corpus, cregcorpus, cregin, cregin_name, cregin_path, cregparse(), cregrestart(), find_corpus(), find_corpus_registry(), TCorpus::id, loaded_corpora, TCorpus::next, TCorpus::nr_of_loads, TCorpus::registry_dir, registry_dir, and TCorpus::registry_name.
Referenced by GetSystemCorpus(), main(), print_all_aligned_lines(), and sencode_parse_options().
cl_next_corpus_property()
CorpusProperty cl_next_corpus_property (CorpusProperty prop)
Gets the next corpus property on the list of properties.
(The corpus properties iterator / property datatype is public.)
Parameters
prop The current property.
Returns
The next property on the list, or NULL if there isn't one.
References TCorpusProperty::next.
Referenced by cl_corpus_property(), and corpus_info().
cl_standard_registry()
char* cl_standard_registry ()
Gets a string containing the path of the default registry directory.
Note this is a pointer to an internal string, and therefore must not be altered or freed.
Returns
The value of the corpus-module-internal variable regdir, which is initialised from the environment variable REGISTRY_ENVVAR or, failing that, the macro REGISTRY_DEFAULT_PATH.
See also
REGISTRY_ENVVAR
REGISTRY_DEFAULT_PATH
References CWB_REGISTRY_DEFAULT_PATH, and CWB_REGISTRY_ENVVAR.
Referenced by cl_new_corpus(), find_corpus(), load_corpusnames(), and main().
cregparse()
int cregparse ()
Parse a corpus registry file.
The file to be parsed is specified by global variables cregin_path and cregin_name.
Function created in output from parsing registry.y
Referenced by cl_new_corpus().
cregrestart()
void cregrestart (FILE * file)
Restarts the registry file parse; function created in output from parsing registry.y.
Referenced by cl_new_corpus().
describe_corpus()
void describe_corpus (Corpus * corpus)
Prints a description of the corpus to STDOUT.
In v4: might be nice to have this function offer an option of XML-style output. It might also be nice to have it return a string, or send to a parameter stream, so that the caller can decide what to do with it: direct UI formatting does not really belong in the low-level CL.
References _Attribute::any, TCorpus::attributes, corpus, describe_attribute(), TCorpus::id, TCorpus::info_file, TCorpus::name, TCorpus::path, TCorpus::registry_dir, and TCorpus::registry_name.
Referenced by main().
find_corpus()
Corpus* find_corpus (char * registry_dir, char * registry_name)
Gets a pointer to the Corpus object with the specified CWB-name and registry location.
(Works by searching the loaded_corpora global linked list.)
Parameters
registry_dir The registry directory.
registry_name The CWB name of the corpus.
Returns
The Corpus, or NULL if it wasn't found.
References cl_standard_registry(), cl_streq, loaded_corpora, TCorpus::next, PATH_SEPARATOR, TCorpus::registry_dir, registry_dir, and TCorpus::registry_name.
Referenced by cl_new_corpus().
find_corpus_registry()
FILE* find_corpus_registry (char * registry_dir, char * registry_name, char ** real_registry_dir)
Gets a file handle for the registry file of the corpus with the specified CWB-name and registry location.
The registry file is opened for text-mode read.
Parameters
registry_dir The registry directory.
registry_name The CWB name of the corpus.
real_registry_dir This will be set to a pointer to the "real" name of the directory derived from the registry_dir parameter.
Returns
A file handle, or NULL in case of error.
References cl_malloc(), CL_MAX_LINE_LENGTH, PATH_SEPARATOR, registry_dir, and SUBDIR_SEPARATOR.
Referenced by cl_new_corpus().
FreeIDList()
static void FreeIDList (IDList * list) static
Deletes an IDList object, and sets the argument pointer to NULL.
Parameters
list IDList to delete.
References cl_free, _idbuf::next, and _idbuf::string.
Referenced by cl_delete_corpus().
memberIDList()
static int memberIDList (char * s, IDList l) static
Checks whether the specified string occurs in the given IDList.
Parameters
s The username, groupname, or hostname to look for.
l The IDList to search.
Returns
Boolean: true if s is a member of the list, else false.
References cl_streq, _idbuf::next, and _idbuf::string.
Referenced by check_access_conditions().
Variable Documentation
charset_names
const charset_spec charset_names[]
a list of charset names as strings paired with CorpusCharset ID values; where there are multiple possible names for one ID, the pair with the CWB-preferred name comes first in the array (and is the same as the identifier used for that charset in the CorpusCharset enumeration).
Referenced by cl_charset_from_name(), cl_charset_name(), and cl_charset_name_canonical().
cregcorpus
Corpus* cregcorpus extern
Pointer to a corpus object that is used when loading from the registry.
(External variable, defined in the output from parsing registry.y)
Referenced by cl_delete_corpus(), and cl_new_corpus().
cregin
FILE* cregin extern
File pointer for loading corpus registry.
(External variable, defined in the output from parsing registry.y)
Referenced by cl_new_corpus().
cregin_name
char* cregin_name = ""
The name of registry file currently being parsed (for registry parser error messages)
See also
cregparse
Referenced by add_corpus_property(), and cl_new_corpus().
cregin_path
char* cregin_path = ""
Full path of the registry file currently being parsed (for registry parser error messages)
See also
cregparse
Referenced by add_corpus_property(), and cl_new_corpus().
errmsg
char errmsg[CL_MAX_LINE_LENGTH]
Buffer for an error message.
{appears not to be used anywhere???}
loaded_corpora
Corpus* loaded_corpora = NULL
Head of a linked list of loaded corpus handles (for memory manager).
Referenced by cl_delete_corpus(), cl_new_corpus(), and find_corpus().