CWB: cqp/corpmanag.h File Reference
corpmanag.h File Reference
#include "../cl/cl.h"
#include "../cl/bitfields.h"
#include "cqp.h"
#include "context_descriptor.h"
Data Structures
struct Range
The Range object represents a range of corpus positions - for instance, the range enclosed by an instance of an s-attribute.
struct cl
The CorpusList object records information on a corpus that CQP recognises.
Typedefs
typedef enum _field_type FieldType
The FieldType object represents the fields (or 'anchor points') of a subcorpus (inc query result).
typedef enum corpus_type CorpusType
The CorpusType object.
typedef struct Range Range
The Range object represents a range of corpus positions - for instance, the range enclosed by an instance of an s-attribute.
typedef struct cl CorpusList
The CorpusList object records information on a corpus that CQP recognises.
Enumerations
enum _field_type {
MatchField = 0 , MatchEndField , TargetField , KeywordField ,
NoField
}
The FieldType object represents the fields (or 'anchor points') of a subcorpus (inc query result).
enum corpus_type {
UNDEF , SYSTEM , SUB , TEMP ,
ALL
}
Underlying enumeration for CorpusType.
enum case_mode { LOWER , UPPER }
An enumeration for lowercase vs.
Functions
FieldType field_name_to_type (const char *name)
Returns a FieldType enumeration corresponding to the field name indicated by its string argument.
const char * field_type_to_name (FieldType field)
Returns a pointer to an internal constant string that labels the FieldType argument.
void init_global_corpuslist (void)
Initialises the global corpus list (sets it to NULL, no matter what its value was).
CorpusList * findcorpus (char *s, CorpusType type, int try_recursive_search)
Finds the pointer to the corpus (or subcorpus, or query result) with the given name.
CorpusList * LoadedCorpus (char *name, char *qualifier, CorpusType type)
Finds a loaded corpus.
CorpusList * dropcorpus (CorpusList *cl, CorpusList *search_from)
Remove a corpus from the global list of corpora.
CorpusList * duplicate_corpus (CorpusList *cl, char *new_name, Boolean force_overwrite)
Duplicate a CorpusList object.
CorpusList * make_temp_corpus (CorpusList *cl, char *new_name)
Copy a corpus as type TEMP.
CorpusList * assign_temp_to_sub (CorpusList *tmp, char *subname)
Convert a temporary corpus to a real subcorpus.
void drop_temp_corpora (void)
Delete temporary corpora, clearing the global list of corpora of all temporary stuff.
void drop_all_corpora (void)
Release all memory from the global corpus list.
Boolean access_corpus (CorpusList *cl)
Assesses whether a specified corpus can be accessed.
void check_available_corpora (CorpusType ct)
Check what corpora of a given type are available on disk.
Boolean valid_subcorpus_name (char *corpusname)
Checks whether corpusname is syntactically valid as a query result name, i.e., either.
Boolean subcorpus_name_is_qualified (const char *corpusname)
Checks whether corpusname is qualified (with name of mother corpus); does not imply syntatic validity.
char * split_subcorpus_name (const char *corpusname, char *mother_name)
Splits a query result "corpus"-name into qualifier and local name.
Boolean save_subcorpus (CorpusList *cl, char *fname)
Save a subcorpus/NQR to disk.
void save_unsaved_subcorpora ()
CorpusList * FirstCorpusFromList ()
Gets the CorpusList pointer for the first corpus on the currently-loaded list.
CorpusList * NextCorpusFromList (CorpusList *cl)
Gets the CorpusList pointer for the next corpus on the currently-loaded list.
int set_current_corpus (CorpusList *cp, int force)
Sets the current corpus (by pointer to the corpus).
int set_current_corpus_name (char *name, int force)
Sets the current corpus (by name).
int touch_corpus (CorpusList *cp)
Touches a corpus, ie, marks it as changed.
void show_corpora (CorpusType type)
A function to print out a list of corpora currently available.
void show_corpus_active (void)
Displays the ID of the active corpus.
Variables
CorpusList * current_corpus
Global pointer to the "current" corpus.
Typedef Documentation
CorpusList
typedef struct cl CorpusList
The CorpusList object records information on a corpus that CQP recognises.
This might be an actual corpus in the registry (->type=SYSTEM), or a subcorpus or query result (->type=SUB).
Note that CorpusList is a bit of a misnomer, although it IS a linked-list entry object, and CQP keeps information on the "corpora" it currently knows about on such a list, in fact this object is often used for passing around information about individual corpora, queries etc. as well.
CorpusType
typedef enum corpus_type CorpusType
The CorpusType object.
FieldType
typedef enum _field_type FieldType
The FieldType object represents the fields (or 'anchor points') of a subcorpus (inc query result).
NoField is always the last field (so it can be used to determine range of field type codes) (the mnemonic is NoField = "no field" = "number of field types")
Range
typedef struct Range Range
The Range object represents a range of corpus positions - for instance, the range enclosed by an instance of an s-attribute.
Enumeration Type Documentation
_field_type
enum _field_type
The FieldType object represents the fields (or 'anchor points') of a subcorpus (inc query result).
NoField is always the last field (so it can be used to determine range of field type codes) (the mnemonic is NoField = "no field" = "number of field types")
Enumerator
MatchField
MatchEndField
TargetField
KeywordField
NoField
case_mode
enum case_mode
An enumeration for lowercase vs.
uppercase mode.
Enumerator
LOWER
UPPER
corpus_type
enum corpus_type
Underlying enumeration for CorpusType.
Gives an identifier for each "type" of corpus CQP can deal with.
Enumerator
UNDEF
undefined status
SYSTEM
system corpus, ie registered corpus
SUB
subcorpus which was generated by a query
TEMP
temporary subcorpus, deleted after query
ALL
any type of corpus
Function Documentation
access_corpus()
Boolean access_corpus (CorpusList * cl)
Assesses whether a specified corpus can be accessed.
That is, it makes sure that the data for corpus in "cl" is loaded and accessible.
Parameters
cl A CorpusList specifying the corpus/NQR to check.
Returns
A boolean - true if cl can be accessed.
References attach_subcorpus(), False, cl::loaded, cl::range, cl::saved, cl::size, SUB, SYSTEM, TEMP, True, and cl::type.
Referenced by apply_setop_to_matchlist(), cat_listed_corpus(), cqi_find_corpus(), cqi_lookup_attribute(), do_cqi_corpus_attributes(), do_cqi_corpus_charset(), do_cqi_corpus_full_name(), findcorpus(), prepare_AlignmentConstraints(), prepare_Query(), SortSubcorpus(), and SortSubcorpusRandomize().
assign_temp_to_sub()
CorpusList* assign_temp_to_sub (CorpusList * tmp, char * subname)
Convert a temporary corpus to a real subcorpus.
assign_temp_to_sub assigns the temporary corpus in *tmp to a "real" subcorpus with name "subname". If such a subcorpus already exists, it is overwritten. The temporary corpus is deleted afterwards. The return value is the new subcorpus (which may be equal to tmp, but not necessarily).
Parameters
tmp Temporary corpus to convert.
subname Name to use for new subcorpus.
Returns
Pointer to new subcorpus.
References cl::abs_fn, auto_save, cl_free, cl_strdup(), cl::corpus, dropcorpus(), False, findcorpus(), initialize_cl(), cl::keywords, cl::loaded, cl::mother_name, cl::mother_size, cl::name, cl::needs_update, cl::query_corpus, cl::query_text, cl::range, cl::registry, save_subcorpus(), cl::saved, cl::size, cl::sortidx, SUB, cl::targets, TEMP, True, cl::type, and UNDEF.
Referenced by do_undump(), and in_UnnamedCorpusCommand().
check_available_corpora()
void check_available_corpora (CorpusType ct)
Check what corpora of a given type are available on disk.
References data_directory, load_corpusnames(), set_current_corpus(), SUB, SYSTEM, TEMP, and UNDEF.
Referenced by execute_side_effects(), and initialize_cqp().
drop_all_corpora()
void drop_all_corpora (void)
Release all memory from the global corpus list.
References corpuslist, current_corpus, destruct_cl(), and cl::next.
Referenced by cqp_cleanup_memory().
drop_temp_corpora()
void drop_temp_corpora (void)
Delete temporary corpora, clearing the global list of corpora of all temporary stuff.
References corpuslist, dropcorpus(), cl::next, TEMP, and cl::type.
Referenced by do_undump(), in_UnnamedCorpusCommand(), and load_corpusnames().
dropcorpus()
CorpusList* dropcorpus (CorpusList * cl, CorpusList * search_from)
Remove a corpus from the global list of corpora.
See also
corpuslist
Parameters
cl The corpus to drop. If NULL, nothing happens.
search_from If NULL, dropcorpus searches from the start of the global list. Otherwise, it starts at the point indicated – which must be an item known to be BEFORE cl in the global list, or else the global list itself. (This makes looping through the whole corpuslist, and deleting some, more efficient.)
Returns
Pointer to previous item on the linked list (which now directly precedes the next item) or, if the first item was deleted, to the new head of the list. Only of use if it is fed back to "search_from" in a subsequent iteration of a loop through the corpuslist (but with caution: if the first item was deleted, it now points to the following item in the list, which must not be skipped in the next iteration). Returns NULL if the dropped corpus was not found on the part of the list searched or if it was the only corpus in corpuslist (which is now empty). See drop_temp_corpora().
References corpuslist, current_corpus, destruct_cl(), cl::next, and set_current_corpus().
Referenced by assign_temp_to_sub(), attach_subcorpus(), do_cqi_cqp_drop_subcorpus(), drop_temp_corpora(), ensure_corpus_size(), and main().
duplicate_corpus()
CorpusList* duplicate_corpus (CorpusList * cl, char * new_name, Boolean force_overwrite)
Duplicate a CorpusList object.
duplicate_corpus creates a copy of an existing corpus and casts its type to SUB. The new corpus is given the name "new_name". If a subcorpus of that name is already present, NULL is returned if force_overwrite is False. If force_overwrite is True, the old corpus is discarded.
This is used for commands likel, for instance,
Parameters
cl The corpus to duplicate
new_name Name for the duplicated corpus.
force_overwrite Boolean: whether or not to force an overwrite if the subcorpus you are attempting to create already exists.
Returns
NULL if you attempted to overwrite with force_overwrite == false. Otherwise, a CorpusList pointer to the new corpus.
References cl::abs_fn, auto_save, cl_malloc(), cl_strdup(), cl::corpus, corpuslist, cqpmessage(), False, initialize_cl(), cl::keywords, cl::loaded, LoadedCorpus(), cl::mother_name, cl::mother_size, cl::name, cl::needs_update, NewCL(), cl::next, cl::query_corpus, cl::query_text, cl::range, cl::registry, save_subcorpus(), cl::saved, cl::size, cl::sortidx, SUB, SYSTEM, cl::targets, True, cl::type, and Warning.
Referenced by findcorpus(), and in_CorpusCommand().
field_name_to_type()
FieldType field_name_to_type (const char * name)
Returns a FieldType enumeration corresponding to the field name indicated by its string argument.
References cl_streq_ci, KeywordField, MatchEndField, MatchField, NoField, and TargetField.
Referenced by do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), and label_lookup().
field_type_to_name()
const char* field_type_to_name (FieldType field)
Returns a pointer to an internal constant string that labels the FieldType argument.
References cqpmessage(), Error, KeywordField, MatchEndField, MatchField, NoField, and TargetField.
Referenced by do_AnchorPoint(), and prepare_do_subset().
findcorpus()
CorpusList* findcorpus (char * s, CorpusType type, int try_recursive_search)
Finds the pointer to the corpus (or subcorpus, or query result) with the given name.
When searching for s (name of corpus) strcmp() is used; no case conversion is done.
If "type" is UNDEF, it returns the first corpus with matching name. Otherwise the returned corpus has the type "type".
Parameters
s Name of the corpus to find (as string)
type If this is UNDEF, all corpora are checked; if it is any other type, only corpora of that type are checked.
try_recursive_search Boolean: whether or not to try to find corpus through implicit expansion.
Returns
Pointer to the CorpusList object for the specified corpus. NULL is returned when the corpus is not yet present.
References access_corpus(), apply_range_set_operation(), ATT_STRUC, ctxtsp::attrib, calculate_leftboundary(), calculate_rightboundary(), CL_MAX_LINE_LENGTH, cl_new_attribute(), cl_strcpy(), COLON, cl::corpus, cqpmessage(), ctxtdir_leftright, ctxtsp::direction, duplicate_corpus(), Range::end, ensure_corpus_size(), expansion, LoadedCorpus(), cl::mother_name, cl::range, RUniq, cl::size, ctxtsp::size, SLASH, ctxtsp::space_type, Range::start, structure, SYSTEM, touch_corpus(), True, cl::type, and Warning.
Referenced by assign_temp_to_sub(), corpus_info(), cqi_find_corpus(), cqi_lookup_attribute(), do_cqi_corpus_attributes(), do_cqi_corpus_charset(), do_cqi_corpus_full_name(), do_RegionElement(), do_translate(), do_undump(), make_temp_corpus(), prepare_AlignmentConstraints(), and set_current_corpus_name().
FirstCorpusFromList()
CorpusList* FirstCorpusFromList ()
Gets the CorpusList pointer for the first corpus on the currently-loaded list.
Function for iterating through the list of currently-loaded corpora.
Returns
The requested CorpusList pointer.
References corpuslist.
Referenced by do_cqi_corpus_list_corpora(), do_cqi_cqp_list_subcorpora(), and main().
init_global_corpuslist()
void init_global_corpuslist (void)
Initialises the global corpus list (sets it to NULL, no matter what its value was).
References corpuslist, and set_current_corpus().
Referenced by initialize_cqp().
LoadedCorpus()
CorpusList* LoadedCorpus (char * name, char * qualifier, CorpusType type)
Finds a loaded corpus.
This function tries to find the corpus with name 'name' in the list of currently loaded corpora. In case of subcorpora, qualifier is the mother's name. in case of system corpora, qualifier is the registry. If qualifier is NULL, it is neglected and the first matching corpus is returned. If type is not UNDEF, only a corpus of that type can be returned. No side effects take place.
Parameters
name The corpus we are looking for.
qualifier An extra "bit" of the corpus name (see function description).
type Which type of corpus is wanted (may be UNDEF, which finds any except TEMP).
Returns
Pointer to the CorpusList of the corpus that was found, or NULL if not found.
References cl_streq, corpuslist, current_corpus, cl::mother_name, cl::name, cl::next, cl::registry, SUB, SYSTEM, TEMP, cl::type, and UNDEF.
Referenced by duplicate_corpus(), ensure_syscorpus(), findcorpus(), and load_corpusnames().
make_temp_corpus()
CorpusList* make_temp_corpus (CorpusList * cl, char * new_name)
Copy a corpus as type TEMP.
make_temp_corpus makes a copy of the corpus in *cl into a corpus of type "TEMP" with name "new_name". If a temporary corpus with that name already exists, it is overwritten.
TODO this is a replica of LOTS AND LOTS of the code from duplicate_corpus.
Parameters
cl The corpus to copy.
new_name Name for the temporary copy.
Returns
NULL for error. Otherwise, a CorpusList pointer to the new corpus.
References cl::abs_fn, cl_malloc(), cl_strdup(), cl::corpus, corpuslist, False, findcorpus(), initialize_cl(), cl::keywords, cl::loaded, cl::mother_name, cl::mother_size, cl::name, cl::needs_update, NewCL(), cl::next, cl::query_corpus, cl::query_text, cl::range, cl::registry, cl::saved, cl::size, cl::sortidx, cl::targets, TEMP, True, and cl::type.
Referenced by do_setop(), do_translate(), do_undump(), in_UnnamedCorpusCommand(), prepare_do_subset(), and prepare_Query().
NextCorpusFromList()
CorpusList* NextCorpusFromList (CorpusList * cl)
Gets the CorpusList pointer for the next corpus on the currently-loaded list.
Function for iterating through the list of currently-loaded corpora.
Parameters
cl The current corpus on the list.
Returns
The requested CorpusList pointer.
References cl::next.
Referenced by do_cqi_corpus_list_corpora(), do_cqi_cqp_list_subcorpora(), and main().
save_subcorpus()
Boolean save_subcorpus (CorpusList * cl, char * fname)
Save a subcorpus/NQR to disk.
Parameters
cl
fname String, filename.
Returns
References cl::abs_fn, cl_close_stream(), CL_MAX_FILENAME_LENGTH, cl_open_stream(), CL_STREAM_MAGIC, CL_STREAM_WRITE_BIN, cqpmessage(), CWB_SUBCORPMAGIC_NEW, data_directory, False, cl::keywords, cl::loaded, cl::mother_name, cl::name, cl::needs_update, cl::range, cl::registry, cl::saved, cl::size, cl::sortidx, SUB, SUBDIR_SEPARATOR, cl::targets, True, cl::type, and Warning.
Referenced by after_CorpusCommand(), assign_temp_to_sub(), delete_intervals(), do_save(), duplicate_corpus(), and save_unsaved_subcorpora().
save_unsaved_subcorpora()
void save_unsaved_subcorpora ()
References corpuslist, cqpmessage(), data_directory, cl::next, save_subcorpus(), cl::saved, SUB, cl::type, and Warning.
Referenced by main().
set_current_corpus()
int set_current_corpus (CorpusList * cp, int force)
Sets the current corpus (by pointer to the corpus).
Parameters
cp Pointer to the corpus to set as current. cp may be NULL, which is legal.
force If true, the current corpus is set to the specified corpus, even if it is ALREADY set to that corpus.
Returns
Always 1.
References ContextDescriptor::attributes, CD, cl::corpus, current_corpus, CWB_DEFAULT_ATT_NAME, DestroyAttributeList(), FindInAL(), _attlist::list, _attrbuf::next, _attrbuf::status, ContextDescriptor::strucAttributes, and update_context_descriptor().
Referenced by after_CorpusCommand(), check_available_corpora(), cqi_activate_corpus(), dropcorpus(), init_global_corpuslist(), and set_current_corpus_name().
set_current_corpus_name()
int set_current_corpus_name (char * name, int force)
Sets the current corpus (by name).
Parameters
name Name of the corpus to set as current.
force If true, the current corpus is set to the specified corpus, even if it is ALREADY set to that corpus.
Returns
True if the corpus was found and set, otherwise false if the corpus could not be found.
References findcorpus(), set_current_corpus(), and UNDEF.
Referenced by initialize_cqp().
show_corpora()
void show_corpora (CorpusType type)
A function to print out a list of corpora currently available.
Either system corpora (SYSTEM) or subcorpora (SUB) can be shown, depending on ct. If type is UNDEF, both are shown.
For subcorpora, a bundle of other information is shown too.
Parameters
type Type of corpus to show (SUB, SYSTEM or UNDEF).
References show_corpora_backend(), SUB, SYSTEM, and UNDEF.
show_corpus_active()
void show_corpus_active (void)
Displays the ID of the active corpus.
(Including any activated subcorpus/NQR.) (Added for child mode mostly.)
References ALL, and show_corpora_backend().
split_subcorpus_name()
char* split_subcorpus_name (const char * corpusname, char * mother_name)
Splits a query result "corpus"-name into qualifier and local name.
This function splits query result name {corpusname} into qualifier (name of mother corpus) and local name; returns pointer to local name part, or NULL if {corpusname} is not syntactically valid.
if mother_name is not NULL, it must point to a buffer of suitable length (CL_MAX_LINE_LENGTH is sufficient) where the qualifier will be stored (empty string for unqualified corpus, and return value == {corpusname} in this case)
Parameters
corpusname "Corpus" name to process. This is not really a corpus but a query result or subcorpus, in the form CORPUS:TheQuery. It won't be modified.
mother_name Buffer for a copy of the qualifer (first part of name, aka the mother, aka the corpus). When using split_subcorpus_name as a syntax validator for possibly qualified names, this would normally be NULL.
Returns
Pointer into the corpusname buffer, at the point where the second part (the subcorpus/query name) begins. NULL is returned if, at any point in corpusname, there is a character that should not be there.
References COLON.
Referenced by do_undump(), and valid_subcorpus_name().
subcorpus_name_is_qualified()
Boolean subcorpus_name_is_qualified (const char * corpusname)
Checks whether corpusname is qualified (with name of mother corpus); does not imply syntatic validity.
References COLON.
Referenced by do_undump(), and in_CorpusCommand().
touch_corpus()
int touch_corpus (CorpusList * cp)
Touches a corpus, ie, marks it as changed.
Parameters
cp The corpus to touch. This must be of type SUB.
Returns
Boolean: true if the touch worked, otherwise false.
References cl::needs_update, cl::saved, SUB, and cl::type.
Referenced by apply_range_set_operation(), delete_intervals(), do_cut(), evaluate_target(), findcorpus(), set_target(), SortSubcorpus(), and SortSubcorpusRandomize().
valid_subcorpus_name()
Boolean valid_subcorpus_name (char * corpusname)
Checks whether corpusname is syntactically valid as a query result name, i.e., either.
identifier
or qualifier.identifier
References split_subcorpus_name().
Referenced by do_undump().
Variable Documentation
current_corpus
CorpusList* current_corpus extern
Global pointer to the "current" corpus.
Referenced by cqp_parse_file(), do_attribute_show(), do_MUQuery(), do_StandardQuery(), do_undump(), drop_all_corpora(), dropcorpus(), execute_side_effects(), in_CorpusCommand(), LoadedCorpus(), prepare_Query(), set_current_corpus(), and show_corpora_backend().