CWB: cqp/corpmanag.c File Reference
corpmanag.c File Reference
#include <stddef.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <dirent.h>
#include <unistd.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include "../cl/cl.h"
#include "../cl/fileutils.h"
#include "../cl/ui-helpers.h"
#include "corpmanag.h"
#include "cqp.h"
#include "options.h"
#include "output.h"
#include "ranges.h"
Macros
#define COLON ':'
#define SLASH '^'
#define subcorpload_debug 0
If this is 1, then debug info is printed on subcorpus load.
Functions
static Boolean attach_subcorpus (CorpusList *cl, char *advertised_directory, char *advertised_filename)
Reads in a sbcorpus/NQR that was previously saved to disk.
static CorpusList * GetSystemCorpus (char *name, char *registry)
Creates a CorpusList object for a named system corpus in a specific registry directory.
static void initialize_cl (CorpusList *cl, int free_name)
Resets a CorpusList object to empty.
void init_global_corpuslist (void)
Initialises the global corpus list (sets it to NULL, no matter what its value was).
static void destruct_cl (CorpusList *cl)
Backend destructor for CorpusList object.
static CorpusList * NewCL (void)
Creates a new CorpusList object.
FieldType field_name_to_type (const char *name)
Returns a FieldType enumeration corresponding to the field name indicated by its string argument.
const char * field_type_to_name (FieldType ft)
Returns a pointer to an internal constant string that labels the FieldType argument.
static int SystemCorpusSize (Corpus *corpus)
A utility function required by ensure_corpus_size()
static Boolean ensure_corpus_size (CorpusList *cl)
This is an internal function used to ensure that a system corpus from the corpus list is accessible and that its size has been computed.
CorpusList * LoadedCorpus (char *name, char *qualifier, CorpusType type)
Finds a loaded corpus.
CorpusList * findcorpus (char *s, CorpusType type, int try_recursive_search)
Finds the pointer to the corpus (or subcorpus, or query result) with the given name.
CorpusList * dropcorpus (CorpusList *cl, CorpusList *search_from)
Remove a corpus from the global list of corpora.
CorpusList * duplicate_corpus (CorpusList *cl, char *new_name, Boolean force_overwrite)
Duplicate a CorpusList object.
CorpusList * make_temp_corpus (CorpusList *cl, char *new_name)
Copy a corpus as type TEMP.
CorpusList * assign_temp_to_sub (CorpusList *tmp, char *subname)
Convert a temporary corpus to a real subcorpus.
void drop_temp_corpora (void)
Delete temporary corpora, clearing the global list of corpora of all temporary stuff.
void drop_all_corpora (void)
Release all memory from the global corpus list.
static char * get_fulllocalpath (CorpusList *cl, int qualify)
Returns a newly allocated string representing a disk location for a saved subcorpus.
static Boolean is_readable_file (char *dir, char *file)
Tests whether a file is accessible.
static void load_corpusnames (enum corpus_type ct)
Looks for loadable corpora on disk in the usual places (so: registry - global or default - for system corpora; data directory for subcorpora; etc.)
void check_available_corpora (CorpusType ct)
Check what corpora of a given type are available on disk.
static CorpusList * ensure_syscorpus (char *registry, char *name)
Boolean save_subcorpus (CorpusList *cl, char *fname)
Save a subcorpus/NQR to disk.
void save_unsaved_subcorpora (void)
CorpusList * FirstCorpusFromList ()
Gets the CorpusList pointer for the first corpus on the currently-loaded list.
CorpusList * NextCorpusFromList (CorpusList *cl)
Gets the CorpusList pointer for the next corpus on the currently-loaded list.
Boolean access_corpus (CorpusList *cl)
Assesses whether a specified corpus can be accessed.
Boolean valid_subcorpus_name (char *corpusname)
Checks whether corpusname is syntactically valid as a query result name, i.e., either.
Boolean subcorpus_name_is_qualified (const char *corpusname)
Checks whether corpusname is qualified (with name of mother corpus); does not imply syntatic validity.
char * split_subcorpus_name (const char *corpusname, char *mother_name)
Splits a query result "corpus"-name into qualifier and local name.
int touch_corpus (CorpusList *cp)
Touches a corpus, ie, marks it as changed.
int set_current_corpus (CorpusList *cp, int force)
Sets the current corpus (by pointer to the corpus).
int set_current_corpus_name (char *name, int force)
Sets the current corpus (by name).
static int show_corpora_sort (const void *p1, const void *p2)
Internal function for sorting list of corpus names.
static void show_corpora_backend (CorpusType ct, int only_active_corpus)
Function that does the work for show_corpora_files.
void show_corpora (CorpusType type)
A function to print out a list of corpora currently available.
void show_corpus_active (void)
Displays the ID of the active corpus.
Variables
static CorpusList * corpuslist = NULL
Global pointer to the head of CQP's linked list of the currently-loaded corpora (and NQRs).
CorpusList * current_corpus
Global pointer to the "current" corpus.
Macro Definition Documentation
COLON
#define COLON ':'
SLASH
#define SLASH '^'
subcorpload_debug
#define subcorpload_debug 0
If this is 1, then debug info is printed on subcorpus load.
Function Documentation
access_corpus()
Boolean access_corpus (CorpusList * cl)
Assesses whether a specified corpus can be accessed.
That is, it makes sure that the data for corpus in "cl" is loaded and accessible.
Parameters
cl A CorpusList specifying the corpus/NQR to check.
Returns
A boolean - true if cl can be accessed.
References attach_subcorpus(), False, cl::loaded, cl::range, cl::saved, cl::size, SUB, SYSTEM, TEMP, True, and cl::type.
Referenced by apply_setop_to_matchlist(), cat_listed_corpus(), cqi_find_corpus(), cqi_lookup_attribute(), do_cqi_corpus_attributes(), do_cqi_corpus_charset(), do_cqi_corpus_full_name(), findcorpus(), prepare_AlignmentConstraints(), prepare_Query(), SortSubcorpus(), and SortSubcorpusRandomize().
assign_temp_to_sub()
CorpusList* assign_temp_to_sub (CorpusList * tmp, char * subname)
Convert a temporary corpus to a real subcorpus.
assign_temp_to_sub assigns the temporary corpus in *tmp to a "real" subcorpus with name "subname". If such a subcorpus already exists, it is overwritten. The temporary corpus is deleted afterwards. The return value is the new subcorpus (which may be equal to tmp, but not necessarily).
Parameters
tmp Temporary corpus to convert.
subname Name to use for new subcorpus.
Returns
Pointer to new subcorpus.
References cl::abs_fn, auto_save, cl_free, cl_strdup(), cl::corpus, dropcorpus(), False, findcorpus(), initialize_cl(), cl::keywords, cl::loaded, cl::mother_name, cl::mother_size, cl::name, cl::needs_update, cl::query_corpus, cl::query_text, cl::range, cl::registry, save_subcorpus(), cl::saved, cl::size, cl::sortidx, SUB, cl::targets, TEMP, True, cl::type, and UNDEF.
Referenced by do_undump(), and in_UnnamedCorpusCommand().
attach_subcorpus()
static Boolean attach_subcorpus (CorpusList * cl, char * advertised_directory, char * advertised_filename) static
Reads in a sbcorpus/NQR that was previously saved to disk.
Parameters
cl Corpus we're currently working in.
advertised_directory
advertised_filename
Returns
Boolean: whether the file was loaded correctly.
References cl::abs_fn, cl_close_stream(), cl_free, cl_malloc(), CL_MAX_FILENAME_LENGTH, cl_open_stream(), cl_strcpy(), cl_strdup(), CL_STREAM_MAGIC, CL_STREAM_READ_BIN, cl::corpus, cqpmessage(), CWB_SUBCORPMAGIC_NEW, CWB_SUBCORPMAGIC_ORIG, dropcorpus(), Range::end, ensure_syscorpus(), False, file_length(), get_fulllocalpath(), initialize_cl(), cl::keywords, cl::loaded, cl::mother_name, cl::mother_size, cl::name, cl::needs_update, cl::range, cl::registry, cl::saved, cl::size, cl::sortidx, Range::start, SUB, SUBDIR_SEP_STRING, SUBDIR_SEPARATOR, cl::targets, TEMP, True, cl::type, and Warning.
Referenced by access_corpus(), and ensure_corpus_size().
check_available_corpora()
void check_available_corpora (CorpusType ct)
Check what corpora of a given type are available on disk.
References data_directory, load_corpusnames(), set_current_corpus(), SUB, SYSTEM, TEMP, and UNDEF.
Referenced by execute_side_effects(), and initialize_cqp().
destruct_cl()
static void destruct_cl (CorpusList * cl) static
Backend destructor for CorpusList object.
Unlike dropcorpus(), it doesn't check the global corpuslist.
References cl_free, initialize_cl(), and True.
Referenced by drop_all_corpora(), and dropcorpus().
drop_all_corpora()
void drop_all_corpora (void)
Release all memory from the global corpus list.
References corpuslist, current_corpus, destruct_cl(), and cl::next.
Referenced by cqp_cleanup_memory().
drop_temp_corpora()
void drop_temp_corpora (void)
Delete temporary corpora, clearing the global list of corpora of all temporary stuff.
References corpuslist, dropcorpus(), cl::next, TEMP, and cl::type.
Referenced by do_undump(), in_UnnamedCorpusCommand(), and load_corpusnames().
dropcorpus()
CorpusList* dropcorpus (CorpusList * cl, CorpusList * search_from)
Remove a corpus from the global list of corpora.
See also
corpuslist
Parameters
cl The corpus to drop. If NULL, nothing happens.
search_from If NULL, dropcorpus searches from the start of the global list. Otherwise, it starts at the point indicated – which must be an item known to be BEFORE cl in the global list, or else the global list itself. (This makes looping through the whole corpuslist, and deleting some, more efficient.)
Returns
Pointer to previous item on the linked list (which now directly precedes the next item) or, if the first item was deleted, to the new head of the list. Only of use if it is fed back to "search_from" in a subsequent iteration of a loop through the corpuslist (but with caution: if the first item was deleted, it now points to the following item in the list, which must not be skipped in the next iteration). Returns NULL if the dropped corpus was not found on the part of the list searched or if it was the only corpus in corpuslist (which is now empty). See drop_temp_corpora().
References corpuslist, current_corpus, destruct_cl(), cl::next, and set_current_corpus().
Referenced by assign_temp_to_sub(), attach_subcorpus(), do_cqi_cqp_drop_subcorpus(), drop_temp_corpora(), ensure_corpus_size(), and main().
duplicate_corpus()
CorpusList* duplicate_corpus (CorpusList * cl, char * new_name, Boolean force_overwrite)
Duplicate a CorpusList object.
duplicate_corpus creates a copy of an existing corpus and casts its type to SUB. The new corpus is given the name "new_name". If a subcorpus of that name is already present, NULL is returned if force_overwrite is False. If force_overwrite is True, the old corpus is discarded.
This is used for commands likel, for instance,
Parameters
cl The corpus to duplicate
new_name Name for the duplicated corpus.
force_overwrite Boolean: whether or not to force an overwrite if the subcorpus you are attempting to create already exists.
Returns
NULL if you attempted to overwrite with force_overwrite == false. Otherwise, a CorpusList pointer to the new corpus.
References cl::abs_fn, auto_save, cl_malloc(), cl_strdup(), cl::corpus, corpuslist, cqpmessage(), False, initialize_cl(), cl::keywords, cl::loaded, LoadedCorpus(), cl::mother_name, cl::mother_size, cl::name, cl::needs_update, NewCL(), cl::next, cl::query_corpus, cl::query_text, cl::range, cl::registry, save_subcorpus(), cl::saved, cl::size, cl::sortidx, SUB, SYSTEM, cl::targets, True, cl::type, and Warning.
Referenced by findcorpus(), and in_CorpusCommand().
ensure_corpus_size()
static Boolean ensure_corpus_size (CorpusList * cl) static
This is an internal function used to ensure that a system corpus from the corpus list is accessible and that its size has been computed.
In case of subcorpora, this function implements delayed loading. It is necessary because of a hack that prevents CQP from determining the sizes of all know corpora at start-up (which caused annoying delays if one or more corpora are not accessible) and from reading all subcorpora in the local corpus directory (which caused a number of delays and crashes with MP templates). ensure_corpus_size() is needed by findcorpus() and ensure_syscorpus() at the very least. It may be needed in other places to keep CQP from crashing.
Parameters
cl The corpus whose accessibility is to be checked.
Returns
Boolean: true if access is OK.
References attach_subcorpus(), cl_errno, cl_error_string(), CL_MAX_FILENAME_LENGTH, cl::corpus, cqpmessage(), dropcorpus(), Range::end, False, cl::loaded, cl::local_dir, cl::mother_name, cl::mother_size, cl::name, cl::range, SUB, SYSTEM, SystemCorpusSize(), True, cl::type, and Warning.
Referenced by ensure_syscorpus(), and findcorpus().
ensure_syscorpus()
static CorpusList* ensure_syscorpus (char * registry, char * name) static
References corpuslist, ensure_corpus_size(), GetSystemCorpus(), LoadedCorpus(), cl::next, registry, and SYSTEM.
Referenced by attach_subcorpus().
field_name_to_type()
FieldType field_name_to_type (const char * name)
Returns a FieldType enumeration corresponding to the field name indicated by its string argument.
References cl_streq_ci, KeywordField, MatchEndField, MatchField, NoField, and TargetField.
Referenced by do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), and label_lookup().
field_type_to_name()
const char* field_type_to_name (FieldType ft)
Returns a pointer to an internal constant string that labels the FieldType argument.
References cqpmessage(), Error, KeywordField, MatchEndField, MatchField, NoField, and TargetField.
Referenced by do_AnchorPoint(), and prepare_do_subset().
findcorpus()
CorpusList* findcorpus (char * s, CorpusType type, int try_recursive_search)
Finds the pointer to the corpus (or subcorpus, or query result) with the given name.
When searching for s (name of corpus) strcmp() is used; no case conversion is done.
If "type" is UNDEF, it returns the first corpus with matching name. Otherwise the returned corpus has the type "type".
Parameters
s Name of the corpus to find (as string)
type If this is UNDEF, all corpora are checked; if it is any other type, only corpora of that type are checked.
try_recursive_search Boolean: whether or not to try to find corpus through implicit expansion.
Returns
Pointer to the CorpusList object for the specified corpus. NULL is returned when the corpus is not yet present.
References access_corpus(), apply_range_set_operation(), ATT_STRUC, ctxtsp::attrib, calculate_leftboundary(), calculate_rightboundary(), CL_MAX_LINE_LENGTH, cl_new_attribute(), cl_strcpy(), COLON, cl::corpus, cqpmessage(), ctxtdir_leftright, ctxtsp::direction, duplicate_corpus(), Range::end, ensure_corpus_size(), expansion, LoadedCorpus(), cl::mother_name, cl::range, RUniq, cl::size, ctxtsp::size, SLASH, ctxtsp::space_type, Range::start, structure, SYSTEM, touch_corpus(), True, cl::type, and Warning.
Referenced by assign_temp_to_sub(), corpus_info(), cqi_find_corpus(), cqi_lookup_attribute(), do_cqi_corpus_attributes(), do_cqi_corpus_charset(), do_cqi_corpus_full_name(), do_RegionElement(), do_translate(), do_undump(), make_temp_corpus(), prepare_AlignmentConstraints(), and set_current_corpus_name().
FirstCorpusFromList()
CorpusList* FirstCorpusFromList ()
Gets the CorpusList pointer for the first corpus on the currently-loaded list.
Function for iterating through the list of currently-loaded corpora.
Returns
The requested CorpusList pointer.
References corpuslist.
Referenced by do_cqi_corpus_list_corpora(), do_cqi_cqp_list_subcorpora(), and main().
get_fulllocalpath()
static char* get_fulllocalpath (CorpusList * cl, int qualify) static
Returns a newly allocated string representing a disk location for a saved subcorpus.
(within the current datadir).
In this format:
     /path/to/datadir/MOTHERCORPUS:Subcorpus
Parameters
cl Record of the subcorpus/NQR whose path we're building.
qualify Boolean. If true, assume that the name DOES need to be prefixed with MOTHERCORPUS: . If false, assume that the name can just be combined with the datadir path.
Returns
Newly allocated string, in the format described above
References cl_free, cl_id_toupper(), CL_MAX_FILENAME_LENGTH, cl_strdup(), data_directory, cl::mother_name, cl::name, SUBDIR_SEP_STRING, and SUBDIR_SEPARATOR.
Referenced by attach_subcorpus().
GetSystemCorpus()
static CorpusList * GetSystemCorpus (char * name, char * registry) static
Creates a CorpusList object for a named system corpus in a specific registry directory.
Returns
Either a pointer to the CorpusList OR NULL if the corpus could not be loaded.
References cl::abs_fn, cl_free, cl_id_tolower(), cl_malloc(), cl_new_corpus(), cl_strdup(), cl::corpus, Range::end, False, cl::keywords, cl::loaded, cl::mother_name, cl::mother_size, cl::name, cl::needs_update, NewCL(), cl::next, cl::range, cl::registry, registry, TCorpus::registry_dir, cl::saved, cl::size, cl::sortidx, Range::start, SYSTEM, cl::targets, True, and cl::type.
Referenced by ensure_syscorpus(), and load_corpusnames().
init_global_corpuslist()
void init_global_corpuslist (void)
Initialises the global corpus list (sets it to NULL, no matter what its value was).
References corpuslist, and set_current_corpus().
Referenced by initialize_cqp().
initialize_cl()
static void initialize_cl (CorpusList * cl, int free_name) static
Resets a CorpusList object to empty.
This is done, largely, by freeing all its members (and setting other members to 0 or NULL)...
Parameters
cl The corpus list to initialise.
free_name Boolean: the name, mother_name and mother_size members will be cleared iff free_name.
References cl::abs_fn, cl::cd, cl_free, cl::corpus, False, cl::keywords, cl::loaded, cl::mother_name, cl::mother_size, cl::name, cl::needs_update, cl::query_corpus, cl::query_text, cl::range, cl::registry, cl::saved, cl::size, cl::sortidx, cl::targets, cl::type, and UNDEF.
Referenced by assign_temp_to_sub(), attach_subcorpus(), destruct_cl(), duplicate_corpus(), and make_temp_corpus().
is_readable_file()
static Boolean is_readable_file (char * dir, char * file) static
Tests whether a file is accessible.
A file is considered accessible iff user can read it and it is not a (sub)directory.
This test is used for registry entries.
Parameters
dir Directory in which the file is to be found.
file The filename to check.
Returns
Boolean: true iff file is accessible.
References cl_free, cl_malloc(), SUBDIR_SEP_STRING, and SUBDIR_SEPARATOR.
Referenced by load_corpusnames().
load_corpusnames()
static void load_corpusnames (enum corpus_type ct) static
Looks for loadable corpora on disk in the usual places (so: registry - global or default - for system corpora; data directory for subcorpora; etc.)
References cl_free, cl_id_toupper(), CL_MAX_FILENAME_LENGTH, CL_MAX_LINE_LENGTH, cl_path_get_component(), cl_standard_registry(), cl_strcpy(), cl_strdup(), COLON, corpus, corpuslist, cqpmessage(), data_directory, drop_temp_corpora(), False, GetSystemCorpus(), is_readable_file(), LoadedCorpus(), TCorpus::name, NewCL(), TCorpus::next, registry, silent, SUB, SYSTEM, TEMP, True, and Warning.
Referenced by check_available_corpora().
LoadedCorpus()
CorpusList* LoadedCorpus (char * name, char * qualifier, CorpusType type)
Finds a loaded corpus.
This function tries to find the corpus with name 'name' in the list of currently loaded corpora. In case of subcorpora, qualifier is the mother's name. in case of system corpora, qualifier is the registry. If qualifier is NULL, it is neglected and the first matching corpus is returned. If type is not UNDEF, only a corpus of that type can be returned. No side effects take place.
Parameters
name The corpus we are looking for.
qualifier An extra "bit" of the corpus name (see function description).
type Which type of corpus is wanted (may be UNDEF, which finds any except TEMP).
Returns
Pointer to the CorpusList of the corpus that was found, or NULL if not found.
References cl_streq, corpuslist, current_corpus, cl::mother_name, cl::name, cl::next, cl::registry, SUB, SYSTEM, TEMP, cl::type, and UNDEF.
Referenced by duplicate_corpus(), ensure_syscorpus(), findcorpus(), and load_corpusnames().
make_temp_corpus()
CorpusList* make_temp_corpus (CorpusList * cl, char * new_name)
Copy a corpus as type TEMP.
make_temp_corpus makes a copy of the corpus in *cl into a corpus of type "TEMP" with name "new_name". If a temporary corpus with that name already exists, it is overwritten.
TODO this is a replica of LOTS AND LOTS of the code from duplicate_corpus.
Parameters
cl The corpus to copy.
new_name Name for the temporary copy.
Returns
NULL for error. Otherwise, a CorpusList pointer to the new corpus.
References cl::abs_fn, cl_malloc(), cl_strdup(), cl::corpus, corpuslist, False, findcorpus(), initialize_cl(), cl::keywords, cl::loaded, cl::mother_name, cl::mother_size, cl::name, cl::needs_update, NewCL(), cl::next, cl::query_corpus, cl::query_text, cl::range, cl::registry, cl::saved, cl::size, cl::sortidx, cl::targets, TEMP, True, and cl::type.
Referenced by do_setop(), do_translate(), do_undump(), in_UnnamedCorpusCommand(), prepare_do_subset(), and prepare_Query().
NewCL()
static CorpusList* NewCL (void) static
Creates a new CorpusList object.
References cl::abs_fn, cl::cd, cl_malloc(), cl::corpus, False, cl::keywords, cl::loaded, cl::local_dir, cl::mother_name, cl::mother_size, cl::name, cl::needs_update, cl::next, cl::query_corpus, cl::query_text, cl::range, cl::registry, cl::saved, cl::size, cl::sortidx, cl::targets, cl::type, and UNDEF.
Referenced by duplicate_corpus(), GetSystemCorpus(), load_corpusnames(), and make_temp_corpus().
NextCorpusFromList()
CorpusList* NextCorpusFromList (CorpusList * cl)
Gets the CorpusList pointer for the next corpus on the currently-loaded list.
Function for iterating through the list of currently-loaded corpora.
Parameters
cl The current corpus on the list.
Returns
The requested CorpusList pointer.
References cl::next.
Referenced by do_cqi_corpus_list_corpora(), do_cqi_cqp_list_subcorpora(), and main().
save_subcorpus()
Boolean save_subcorpus (CorpusList * cl, char * fname)
Save a subcorpus/NQR to disk.
Parameters
cl
fname String, filename.
Returns
References cl::abs_fn, cl_close_stream(), CL_MAX_FILENAME_LENGTH, cl_open_stream(), CL_STREAM_MAGIC, CL_STREAM_WRITE_BIN, cqpmessage(), CWB_SUBCORPMAGIC_NEW, data_directory, False, cl::keywords, cl::loaded, cl::mother_name, cl::name, cl::needs_update, cl::range, cl::registry, cl::saved, cl::size, cl::sortidx, SUB, SUBDIR_SEPARATOR, cl::targets, True, cl::type, and Warning.
Referenced by after_CorpusCommand(), assign_temp_to_sub(), delete_intervals(), do_save(), duplicate_corpus(), and save_unsaved_subcorpora().
save_unsaved_subcorpora()
void save_unsaved_subcorpora (void)
References corpuslist, cqpmessage(), data_directory, cl::next, save_subcorpus(), cl::saved, SUB, cl::type, and Warning.
Referenced by main().
set_current_corpus()
int set_current_corpus (CorpusList * cp, int force)
Sets the current corpus (by pointer to the corpus).
Parameters
cp Pointer to the corpus to set as current. cp may be NULL, which is legal.
force If true, the current corpus is set to the specified corpus, even if it is ALREADY set to that corpus.
Returns
Always 1.
References ContextDescriptor::attributes, CD, cl::corpus, current_corpus, CWB_DEFAULT_ATT_NAME, DestroyAttributeList(), FindInAL(), _attlist::list, _attrbuf::next, _attrbuf::status, ContextDescriptor::strucAttributes, and update_context_descriptor().
Referenced by after_CorpusCommand(), check_available_corpora(), cqi_activate_corpus(), dropcorpus(), init_global_corpuslist(), and set_current_corpus_name().
set_current_corpus_name()
int set_current_corpus_name (char * name, int force)
Sets the current corpus (by name).
Parameters
name Name of the corpus to set as current.
force If true, the current corpus is set to the specified corpus, even if it is ALREADY set to that corpus.
Returns
True if the corpus was found and set, otherwise false if the corpus could not be found.
References findcorpus(), set_current_corpus(), and UNDEF.
Referenced by initialize_cqp().
show_corpora()
void show_corpora (CorpusType type)
A function to print out a list of corpora currently available.
Either system corpora (SYSTEM) or subcorpora (SUB) can be shown, depending on ct. If type is UNDEF, both are shown.
For subcorpora, a bundle of other information is shown too.
Parameters
type Type of corpus to show (SUB, SYSTEM or UNDEF).
References show_corpora_backend(), SUB, SYSTEM, and UNDEF.
show_corpora_backend()
static void show_corpora_backend (CorpusType ct, int only_active_corpus) static
Function that does the work for show_corpora_files.
See also
show_corpora_files
show_corpus_active
Parameters
ct Which type of corpus to show. Must be SUB or SYSTEM.
only_active_corpus If true, then only the active corpus's info is printed. If a subcorpus is active then CORPUS:SUBCORPUS is printed. The ct argument is, in that case, ignored.
References cl_free, cl_malloc(), corpuslist, current_corpus, ilist_end(), ilist_print_break(), ilist_print_item(), ilist_start(), cl::loaded, cl::mother_name, cl::name, cl::needs_update, cl::next, pretty_print, cl::saved, show_corpora_sort(), cl::size, SUB, SYSTEM, and cl::type.
Referenced by show_corpora(), and show_corpus_active().
show_corpora_sort()
static int show_corpora_sort (const void * p1, const void * p2) static
Internal function for sorting list of corpus names.
See also
show_corpora
Referenced by show_corpora_backend().
show_corpus_active()
void show_corpus_active (void)
Displays the ID of the active corpus.
(Including any activated subcorpus/NQR.) (Added for child mode mostly.)
References ALL, and show_corpora_backend().
split_subcorpus_name()
char* split_subcorpus_name (const char * corpusname, char * mother_name)
Splits a query result "corpus"-name into qualifier and local name.
This function splits query result name {corpusname} into qualifier (name of mother corpus) and local name; returns pointer to local name part, or NULL if {corpusname} is not syntactically valid.
if mother_name is not NULL, it must point to a buffer of suitable length (CL_MAX_LINE_LENGTH is sufficient) where the qualifier will be stored (empty string for unqualified corpus, and return value == {corpusname} in this case)
Parameters
corpusname "Corpus" name to process. This is not really a corpus but a query result or subcorpus, in the form CORPUS:TheQuery. It won't be modified.
mother_name Buffer for a copy of the qualifer (first part of name, aka the mother, aka the corpus). When using split_subcorpus_name as a syntax validator for possibly qualified names, this would normally be NULL.
Returns
Pointer into the corpusname buffer, at the point where the second part (the subcorpus/query name) begins. NULL is returned if, at any point in corpusname, there is a character that should not be there.
References COLON.
Referenced by do_undump(), and valid_subcorpus_name().
subcorpus_name_is_qualified()
Boolean subcorpus_name_is_qualified (const char * corpusname)
Checks whether corpusname is qualified (with name of mother corpus); does not imply syntatic validity.
References COLON.
Referenced by do_undump(), and in_CorpusCommand().
SystemCorpusSize()
static int SystemCorpusSize (Corpus * corpus) static
A utility function required by ensure_corpus_size()
References ATT_POS, cl_max_cpos(), cl_new_attribute(), corpus, and CWB_DEFAULT_ATT_NAME.
Referenced by ensure_corpus_size().
touch_corpus()
int touch_corpus (CorpusList * cp)
Touches a corpus, ie, marks it as changed.
Parameters
cp The corpus to touch. This must be of type SUB.
Returns
Boolean: true if the touch worked, otherwise false.
References cl::needs_update, cl::saved, SUB, and cl::type.
Referenced by apply_range_set_operation(), delete_intervals(), do_cut(), evaluate_target(), findcorpus(), set_target(), SortSubcorpus(), and SortSubcorpusRandomize().
valid_subcorpus_name()
Boolean valid_subcorpus_name (char * corpusname)
Checks whether corpusname is syntactically valid as a query result name, i.e., either.
identifier
or qualifier.identifier
References split_subcorpus_name().
Referenced by do_undump().
Variable Documentation
corpuslist
CorpusList* corpuslist = NULL static
Global pointer to the head of CQP's linked list of the currently-loaded corpora (and NQRs).
Referenced by drop_all_corpora(), drop_temp_corpora(), dropcorpus(), duplicate_corpus(), ensure_syscorpus(), FirstCorpusFromList(), init_global_corpuslist(), load_corpusnames(), LoadedCorpus(), make_temp_corpus(), save_unsaved_subcorpora(), and show_corpora_backend().
current_corpus
CorpusList* current_corpus
Global pointer to the "current" corpus.
Referenced by cqp_parse_file(), do_attribute_show(), do_MUQuery(), do_StandardQuery(), do_undump(), drop_all_corpora(), dropcorpus(), execute_side_effects(), in_CorpusCommand(), LoadedCorpus(), prepare_Query(), set_current_corpus(), and show_corpora_backend().