CWB: cqp/cqp.h File Reference
cqp.h File Reference
#include <stdio.h>
Macros
#define CQPRC_NAME ".cqprc"
Default filename for the CQP settings file (expected in home folder).
#define CQPMACROS_NAME ".cqpmacros"
Default filename for the CQP macros file (expected in home folder).
#define CQP_SOURCE_MAXNEST 42
Maximum nesting depth when source'ing files.
#define QUERY_BUFFER_SIZE 2048
Size of the CQP query buffer.
#define CQP_PARSE_ERROR_LINE "PARSE ERROR\n"
Line printed when a parse error is encountered in child mode (easily spotted by parent)
#define True 1
DEPRACATED macros for Boolean true and false.
#define False 0
DEPRACATED macros for Boolean true and false.
Typedefs
typedef int Boolean
DEPRACATED means of storing a Boolean value
typedef enum _matching_strategy MatchingStrategy
MatchingStrategy type : represents one of the possible matching strategies for regular-expression queries in CQP.
typedef enum _cyctype CYCtype
The "corpus yielding command type" type.
typedef void(* InterruptCheckProc) (void)
Interrupt callback functions are of this type.
Enumerations
enum _matching_strategy { traditional , shortest_match , standard_match , longest_match }
MatchingStrategy type : represents one of the possible matching strategies for regular-expression queries in CQP.
enum _cyctype {
NoExpression , Query , Activation , SetOperation ,
Assignment
}
The "corpus yielding command type" type.
Functions
int initialize_cqp (int argc, char **argv)
Initialises the CQP program (or cqpserver or cqpcl).
void cqp_cleanup_memory (void)
Aggregator for different functions that free up global allocations.
int cqp_parse_file (FILE *src, int exit_on_parse_errors)
Parses a stream for CQP query syntax.
int cqp_parse_string (char *s)
Parses a string for CQP query syntax.
void CheckForInterrupts (void)
Calls the interrupt callback function, if set.
void install_signal_handler (void)
Installs the interrupt signal handler function with the OS.
Variables
char QueryBuffer [QUERY_BUFFER_SIZE]
buffer for queries
int QueryBufferP
index into this buffer, for appending
int QueryBufferOverflow
flag which signals buffer overflows
char * searchstr
Global variable containing a search string that is to be converted to a DFA.
CYCtype LastExpression
Global variable indicating type (CYC) of last expression.
char * cqp_input_string
Pointer that stores the address of strings read from the CLI by CQP.
int cqp_input_string_ix
index into the CQP input string; used for character-by-character read.
int exit_cqp
Boolean: 1 iff the exit command was issued while parsing.
int cqp_error_status
Global error status for CQP (will be returned to the caller when CQP exits).
int reading_cqprc
Boolean: true iff cqp_parse_file() - the main query syntax parsing function - is currently reading from the cqprc file handle OR the cqpmacros file handle.
int EvaluationIsRunning
Boolean indicating that an interruptible process is currently running.
int signal_handler_is_installed
Boolean.
Macro Definition Documentation
CQP_PARSE_ERROR_LINE
#define CQP_PARSE_ERROR_LINE "PARSE ERROR\n"
Line printed when a parse error is encountered in child mode (easily spotted by parent)
CQP_SOURCE_MAXNEST
#define CQP_SOURCE_MAXNEST 42
Maximum nesting depth when source'ing files.
See also
cqp_parse_file
CQPMACROS_NAME
#define CQPMACROS_NAME ".cqpmacros"
Default filename for the CQP macros file (expected in home folder).
CQPRC_NAME
#define CQPRC_NAME ".cqprc"
Default filename for the CQP settings file (expected in home folder).
False
#define False 0
DEPRACATED macros for Boolean true and false.
QUERY_BUFFER_SIZE
#define QUERY_BUFFER_SIZE 2048
Size of the CQP query buffer.
True
#define True 1
DEPRACATED macros for Boolean true and false.
Typedef Documentation
Boolean
typedef int Boolean
DEPRACATED means of storing a Boolean value
CYCtype
typedef enum _cyctype CYCtype
The "corpus yielding command type" type.
Each possible value of the enumeration represents a particular "type" of command that may potentially yield a (sub)corpus.
InterruptCheckProc
typedef void(* InterruptCheckProc) (void)
Interrupt callback functions are of this type.
MatchingStrategy
typedef enum _matching_strategy MatchingStrategy
MatchingStrategy type : represents one of the possible matching strategies for regular-expression queries in CQP.
Affects the action of ?, * and + operators.
Enumeration Type Documentation
_cyctype
enum _cyctype
The "corpus yielding command type" type.
Each possible value of the enumeration represents a particular "type" of command that may potentially yield a (sub)corpus.
Enumerator
NoExpression
Query
A query (yielding a query-result subcorpus)
Activation
A corpus-activation command.
SetOperation
A set operation such as intersect or diff.
Assignment
An assignment command (assigning a subcorpus/NQR to an ID).
_matching_strategy
enum _matching_strategy
MatchingStrategy type : represents one of the possible matching strategies for regular-expression queries in CQP.
Affects the action of ?, * and + operators.
Enumerator
traditional
"traditional" strategy
shortest_match
match shortest possible token sequences
standard_match
match optional elements at the start but not at the end of the token sequences
longest_match
find longest possible token sequences
Function Documentation
CheckForInterrupts()
void CheckForInterrupts (void)
Calls the interrupt callback function, if set.
*
basically a nop since the callback hook is never set. this is called in eval.c and targets.
References interruptCallbackHook.
Referenced by evaluate_target(), and simulate().
cqp_cleanup_memory()
void cqp_cleanup_memory (void)
Aggregator for different functions that free up global allocations.
Call on shutdown.
References cleanup_kwic_line_memory(), drop_all_corpora(), and drop_macros().
Referenced by main().
cqp_parse_file()
int cqp_parse_file (FILE * src, int exit_on_parse_errors)
Parses a stream for CQP query syntax.
We're assuming that this is a normal pipe, IE, no interactive shenanigans need to be accounted for (either Readline is unavailable, or the cqp program was started without -e.).
Note that cqp_parse_file() fclose()s fd unless it is STDOUT.
See also
cqp_parse_string
Parameters
src File handle of the file to parse. The file may have been opened with cl_open_stream() (but also plain FILE * objects are fine too).
exit_on_parse_errors Boolean: should CQP stop processing this stream on parse errors?
Returns
Boolean: true = all ok, false = a problem.
References child_process, cl_close_stream(), cl_streq, cl_test_stream(), cqp_input_string, cqp_input_string_ix, CQP_PARSE_ERROR_LINE, CQP_SOURCE_MAXNEST, current_corpus, delete_macro_buffers(), exit_cqp, InputBufferList, cl::mother_name, cl::name, quiet, reading_cqprc, silent, cl::size, yyin, yyparse(), and yyrestart().
Referenced by do_exec(), initialize_cqp(), and main().
cqp_parse_string()
int cqp_parse_string (char * s)
Parses a string for CQP query syntax.
The string is assumed to have been provided by the Readline library or similar. IE, we are running with "cqp -e".
See also
USE_READLINE
Parameters
s The string to parse.
Returns
Boolean: true = all ok, false = a problem.
References cqp_input_string, cqp_input_string_ix, cqpmessage(), cqpserver, Error, exit_cqp, and yyparse().
Referenced by do_cqi_cqp_query(), and main().
initialize_cqp()
int initialize_cqp (int argc, char ** argv)
Initialises the CQP program (or cqpserver or cqpcl).
This function:
initialises the global variables;
initialises the built-in random number generator;
initialises the macro database;
parses the program options;
reads the initialisation file;
reads the macro initialisation file;
and loads the default corpus, if any.
Parameters
argc The argc from main()
argv The argv from main()
Returns
Always 1.
References batchfh, batchmode, check_available_corpora(), child_process, cl_free, cl_malloc(), CL_MAX_FILENAME_LENGTH, cl_randomize(), cl_startup(), cqp_error_status, cqp_init_file, cqp_parse_file(), CQPMACROS_NAME, cqpmessage(), CQPRC_NAME, cqpserver, default_corpus, ee_ix, enable_macros, exit_cqp, init_global_corpuslist(), init_macros(), macro_init_file, parse_options(), parser_debug, reading_cqprc, set_current_corpus_name(), SUBDIR_SEPARATOR, UNDEF, and Warning.
Referenced by main().
install_signal_handler()
void install_signal_handler (void)
Installs the interrupt signal handler function with the OS.
This function installs a Ctrl-C interrupt handler (which clears the EvaluationIsRunning flag). The function installed is sigINT_signal_handler.
See also
sigINT_signal_handler
References cqpmessage(), sigINT_signal_handler(), signal_handler_is_installed, and Warning.
Referenced by check_alignment_constraints(), ComputeGroupInternally(), evaluate_subset(), evaluate_target(), main(), run_standard_query_dfa(), SortSubcorpus(), and SortSubcorpusRandomize().
Variable Documentation
cqp_error_status
int cqp_error_status extern
Global error status for CQP (will be returned to the caller when CQP exits).
For the moment, it's simply boolean (0 = all OK, anything else = error). Later, we might want to define some error macros (maybe have the CDA_ macros as a subset for errors bubbling up from CL, plus also extra macros for other errors).
TODO actually get this variable set in various error conditions.
Referenced by accept_connection(), ActivateCorpus(), calculate_ranges(), cqp_usage(), dup_reftab(), execute_side_effects(), initialize_cqp(), LEX(), MacroHashDelete(), main(), Parse(), parse_options(), PUSH(), regex2dfa(), REGEX2DFA_ERROR(), send_cl_error(), set_reftab(), and sigINT_signal_handler().
cqp_input_string
char* cqp_input_string extern
Pointer that stores the address of strings read from the CLI by CQP.
Referenced by cqp_parse_file(), cqp_parse_string(), and yy_input_char().
cqp_input_string_ix
int cqp_input_string_ix extern
index into the CQP input string; used for character-by-character read.
Referenced by cqp_parse_file(), cqp_parse_string(), and yy_input_char().
EvaluationIsRunning
int EvaluationIsRunning extern
Boolean indicating that an interruptible process is currently running.
The process in question is one that may be expected to be non-instantaneous. This variable is turned off by the Ctrl+C interrupt handler.
See also
sigINT_signal_handler
Referenced by calculate_initial_matchlist_1(), check_alignment_constraints(), ComputeGroupInternally(), cqp_run_mu_query(), cqp_run_tab_query(), eval_bool(), eval_mu_tree(), evaluate_subset(), evaluate_target(), get_leaf_value(), group2compare(), i2compare(), match_first_pattern(), run_standard_query_dfa(), sigINT_signal_handler(), simulate(), SortSubcorpus(), and SortSubcorpusRandomize().
exit_cqp
int exit_cqp extern
Boolean: 1 iff the exit command was issued while parsing.
Referenced by cqp_parse_file(), cqp_parse_string(), and initialize_cqp().
LastExpression
CYCtype LastExpression extern
Global variable indicating type (CYC) of last expression.
Referenced by after_CorpusCommand(), and prepare_input().
QueryBuffer
char QueryBuffer[QUERY_BUFFER_SIZE] extern
buffer for queries
Referenced by addHistoryLine(), after_CorpusCommand(), after_Query(), prepare_Query(), resetQueryBuffer(), and yy_input_char().
QueryBufferOverflow
int QueryBufferOverflow extern
flag which signals buffer overflows
Referenced by after_CorpusCommand(), after_Query(), resetQueryBuffer(), and yy_input_char().
QueryBufferP
int QueryBufferP extern
index into this buffer, for appending
Referenced by after_Query(), resetQueryBuffer(), and yy_input_char().
reading_cqprc
int reading_cqprc extern
Boolean: true iff cqp_parse_file() - the main query syntax parsing function - is currently reading from the cqprc file handle OR the cqpmacros file handle.
See also
cqprc
cqp_parse_file
Referenced by addHistoryLine(), cqp_parse_file(), initialize_cqp(), and yy_input_char().
searchstr
char* searchstr extern
Global variable containing a search string that is to be converted to a DFA.
(Needs to be global; functions using the DFA write to it, and then the DFA parser reads from it. Declared as an external global in cqp.h so other parts of CQP can access it. The actual space is not allocated here, rather a pointer, passed as an argument to regex2dfa(), is copied here.)
Referenced by do_SearchPattern(), do_StandardQuery(), GET(), prepare_input(), prepare_Query(), and regex2dfa().
signal_handler_is_installed
int signal_handler_is_installed extern
Boolean.
Referenced by install_signal_handler(), and sigINT_signal_handler().