CWB: CQi/cqpserver.c File Reference
cqpserver.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "server.h"
#include "auth.h"
#include "log.h"
#include "cqi.h"
#include "../cl/cl.h"
#include "../cqp/cqp.h"
#include "../cqp/options.h"
#include "../cqp/corpmanag.h"
#include "../cqp/groups.h"
Functions
void cqiserver_unknown_command_error (int cmd)
Shuts down the server with an "unknown CQi command" error condition.
void cqiserver_wrong_command_error (int cmd)
Shuts down the server with an "CQi command not allowed here" error condition.
void cqiserver_internal_error (char *function, char *reason)
Shuts down the server with an "internal error" condition.
static void send_cl_error (void)
Sends the current CL error value to the client.
static void do_cqi_corpus_list_corpora (void)
static void do_cqi_corpus_charset (void)
static void do_cqi_corpus_properties (void)
static void send_cqi_corpus_attributes (Corpus *c, int type)
this function sends attributes of a certain type as a STRING[] to the client; helper for do_cqi_corpus_attributes()
void do_cqi_corpus_attributes (int type)
void do_cqi_corpus_full_name (void)
void do_cqi_corpus_structural_attribute_has_values (void)
void do_cqi_cl_attribute_size (void)
void do_cqi_cl_lexicon_size (void)
void do_cqi_cl_drop_attribute (void)
void do_cqi_cl_str2id (void)
void do_cqi_cl_id2str (void)
void do_cqi_cl_id2freq (void)
void do_cqi_cl_cpos2str (void)
void do_cqi_cl_cpos2id (void)
void do_cqi_cl_cpos2struc (void)
void do_cqi_cl_cpos2lbound (void)
void do_cqi_cl_cpos2rbound (void)
void do_cqi_cl_cpos2alg (void)
void do_cqi_cl_struc2str (void)
void do_cqi_cl_id2cpos (void)
void do_cqi_cl_idlist2cpos (void)
void do_cqi_cl_regex2id (void)
void do_cqi_cl_struc2cpos (void)
void do_cqi_cl_alg2cpos (void)
void do_cqi_cqp_list_subcorpora (void)
static void query_remove_semicolon (char *query)
Remove any trailing semicolon terminators from a query.
void do_cqi_cqp_query (void)
void do_cqi_cqp_subcorpus_size (void)
static const char * cqi_field_name (cqi_byte field)
Returns const string representations of CQI_CONST_FIELD_ values.
void do_cqi_cqp_subcorpus_has_field (void)
void do_cqi_send_minus_one_list (int n)
Sends n instances of integer -1 to the client.
void do_cqi_cqp_dump_subcorpus (void)
void do_cqi_cqp_drop_subcorpus (void)
void do_cqi_cqp_fdist_1 (void)
void do_cqi_cqp_fdist_2 (void)
static void interpreter (void)
The CQP server's command interpreter loop.
int main (int argc, char *argv[])
Main function for the cqpserver app.
Variables
char * user = ""
String containing the username sent by the currently-connect CQi client.
char * passwd = ""
String containing the password sent by the currently-connect CQi client.
Function Documentation
cqi_field_name()
static const char* cqi_field_name (cqi_byte field) inline static
Returns const string representations of CQI_CONST_FIELD_ values.
(DO NOT FREE.)
Utility function, used for debugging output & to check valid fields in subroutines below.
References CQI_CONST_FIELD_KEYWORD, CQI_CONST_FIELD_MATCH, CQI_CONST_FIELD_MATCHEND, and CQI_CONST_FIELD_TARGET.
Referenced by do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), and do_cqi_cqp_subcorpus_has_field().
cqiserver_internal_error()
void cqiserver_internal_error (char * function, char * reason)
Shuts down the server with an "internal error" condition.
Both parameters will be printed as part of the shutdown error message.
Parameters
function String: should be name of the calling function, that is, the point where the error was raised.
reason String containing any other explanatory details about the error.
References cqiserver_log(), and Error.
Referenced by do_cqi_cqp_dump_subcorpus(), and do_cqi_cqp_subcorpus_has_field().
cqiserver_unknown_command_error()
void cqiserver_unknown_command_error (int cmd)
Shuts down the server with an "unknown CQi command" error condition.
Parameters
cmd The integer representing the unknown command received from the client.
References cqiserver_log(), and Error.
Referenced by interpreter().
cqiserver_wrong_command_error()
void cqiserver_wrong_command_error (int cmd)
Shuts down the server with an "CQi command not allowed here" error condition.
Parameters
cmd The integer representing the wrong command received from the client.
References cqiserver_log(), and Error.
Referenced by interpreter(), and main().
do_cqi_cl_alg2cpos()
void do_cqi_cl_alg2cpos (void)
References ATT_ALIGN, cl_alg2cpos(), cl_free, cqi_command(), cqi_data_int_int_int_int(), cqi_errno, cqi_lookup_attribute(), cqi_read_int(), cqi_read_string(), cqiserver_debug_msg(), s1, s2, and send_cl_error().
Referenced by interpreter().
do_cqi_cl_attribute_size()
void do_cqi_cl_attribute_size (void)
References ATT_ALIGN, ATT_POS, ATT_STRUC, cl_free, cl_max_alg(), cl_max_cpos(), cl_max_struc(), cqi_command(), cqi_data_int(), cqi_errno, cqi_lookup_attribute(), cqi_read_string(), cqiserver_debug_msg(), and send_cl_error().
Referenced by interpreter().
do_cqi_cl_cpos2alg()
void do_cqi_cl_cpos2alg (void)
References ATT_ALIGN, cl_cpos2alg(), cl_free, cqi_command(), CQI_DATA_INT_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqi_send_int(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_cpos2id()
void do_cqi_cl_cpos2id (void)
References ATT_POS, cl_cpos2id(), cl_free, cqi_command(), CQI_DATA_INT_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqi_send_int(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_cpos2lbound()
void do_cqi_cl_cpos2lbound (void)
References ATT_STRUC, cl_cpos2struc(), cl_free, cl_struc2cpos(), cqi_command(), CQI_DATA_INT_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqi_send_int(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_cpos2rbound()
void do_cqi_cl_cpos2rbound (void)
References ATT_STRUC, cl_cpos2struc(), cl_free, cl_struc2cpos(), cqi_command(), CQI_DATA_INT_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqi_send_int(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_cpos2str()
void do_cqi_cl_cpos2str (void)
References ATT_POS, cl_cpos2str(), cl_free, cqi_command(), CQI_DATA_STRING_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqi_send_int(), cqi_send_string(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_cpos2struc()
void do_cqi_cl_cpos2struc (void)
References ATT_STRUC, cl_cpos2struc(), cl_free, cqi_command(), CQI_DATA_INT_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqi_send_int(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_drop_attribute()
void do_cqi_cl_drop_attribute (void)
References cqi_general_error(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_id2cpos()
void do_cqi_cl_id2cpos (void)
References ATT_POS, cl_free, cl_id2cpos, cqi_command(), cqi_data_int_list(), cqi_errno, cqi_lookup_attribute(), cqi_read_int(), cqi_read_string(), cqiserver_debug_msg(), and send_cl_error().
Referenced by interpreter().
do_cqi_cl_id2freq()
void do_cqi_cl_id2freq (void)
References ATT_POS, cl_free, cl_id2freq(), cqi_command(), CQI_DATA_INT_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqi_send_int(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_id2str()
void do_cqi_cl_id2str (void)
References ATT_POS, cl_free, cl_id2str(), cqi_command(), CQI_DATA_STRING_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqi_send_int(), cqi_send_string(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_idlist2cpos()
void do_cqi_cl_idlist2cpos (void)
References ATT_POS, cl_free, cl_idlist2cpos, cqi_command(), cqi_data_int_list(), cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqiserver_debug_arglist(), cqiserver_debug_msg(), and send_cl_error().
Referenced by interpreter().
do_cqi_cl_lexicon_size()
void do_cqi_cl_lexicon_size (void)
References ATT_POS, cl_free, cl_max_id(), cqi_command(), cqi_data_int(), cqi_errno, cqi_lookup_attribute(), cqi_read_string(), cqiserver_debug_msg(), and send_cl_error().
Referenced by interpreter().
do_cqi_cl_regex2id()
void do_cqi_cl_regex2id (void)
References ATT_POS, CDA_OK, cl_errno, cl_free, cl_regex2id(), cqi_command(), cqi_data_int_list(), cqi_errno, cqi_lookup_attribute(), cqi_read_string(), cqiserver_debug_msg(), and send_cl_error().
Referenced by interpreter().
do_cqi_cl_str2id()
void do_cqi_cl_str2id (void)
References ATT_POS, cl_free, cl_str2id(), cqi_command(), CQI_DATA_INT_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_string(), cqi_read_string_list(), cqi_send_int(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cl_struc2cpos()
void do_cqi_cl_struc2cpos (void)
References ATT_STRUC, cl_free, cl_struc2cpos(), cqi_command(), cqi_data_int_int(), cqi_errno, cqi_lookup_attribute(), cqi_read_int(), cqi_read_string(), cqiserver_debug_msg(), and send_cl_error().
Referenced by interpreter().
do_cqi_cl_struc2str()
void do_cqi_cl_struc2str (void)
References ATT_STRUC, cl_free, cl_struc2str(), cqi_command(), CQI_DATA_STRING_LIST, cqi_errno, cqi_flush(), cqi_lookup_attribute(), cqi_read_int_list(), cqi_read_string(), cqi_send_int(), cqi_send_string(), cqi_send_word(), cqiserver_debug_arglist(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_corpus_attributes()
void do_cqi_corpus_attributes (int type)
References access_corpus(), ATT_ALIGN, ATT_POS, ATT_STRUC, cl_free, cl::corpus, cqi_command(), CQI_CQP_ERROR_NO_SUCH_CORPUS, cqi_general_error(), cqi_read_string(), cqiserver_debug_msg(), findcorpus(), send_cqi_corpus_attributes(), server_debug, and SYSTEM.
Referenced by interpreter().
do_cqi_corpus_charset()
static void do_cqi_corpus_charset (void) static
References access_corpus(), TCorpus::charset, cl_charset_name(), cl_free, cl::corpus, cqi_command(), CQI_CQP_ERROR_NO_SUCH_CORPUS, cqi_data_string(), cqi_read_string(), cqiserver_debug_msg(), findcorpus(), and SYSTEM.
Referenced by interpreter().
do_cqi_corpus_full_name()
void do_cqi_corpus_full_name (void)
References access_corpus(), cl_free, cl::corpus, cqi_command(), CQI_CQP_ERROR_NO_SUCH_CORPUS, cqi_data_string(), cqi_read_string(), cqiserver_debug_msg(), findcorpus(), TCorpus::name, and SYSTEM.
Referenced by interpreter().
do_cqi_corpus_list_corpora()
static void do_cqi_corpus_list_corpora (void) static
References CQI_DATA_STRING_LIST, cqi_flush(), cqi_send_int(), cqi_send_string(), cqi_send_word(), cqiserver_debug_msg(), FirstCorpusFromList(), cl::name, NextCorpusFromList(), SYSTEM, and cl::type.
Referenced by interpreter().
do_cqi_corpus_properties()
static void do_cqi_corpus_properties (void) static
References cl_free, cqi_data_string_list(), cqi_read_string(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_corpus_structural_attribute_has_values()
void do_cqi_corpus_structural_attribute_has_values (void)
References ATT_STRUC, cl_free, cl_struc_values(), cqi_command(), cqi_data_bool(), cqi_errno, cqi_lookup_attribute(), cqi_read_string(), and cqiserver_debug_msg().
Referenced by interpreter().
do_cqi_cqp_drop_subcorpus()
void do_cqi_cqp_drop_subcorpus (void)
References cl_free, cqi_command(), cqi_errno, CQI_ERROR_SYNTAX_ERROR, cqi_find_corpus(), cqi_read_string(), CQI_STATUS_OK, cqiserver_debug_msg(), dropcorpus(), and split_subcorpus_spec().
Referenced by interpreter().
do_cqi_cqp_dump_subcorpus()
void do_cqi_cqp_dump_subcorpus (void)
References cl_free, cqi_command(), CQI_CONST_FIELD_KEYWORD, CQI_CONST_FIELD_MATCH, CQI_CONST_FIELD_MATCHEND, CQI_CONST_FIELD_TARGET, CQI_CQP_ERROR_INVALID_FIELD, CQI_CQP_ERROR_OUT_OF_RANGE, CQI_DATA_INT_LIST, cqi_errno, cqi_field_name(), cqi_find_corpus(), cqi_flush(), cqi_read_byte(), cqi_read_int(), cqi_read_string(), cqi_send_int(), cqi_send_word(), cqiserver_debug_msg(), cqiserver_internal_error(), do_cqi_send_minus_one_list(), Range::end, cl::keywords, cl::range, cl::size, Range::start, and cl::targets.
Referenced by interpreter().
do_cqi_cqp_fdist_1()
void do_cqi_cqp_fdist_1 (void)
References cl_free, compute_grouping(), _grouptable::count_cells, cqi_command(), CQI_CQP_ERROR_GENERAL, CQI_CQP_ERROR_INVALID_FIELD, CQI_DATA_INT_TABLE, cqi_errno, cqi_field_name(), cqi_find_corpus(), cqi_flush(), cqi_read_byte(), cqi_read_int(), cqi_read_string(), cqi_send_int(), cqi_send_word(), cqiserver_debug_msg(), field_name_to_type(), free_group(), _id_cnt_mapping::freq, NoField, _grouptable::nr_cells, and _id_cnt_mapping::t.
Referenced by interpreter().
do_cqi_cqp_fdist_2()
void do_cqi_cqp_fdist_2 (void)
References cl_free, compute_grouping(), _grouptable::count_cells, cqi_command(), CQI_CQP_ERROR_GENERAL, CQI_CQP_ERROR_INVALID_FIELD, CQI_DATA_INT_TABLE, cqi_errno, cqi_field_name(), cqi_find_corpus(), cqi_flush(), cqi_read_byte(), cqi_read_int(), cqi_read_string(), cqi_send_int(), cqi_send_word(), cqiserver_debug_msg(), field_name_to_type(), free_group(), _id_cnt_mapping::freq, NoField, _grouptable::nr_cells, _id_cnt_mapping::s, and _id_cnt_mapping::t.
Referenced by interpreter().
do_cqi_cqp_list_subcorpora()
void do_cqi_cqp_list_subcorpora (void)
References check_corpus_name, cl_free, cl::corpus, corpus, cqi_command(), CQI_DATA_STRING_LIST, cqi_errno, cqi_find_corpus(), cqi_flush(), cqi_read_string(), cqi_send_int(), cqi_send_string(), cqi_send_word(), cqiserver_debug_msg(), FirstCorpusFromList(), cl::name, NextCorpusFromList(), SUB, and cl::type.
Referenced by interpreter().
do_cqi_cqp_query()
void do_cqi_cqp_query (void)
References check_subcorpus_name, cl_free, cl_malloc(), cl_random_fraction(), combine_subcorpus_spec(), cqi_activate_corpus(), cqi_command(), CQI_CQP_ERROR_GENERAL, cqi_errno, cqi_find_corpus(), cqi_read_string(), CQI_STATUS_OK, cqiserver_debug_msg(), cqiserver_log(), cqp_parse_string(), Info, query_lock, query_remove_semicolon(), cl::size, split_subcorpus_spec(), and user.
Referenced by interpreter().
do_cqi_cqp_subcorpus_has_field()
void do_cqi_cqp_subcorpus_has_field (void)
References cl_free, cqi_command(), CQI_CONST_FIELD_KEYWORD, CQI_CONST_FIELD_MATCH, CQI_CONST_FIELD_MATCHEND, CQI_CONST_FIELD_TARGET, CQI_CONST_NO, CQI_CONST_YES, CQI_CQP_ERROR_INVALID_FIELD, cqi_data_bool(), cqi_errno, cqi_field_name(), cqi_find_corpus(), cqi_flush(), cqi_read_byte(), cqi_read_string(), cqiserver_debug_msg(), cqiserver_internal_error(), cl::keywords, and cl::targets.
Referenced by interpreter().
do_cqi_cqp_subcorpus_size()
void do_cqi_cqp_subcorpus_size (void)
References cl_free, cqi_command(), cqi_data_int(), cqi_errno, cqi_find_corpus(), cqi_read_string(), cqiserver_debug_msg(), and cl::size.
Referenced by interpreter().
do_cqi_send_minus_one_list()
void do_cqi_send_minus_one_list (int n)
Sends n instances of integer -1 to the client.
Utility function for do_cqi_cqp_dump_subcorpus().
This is the error condition of the CQI_CQP_DUMP_SUBCORPUS command: it returns a list of (-1) values if requested field is not set.
It is assumed that the length of the lsit has already been sent.
Parameters
n Length of list to send.
References cqi_send_int().
Referenced by do_cqi_cqp_dump_subcorpus().
interpreter()
static void interpreter (void) static
The CQP server's command interpreter loop.
The loops starts running when this function is called, and when the exit command is reveived (CQI_CTRL_BYE) (returns on exit)
References ATT_ALIGN, ATT_POS, ATT_STRUC, CQI_ASK_FEATURE, CQI_ASK_FEATURE_CL_2_3, CQI_ASK_FEATURE_CQI_1_0, CQI_ASK_FEATURE_CQP_2_3, CQI_CL, CQI_CL_ALG2CPOS, CQI_CL_ATTRIBUTE_SIZE, CQI_CL_CPOS2ALG, CQI_CL_CPOS2ID, CQI_CL_CPOS2LBOUND, CQI_CL_CPOS2RBOUND, CQI_CL_CPOS2STR, CQI_CL_CPOS2STRUC, CQI_CL_DROP_ATTRIBUTE, CQI_CL_ID2CPOS, CQI_CL_ID2FREQ, CQI_CL_ID2STR, CQI_CL_IDLIST2CPOS, CQI_CL_LEXICON_SIZE, CQI_CL_REGEX2ID, CQI_CL_STR2ID, CQI_CL_STRUC2CPOS, CQI_CL_STRUC2STR, cqi_command(), CQI_CONST_NO, CQI_CONST_YES, CQI_CORPUS, CQI_CORPUS_ALIGNMENT_ATTRIBUTES, CQI_CORPUS_CHARSET, CQI_CORPUS_FULL_NAME, CQI_CORPUS_LIST_CORPORA, CQI_CORPUS_POSITIONAL_ATTRIBUTES, CQI_CORPUS_PROPERTIES, CQI_CORPUS_STRUCTURAL_ATTRIBUTE_HAS_VALUES, CQI_CORPUS_STRUCTURAL_ATTRIBUTES, CQI_CQP, CQI_CQP_DROP_SUBCORPUS, CQI_CQP_DUMP_SUBCORPUS, CQI_CQP_FDIST_1, CQI_CQP_FDIST_2, CQI_CQP_LIST_SUBCORPORA, CQI_CQP_QUERY, CQI_CQP_SUBCORPUS_HAS_FIELD, CQI_CQP_SUBCORPUS_SIZE, CQI_CTRL, CQI_CTRL_BYE, CQI_CTRL_CONNECT, CQI_CTRL_LAST_GENERAL_ERROR, CQI_CTRL_PING, CQI_CTRL_USER_ABORT, cqi_data_bool(), cqi_data_string(), cqi_error_string, cqi_read_command(), CQI_STATUS_BYE_OK, CQI_STATUS_PING_OK, cqiserver_debug_msg(), cqiserver_unknown_command_error(), cqiserver_wrong_command_error(), do_cqi_cl_alg2cpos(), do_cqi_cl_attribute_size(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_drop_attribute(), do_cqi_cl_id2cpos(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), do_cqi_cl_lexicon_size(), do_cqi_cl_regex2id(), do_cqi_cl_str2id(), do_cqi_cl_struc2cpos(), do_cqi_cl_struc2str(), do_cqi_corpus_attributes(), do_cqi_corpus_charset(), do_cqi_corpus_full_name(), do_cqi_corpus_list_corpora(), do_cqi_corpus_properties(), do_cqi_corpus_structural_attribute_has_values(), do_cqi_cqp_drop_subcorpus(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), do_cqi_cqp_query(), do_cqi_cqp_subcorpus_has_field(), and do_cqi_cqp_subcorpus_size().
Referenced by main().
main()
int main (int argc, char * argv[])
Main function for the cqpserver app.
References accept_connection(), add_host_to_list(), add_user_to_list(), authenticate_user(), auto_save, autoshow, check_grant(), cl_randomize(), cqi_command(), CQI_CTRL_CONNECT, CQI_ERROR_CONNECT_REFUSED, cqi_read_command(), cqi_read_string(), CQI_STATUS_CONNECT_OK, cqiserver_log(), cqiserver_welcome(), cqiserver_wrong_command_error(), cqp_cleanup_memory(), cqp_error_status, cqpserver, dropcorpus(), Error, FirstCorpusFromList(), Info, initialize_cqp(), interpreter(), localhost, cl::name, NextCorpusFromList(), paging, passwd, server_port, silent, and user.
query_remove_semicolon()
static void query_remove_semicolon (char * query) inline static
Remove any trailing semicolon terminators from a query.
CQP commands must be terminated with a single semicolon; multiple semicolons will be interpreted as empty commands and produce an error in do_cqi_cqp_query(), which allows only a single command to be executed for safety reasons. So we remove all semicolons from the query here, then add a single semicolon when constructing the full CQP command. Note that a query sent via the CQi API should not have a trailing semicolon in the first place, so this function just provides some leniency for user errors.
Parameters
query the query string, which may be truncated in-place
Referenced by do_cqi_cqp_query().
send_cl_error()
static void send_cl_error (void) static
Sends the current CL error value to the client.
This function takes the current contents of of the CL library's global cl_errno error value and sends it to the client.
It takes the CL error consant and translates it into the corresponding CQI_CL_ERROR_* constant.
NB: This function shuts down the server with an error condition if cl_errno does not actually contain an error condition.
See also
cl_errno
References CDA_EATTTYPE, CDA_EBADREGEX, CDA_EIDORNG, CDA_EIDXORNG, CDA_ENODATA, CDA_ENOMEM, CDA_ENYI, CDA_EOTHER, CDA_EPATTERN, CDA_EPOSORNG, CDA_OK, cl_errno, CQI_CL_ERROR_CORPUS_ACCESS, CQI_CL_ERROR_INTERNAL, CQI_CL_ERROR_OUT_OF_MEMORY, CQI_CL_ERROR_OUT_OF_RANGE, CQI_CL_ERROR_REGEX, CQI_CL_ERROR_WRONG_ATTRIBUTE_TYPE, cqi_command(), cqiserver_debug_msg(), cqiserver_log(), cqp_error_status, and Error.
Referenced by do_cqi_cl_alg2cpos(), do_cqi_cl_attribute_size(), do_cqi_cl_id2cpos(), do_cqi_cl_idlist2cpos(), do_cqi_cl_lexicon_size(), do_cqi_cl_regex2id(), and do_cqi_cl_struc2cpos().
send_cqi_corpus_attributes()
static void send_cqi_corpus_attributes (Corpus * c, int type) static
this function sends attributes of a certain type as a STRING[] to the client; helper for do_cqi_corpus_attributes()
References _Attribute::any, CQI_DATA_STRING_LIST, cqi_flush(), cqi_send_int(), cqi_send_string(), cqi_send_word(), first_corpus_attribute(), next_corpus_attribute(), and _Attribute::type.
Referenced by do_cqi_corpus_attributes().
Variable Documentation
passwd
char* passwd = ""
String containing the password sent by the currently-connect CQi client.
Referenced by add_user_to_list(), ascii_print_corpus_header(), authenticate_user(), check_access_conditions(), html_print_corpus_header(), latex_print_corpus_header(), main(), and sgml_print_corpus_header().
user
char* user = ""
String containing the username sent by the currently-connect CQi client.
Referenced by add_user_to_list(), authenticate_user(), check_grant(), do_cqi_cqp_query(), find_user(), main(), and show_grants().