CWB: utils/cwb-encode.c File Reference
cwb-encode.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <ctype.h>
#include <math.h>
#include <stdarg.h>
#include <limits.h>
#include <time.h>
#include <dirent.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <glib.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/storage.h"
#include "../cl/endian.h"
Data Structures
struct s_att_builder
s_att_builder object: represents an S-attribute being encoded, and holds some information about the currently-being-processed instance of that S-attribute.
struct p_att_builder
p_att_builder object: represents a P-attribute being encoded.
Macros
#define UMASK 0644
User privileges of new files (octal format)
#define FIELDSEPS "\t\n"
String containing the characters that can function as field separators.
#define MAX_ATTRIBUTES 1024
Max number of attributes of a single kind (s or p).
#define REP_CHECK_LEXHASH_SIZE 1000
nr of buckets of lexhashes used for checking duplicate errors (undeclared element and attribute names in XML tags)
#define MAX_INPUT_LINE_LENGTH 65536
Input buffer size.
#define DEFAULT_INFILE_EXTENSION ".vrt"
Normal extension for CWB input text files.
#define PATH_STRUC_RNG "%s" SUBDIR_SEP_STRING "%s.rng"
Path implementing CL naming convention for S-attribute RNG files.
#define PATH_STRUC_AVX "%s" SUBDIR_SEP_STRING "%s.avx"
Path implementing CL naming convention for S-attribute AVX (att-val index) files.
#define PATH_STRUC_AVS "%s" SUBDIR_SEP_STRING "%s.avs"
Path implementing CL naming convention for S-attribute AVS (attribute values) files.
#define PATH_POS_CORPUS "%s" SUBDIR_SEP_STRING "%s.corpus"
Path implementing CL naming convention for P-attribute Corpus files.
#define PATH_POS_LEX "%s" SUBDIR_SEP_STRING "%s.lexicon"
Path implementing CL naming convention for P-attribute Lexicon files.
#define PATH_POS_LEXIDX "%s" SUBDIR_SEP_STRING "%s.lexicon.idx"
Path implementing CL naming convention for P-attribute Lexicon-index files.
Typedefs
typedef struct s_att_builder s_att_builder
s_att_builder object: represents an S-attribute being encoded, and holds some information about the currently-being-processed instance of that S-attribute.
Functions
char * encode_strtok (register char *s, register const char *delim)
A replacement for the strtok() function which doesn't skip empty fields.
void encode_print_time (FILE *stream, char *msg)
Prints a message plus the current time to the specified file/stream.
void encode_usage (void)
Prints a usage message and exits the program.
void encode_print_input_lineno (void)
Prints the input line number (and input filename, if applicable) on STDERR, for error messages and warnings.
void encode_error (char *format,...)
Prints an error message to STDERR, automatically adding a message on the location of the error in the corpus.
cl_string_list encode_scan_directory (char *dir)
Get a list of files in a given directory.
int s_att_builder_find (char *name)
Gets the index (in the global s_encoder array) of the encoder of a specified S-attribute.
void s_att_print_registry_line (s_att_builder *encoder, FILE *dst, int print_comment)
Prints registry lines for a given s-attribute, and its children, if any, to the specified file handle.
s_att_builder * s_att_declare (char *name, char *directory, int store_values, int null_attribute)
Creates a s_att_builder object to store a specified s-attribute (and, if appropriate, does the same for children-attributes).
void s_att_close_range (s_att_builder *encoder, int end_pos)
Closes a currently open instance (aka region, range) of an S-attribute.
void s_att_open_range (s_att_builder *encoder, int start_pos, char *annot)
Opens an instance of the given S-attribute.
int p_att_builder_find (char *name)
Finds a p-attribute (in the global p_encoder array).
int p_att_declare (char *name, char *directory, int nr_buckets)
Sets up a new p-attribute builder, including opening corpus, lex and index file handles.
void p_att_builder_close_all (void)
Closes all three file handles for each of the wattr objects in cwb-encode's global array.
void encode_parse_options (int argc, char **argv)
Parses program options and sets global variables.
void encode_add_p_attr_line (char *str)
Processes a token data line.
int encode_get_input_line (char *buffer, int bufsize)
Reads one input line into the specified buffer (either from stdin, or from one or more input files).
void encode_generate_registry_file (char *registry_file)
Writes a registry file for the corpus that has been encoded.
int looks_like_a_token (const char *line)
Check whether input line looks like a token with annotations, i.e.
int main (int argc, char **argv)
Main function for cwb-encode.
Variables
char * field_separators = FIELDSEPS
string containing the characters that can function as field separators
char * undef_value = CWB_PA_UNDEF_VALUE
string used as value of P-attributes when a value is missing, ie if a tab-delimited field is empty
int debug = 0
debug mode on or off?
int silent = 0
hide messages
int verbose = 0
show progress (this is not the opposite of silent!)
int xml_aware = 0
substitute XML entities in p-attributes & ignore <? and <! lines
int skip_empty_lines = 0
skip empty lines when encoding?
int auto_null = 0
auto-declare null attributes for unknown XML tags
unsigned line = 0
corpus position currently being encoded (ie cpos of next token); unsigned so it doesn't wrap after first 2^31 tokens and thus we can abort encoding when corpus size is exceeded
int strip_blanks = 0
strip leading and trailing blanks from input and token annotations
cl_string_list input_files = NULL
list of input file(s) (-f option(s))
int nr_input_files = 0
number of input files (length of list after option processing)
int current_input_file = 0
index of input file currently being processed
char * current_input_file_name = NULL
filename of current input file, for error messages
FILE * input_fh = NULL
file handle for current input file (or pipe) (text mode!)
unsigned long input_line = 0
input line number (reset for each new file) for error messages
char * registry_file = NULL
if set, auto-generate registry file named {registry_file}, listing declared attributes
char * directory = NULL
corpus data directory (no longer defaults to current directory)
const char * encoding_charset_name = "latin1"
character set label that is inserted into the registry file
CorpusCharset encoding_charset
a charset object to be generated from corpus_character_set
int clean_strings = 0
clean up input strings by replacing invalid bytes with '?'
int numbered = 0
alternative input mode with token lines numbered in first column
int encode_token_numbers = 0
whether token numbers in this input mode are encoded in a p-attribute
char * conll_sentence_attribute = NULL
encode blank lines as sentence breaks in this attribute
s_att_builder s_encoder [MAX_ATTRIBUTES]
A global array for keeping track of S-attributes being encoded.
int s_encoder_ix = 0
s_att_builder * conll_sentence_satt = NULL
optional hidden s-attribute for encoding blank lines as sentence breaks (-L option)
p_att_builder p_encoder [MAX_ATTRIBUTES]
A global array for keeping track of P-attributes being encoded.
int p_encoder_ix = 0
cl_lexhash undeclared_sattrs = NULL
lookup hash for undeclared s-attributes and s-attributes declared with -S that have annotations (which will be ignored), so warnings are issued only once
char * progname = NULL
name of the currently running program
Macro Definition Documentation
DEFAULT_INFILE_EXTENSION
#define DEFAULT_INFILE_EXTENSION ".vrt"
Normal extension for CWB input text files.
(must have exactly 4 characters; .gz/.bz2 may be added to this if the file is compressed.)
FIELDSEPS
#define FIELDSEPS "\t\n"
String containing the characters that can function as field separators.
MAX_ATTRIBUTES
#define MAX_ATTRIBUTES 1024
Max number of attributes of a single kind (s or p).
MAX_INPUT_LINE_LENGTH
#define MAX_INPUT_LINE_LENGTH 65536
Input buffer size.
If we have XML tags with attributes, input lines can become pretty long (but there's basically just a single buffer)
PATH_POS_CORPUS
#define PATH_POS_CORPUS "%s" SUBDIR_SEP_STRING "%s.corpus"
Path implementing CL naming convention for P-attribute Corpus files.
PATH_POS_LEX
#define PATH_POS_LEX "%s" SUBDIR_SEP_STRING "%s.lexicon"
Path implementing CL naming convention for P-attribute Lexicon files.
PATH_POS_LEXIDX
#define PATH_POS_LEXIDX "%s" SUBDIR_SEP_STRING "%s.lexicon.idx"
Path implementing CL naming convention for P-attribute Lexicon-index files.
PATH_STRUC_AVS
#define PATH_STRUC_AVS "%s" SUBDIR_SEP_STRING "%s.avs"
Path implementing CL naming convention for S-attribute AVS (attribute values) files.
PATH_STRUC_AVX
#define PATH_STRUC_AVX "%s" SUBDIR_SEP_STRING "%s.avx"
Path implementing CL naming convention for S-attribute AVX (att-val index) files.
PATH_STRUC_RNG
#define PATH_STRUC_RNG "%s" SUBDIR_SEP_STRING "%s.rng"
Path implementing CL naming convention for S-attribute RNG files.
REP_CHECK_LEXHASH_SIZE
#define REP_CHECK_LEXHASH_SIZE 1000
nr of buckets of lexhashes used for checking duplicate errors (undeclared element and attribute names in XML tags)
UMASK
#define UMASK 0644
User privileges of new files (octal format)
Typedef Documentation
s_att_builder
typedef struct s_att_builder s_att_builder
s_att_builder object: represents an S-attribute being encoded, and holds some information about the currently-being-processed instance of that S-attribute.
Function Documentation
encode_add_p_attr_line()
void encode_add_p_attr_line (char * str)
Processes a token data line.
That is, it processes a line that is not an XML line.
Note that this is destructive - the argument character string will be changed in situ via an strtok-like mechanim.
Parameters
str A string containing the line to process.
References cl_free, cl_lexhash_add(), cl_lexhash_id(), cl_make_set(), CL_MAX_LINE_LENGTH, cl_strdup(), cl_xml_entity_decode(), encode_error(), encode_print_input_lineno(), encode_strtok(), encoding_charset, field_separators, _cl_lexhash_entry::id, NwriteInt(), p_encoder, p_encoder_ix, p_att_builder::position, silent, strip_blanks, token, undef_value, utf8, and xml_aware.
Referenced by main().
encode_error()
void encode_error (char * format, ...)
Prints an error message to STDERR, automatically adding a message on the location of the error in the corpus.
Then exits the program.
Parameters
format Format-specifying string of the error message.
... Additional arguments, printf-style.
References current_input_file, encode_print_input_lineno(), and input_line.
Referenced by encode_add_p_attr_line(), encode_generate_registry_file(), encode_get_input_line(), encode_parse_options(), encode_scan_directory(), main(), p_att_builder_close_all(), p_att_declare(), s_att_close_range(), and s_att_declare().
encode_generate_registry_file()
void encode_generate_registry_file (char * registry_file)
Writes a registry file for the corpus that has been encoded.
Part of cwb-encode; not a library function.
Parameters
registry_file String containing the path of the file to write.
References cl_free, cl_id_tolower(), cl_id_toupper(), cl_id_validate(), cl_malloc(), cl_path_registry_quote(), cl_strdup(), CWB_INFOFILE_DEFAULT_NAME, debug, directory, encode_error(), encoding_charset_name, p_encoder, p_encoder_ix, registry_file, s_att_print_registry_line(), s_encoder, s_encoder_ix, and SUBDIR_SEPARATOR.
Referenced by main().
encode_get_input_line()
int encode_get_input_line (char * buffer, int bufsize)
Reads one input line into the specified buffer (either from stdin, or from one or more input files).
The input files are not passed to the function, but are taken from the program global variables.
This function returns False when the last input file has been completely read, and automatically closes files.
If the line that is read is not valid according to the character set specified for the corpus, then an error will be printed and the program shut down.
Parameters
buffer Where to load the line to. Assumed to be MAX_INPUT_LINE_LENGTH long.
bufsize Not currently used, but should be MAX_INPUT_LINE_LENGTH in case of future use!
Returns
boolean: true for all OK, false for a problem.
References cl_close_stream(), cl_error(), cl_open_stream(), cl_strcpy(), CL_STREAM_MAGIC, CL_STREAM_READ, cl_string_canonical(), cl_string_list_get(), cl_string_validate_encoding(), cl_string_zap_controls(), clean_strings, current_input_file, current_input_file_name, encode_error(), encoding_charset, encoding_charset_name, input_fh, input_files, input_line, MAX_INPUT_LINE_LENGTH, nr_input_files, REQUIRE_NFC, and utf8.
Referenced by main().
encode_parse_options()
void encode_parse_options (int argc, char ** argv)
Parses program options and sets global variables.
Parameters
argc argc - passed from main()
argv argv - passed from main()
References auto_null, cl_charset_name_canonical(), cl_delete_string_list(), cl_str_is, cl_string_list_append(), cl_string_list_get(), cl_string_list_size(), clean_strings, conll_sentence_attribute, conll_sentence_satt, CWB_DEFAULT_ATT_NAME, debug, directory, encode_error(), encode_scan_directory(), encode_token_numbers, encode_usage(), encoding_charset_name, input_files, MAX_ATTRIBUTES, numbered, p_att_builder_find(), p_att_declare(), p_encoder_ix, progname, registry_file, s_att_builder_find(), s_att_declare(), s_encoder_ix, silent, skip_empty_lines, strip_blanks, undef_value, verbose, and xml_aware.
Referenced by main().
encode_print_input_lineno()
void encode_print_input_lineno (void)
Prints the input line number (and input filename, if applicable) on STDERR, for error messages and warnings.
References current_input_file_name, input_line, and nr_input_files.
Referenced by encode_add_p_attr_line(), encode_error(), main(), s_att_close_range(), and s_att_open_range().
encode_print_time()
void encode_print_time (FILE * stream, char * msg)
Prints a message plus the current time to the specified file/stream.
Parameters
stream Stream to print to.
msg Message to incorporate into the string that is printed.
Referenced by main().
encode_scan_directory()
cl_string_list encode_scan_directory (char * dir)
Get a list of files in a given directory.
This function only lists files with .vrt or .vrt.(gz|bz2) extensions, and only files identified by POSIX stat() as "regular".
(Note that .vrt is dependent on DEFAULT_INFILE_EXTENSION.)
See also
DEFAULT_INFILE_EXTENSION
Parameters
dir Path of directory to look in.
Returns
List of paths to files (including the directory name). Returned as a cl_string_list object.
References cl_free, cl_malloc(), cl_new_string_list(), cl_string_list_append(), cl_string_list_qsort(), DEFAULT_INFILE_EXTENSION, encode_error(), input_files, and SUBDIR_SEPARATOR.
Referenced by encode_parse_options().
encode_strtok()
char* encode_strtok (register char * s, register const char * delim)
A replacement for the strtok() function which doesn't skip empty fields.
Parameters
s The string to split.
delim Delimiters to use in splitting.
Returns
The next token from the string.
Referenced by encode_add_p_attr_line().
encode_usage()
void encode_usage (void)
Prints a usage message and exits the program.
References CWB_VERSION, DEFAULT_INFILE_EXTENSION, progname, and undef_value.
Referenced by encode_parse_options().
looks_like_a_token()
int looks_like_a_token (const char * line)
Check whether input line looks like a token with annotations, i.e.
whether it has the correct number of k > 1 TAB-separated fields.
Used to suppress error messages about malformed XML tags if they are likely to be tokens starting with '<'.
Parameters
line Input line (read-only, must be NUL-terminated).
Returns
boolean: true if line looks like at token
References line, and p_encoder_ix.
Referenced by main().
main()
int main (int argc, char ** argv)
Main function for cwb-encode.
As well as the entry point to the program, this contains the main loop for each line of the corpus to be encoded.
The string of each line is sent to one of a number of different functions, depending on what is found in that string!
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References auto_null, s_att_builder::automatic, s_att_builder::avs_fh, s_att_builder::avx_fh, buf, cl_charset_from_name(), cl_lexhash_add(), cl_lexhash_freq(), CL_MAX_CORPUS_SIZE, cl_new_lexhash(), cl_new_string_list(), cl_set_debug_level(), cl_startup(), cl_string_chomp(), cl_string_list_get(), cl_string_list_size(), cl_xml_is_name_char, COMMA_SEP_THOUSANDS_CONVSPEC, conll_sentence_satt, debug, s_att_builder::element_drop_count, encode_add_p_attr_line(), encode_error(), encode_generate_registry_file(), encode_get_input_line(), encode_parse_options(), encode_print_input_lineno(), encode_print_time(), encode_token_numbers, encoding_charset, encoding_charset_name, input_files, input_line, s_att_builder::is_open, line, looks_like_a_token(), MAX_INPUT_LINE_LENGTH, s_att_builder::max_recursion, s_att_builder::name, nr_input_files, s_att_builder::null_attribute, numbered, p_att_builder_close_all(), progname, s_att_builder::recursion_level, registry_file, REP_CHECK_LEXHASH_SIZE, s_att_builder::rng_fh, s_att_builder_find(), s_att_close_range(), s_att_open_range(), s_encoder, s_encoder_ix, silent, skip_empty_lines, s_att_builder::store_values, strip_blanks, undeclared_sattrs, verbose, and xml_aware.
p_att_builder_close_all()
void p_att_builder_close_all (void)
Closes all three file handles for each of the wattr objects in cwb-encode's global array.
References encode_error(), p_encoder, and p_encoder_ix.
Referenced by main().
p_att_builder_find()
int p_att_builder_find (char * name)
Finds a p-attribute (in the global p_encoder array).
Returns the index (in p_encoder) of the p-attribute with the given name.
See also
p_encoder
Parameters
name The P-attribute to search for.
Returns
Index (as integer), or -1 if not found.
References cl_streq, p_encoder, and p_encoder_ix.
Referenced by encode_parse_options().
p_att_declare()
int p_att_declare (char * name, char * directory, int nr_buckets)
Sets up a new p-attribute builder, including opening corpus, lex and index file handles.
All files are opened for write in the globally-specified data directory.
See also
directory
Parameters
name Identifier string of the p-attribute
directory The directory where the CWB data files will go.
nr_buckets Number of buckets in the lexhash of the new p-attribute (value passed to cl_new_lexhash())
Returns
Always 1.
References CL_MAX_LINE_LENGTH, cl_new_lexhash(), cl_strdup(), CWB_DEFAULT_ATT_NAME, directory, encode_error(), p_att_builder::feature_set, p_att_builder::lh, p_att_builder::name, p_encoder, p_encoder_ix, PATH_POS_CORPUS, PATH_POS_LEX, PATH_POS_LEXIDX, and p_att_builder::position.
Referenced by encode_parse_options().
s_att_builder_find()
int s_att_builder_find (char * name)
Gets the index (in the global s_encoder array) of the encoder of a specified S-attribute.
See also
s_encoder
Parameters
name The S-attribute to search for.
Returns
Index (as integer). -1 if the S-attribute is not found.
References cl_streq, s_encoder, and s_encoder_ix.
Referenced by encode_parse_options(), and main().
s_att_close_range()
void s_att_close_range (s_att_builder * encoder, int end_pos)
Closes a currently open instance (aka region, range) of an S-attribute.
Parameters
encoder Pointer to the S-attribute builder whose range should close.
end_pos The corpus position at which this instance closes.
References s_att_builder::annot, s_att_builder::avs_fh, s_att_builder::avx_fh, cl_free, cl_lexhash_add(), cl_lexhash_find(), CL_MAX_LINE_LENGTH, cl_strdup(), cl_string_list_get(), cl_string_list_size(), _cl_lexhash_entry::data, debug, s_att_builder::el_attributes, s_att_builder::el_atts_list, encode_error(), encode_print_input_lineno(), encoding_charset, s_att_builder::has_children, input_line, _cl_lexhash_entry::_cl_lexhash_entry_data::integer, s_att_builder::is_open, s_att_builder::lh, s_att_builder::max_recursion, s_att_builder::name, s_att_builder::null_attribute, s_att_builder::num, NwriteInt(), s_att_builder::offset, _cl_lexhash_entry::_cl_lexhash_entry_data::pointer, s_att_builder::recursion_children, s_att_builder::recursion_level, s_att_builder::rng_fh, silent, s_att_builder::start_pos, s_att_builder::store_values, and utf8.
Referenced by main(), and s_att_open_range().
s_att_declare()
s_att_builder* s_att_declare (char * name, char * directory, int store_values, int null_attribute)
Creates a s_att_builder object to store a specified s-attribute (and, if appropriate, does the same for children-attributes).
The new s_att_builder object is placed in a global variable, but a pointer is also returned. So you can ignore the return value or not, as you prefer.
This is the function where the command-line formalism for defining s-attributes is defined.
See also
s_encoder
Parameters
name The string from the user specifying the name of this attribute, recursion and any "attributes" of this XML element - e.g. "text:0+id"
directory The directory where the CWB data files will go.
store_values boolean: indicates whether this s-attribute was specified with -V (true) or -S (false) when the program was invoked.
null_attribute boolean: this is a null attribute, i.e. an XML element to be ignored.
Returns
Pointer to the new s_att_builder object (which is a member of the global array).
References s_att_builder::annot, s_att_builder::automatic, s_att_builder::avs_fh, s_att_builder::avx_fh, buf, cl_calloc(), cl_free, cl_lexhash_add(), cl_lexhash_id(), CL_MAX_LINE_LENGTH, cl_new_lexhash(), cl_new_string_list(), cl_strcpy(), cl_strdup(), cl_string_list_append(), _cl_lexhash_entry::data, debug, s_att_builder::dir, directory, s_att_builder::el_attributes, s_att_builder::el_atts_list, s_att_builder::el_undeclared_attributes, s_att_builder::element_drop_count, encode_error(), s_att_builder::feature_set, s_att_builder::has_children, s_att_builder::in_registry, s_att_builder::is_open, s_att_builder::lh, MAX_ATTRIBUTES, s_att_builder::max_recursion, s_att_builder::name, s_att_builder::null_attribute, s_att_builder::num, s_att_builder::offset, PATH_STRUC_AVS, PATH_STRUC_AVX, PATH_STRUC_RNG, _cl_lexhash_entry::_cl_lexhash_entry_data::pointer, s_att_builder::recursion_children, s_att_builder::recursion_level, REP_CHECK_LEXHASH_SIZE, s_att_builder::rng_fh, s_encoder, s_encoder_ix, s_att_builder::start_pos, and s_att_builder::store_values.
Referenced by encode_parse_options().
s_att_open_range()
void s_att_open_range (s_att_builder * encoder, int start_pos, char * annot)
Opens an instance of the given S-attribute.
If encoder has element attribute children, range_open() will mess around with the string annotation (otherwise not).
Parameters
encoder The S-attribute to open.
start_pos The corpus position at which this instance begins.
annot The annotation string (the XML element's att-val pairs).
References s_att_builder::annot, cl_free, cl_lexhash_add(), cl_lexhash_find(), cl_lexhash_freq(), cl_make_set(), cl_strdup(), cl_string_list_get(), cl_string_list_size(), cl_xml_entity_decode(), cl_xml_is_name_char, _cl_lexhash_entry::data, debug, s_att_builder::el_attributes, s_att_builder::el_atts_list, s_att_builder::el_undeclared_attributes, s_att_builder::element_drop_count, encode_print_input_lineno(), s_att_builder::feature_set, s_att_builder::has_children, input_line, _cl_lexhash_entry::_cl_lexhash_entry_data::integer, s_att_builder::is_open, line, s_att_builder::max_recursion, s_att_builder::name, s_att_builder::null_attribute, _cl_lexhash_entry::_cl_lexhash_entry_data::pointer, s_att_builder::recursion_children, s_att_builder::recursion_level, s_att_close_range(), silent, s_att_builder::start_pos, s_att_builder::store_values, strip_blanks, token, and undeclared_sattrs.
Referenced by main().
s_att_print_registry_line()
void s_att_print_registry_line (s_att_builder * encoder, FILE * dst, int print_comment)
Prints registry lines for a given s-attribute, and its children, if any, to the specified file handle.
Parameters
encoder The s-attribute in question.
dst Stream for the registry file to write the line to.
print_comment Boolean: if true, a comment on the original XML tags is printed.
References cl_lexhash_find(), cl_string_list_get(), cl_string_list_size(), _cl_lexhash_entry::data, s_att_builder::el_attributes, s_att_builder::el_atts_list, s_att_builder::has_children, s_att_builder::in_registry, s_att_builder::max_recursion, s_att_builder::name, s_att_builder::null_attribute, _cl_lexhash_entry::_cl_lexhash_entry_data::pointer, s_att_builder::recursion_children, and s_att_builder::store_values.
Referenced by encode_generate_registry_file().
Variable Documentation
auto_null
int auto_null = 0
auto-declare null attributes for unknown XML tags
Referenced by encode_parse_options(), and main().
clean_strings
int clean_strings = 0
clean up input strings by replacing invalid bytes with '?'
Referenced by encode_get_input_line(), and encode_parse_options().
conll_sentence_attribute
char* conll_sentence_attribute = NULL
encode blank lines as sentence breaks in this attribute
Referenced by encode_parse_options().
conll_sentence_satt
s_att_builder* conll_sentence_satt = NULL
optional hidden s-attribute for encoding blank lines as sentence breaks (-L option)
Referenced by encode_parse_options(), and main().
current_input_file
int current_input_file = 0
index of input file currently being processed
Referenced by encode_error(), and encode_get_input_line().
current_input_file_name
char* current_input_file_name = NULL
filename of current input file, for error messages
Referenced by encode_get_input_line(), and encode_print_input_lineno().
debug
int debug = 0
debug mode on or off?
Referenced by encode_generate_registry_file(), encode_parse_options(), main(), s_att_close_range(), s_att_declare(), and s_att_open_range().
directory
char* directory = NULL
corpus data directory (no longer defaults to current directory)
Referenced by encode_generate_registry_file(), encode_parse_options(), p_att_declare(), s_att_declare(), sencode_declare_new_satt(), and sencode_parse_options().
encode_token_numbers
int encode_token_numbers = 0
whether token numbers in this input mode are encoded in a p-attribute
Referenced by encode_parse_options(), and main().
encoding_charset
CorpusCharset encoding_charset
a charset object to be generated from corpus_character_set
Referenced by encode_add_p_attr_line(), encode_get_input_line(), main(), and s_att_close_range().
encoding_charset_name
const char* encoding_charset_name = "latin1"
character set label that is inserted into the registry file
Referenced by encode_generate_registry_file(), encode_get_input_line(), encode_parse_options(), and main().
field_separators
char* field_separators = FIELDSEPS
string containing the characters that can function as field separators
Referenced by encode_add_p_attr_line().
input_fh
FILE* input_fh = NULL
file handle for current input file (or pipe) (text mode!)
Referenced by encode_get_input_line().
input_files
cl_string_list input_files = NULL
list of input file(s) (-f option(s))
Referenced by encode_get_input_line(), encode_parse_options(), encode_scan_directory(), and main().
input_line
unsigned long input_line = 0
input line number (reset for each new file) for error messages
Referenced by encode_error(), encode_get_input_line(), encode_print_input_lineno(), load_macro_file(), main(), s_att_close_range(), and s_att_open_range().
line
unsigned line = 0
corpus position currently being encoded (ie cpos of next token); unsigned so it doesn't wrap after first 2^31 tokens and thus we can abort encoding when corpus size is exceeded
Referenced by looks_like_a_token(), main(), and s_att_open_range().
nr_input_files
int nr_input_files = 0
number of input files (length of list after option processing)
Referenced by encode_get_input_line(), encode_print_input_lineno(), and main().
numbered
int numbered = 0
alternative input mode with token lines numbered in first column
Referenced by encode_parse_options(), and main().
p_encoder
p_att_builder p_encoder[MAX_ATTRIBUTES]
A global array for keeping track of P-attributes being encoded.
Referenced by encode_add_p_attr_line(), encode_generate_registry_file(), p_att_builder_close_all(), p_att_builder_find(), and p_att_declare().
p_encoder_ix
int p_encoder_ix = 0
See also
p_encoder
Referenced by encode_add_p_attr_line(), encode_generate_registry_file(), encode_parse_options(), looks_like_a_token(), p_att_builder_close_all(), p_att_builder_find(), and p_att_declare().
progname
char* progname = NULL
name of the currently running program
Name of the program (from the shell)
Referenced by encode_parse_options(), encode_usage(), and main().
registry_file
char* registry_file = NULL
if set, auto-generate registry file named {registry_file}, listing declared attributes
Referenced by encode_generate_registry_file(), encode_parse_options(), and main().
s_encoder
s_att_builder s_encoder[MAX_ATTRIBUTES]
A global array for keeping track of S-attributes being encoded.
Referenced by encode_generate_registry_file(), main(), s_att_builder_find(), and s_att_declare().
s_encoder_ix
int s_encoder_ix = 0
See also
s_encoder
Referenced by encode_generate_registry_file(), encode_parse_options(), main(), s_att_builder_find(), and s_att_declare().
silent
int silent = 0
hide messages
Disables some messages & warnings (used rather inconsistently).
Referenced by encode_add_p_attr_line(), encode_parse_options(), main(), s_att_close_range(), and s_att_open_range().
skip_empty_lines
int skip_empty_lines = 0
skip empty lines when encoding?
Referenced by encode_parse_options(), and main().
strip_blanks
int strip_blanks = 0
strip leading and trailing blanks from input and token annotations
Referenced by encode_add_p_attr_line(), encode_parse_options(), main(), and s_att_open_range().
undeclared_sattrs
cl_lexhash undeclared_sattrs = NULL
lookup hash for undeclared s-attributes and s-attributes declared with -S that have annotations (which will be ignored), so warnings are issued only once
Referenced by main(), and s_att_open_range().
undef_value
char* undef_value = CWB_PA_UNDEF_VALUE
string used as value of P-attributes when a value is missing, ie if a tab-delimited field is empty
Referenced by encode_add_p_attr_line(), encode_parse_options(), and encode_usage().
verbose
int verbose = 0
show progress (this is not the opposite of silent!)
Referenced by encode_parse_options(), and main().
xml_aware
int xml_aware = 0
substitute XML entities in p-attributes & ignore <? and <! lines
Referenced by encode_add_p_attr_line(), encode_parse_options(), and main().