CWB: utils/cwb-align-show.c File Reference
cwb-align-show.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
Macros
#define MIN_COL_WIDTH 20
#define MAX_COL_WIDTH 256
#define WIDE_COL_WIDTH 55
wider column width available on request (-W option)
#define WIDE_COL_SEP 6
column separator to accompany the wider columns
Functions
void alignshow_print_help (void)
Lists interactive commands on STDERR.
void alignshow_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
int alignshow_parse_args (int ac, char *av[], int min_args)
Parses the program's commandline arguments.
void alignshow_goodbye (int error_level)
Closes the alignment file handle (if open) and exits the program.
void alignshow_end_of_alignment (void)
Exits the program because the end of the .align file has been reached.
void alignshow_skip_next_region (FILE *f)
Reads and discards the next alignment region from an .align file.
void alignshow_print_next_region (FILE *f)
Reads the next alignment region from a .align file, and displays it on STDOUT.
int main (int argc, char **argv)
Main function for cwb-align-show.
Variables
char * progname = ""
Name of the program (from the shell)
char corpus1_name [CL_MAX_FILENAME_LENGTH]
name of the source corpus
char corpus2_name [CL_MAX_FILENAME_LENGTH]
name of the target corpus
char s1_name [CL_MAX_FILENAME_LENGTH]
name of the source sentence regions
char s2_name [CL_MAX_FILENAME_LENGTH]
name of the target sentence regions
char word_name [CL_MAX_FILENAME_LENGTH] = "word"
name of the p-attribute used to display tokens (usually word)
Corpus * corpus1
corpus handle: source corpus
Corpus * corpus2
corpus handle: target corpus
Attribute * w1
{word} attribute (or whatever is selected with -P) handle: source
Attribute * s1
sentence attribute handle: source
Attribute * w2
{word} attribute (or whatever is selected with -P) handle: target
Attribute * s2
sentence attribute handle: target
char * registry_dir = NULL
registry directory (NULL = use CL default)
char * align_name = ""
name of the .align file
FILE * af = NULL
file handle .align file
int COL_WIDTH = 38
width of a display column (one column for each language)
int COL_SEP = 2
column separator (blanks)
Macro Definition Documentation
MAX_COL_WIDTH
#define MAX_COL_WIDTH 256
MIN_COL_WIDTH
#define MIN_COL_WIDTH 20
WIDE_COL_SEP
#define WIDE_COL_SEP 6
column separator to accompany the wider columns
WIDE_COL_WIDTH
#define WIDE_COL_WIDTH 55
wider column width available on request (-W option)
Function Documentation
alignshow_end_of_alignment()
void alignshow_end_of_alignment (void)
Exits the program because the end of the .align file has been reached.
References alignshow_goodbye().
Referenced by alignshow_print_next_region(), and alignshow_skip_next_region().
alignshow_goodbye()
void alignshow_goodbye (int error_level)
Closes the alignment file handle (if open) and exits the program.
Parameters
error_level The exit code that is returned to the OS.
References af, and cl_close_stream().
Referenced by alignshow_end_of_alignment(), and main().
alignshow_parse_args()
int alignshow_parse_args (int ac, char * av[], int min_args)
Parses the program's commandline arguments.
Usage: optindex = alignshow_parse_args(argc, argv, required_arguments);
Parameters
ac The program's argc
av The program's argv
min_args Minimum number of arguments to be parsed.
Returns
The value of optind after parsing, ie the index of the first argument in argv[]
References alignshow_usage(), COL_SEP, COL_WIDTH, MAX_COL_WIDTH, MIN_COL_WIDTH, progname, registry_dir, WIDE_COL_SEP, WIDE_COL_WIDTH, and word_name.
Referenced by main().
alignshow_print_help()
void alignshow_print_help (void)
Lists interactive commands on STDERR.
References progname.
Referenced by alignshow_usage(), and main().
alignshow_print_next_region()
void alignshow_print_next_region (FILE * f)
Reads the next alignment region from a .align file, and displays it on STDOUT.
Parameters
f The file handle to read from.
References alignshow_end_of_alignment(), cl_cpos2str(), CL_MAX_LINE_LENGTH, COL_SEP, COL_WIDTH, line, MAX_COL_WIDTH, progname, w1, w2, and word.
Referenced by main().
alignshow_skip_next_region()
void alignshow_skip_next_region (FILE * f)
Reads and discards the next alignment region from an .align file.
Parameters
f The file handle to read from.
References alignshow_end_of_alignment(), CL_MAX_LINE_LENGTH, and line.
Referenced by main().
alignshow_usage()
void alignshow_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
References alignshow_print_help(), COL_SEP, COL_WIDTH, CWB_VERSION, and progname.
Referenced by alignshow_parse_args().
main()
int main (int argc, char ** argv)
Main function for cwb-align-show.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References af, align_name, alignshow_goodbye(), alignshow_parse_args(), alignshow_print_help(), alignshow_print_next_region(), alignshow_skip_next_region(), ATT_POS, ATT_STRUC, CL_MAX_LINE_LENGTH, cl_new_attribute(), cl_new_corpus(), cl_open_stream(), cl_startup(), CL_STREAM_MAGIC, CL_STREAM_READ, corpus1, corpus1_name, corpus2, corpus2_name, line, progname, registry_dir, s1, s1_name, s2, s2_name, w1, w2, and word_name.
Variable Documentation
af
FILE* af = NULL
file handle .align file
Referenced by alignshow_goodbye(), and main().
align_name
char* align_name = ""
name of the .align file
Referenced by main().
COL_SEP
int COL_SEP = 2
column separator (blanks)
Referenced by alignshow_parse_args(), alignshow_print_next_region(), and alignshow_usage().
COL_WIDTH
int COL_WIDTH = 38
width of a display column (one column for each language)
Referenced by alignshow_parse_args(), alignshow_print_next_region(), and alignshow_usage().
corpus1
Corpus* corpus1
corpus handle: source corpus
Referenced by apply_range_set_operation(), and main().
corpus1_name
char corpus1_name[CL_MAX_FILENAME_LENGTH]
name of the source corpus
Referenced by main().
corpus2
Corpus* corpus2
corpus handle: target corpus
Referenced by apply_range_set_operation(), and main().
corpus2_name
char corpus2_name[CL_MAX_FILENAME_LENGTH]
name of the target corpus
Referenced by main().
progname
char* progname = ""
Name of the program (from the shell)
Referenced by alignshow_parse_args(), alignshow_print_help(), alignshow_print_next_region(), alignshow_usage(), and main().
registry_dir
char* registry_dir = NULL
registry directory (NULL = use CL default)
Referenced by alignshow_parse_args(), and main().
s1
Attribute* s1
sentence attribute handle: source
Referenced by cl_set_intersection(), cl_strcmp(), cl_string_qsort_compare(), do_cqi_cl_alg2cpos(), do_translate(), group2compare(), i2compare(), and main().
s1_name
char s1_name[CL_MAX_FILENAME_LENGTH]
name of the source sentence regions
Referenced by main().
s2
Attribute* s2
sentence attribute handle: target
Referenced by cl_set_intersection(), cl_strcmp(), cl_string_qsort_compare(), do_cqi_cl_alg2cpos(), do_translate(), group2compare(), i2compare(), and main().
s2_name
char s2_name[CL_MAX_FILENAME_LENGTH]
name of the target sentence regions
Referenced by main().
w1
Attribute* w1
{word} attribute (or whatever is selected with -P) handle: source
Referenced by alignshow_print_next_region(), compare_cells(), and main().
w2
Attribute* w2
{word} attribute (or whatever is selected with -P) handle: target
Referenced by alignshow_print_next_region(), compare_cells(), and main().
word_name
char word_name[CL_MAX_FILENAME_LENGTH] = "word"
name of the p-attribute used to display tokens (usually word)
Referenced by alignshow_parse_args(), and main().