CWB: utils/cwb-lexdecode.c File Reference
cwb-lexdecode.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <math.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
Functions
void lexdecode_print_item_info (Attribute *attr, int id, char *fallback_s)
Prints information about a specified item on a P-attribute.
void lexdecode_show (char *attr_name, char *rx, int rx_flags)
Prints out the lexicon of a P-attribute.
void lexdecode_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
int main (int argc, char **argv)
Main function for cwb-lexdecode.
Variables
char * progname
String set to the name of this program.
int print_nr = 0
boolean: flag whether we should print line numbers
int print_freqs = 0
boolean: print the frequencies of the words?
int print_len = 0
boolean: print the word length s?
int dont_pad_cols = 0
boolean: omit padding spaces on numeric columns?
int sort = 0
boolean: print the lexicon in a sorted order?
int input_are_numbers = 0
boolean: read lexicon IDs from file?
int show_size_only = 0
boolean: do_show should just print the size of the lexicon and exit?
int freq_0_if_unknown = 0
boolean: print out unknown words with freq 0?
Corpus * corpus = NULL
char * corpus_id = NULL
char * input_filename = NULL
Function Documentation
lexdecode_print_item_info()
void lexdecode_print_item_info (Attribute * attr, int id, char * fallback_s)
Prints information about a specified item on a P-attribute.
Parameters
attr The attribute to search
id The id number of the item (type) in question
fallback_s String to print if the item is not found (use NULL to use a default fallback string)
References CDA_OK, cl_errno, cl_error(), cl_id2all(), dont_pad_cols, print_freqs, print_len, and print_nr.
Referenced by lexdecode_show().
lexdecode_show()
void lexdecode_show (char * attr_name, char * rx, int rx_flags)
Prints out the lexicon of a P-attribute.
This is the business end of the cwb-lexdecode program.
Parameters
attr_name Name of the attribute to decode.
rx A regex that items must match to be printed. NULL if no regex is to be specified.
rx_flags IGNORE_CASE; IGNORE_DIAC; both; or neither.
References ATT_POS, cl_all_ok, cl_close_stream(), cl_error(), cl_max_cpos(), cl_max_id(), CL_MAX_LINE_LENGTH, cl_new_attribute(), cl_open_stream(), cl_regex2id(), cl_sort2id(), cl_str2id(), CL_STREAM_MAGIC, CL_STREAM_READ, corpus, corpus_id, freq_0_if_unknown, input_are_numbers, input_fd, input_filename, lexdecode_print_item_info(), progname, show_size_only, and sort.
Referenced by main().
lexdecode_usage()
void lexdecode_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
References CWB_VERSION, and progname.
Referenced by main().
main()
int main (int argc, char ** argv)
Main function for cwb-lexdecode.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References cl_delete_corpus(), cl_new_corpus(), cl_set_optimize(), cl_standard_registry(), cl_startup(), corpus, corpus_id, CWB_DEFAULT_ATT_NAME, dont_pad_cols, freq_0_if_unknown, IGNORE_CASE, IGNORE_DIAC, input_are_numbers, input_filename, lexdecode_show(), lexdecode_usage(), print_freqs, print_len, print_nr, progname, registry_directory, show_size_only, and sort.
Variable Documentation
corpus
Corpus* corpus = NULL
Referenced by lexdecode_show(), and main().
corpus_id
char* corpus_id = NULL
Referenced by lexdecode_show(), and main().
dont_pad_cols
int dont_pad_cols = 0
boolean: omit padding spaces on numeric columns?
Referenced by lexdecode_print_item_info(), and main().
freq_0_if_unknown
int freq_0_if_unknown = 0
boolean: print out unknown words with freq 0?
Referenced by lexdecode_show(), and main().
input_are_numbers
int input_are_numbers = 0
boolean: read lexicon IDs from file?
Referenced by lexdecode_show(), and main().
input_filename
char* input_filename = NULL
Referenced by lexdecode_show(), and main().
print_freqs
int print_freqs = 0
boolean: print the frequencies of the words?
Referenced by lexdecode_print_item_info(), and main().
print_len
int print_len = 0
boolean: print the word length s?
Referenced by lexdecode_print_item_info(), and main().
print_nr
int print_nr = 0
boolean: flag whether we should print line numbers
Referenced by lexdecode_print_item_info(), and main().
progname
char* progname
String set to the name of this program.
Name of the program (from the shell)
Referenced by lexdecode_show(), lexdecode_usage(), and main().
show_size_only
int show_size_only = 0
boolean: do_show should just print the size of the lexicon and exit?
Referenced by lexdecode_show(), and main().
sort
int sort = 0
boolean: print the lexicon in a sorted order?
Referenced by cl_idlist2cpos_oldstyle(), lexdecode_show(), and main().