CWB: utils/cwb-scan-corpus.c File Reference
cwb-scan-corpus.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <assert.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/corpus.h"
#include "../cl/special-chars.h"
Data Structures
struct _Hash
A specialised hashtable for computing frequency distributions over tuples of lexicon IDs.
Macros
#define MAX_N 32
maximum value of N (makes life a little easier)
Functions
void scancorpus_usage (void)
Prints a usage message and exits the program.
int scancorpus_parse_options (int argc, char *argv[])
Parses the command-line options of the program.
int scancorpus_word_is_regular (char *s)
Check regularity of a token.
void scancorpus_add_key (char *key)
Adds a key to global variable Hash.
int get_next_range (int *start, int *end)
Reads the next range of corpus positions.
void print_ngram_entry (FILE *fh, cl_ngram_hash_entry entry)
Format n-gram hash entry.
int collate_ngram_entries (const void *a, const void *b)
Collate two n-gram hash entries in canonical sort order (callback for qsort())
int main (int argc, char *argv[])
Main function for cwb-scan-corpus.
Variables
struct _Hash Hash
Corpus * C
corpus we're working on
char * reg_dir = NULL
registry directory (NULL -> use default)
char * corpname = NULL
corpus name (command-line)
int check_words = 0
if set, accept only 'regular' words in frequency counts
CL_Regex regular_rx = NULL
regex object for use when check_words is true.
char * progname = NULL
name of this program (from shell command)
char * output_file = NULL
output file name (-o option)
int sort_output = 0
sort output in canonical order (-S option)
int frequency_threshold = 0
frequency threshold for result table (-f option)
char * frequency_att = NULL
p-attribute with frequency entries for corpus rows (when abusing corpus as frequency database)
char * within_att = NULL
s-attribute that n-grams must be contained in, with optional document frequency counts
int do_within = 0
n-grams must be within region (-w <att>)
int do_df = 0
compute document frequencies wrt.
int global_start = 0
start scanning at this cpos (defaults to start of corpus)
int global_end = -1
will be set up in main() unless changed with -e switch.
char * ranges_file = NULL
file with ranges to scan (pairs of corpus positions)
FILE * ranges_fh = NULL
corresponding filehandle
int quiet = 0
if set, don't show progress information on stderr
int n_buckets = 0
if set, use fixed number of buckets; otherwise, revert to cl_ngram_hash defaults
int debug_level = 0
CL debug level.
Macro Definition Documentation
MAX_N
#define MAX_N 32
maximum value of N (makes life a little easier)
Function Documentation
collate_ngram_entries()
int collate_ngram_entries (const void * a, const void * b)
Collate two n-gram hash entries in canonical sort order (callback for qsort())
Canonical sort order iteratively compares the elements of the two n-grams as unsigned byte sequences, i.e. using strcmp() according to the C99 standard. Since CWB annotation strings must not contain control characters, this is equivalent to a strcmp() on the full n-grams with TAB separators.
Parameters
a pointer to first n-gram entry (i.e. a cl_ngram_hash_entry *)
b pointer to second n-gram entry (i.e. a cl_ngram_hash_entry *)
Returns
-1 if a < b, 0 if a == b, +1 if a > b
References _Hash::att, cl_id2str(), Hash, _Hash::is_constraint, _Hash::is_structural, _Hash::N, _cl_ngram_hash_entry::ngram, and _Hash::source_base.
Referenced by main().
get_next_range()
int get_next_range (int * start, int * end)
Reads the next range of corpus positions.
The ranges of corpus positions are taken either from global settings (-s, -e) or from a specified file (-R).
Parameters
start Where to put the start of the next range.
end Where to put the end of the next range.
Returns
FALSE after last range, TRUE otherwise
References CL_MAX_LINE_LENGTH, global_end, global_start, and ranges_fh.
Referenced by main().
main()
int main (int argc, char * argv[])
Main function for cwb-scan-corpus.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References _Hash::att, ATT_POS, ATT_STRUC, C, TCorpus::charset, check_words, cl_close_stream(), cl_cpos2id(), cl_cpos2struc(), cl_delete_regex(), cl_error(), cl_free, cl_id2str(), cl_malloc(), cl_max_cpos(), cl_max_id(), cl_max_struc(), cl_new_attribute(), cl_new_corpus(), cl_new_ngram_hash(), cl_new_regex(), cl_ngram_hash_add(), cl_ngram_hash_auto_grow(), cl_ngram_hash_get_entries(), cl_ngram_hash_iterator_next(), cl_ngram_hash_iterator_reset(), cl_ngram_hash_payload(), cl_ngram_hash_print_stats(), cl_ngram_hash_size(), cl_open_stream(), cl_regex_match(), cl_set_debug_level(), cl_standard_registry(), cl_startup(), CL_STREAM_MAGIC, CL_STREAM_READ, CL_STREAM_WRITE, cl_struc2cpos(), cl_struc2str(), collate_ngram_entries(), _Hash::constraint_ok, corpname, _Hash::current_struc, debug_level, do_df, do_within, _Hash::end_cpos, _cl_ngram_hash_entry::freq, _Hash::frequency, frequency_att, frequency_threshold, _Hash::frequency_values, get_next_range(), global_end, global_start, Hash, _Hash::id_list, _Hash::id_list_size, _Hash::is_constraint, _Hash::is_negated, _Hash::is_structural, _Hash::K, MAX_N, _Hash::max_offset, _Hash::N, n_buckets, _Hash::offset, output_file, print_ngram_entry(), progname, quiet, ranges_fh, ranges_file, reg_dir, _Hash::regex, regular_rx, scancorpus_add_key(), scancorpus_parse_options(), scancorpus_usage(), scancorpus_word_is_regular(), sort_output, _Hash::source_base, _Hash::start_cpos, _Hash::table, utf8, _Hash::virtual_id, _Hash::within, within_att, and word.
print_ngram_entry()
void print_ngram_entry (FILE * fh, cl_ngram_hash_entry entry)
Format n-gram hash entry.
The formatted n-gram entry is written to the specified stream in format [freq] TAB [w1] TAB [w2] TAB ...
Parameters
fh output stream (use stdout to display in terminal)
entry n-gram hash entry to be printed
References _Hash::att, cl_id2str(), _cl_ngram_hash_entry::freq, Hash, _Hash::is_constraint, _Hash::is_structural, _Hash::N, _cl_ngram_hash_entry::ngram, and _Hash::source_base.
Referenced by main().
scancorpus_add_key()
void scancorpus_add_key (char * key)
Adds a key to global variable Hash.
Parameters
key String specifying the key (passed by main() from a command-line argument)
References _Hash::att, ATT_POS, ATT_STRUC, buf, C, check_words, cl_corpus_charset(), cl_id2str(), CL_MAX_LINE_LENGTH, cl_max_struc(), cl_new_attribute(), cl_new_regex(), cl_regex2id(), cl_struc2str(), cl_struc_values(), _Hash::constraint_ok, corpname, _Hash::current_struc, _Hash::end_cpos, Hash, _Hash::id_list, _Hash::id_list_size, IGNORE_CASE, IGNORE_DIAC, _Hash::is_constraint, _Hash::is_negated, _Hash::is_structural, _Hash::K, key, _Hash::max_offset, _Hash::N, _Hash::offset, _Hash::regex, scancorpus_word_is_regular(), _Hash::source_base, and _Hash::start_cpos.
Referenced by main().
scancorpus_parse_options()
int scancorpus_parse_options (int argc, char * argv[])
Parses the command-line options of the program.
Parameters
argc argc from main()
argv argv from main()
Returns
The value of global optind after the function has run.
References check_words, debug_level, do_df, do_within, frequency_att, frequency_threshold, global_end, global_start, n_buckets, output_file, quiet, ranges_file, reg_dir, scancorpus_usage(), sort_output, and within_att.
Referenced by main().
scancorpus_usage()
void scancorpus_usage (void)
Prints a usage message and exits the program.
References CWB_VERSION, and MAX_N.
Referenced by main(), and scancorpus_parse_options().
scancorpus_word_is_regular()
int scancorpus_word_is_regular (char * s)
Check regularity of a token.
A token is "regular" if it contains only letters, numbers and dashes (with no dash at the start or end).
"Regularity" is used as a filter on the corpus iff the -C option is specified.
Parameters
s String containing the token to check.
Returns
True if the token is regular, otherwise false.
References C, TCorpus::charset, cl_iso_char_is_alphanumeric(), cl_regex_match(), regular_rx, and utf8.
Referenced by main(), and scancorpus_add_key().
Variable Documentation
C
Corpus* C
corpus we're working on
Referenced by main(), regex2dfa(), scancorpus_add_key(), scancorpus_word_is_regular(), and WriteStates().
check_words
int check_words = 0
if set, accept only 'regular' words in frequency counts
Referenced by main(), scancorpus_add_key(), and scancorpus_parse_options().
corpname
char* corpname = NULL
corpus name (command-line)
Referenced by do_undump(), main(), and scancorpus_add_key().
debug_level
int debug_level = 0
CL debug level.
Referenced by main(), and scancorpus_parse_options().
do_df
int do_df = 0
compute document frequencies wrt.
s-attribute (-d <att>, implies -w <att>)
Referenced by main(), and scancorpus_parse_options().
do_within
int do_within = 0
n-grams must be within region (-w <att>)
Referenced by ComputeGroupInternally(), main(), and scancorpus_parse_options().
frequency_att
char* frequency_att = NULL
p-attribute with frequency entries for corpus rows (when abusing corpus as frequency database)
Referenced by main(), and scancorpus_parse_options().
frequency_threshold
int frequency_threshold = 0
frequency threshold for result table (-f option)
Referenced by main(), and scancorpus_parse_options().
global_end
int global_end = -1
will be set up in main() unless changed with -e switch.
See also
global_start
Referenced by get_next_range(), main(), and scancorpus_parse_options().
global_start
int global_start = 0
start scanning at this cpos (defaults to start of corpus)
Referenced by get_next_range(), main(), and scancorpus_parse_options().
Hash
struct _Hash Hash
Referenced by collate_ngram_entries(), main(), print_ngram_entry(), and scancorpus_add_key().
n_buckets
int n_buckets = 0
if set, use fixed number of buckets; otherwise, revert to cl_ngram_hash defaults
Referenced by main(), and scancorpus_parse_options().
output_file
char* output_file = NULL
output file name (-o option)
Referenced by main(), and scancorpus_parse_options().
progname
char* progname = NULL
name of this program (from shell command)
Name of the program (from the shell)
Referenced by main().
quiet
int quiet = 0
if set, don't show progress information on stderr
Referenced by main(), and scancorpus_parse_options().
ranges_fh
FILE* ranges_fh = NULL
corresponding filehandle
Referenced by get_next_range(), and main().
ranges_file
char* ranges_file = NULL
file with ranges to scan (pairs of corpus positions)
Referenced by main(), and scancorpus_parse_options().
reg_dir
char* reg_dir = NULL
registry directory (NULL -> use default)
Referenced by main(), and scancorpus_parse_options().
regular_rx
CL_Regex regular_rx = NULL
regex object for use when check_words is true.
See also
scancorpus_word_is_regular
Referenced by main(), and scancorpus_word_is_regular().
sort_output
int sort_output = 0
sort output in canonical order (-S option)
Referenced by main(), and scancorpus_parse_options().
within_att
char* within_att = NULL
s-attribute that n-grams must be contained in, with optional document frequency counts
Referenced by main(), and scancorpus_parse_options().