CWB: utils/cwb-align-decode.c File Reference
cwb-align-decode.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
Functions
void aligndecode_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
int main (int argc, char **argv)
Main function for cwb-align-decode.
Variables
char * progname
Name of the program (from the shell)
Function Documentation
aligndecode_usage()
void aligndecode_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
References CWB_VERSION, and progname.
Referenced by main().
main()
int main (int argc, char ** argv)
Main function for cwb-align-decode.
Prints .align file header, followed by start and end positions of alignment beads of the specified sentence-level alignment to STDOUT,
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References aligndecode_usage(), ATT_ALIGN, cl_alg2cpos(), cl_error(), cl_id_tolower(), cl_id_toupper(), cl_max_alg(), cl_new_attribute(), cl_new_corpus(), cl_standard_registry(), cl_startup(), cl_strdup(), corpus, corpus_id, progname, and registry_directory.
Variable Documentation
progname
char* progname
Name of the program (from the shell)
Referenced by aligndecode_usage(), and main().