CWB: utils/cwb-decode.c File Reference
cwb-decode.c File Reference
#include <ctype.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/corpus.h"
#include "../cl/attributes.h"
Data Structures
struct AVList
Chain of s-attributes that represent attribute-value pairs of an XML region.
struct AttSpec
Represents an attribute to be printed together with some additional information.
struct SAttRegion
Represents a single s-attribute region and its annotation.
Macros
#define MAX_ATTRS 2048
Maximum number of attributes that can be printed.
#define MAX_PRINT_VALUES 1024
Maximum number of attributes whose "surrounding values" can be printed in matchlist mode.
Typedefs
typedef struct AVList * AVList
Chain of s-attributes that represent attribute-value pairs of an XML region.
typedef enum _output_modes OutputMode
Supported output formats:
Enumerations
enum _output_modes {
StandardMode , LispMode , EncodeMode , ConclineMode ,
XMLMode
}
Supported output formats:
Functions
void cleanup_and_exit (int error_code)
Cleans up memory prior to an error-prompted exit.
void decode_usage (int exit_code)
Prints a usage message and exits the program.
int is_num (char *s)
Check whether a string represents a number.
const char * decode_string_escape (const char *s)
Escapes a string according to the currently active global mode.
void decode_print_xml_declaration (void)
Prints an XML declaration, using character set specification obtained from the global corpus variable.
void decode_sort_s_att_regions (void)
Sorts s_att_regions[MAX_ATTRS] in ascending 'nested' order, using sar_sort_index[] (which is automatically initialised).
int decode_attribute_is_in_list (Attribute *handle, AttSpec *att_list, int att_list_size)
Determines whether or not a given Attribute is in an array of attribute specifications.
Attribute * get_attribute_handle (const char *name, int type)
Obtains CWB handle for the specified attribute.
int decode_add_attribute (const char *name, int type, const char *display_name, const char *avspec, int recursion)
Adds a specified attribute (by name and type) to the global print_list array.
int decode_add_s_attribute (const char *att_spec)
Add structural attribute, with support for an extended specification as shown below.
void decode_verify_print_value_list (void)
Check the context of the global printValues array, to check that no s-attribute in it is declared in the main print_list_index as well.
void decode_print_surrounding_s_att_values (int position)
Prints a starting tag for each s-attribute surrounding the position (for -V flags)
void decode_expand_context (int *start, int *end, Attribute *context)
Expand range [start] .
void decode_print_token_sequence (int start_position, int end_position, Attribute *context, int skip_token)
Prints out the requested attributes for a sequence of tokens (or a single token if end_position == -1, which also indicates that we're not in matchlist mode).
int main (int argc, char **argv)
Main function for cwb-decode.
Variables
char * progname = NULL
Name of the program (from the shell)
char * registry_directory = NULL
char * corpus_id = NULL
Corpus * corpus = NULL
AttSpec print_list [MAX_ATTRS]
array of attributes selected by user for printing
int print_list_index = 0
Number of atts added to print_list (so far), i.e.
SAttRegion s_att_regions [MAX_ATTRS]
int sar_sort_index [MAX_ATTRS]
index used for bubble-sorting list of regions
int N_sar = 0
number of regions currently in list (may change for each token printed)
Attribute * printValues [MAX_PRINT_VALUES]
List of s-attributes whose values are to be printed.
int printValuesIndex = 0
Number of atts added to printValues (so far); used with less-than, = top limit for scrolling that array.
int first_token
cpos of token to begin output at
int last_token
cpos of token to end output at (inclusive; ie this one gets printed!)
int maxlast
maximum ending cpos + 1 (deduced from size of p-attribute);
int printnum = 0
whether or not token numbers are to be printed (-n option)
Attribute * conll_delimiter = NULL
if not NULL, print empty line after each region of this s-attribute
OutputMode mode = StandardMode
global variable for overall output mode
int xml_compatible = 0
xml-style, for (cwb-encode -x ...); EncodeMode only, selected by -Cx
Macro Definition Documentation
MAX_ATTRS
#define MAX_ATTRS 2048
Maximum number of attributes that can be printed.
MAX_PRINT_VALUES
#define MAX_PRINT_VALUES 1024
Maximum number of attributes whose "surrounding values" can be printed in matchlist mode.
Typedef Documentation
AVList
typedef struct AVList * AVList
Chain of s-attributes that represent attribute-value pairs of an XML region.
OutputMode
typedef enum _output_modes OutputMode
Supported output formats:
EncodeMode -C, -Cx ... the main and best-supported output format XMLMode -X ... XML output ConclineMode -H ... "horizontal" output, intended for kwic-style concordance lines LispMode -L ... Lisp-style notation StandardMode ... the default output format
Enumeration Type Documentation
_output_modes
enum _output_modes
Supported output formats:
EncodeMode -C, -Cx ... the main and best-supported output format XMLMode -X ... XML output ConclineMode -H ... "horizontal" output, intended for kwic-style concordance lines LispMode -L ... Lisp-style notation StandardMode ... the default output format
Enumerator
StandardMode
LispMode
EncodeMode
ConclineMode
XMLMode
Function Documentation
cleanup_and_exit()
void cleanup_and_exit (int error_code)
Cleans up memory prior to an error-prompted exit.
This should be completely superfluous because cwb-decode doesn't acquire any external resources (and memory will be released much more efficiently by program termination).
Parameters
error_code Value to be returned by the program when it exits.
References AttSpec::av_list, cl_delete_attribute(), cl_delete_corpus(), cl_free, corpus, AVList::handle, AVList::name, AVList::next, print_list, and print_list_index.
Referenced by decode_add_attribute(), decode_add_s_attribute(), decode_print_token_sequence(), decode_usage(), get_attribute_handle(), and main().
decode_add_attribute()
int decode_add_attribute (const char * name, int type, const char * display_name, const char * avspec, int recursion)
Adds a specified attribute (by name and type) to the global print_list array.
Aborts the program if that array is already full or another error occurs.
Parameters
name CWB name of the attribute.
type Attribute type (ATT_POS, ATT_STRUC, ATT_ALIGN).
display_name Print attribute under a different name (NULL: use 'name').
avspec Optional '+'-separated specifier of XML attribute-value pairs (ATT_STRUC only).
recursion Recursion level, appended to all attribute names (esp. those created by avspec).
Returns
Boolean.
References ATT_STRUC, AttSpec::av_list, cl_free, cl_malloc(), CL_MAX_LINE_LENGTH, cl_max_struc(), cl_strcpy(), cl_strdup(), cl_struc_values(), cleanup_and_exit(), corpus_id, decode_attribute_is_in_list(), get_attribute_handle(), AttSpec::handle, MAX_ATTRS, AVList::name, AttSpec::name, AVList::next, print_list, print_list_index, and AttSpec::type.
Referenced by decode_add_s_attribute(), and main().
decode_add_s_attribute()
int decode_add_s_attribute (const char * att_spec)
Add structural attribute, with support for an extended specification as shown below.
If it includes a recursion marker, further s-attributes will be declared. Aborts the program with a suitable message if any error is encountered.
An extended attribute specification has a form similar to that used by cwb-encode, with the addition of an alternative display_name that can optionally be specified.
[display_name=]name[:N][+av1+av2+...]
Parameters
att_spec Attribute specification of the form described above.
Returns
Boolean.
References ATT_STRUC, cl_free, cl_strdup(), cleanup_and_exit(), and decode_add_attribute().
Referenced by main().
decode_attribute_is_in_list()
int decode_attribute_is_in_list (Attribute * handle, AttSpec * att_list, int att_list_size)
Determines whether or not a given Attribute is in an array of attribute specifications.
Parameters
handle CWB handle of the attribute to look for.
att_list Pointer to the first member of the array (i.e. array name).
att_list_size Upper bound of the array (the last member the function checks is attlist[attlist_size-1]).
Returns
Boolean.
Referenced by decode_add_attribute(), and decode_verify_print_value_list().
decode_expand_context()
void decode_expand_context (int * start, int * end, Attribute * context)
Expand range [start] .
. [end] to encompass full regions of s-attribute [context].
Function arguments are overwritten with the new values.
References cl_cpos2struc2cpos().
Referenced by decode_print_token_sequence(), and main().
decode_print_surrounding_s_att_values()
void decode_print_surrounding_s_att_values (int position)
Prints a starting tag for each s-attribute surrounding the position (for -V flags)
References _Attribute::any, cl_cpos2struc(), cl_struc2str(), ConclineMode, decode_string_escape(), EncodeMode, LispMode, mode, printValues, printValuesIndex, StandardMode, and XMLMode.
Referenced by main().
decode_print_token_sequence()
void decode_print_token_sequence (int start_position, int end_position, Attribute * context, int skip_token)
Prints out the requested attributes for a sequence of tokens (or a single token if end_position == -1, which also indicates that we're not in matchlist mode).
If the -c flag was used (and, thus, the context parameter is not NULL), then the sequence is extended to the entire s-attribute region (intended for matchlist mode).
If the additional skip_token parameter is true, only XML tags before/after each token are printed, but not the tokens themselves (for subcorpus mode).
References SAttRegion::annot, ATT_ALIGN, ATT_DYN, ATT_POS, ATT_STRUC, AttSpec::av_list, SAttRegion::av_list, CDA_EALIGN, CDA_ESTRUC, cl_alg2cpos(), cl_cpos2alg(), cl_cpos2boundary(), cl_cpos2str(), cl_cpos2struc(), cl_cpos2struc2cpos(), cl_cpos2struc2str(), cl_errno, cl_error(), cl_struc2cpos(), cl_struc2str(), cl_struc_values(), cleanup_and_exit(), ConclineMode, conll_delimiter, decode_expand_context(), decode_sort_s_att_regions(), decode_string_escape(), EncodeMode, SAttRegion::end, AVList::handle, LispMode, mode, N_sar, SAttRegion::name, AVList::name, AttSpec::name, AVList::next, print_list, print_list_index, printnum, s_att_regions, sar_sort_index, StandardMode, SAttRegion::start, STRUC_RBOUND, and XMLMode.
Referenced by main().
decode_print_xml_declaration()
void decode_print_xml_declaration (void)
Prints an XML declaration, using character set specification obtained from the global corpus variable.
References arabic, charset, cl_corpus_charset(), corpus, cyrillic, greek, hebrew, latin1, latin2, latin3, latin4, latin5, latin6, latin7, latin8, latin9, unknown_charset, and utf8.
Referenced by main().
decode_sort_s_att_regions()
void decode_sort_s_att_regions (void)
Sorts s_att_regions[MAX_ATTRS] in ascending 'nested' order, using sar_sort_index[] (which is automatically initialised).
Since only regions which begin or end at the current token are considered, such an ordering is always possible; without knowing the current token, we sort by end position descending, then by start position ascending, which gives us:
first the regions corresponding to start tags, beginning with the 'largest' region
then the regions corresponding to end tags, again beginning with the 'largest' region
The function uses bubble sort in order to retain the existing order of identical regions.
References SAttRegion::end, N_sar, s_att_regions, sar_sort_index, and SAttRegion::start.
Referenced by decode_print_token_sequence().
decode_string_escape()
const char* decode_string_escape (const char * s)
Escapes a string according to the currently active global mode.
In XMLMode, this function converts the string to an encoded XML string; all 'critical' characters are replaced by entity references, and C0 control characters are replaced with blanks. (This also happens in other modes - i.e. compact - if the global xml_compatible variable is true.)
In LispMode, it converts the string to a Lisp string with the required escapes (probably!)
In any other mode, it does nothing, and just returns the argument pointer.
It is safe to use this function without checking for a NULL argument, as NULLs will just be returned as NULLs.
Warning: returns pointer to static internal buffer of fixed size; in particular, don't use it twice in a single argument list!
See also
EncodeMode
Parameters
s String to encode.
Returns
Pointer to encoded string in static internal buffer; or, the argument s iff the mode is not one that requires any encoding. If the argument is NULL, NULL is returned.
References CL_MAX_LINE_LENGTH, LispMode, mode, xml_compatible, and XMLMode.
Referenced by decode_print_surrounding_s_att_values(), and decode_print_token_sequence().
decode_usage()
void decode_usage (int exit_code)
Prints a usage message and exits the program.
Parameters
exit_code Value to be returned by the program when it exits.
References cleanup_and_exit(), CWB_VERSION, and progname.
Referenced by main().
decode_verify_print_value_list()
void decode_verify_print_value_list (void)
Check the context of the global printValues array, to check that no s-attribute in it is declared in the main print_list_index as well.
If an attribute is found to be declared in both, a warning is printed.
References corpus_id, decode_attribute_is_in_list(), print_list, print_list_index, printValues, and printValuesIndex.
Referenced by main().
get_attribute_handle()
Attribute* get_attribute_handle (const char * name, int type)
Obtains CWB handle for the specified attribute.
Aborts the program in case of any error, so the return value does not need to be checked.
Parameters
name CWB name of the attribute.
type Attribute type (ATT_POS, ATT_STRUC, ATT_ALIGN).
Returns
CWB handle of the attribute (Attribute *).
References ATT_ALIGN, ATT_DYN, ATT_POS, ATT_STRUC, cl_new_attribute(), cleanup_and_exit(), corpus, corpus_id, and progname.
Referenced by decode_add_attribute().
is_num()
int is_num (char * s)
Check whether a string represents a number.
Parameters
s The string to check.
Returns
Boolean: true iff s contains only digits.
Referenced by main().
main()
int main (int argc, char ** argv)
Main function for cwb-decode.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References _Attribute::any, ATT_ALIGN, ATT_POS, ATT_STRUC, TCorpus::attributes, cl_close_stream(), cl_error(), cl_max_cpos(), CL_MAX_LINE_LENGTH, cl_new_attribute(), cl_new_corpus(), cl_open_stream(), cl_standard_registry(), cl_startup(), cl_str_is, CL_STREAM_MAGIC, CL_STREAM_READ, cl_struc_values(), cleanup_and_exit(), ConclineMode, conll_delimiter, corpus, corpus_id, decode_add_attribute(), decode_add_s_attribute(), decode_expand_context(), decode_print_surrounding_s_att_values(), decode_print_token_sequence(), decode_print_xml_declaration(), decode_usage(), decode_verify_print_value_list(), EncodeMode, first_token, input_file, input_filename, is_num(), last_token, LispMode, MAX_PRINT_VALUES, maxlast, mode, print_list, print_list_index, printnum, printValues, printValuesIndex, progname, registry_directory, token, xml_compatible, and XMLMode.
Variable Documentation
conll_delimiter
Attribute* conll_delimiter = NULL
if not NULL, print empty line after each region of this s-attribute
Referenced by decode_print_token_sequence(), and main().
corpus
Corpus* corpus = NULL
Referenced by cleanup_and_exit(), decode_print_xml_declaration(), get_attribute_handle(), and main().
corpus_id
char* corpus_id = NULL
Referenced by decode_add_attribute(), decode_verify_print_value_list(), get_attribute_handle(), and main().
first_token
int first_token
cpos of token to begin output at
Referenced by main().
last_token
int last_token
cpos of token to end output at (inclusive; ie this one gets printed!)
Referenced by main().
maxlast
int maxlast
maximum ending cpos + 1 (deduced from size of p-attribute);
Referenced by main().
mode
OutputMode mode = StandardMode
global variable for overall output mode
Referenced by cat_listed_corpus(), cl_open_stream(), decode_print_surrounding_s_att_values(), decode_print_token_sequence(), decode_string_escape(), delete_intervals(), do_delete_lines(), main(), mallocfile(), mmapfile(), open_rd_output_stream(), print_concordance_body(), and print_corpus_info_header().
N_sar
int N_sar = 0
number of regions currently in list (may change for each token printed)
Referenced by decode_print_token_sequence(), and decode_sort_s_att_regions().
print_list
AttSpec print_list[MAX_ATTRS]
array of attributes selected by user for printing
Referenced by cleanup_and_exit(), decode_add_attribute(), decode_print_token_sequence(), decode_verify_print_value_list(), and main().
print_list_index
int print_list_index = 0
Number of atts added to print_list (so far), i.e.
index of the first free element
Referenced by cleanup_and_exit(), decode_add_attribute(), decode_print_token_sequence(), decode_verify_print_value_list(), and main().
printnum
int printnum = 0
whether or not token numbers are to be printed (-n option)
Referenced by decode_print_token_sequence(), and main().
printValues
Attribute* printValues[MAX_PRINT_VALUES]
List of s-attributes whose values are to be printed.
Referenced by decode_print_surrounding_s_att_values(), decode_verify_print_value_list(), and main().
printValuesIndex
int printValuesIndex = 0
Number of atts added to printValues (so far); used with less-than, = top limit for scrolling that array.
Referenced by decode_print_surrounding_s_att_values(), decode_verify_print_value_list(), and main().
progname
char* progname = NULL
Name of the program (from the shell)
Name of the program (from the shell)
Referenced by decode_usage(), get_attribute_handle(), and main().
registry_directory
char* registry_directory = NULL
Referenced by main().
s_att_regions
SAttRegion s_att_regions[MAX_ATTRS]
Referenced by decode_print_token_sequence(), and decode_sort_s_att_regions().
sar_sort_index
int sar_sort_index[MAX_ATTRS]
index used for bubble-sorting list of regions
Referenced by decode_print_token_sequence(), and decode_sort_s_att_regions().
xml_compatible
int xml_compatible = 0
xml-style, for (cwb-encode -x ...); EncodeMode only, selected by -Cx
Referenced by decode_string_escape(), and main().