CWB: utils/cwb-describe-corpus.c File Reference
cwb-describe-corpus.c File Reference
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include "../cl/ui-helpers.h"
Functions
void describecorpus_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
void describecorpus_show_attribute_names (Corpus *corpus, int type)
Prints the names of attributes in a corpus to STDOUT.
void describecorpus_show_basic_info (Corpus *corpus, int with_attribute_names)
Prints basic information about a corpus to STDOUT.
void describecorpus_show_statistics (Corpus *corpus)
Prints statistical information about a corpus to STDOUT.
int main (int argc, char **argv)
Main function for cwb-describe-corpus.
Variables
char * progname = NULL
String set to the name of this program.
Function Documentation
describecorpus_show_attribute_names()
void describecorpus_show_attribute_names (Corpus * corpus, int type)
Prints the names of attributes in a corpus to STDOUT.
Only one type of attribute is analysed.
Parameters
corpus The corpus to analyse.
type The type of attribute to show. This should be one of the constants in cl.h (ATT_POS etc.)
References _Attribute::any, TCorpus::attributes, corpus, ilist_print_item(), and ilist_start().
Referenced by describecorpus_show_basic_info().
describecorpus_show_basic_info()
void describecorpus_show_basic_info (Corpus * corpus, int with_attribute_names)
Prints basic information about a corpus to STDOUT.
Parameters
corpus The corpus to report on.
with_attribute_names Boolean: iff true, the counts of each type of attribute are followed by a list of attribute names.
References _Attribute::any, ATT_ALIGN, ATT_POS, ATT_STRUC, TCorpus::attributes, TCorpus::charset, cl_charset_name(), cl_max_cpos(), cl_new_attribute(), corpus, describecorpus_show_attribute_names(), TCorpus::info_file, TCorpus::name, TCorpus::path, TCorpus::registry_dir, TCorpus::registry_name, and word.
Referenced by main().
describecorpus_show_statistics()
void describecorpus_show_statistics (Corpus * corpus)
Prints statistical information about a corpus to STDOUT.
Each corpus attribute gets info printed about it: tokens and types for a P-attribute, number of instances of regions for an S-attribute, number of alignment blocks for an A-attribute.
Parameters
corpus The corpus to analyse.
References _Attribute::any, ATT_ALIGN, ATT_POS, ATT_STRUC, TCorpus::attributes, cl_has_extended_alignment(), cl_max_alg(), cl_max_cpos(), cl_max_id(), cl_max_struc(), cl_struc_values(), and corpus.
Referenced by main().
describecorpus_usage()
void describecorpus_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
References CWB_VERSION, and progname.
Referenced by main().
main()
int main (int argc, char ** argv)
Main function for cwb-describe-corpus.
Prints information about an indexed corpus to STDOUT.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References cl_delete_corpus(), cl_new_corpus(), cl_startup(), corpus, describe_corpus(), describecorpus_show_basic_info(), describecorpus_show_statistics(), describecorpus_usage(), progname, and registry.
Variable Documentation
progname
char* progname = NULL
String set to the name of this program.
Name of the program (from the shell)
Referenced by describecorpus_usage(), and main().