CWB: utils/cwb-huffcode.c File Reference
cwb-huffcode.c File Reference
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include "../cl/storage.h"
#include "../cl/bitio.h"
Functions
void print_binary_integer (unsigned int i, int width, FILE *stream)
Prints, to the specified stream, a string containing a binary representation of an integer.
static void dump_heap (unsigned int *heap, int heap_size, int node, int indent)
Dumps the specified heap of memory to the program's STDOUT.
static void print_heap (unsigned int *heap, int heap_size, char *title)
Prints a description of the specified heap of memory to the program's STDOUT.
static int sift (unsigned int *heap, int heap_size, int node)
Sifts the heap into order.
static int WriteHCD (char *filename, HCD *hc)
Writes a Huffman code descriptor to file.
static int ReadHCD (char *filename, HCD *hc)
Reads a Huffman Code Descriptor from file.
static int compute_code_lengths (Attribute *attr, HCD *hc, char *fname)
Compresses the token stream of a p-attribute.
static void decode_check_huff (Attribute *attr, char *fname)
Checks a huffcoded attribute for errors by decompressing it.
static void huffcode_usage (char *msg, int error_code)
Prints a usage message and exits the program.
int main (int argc, char **argv)
Main function for cwb-huffcode.
Variables
int the_truth_is_out_there = 0
Level of progress-info (inc compression protocol) message output: 0 = none, 4 = everything.
int i_want_to_believe = 0
Suppress error checks? True = yews, false = 0.
FILE * protocol
File handle for this program's progress-info output: note, it is always stdout.
char * progname
Name of the program (from the shell)
Corpus * corpus
char * corpus_id = NULL
int debug = 0
Function Documentation
compute_code_lengths()
static int compute_code_lengths (Attribute * attr, HCD * hc, char * fname) static
Compresses the token stream of a p-attribute.
Three files are created: the compressed token stream, the descriptor block, and a sync file.
Parameters
attr The attribute to compress.
hc Location for the resulting Huffmann code descriptor block.
fname Base filename for the resulting files.
References _Attribute::any, BFclose(), BFflush(), BFopen(), BFposition(), BFwriteWord(), cl_all_ok, cl_calloc(), cl_cpos2id(), cl_error(), cl_free, cl_id2freq(), cl_id2str(), cl_malloc(), cl_max_cpos(), cl_max_id(), CL_MAX_LINE_LENGTH, CompCorpus, CompCorpusFreqs, CompHuffCodes, CompHuffSeq, CompHuffSync, CompLexicon, CompLexiconIdx, component_full_name(), corpus, corpus_id, ensure_component(), _huffman_code_descriptor::lcount, _huffman_code_descriptor::length, _huffman_code_descriptor::max_codelen, MAXCODELEN, _huffman_code_descriptor::min_code, _huffman_code_descriptor::min_codelen, NwriteInt(), print_binary_integer(), print_heap(), protocol, TCorpus::registry_dir, TCorpus::registry_name, sift(), _huffman_code_descriptor::size, _huffman_code_descriptor::symbols, _huffman_code_descriptor::symindex, SYNCHRONIZATION, the_truth_is_out_there, and WriteHCD().
Referenced by main().
decode_check_huff()
static void decode_check_huff (Attribute * attr, char * fname) static
Checks a huffcoded attribute for errors by decompressing it.
This function assumes that compute_code_lengths() has been called beforehand and made sure that the uncompressed token sequence is used by CL access functions.
It exits on error, so there's no return value.
Parameters
attr The attribute to check.
fname Base filename to use for the three compressed-attribute files. Can be NULL, in which case the filenames in the attribute are used.
References _Attribute::any, BFclose(), BFflush(), BFopen(), BFposition(), BFread(), cl_all_ok, cl_cpos2id(), cl_max_cpos(), CL_MAX_LINE_LENGTH, cl_strcpy(), CompCorpus, CompHuffCodes, CompHuffSeq, CompHuffSync, component_full_name(), corpus_id, _huffman_code_descriptor::length, _huffman_code_descriptor::min_code, NreadInt(), ReadHCD(), _huffman_code_descriptor::symbols, _huffman_code_descriptor::symindex, and SYNCHRONIZATION.
Referenced by main().
dump_heap()
static void dump_heap (unsigned int * heap, int heap_size, int node, int indent) static
Dumps the specified heap of memory to the program's STDOUT.
See also
protocol
Parameters
heap Location of the heap to dump.
heap_size Number of nodes in the heap.
node Heap at which to begin dumping.
indent How many tabs to indent the start of each line.
References node, and protocol.
Referenced by print_heap().
huffcode_usage()
static void huffcode_usage (char * msg, int error_code) static
Prints a usage message and exits the program.
Parameters
msg A message about the error.
error_code Value to be returned by the program when it exits.
References cl_delete_corpus(), corpus, CWB_VERSION, and progname.
Referenced by main().
main()
int main (int argc, char ** argv)
Main function for cwb-huffcode.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References _Attribute::any, ATT_POS, TCorpus::attributes, cl_delete_corpus(), cl_new_attribute(), cl_new_corpus(), cl_standard_registry(), cl_startup(), compute_code_lengths(), corpus, corpus_id, CWB_DEFAULT_ATT_NAME, debug, decode_check_huff(), huffcode_usage(), i_want_to_believe, progname, protocol, registry_directory, and the_truth_is_out_there.
print_binary_integer()
void print_binary_integer (unsigned int i, int width, FILE * stream)
Prints, to the specified stream, a string containing a binary representation of an integer.
Parameters
i Integer to print.
width Number of bits in the integer.
stream Where to print to.
Referenced by compute_code_lengths().
print_heap()
static void print_heap (unsigned int * heap, int heap_size, char * title) static
Prints a description of the specified heap of memory to the program's STDOUT.
See also
protocol
Parameters
heap Location of the heap to print.
heap_size Number of nodes in the heap.
title Title of the heap to print.
References dump_heap(), and protocol.
Referenced by compute_code_lengths().
ReadHCD()
static int ReadHCD (char * filename, HCD * hc) static
Reads a Huffman Code Descriptor from file.
Parameters
filename Path to file where descriptor is saved.
hc Pointer to location where the descriptor block will be loaded to.
Returns
Boolean: true for all OK, false for error.
References cl_malloc(), _huffman_code_descriptor::lcount, _huffman_code_descriptor::length, _huffman_code_descriptor::max_codelen, MAXCODELEN, _huffman_code_descriptor::min_code, _huffman_code_descriptor::min_codelen, NreadInt(), NreadInts(), _huffman_code_descriptor::size, _huffman_code_descriptor::symbols, and _huffman_code_descriptor::symindex.
Referenced by decode_check_huff().
sift()
static int sift (unsigned int * heap, int heap_size, int node) static
Sifts the heap into order.
Parameters
heap Location of the heap to sift.
heap_size Number of nodes in the heap.
node Node at which to begin sifting.
Returns
Number of swaps needed during the sifting.
References node.
Referenced by compute_code_lengths().
WriteHCD()
static int WriteHCD (char * filename, HCD * hc) static
Writes a Huffman code descriptor to file.
Parameters
filename Path to file where descriptor is to be saved.
hc Pointer to the descriptor block to save.
Returns
Boolean: true for all OK, false for error.
References _huffman_code_descriptor::lcount, _huffman_code_descriptor::length, _huffman_code_descriptor::max_codelen, MAXCODELEN, _huffman_code_descriptor::min_code, _huffman_code_descriptor::min_codelen, NwriteInt(), NwriteInts(), _huffman_code_descriptor::size, _huffman_code_descriptor::symbols, and _huffman_code_descriptor::symindex.
Referenced by compute_code_lengths().
Variable Documentation
corpus
Corpus* corpus
Referenced by compute_code_lengths(), huffcode_usage(), and main().
corpus_id
char* corpus_id = NULL
Referenced by compute_code_lengths(), decode_check_huff(), and main().
debug
int debug = 0
Referenced by main().
i_want_to_believe
int i_want_to_believe = 0
Suppress error checks? True = yews, false = 0.
Referenced by main().
progname
char* progname
Name of the program (from the shell)
Name of the program (from the shell)
Referenced by huffcode_usage(), and main().
protocol
FILE* protocol
File handle for this program's progress-info output: note, it is always stdout.
Referenced by compute_code_lengths(), dump_heap(), main(), and print_heap().
the_truth_is_out_there
int the_truth_is_out_there = 0
Level of progress-info (inc compression protocol) message output: 0 = none, 4 = everything.
Referenced by compute_code_lengths(), and main().