CWB: utils/cwb-decode-nqrfile.c File Reference
cwb-decode-nqrfile.c File Reference
See cqp/corpmanag.c for the file format that this utility decodes.
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
Functions
int file_length_from_handle (FILE *file_handle)
Gets the size of the file.
int nqrfile_print_info (FILE *src, int print_header)
Reads a subcorpus file and prints information about it to STDOUT.
int main (int argc, char **argv)
Main function for cwb-decode-nqrfile.
Detailed Description
See cqp/corpmanag.c for the file format that this utility decodes.
Function Documentation
file_length_from_handle()
int file_length_from_handle (FILE * file_handle)
Gets the size of the file.
The ponderous name is to avoid clashing with a function in the CL.
Parameters
file_handle File handle.
Returns
The size of the file, from stat().
Referenced by nqrfile_print_info().
main()
int main (int argc, char ** argv)
Main function for cwb-decode-nqrfile.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References cl_startup(), cl_str_is, and nqrfile_print_info().
nqrfile_print_info()
int nqrfile_print_info (FILE * src, int print_header)
Reads a subcorpus file and prints information about it to STDOUT.
"Subcorpus file" here means (a) it begins with the subcorpus magic number; (b) then there is a "registry" area terminated by one or more zero bytes; (c) then there may be the size of the subcorpus; (d) then there are a whole load of start-end range integer pairs, to the end of the file.
The registry is printed iff print_header. The start-end pairs are printed on tab-delimited lines, one line per pair.
Parameters
src File pointer.
print_header Boolean: controls whether a "registry" header in the subcorpus file gets printed or not
Returns
Boolean: true for all OK, false for problem.
References cl_free, cl_malloc(), CWB_SUBCORPMAGIC_NEW, CWB_SUBCORPMAGIC_ORIG, file_length_from_handle(), and registry.
Referenced by main().