CWB: utils/cwb-makeall.c File Reference
cwb-makeall.c File Reference
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include "../cl/endian.h"
#include "../cl/fileutils.h"
Functions
int component_ok (Attribute *attr, ComponentID cid)
Checks whether a component has already been created.
void makeall_make_component (Attribute *attr, ComponentID cid)
Creates a component for the specified attribute.
int validate_revcorp (Attribute *attr)
Validates the REVCORP component of the given attribute.
void makeall_do_attribute (Attribute *attr, ComponentID cid, int validate)
Create a given component (or all components) for an attribute.
void makeall_usage (void)
Prints a usage message and exits the program.
int main (int argc, char **argv)
Main function for cwb-makeall.
Variables
Corpus * corpus
The corpus we are working on.
char * progname = NULL
Name of this program.
Function Documentation
component_ok()
int component_ok (Attribute * attr, ComponentID cid)
Checks whether a component has already been created.
Parameters
attr The attribute of the component to check.
cid The component ID of the component to check.
Returns
TRUE iff the component has already been created.
References component_state(), ComponentDefined, ComponentLoaded, and ComponentUnloaded.
Referenced by makeall_do_attribute(), and makeall_make_component().
main()
int main (int argc, char ** argv)
Main function for cwb-makeall.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References _Attribute::any, ATT_POS, TCorpus::attributes, cl_new_attribute(), cl_new_corpus(), cl_set_debug_level(), cl_set_memory_limit(), cl_standard_registry(), cl_startup(), CompDirectory, CompLast, component_id(), corpus, corpus_id, drop_component(), makeall_do_attribute(), makeall_usage(), progname, TCorpus::registry_dir, registry_directory, and _Attribute::type.
makeall_do_attribute()
void makeall_do_attribute (Attribute * attr, ComponentID cid, int validate)
Create a given component (or all components) for an attribute.
Parameters
attr The attribute to work on.
cid If this is CompLast, all components will be created. Otherwise, it specifies the single component that will be created.
validate boolean - if true, validate_revcorp is called to check the resulting revcorp.
References _Attribute::any, cid_name(), cl_str_is, CompCompRF, CompCompRFX, CompCorpus, CompCorpusFreqs, CompHuffCodes, CompHuffSeq, CompHuffSync, CompLast, CompLexicon, CompLexiconIdx, CompLexiconSrt, component_ok(), CompRevCorpus, CompRevCorpusIdx, is_directory(), makeall_make_component(), and validate_revcorp().
Referenced by main().
makeall_make_component()
void makeall_make_component (Attribute * attr, ComponentID cid)
Creates a component for the specified attribute.
This function will create the component if it doesn't already exist; it aborts on error.
See also
create_component
Parameters
attr The attribute of the component to create.
cid The component ID of the component to create.
References cid_name(), component_ok(), component_state(), ComponentLoaded, ComponentUnloaded, and create_component().
Referenced by makeall_do_attribute().
makeall_usage()
void makeall_usage (void)
Prints a usage message and exits the program.
References CWB_VERSION, and progname.
Referenced by main().
validate_revcorp()
int validate_revcorp (Attribute * attr)
Validates the REVCORP component of the given attribute.
This function validates a REVCORP (i.e. an uncompressed index). It assumes that a lexicon, frequencies and (compressed or uncompressed) token stream are available for CL access for the given attribute.
Parameters
attr The attribute whose REVCORP should be checked.
Returns
True for all OK, false for a problem.
References cid_name(), cl_calloc(), cl_cpos2id(), cl_free, cl_id2freq(), cl_max_cpos(), cl_max_id(), CompRevCorpus, TComponent::data, TMblob::data, ensure_component(), and TComponent::size.
Referenced by makeall_do_attribute().
Variable Documentation
corpus
Corpus* corpus
The corpus we are working on.
Referenced by main().
progname
char* progname = NULL
Name of this program.
Name of the program (from the shell)
Referenced by main(), and makeall_usage().