CWB: utils/cwb-s-encode.c File Reference
cwb-s-encode.c File Reference
cwb-s-encode adds an s-attribute to an existing corpus.
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <assert.h>
#include <limits.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/endian.h"
#include "../cl/storage.h"
Data Structures
struct mini_s_builder
mini_s_builder object - distinct from, and simpler than the similar object in cwb-encode.
struct s_region
The "structure list" data type is used for 'adding' regions (-a).
Macros
#define UMASK 0644
#define RNG_RNG "%s" SUBDIR_SEP_STRING "%s.rng"
printf format string for path of file storing ranges of given structural attribute
#define RNG_AVX "%s" SUBDIR_SEP_STRING "%s.avx"
printf format string for path of attribute value index of a given structural attribute
#define RNG_AVS "%s" SUBDIR_SEP_STRING "%s.avs"
printf format string for path of attribute values of a given structural attribute
Typedefs
typedef struct s_region * s_region
The "structure list" data type is used for 'adding' regions (-a).
Enumerations
enum { set_none , set_any , set_regular , set_whitespace }
Functions
void SL_rewind (void)
Rewind the index-pointer to the start of the global structure list.
s_region SL_next (void)
Gets a pointer to the next available structure on the global structure list.
s_region SL_seek (int cpos)
Find region containing (or preceding) cpos; NULL = start of list; sets SL_Point to returned value.
s_region SL_insert_after_point (int start, int end, char *annot)
Insert region [start, end, annot] after SL_Point; no overlap/position checking.
void SL_delete (s_region item)
delete region from list; updates SL_Point if it happened to point at item
void SL_insert (int start, int end, char *annot)
Inserts an item into the global structure list.
int sencode_parse_line (char *line, int *start, int *end, char **annot)
Parses an input line into cwb-s-encode.
char * sencode_check_set (char *annot)
Changes an annotation string to standard set attribute syntax.
void sencode_usage (void)
print usage message and exit
void sencode_declare_new_satt (char *name, char *directory, int store_values)
Initialises the "new_satt" variable for the s-attribute to be encoded, and sets name/directory.
void sencode_open_files (void)
Open disk files for the s-attribute being encoded (must have been declared first).
void sencode_close_files (void)
Close the disk files for the s-attribute being encoded.
void sencode_parse_options (int argc, char **argv)
Parse options and set global variables.
void sencode_write_region (int start, int end, char *annot)
Write data about a region to disk files (as defined in global variable new_satt).
int main (int argc, char **argv)
Main function for cwb-s-encode.
Variables
int debug = 0
debug mode on/off
int silent = 0
avoid messages in -M / -a modes
int strip_blanks_in_values = 0
int set_syntax_strict = 0
check that set attributes are always given in the same syntax
int in_memory = 0
create list of regions in memory (allowing non-linear input), then write to disk
int add_to_existing = 0
add to existing attribute: implies in_memory; existing regions are automatically inserted at startup
FILE * text_fd = NULL
stream handle for file to read from.
unsigned long input_line = 0
input line number (used for error messages)
Corpus * corpus = NULL
corpus we're working on; at the moment, this is only required for add_to_existing
CorpusCharset encoding_charset
a charset object; will be the same as that of corpus if we are adding to an existing corpus, otherwise, should be declared.
const char * encoding_charset_name = "latin1"
character set label from the -c option.
int clean_strings = 0
clean up input strings by replacing invalid bytes with '?' (except for UTF8 encoding)
enum { ... } set_att = set_none
feature-set attributes: type of.
mini_s_builder new_satt
Global (and only) instance of the cwb-s-encode mini_s_builder object.
char * progname = NULL
Name of the program (from the shell)
s_region StructureList = NULL
(single) global list of s-att regions
s_region SL_Point = NULL
pointer into global list; NULL = start of list; linear search starts from SL_Point
cl_lexhash LH = NULL
Lexhash used when writing regions, to avoid multiple copies of annotations (-m mode)
Detailed Description
cwb-s-encode adds an s-attribute to an existing corpus.
Input: a list of regions (on stdin or in the file specified in the first argument to the program name) with lines in the following format:
start TAB end [ TAB annotation ]
start = corpus position of first token in region (integer as text) end = corpus position of last token in region (integer as text) annotation = annotation text (only if s-attribute was specified with -V)
Output: file att.rng (plus att.avs, att.avx for -V attributes) where att is the specified attribute name.
Macro Definition Documentation
RNG_AVS
#define RNG_AVS "%s" SUBDIR_SEP_STRING "%s.avs"
printf format string for path of attribute values of a given structural attribute
RNG_AVX
#define RNG_AVX "%s" SUBDIR_SEP_STRING "%s.avx"
printf format string for path of attribute value index of a given structural attribute
RNG_RNG
#define RNG_RNG "%s" SUBDIR_SEP_STRING "%s.rng"
printf format string for path of file storing ranges of given structural attribute
UMASK
#define UMASK 0644
Typedef Documentation
s_region
typedef struct s_region * s_region
The "structure list" data type is used for 'adding' regions (-a).
In this case, all existing regions are read into an ordered, bidirectional list; new regions are inserted into that list (overlaps are automatically resolved in favour of the 'earlier' region; if start point is identical, the longer region is retained). Only once the entire input has been read is the data actually encoded and stored on disk.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
set_none
set_any
set_regular
set_whitespace
Function Documentation
main()
int main (int argc, char ** argv)
Main function for cwb-s-encode.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References add_to_existing, s_region::annot, ATT_STRUC, buf, cl_free, CL_MAX_LINE_LENGTH, cl_max_struc(), cl_new_attribute(), cl_startup(), cl_string_chomp(), cl_struc2cpos(), cl_struc2str(), cl_struc_values(), corpus, debug, s_region::end, in_memory, input_line, mini_s_builder::last_cpos, mini_s_builder::name, new_satt, progname, sencode_check_set(), sencode_close_files(), sencode_parse_line(), sencode_parse_options(), sencode_write_region(), set_att, set_none, silent, SL_insert(), SL_next(), SL_rewind(), s_region::start, mini_s_builder::store_values, and text_fd.
sencode_check_set()
char* sencode_check_set (char * annot)
Changes an annotation string to standard set attribute syntax.
On first call, the function checks whether annotations are already given in standard '|'-delimited form; otherwise we assume we are using whitespace to split.
The return string may have been newly allocated (i.e. caller must use & free the returned value).
If there are syntax errors, returns NULL.
Parameters
annot The annotation string to check.
Returns
The standardised string, or NULL if there was an error in the call to cl_make_set().
References s_region::annot, cl_free, cl_make_set(), set_any, set_att, set_none, set_regular, set_syntax_strict, and set_whitespace.
Referenced by main().
sencode_close_files()
void sencode_close_files (void)
Close the disk files for the s-attribute being encoded.
References mini_s_builder::avs, mini_s_builder::avx, mini_s_builder::fd, new_satt, and mini_s_builder::ready.
Referenced by main().
sencode_declare_new_satt()
void sencode_declare_new_satt (char * name, char * directory, int store_values)
Initialises the "new_satt" variable for the s-attribute to be encoded, and sets name/directory.
References mini_s_builder::avs, mini_s_builder::avx, cl_strdup(), mini_s_builder::dir, directory, mini_s_builder::fd, mini_s_builder::last_cpos, mini_s_builder::name, new_satt, mini_s_builder::num, mini_s_builder::offset, mini_s_builder::ready, and mini_s_builder::store_values.
Referenced by sencode_parse_options().
sencode_open_files()
void sencode_open_files (void)
Open disk files for the s-attribute being encoded (must have been declared first).
References mini_s_builder::avs, mini_s_builder::avx, buf, CL_MAX_LINE_LENGTH, mini_s_builder::dir, mini_s_builder::fd, mini_s_builder::name, new_satt, mini_s_builder::ready, RNG_AVS, RNG_AVX, RNG_RNG, and mini_s_builder::store_values.
Referenced by sencode_write_region().
sencode_parse_line()
int sencode_parse_line (char * line, int * start, int * end, char ** annot)
Parses an input line into cwb-s-encode.
Usage:
ok = sencode_parse_line(char *line, int *start, int *end, char **annot);
Expects standard TAB-separated format; first two fields must be numbers, optional third field is returned in annot - if not present, annot is set to NULL.
Parameters
line The line to be parsed (without trailing line break).
start Out-parameter: Location to put the start cpos.
end Out-parameter: Location to put the end cos.
annot Out-parameter: Location to put the annotation string.
Returns
Boolean; true for all OK, false for error.
References s_region::annot, cl_free, cl_strdup(), cl_string_canonical(), CL_STRING_CANONICAL_STRDUP, cl_string_validate_encoding(), cl_string_zap_controls(), clean_strings, encoding_charset, encoding_charset_name, s_region::end, input_line, line, REQUIRE_NFC, s_region::start, and utf8.
Referenced by main().
sencode_parse_options()
void sencode_parse_options (int argc, char ** argv)
Parse options and set global variables.
References add_to_existing, cl_charset_from_name(), cl_charset_name_canonical(), cl_corpus_charset(), cl_error(), cl_new_corpus(), cl_open_stream(), CL_STREAM_MAGIC, CL_STREAM_READ, CL_STREAM_STDIO, corpus, debug, directory, encoding_charset, encoding_charset_name, in_memory, mini_s_builder::name, new_satt, registry, sencode_declare_new_satt(), sencode_usage(), set_any, set_att, set_syntax_strict, silent, strip_blanks_in_values, and text_fd.
Referenced by main().
sencode_usage()
void sencode_usage (void)
print usage message and exit
References CWB_VERSION, and progname.
Referenced by sencode_parse_options().
sencode_write_region()
void sencode_write_region (int start, int end, char * annot)
Write data about a region to disk files (as defined in global variable new_satt).
References s_region::annot, mini_s_builder::avs, mini_s_builder::avx, cl_lexhash_add(), cl_lexhash_find(), cl_new_lexhash(), _cl_lexhash_entry::data, s_region::end, mini_s_builder::fd, _cl_lexhash_entry::_cl_lexhash_entry_data::integer, mini_s_builder::last_cpos, LH, mini_s_builder::name, new_satt, mini_s_builder::num, NwriteInt(), mini_s_builder::offset, mini_s_builder::ready, sencode_open_files(), s_region::start, and mini_s_builder::store_values.
Referenced by main().
SL_delete()
void SL_delete (s_region item)
delete region from list; updates SL_Point if it happened to point at item
References cl_free, SL_Point, and StructureList.
Referenced by SL_insert().
SL_insert()
void SL_insert (int start, int end, char * annot)
Inserts an item into the global structure list.
It adds a new region to the list: its start point, its end point, its annotation.
Combines SL_seek(), SL_insert_at_point() and ambiguity resolution.
References s_region::annot, s_region::end, SL_delete(), SL_insert_after_point(), SL_seek(), and s_region::start.
Referenced by main().
SL_insert_after_point()
s_region SL_insert_after_point (int start, int end, char * annot)
Insert region [start, end, annot] after SL_Point; no overlap/position checking.
References s_region::annot, cl_malloc(), cl_strdup(), s_region::end, s_region::next, s_region::prev, SL_Point, s_region::start, and StructureList.
Referenced by SL_insert().
SL_next()
s_region SL_next (void)
Gets a pointer to the next available structure on the global structure list.
Returns NULL if we're at the end of the list.
References s_region::next, and SL_Point.
Referenced by main().
SL_rewind()
void SL_rewind (void)
Rewind the index-pointer to the start of the global structure list.
References SL_Point, and StructureList.
Referenced by main().
SL_seek()
s_region SL_seek (int cpos)
Find region containing (or preceding) cpos; NULL = start of list; sets SL_Point to returned value.
References s_region::end, s_region::next, s_region::prev, SL_Point, s_region::start, and StructureList.
Referenced by SL_insert().
Variable Documentation
add_to_existing
int add_to_existing = 0
add to existing attribute: implies in_memory; existing regions are automatically inserted at startup
Referenced by main(), and sencode_parse_options().
clean_strings
int clean_strings = 0
clean up input strings by replacing invalid bytes with '?' (except for UTF8 encoding)
Referenced by sencode_parse_line().
corpus
Corpus* corpus = NULL
corpus we're working on; at the moment, this is only required for add_to_existing
Referenced by main(), and sencode_parse_options().
debug
int debug = 0
debug mode on/off
Referenced by main(), and sencode_parse_options().
encoding_charset
CorpusCharset encoding_charset
a charset object; will be the same as that of corpus if we are adding to an existing corpus, otherwise, should be declared.
Referenced by sencode_parse_line(), and sencode_parse_options().
encoding_charset_name
const char* encoding_charset_name = "latin1"
character set label from the -c option.
Value = pre-4.0 default of latin1.
Referenced by sencode_parse_line(), and sencode_parse_options().
in_memory
int in_memory = 0
create list of regions in memory (allowing non-linear input), then write to disk
Referenced by main(), and sencode_parse_options().
input_line
unsigned long input_line = 0
input line number (used for error messages)
Referenced by main(), and sencode_parse_line().
LH
cl_lexhash LH = NULL
Lexhash used when writing regions, to avoid multiple copies of annotations (-m mode)
Referenced by sencode_write_region().
new_satt
mini_s_builder new_satt
Global (and only) instance of the cwb-s-encode mini_s_builder object.
Contains information on the new s-attribute being coded.
Referenced by main(), sencode_close_files(), sencode_declare_new_satt(), sencode_open_files(), sencode_parse_options(), and sencode_write_region().
progname
char* progname = NULL
Name of the program (from the shell)
Name of the program (from the shell)
Referenced by main(), and sencode_usage().
enum { ... } set_att
feature-set attributes: type of.
Initial value: not a feature set. Changes to set_any once we know we are dealing with a feature set. Changes to set_regular or set_whitespace once we know which format of f.s. it is.
Referenced by main(), sencode_check_set(), and sencode_parse_options().
set_syntax_strict
int set_syntax_strict = 0
check that set attributes are always given in the same syntax
Referenced by sencode_check_set(), and sencode_parse_options().
silent
int silent = 0
avoid messages in -M / -a modes
Disables some messages & warnings (used rather inconsistently).
Referenced by main(), and sencode_parse_options().
SL_Point
s_region SL_Point = NULL
pointer into global list; NULL = start of list; linear search starts from SL_Point
Referenced by SL_delete(), SL_insert_after_point(), SL_next(), SL_rewind(), and SL_seek().
strip_blanks_in_values
int strip_blanks_in_values = 0
Referenced by sencode_parse_options().
StructureList
s_region StructureList = NULL
(single) global list of s-att regions
Referenced by SL_delete(), SL_insert_after_point(), SL_rewind(), and SL_seek().
text_fd
FILE* text_fd = NULL
stream handle for file to read from.
Referenced by main(), and sencode_parse_options().