CWB: utils/cwb-compress-rdx.c File Reference
cwb-compress-rdx.c File Reference
#include <math.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include "../cl/storage.h"
#include "../cl/bitio.h"
#include "../cl/compression.h"
Functions
void compressrdx_usage (char *msg, int error_code)
Prints a usage message and exits the program.
void compressrdx_cleanup (int error_code)
Cleans up memory prior to an (error-prompted or normal) exit.
void compress_reversed_index (Attribute *attr, char *output_fn)
Compresses the reversed index of a p-attribute.
void decompress_check_reversed_index (Attribute *attr, char *output_fn)
Checks a compressed reversed index for errors by decompressing it.
int main (int argc, char **argv)
Main function for cwb-compress-rdx.
Variables
char * progname = NULL
Name of the program.
char * corpus_id = NULL
CWB id of the corpus we are working on.
Corpus * corpus
Record for the corpus we are working on.
int debug = 0
debug level
FILE * debug_output
where debug messages are to be sent to (stderr)
int codepos = 0
stores current position in a bit-write-file
Function Documentation
compress_reversed_index()
void compress_reversed_index (Attribute * attr, char * output_fn)
Compresses the reversed index of a p-attribute.
Parameters
attr The attribute to compress the index of.
output_fn Base name for the compressed RDX files to be written (if this is null, filenames will be taken from the attribute).
References _Attribute::any, BFclose(), BFflush(), BFopen(), BFposition(), CDA_OK, cl_delete_stream(), cl_errno, cl_error(), cl_id2freq(), cl_max_cpos(), CL_MAX_FILENAME_LENGTH, cl_max_id(), cl_new_stream(), cl_read_stream(), codepos, CompCompRF, CompCompRFX, component_full_name(), compressrdx_cleanup(), CompRevCorpus, CompRevCorpusIdx, compute_ba(), corpus_id, debug, debug_output, ensure_component(), NwriteInt(), and write_golomb_code().
Referenced by main().
compressrdx_cleanup()
void compressrdx_cleanup (int error_code)
Cleans up memory prior to an (error-prompted or normal) exit.
Parameters
error_code Value to be returned by the program when it exits.
References cl_delete_corpus(), corpus, and debug_output.
Referenced by compress_reversed_index(), compressrdx_usage(), decompress_check_reversed_index(), and main().
compressrdx_usage()
void compressrdx_usage (char * msg, int error_code)
Prints a usage message and exits the program.
Parameters
msg A message about the error.
error_code Value to be returned by the program when it exits.
References compressrdx_cleanup(), CWB_VERSION, and progname.
Referenced by main().
decompress_check_reversed_index()
void decompress_check_reversed_index (Attribute * attr, char * output_fn)
Checks a compressed reversed index for errors by decompressing it.
This function this assumes that compress_reversed_index() has been called beforehand and made sure that the uncompressed index is usable by CL access functions.
Parameters
attr The attribute to check the index of.
output_fn Base name for the compressed RDX files to be read (if this is null, filenames will be taken from the attribute).
References _Attribute::any, BFclose(), BFflush(), BFopen(), CDA_OK, cl_delete_stream(), cl_errno, cl_error(), cl_id2freq(), cl_max_cpos(), CL_MAX_FILENAME_LENGTH, cl_max_id(), cl_new_stream(), cl_read_stream(), CompCompRF, CompCompRFX, component_full_name(), compressrdx_cleanup(), CompRevCorpus, CompRevCorpusIdx, compute_ba(), corpus_id, debug, debug_output, PositionStream, and read_golomb_code_bf().
Referenced by main().
main()
int main (int argc, char ** argv)
Main function for cwb-compress-rdx.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References _Attribute::any, ATT_POS, TCorpus::attributes, cl_new_attribute_oldstyle, cl_new_corpus(), cl_standard_registry(), cl_startup(), compress_reversed_index(), compressrdx_cleanup(), compressrdx_usage(), corpus, corpus_id, CWB_DEFAULT_ATT_NAME, debug, debug_output, decompress_check_reversed_index(), i_want_to_believe, progname, and registry_directory.
Variable Documentation
codepos
int codepos = 0
stores current position in a bit-write-file
Referenced by compress_reversed_index().
corpus
Corpus* corpus
Record for the corpus we are working on.
Referenced by add_corpus_property(), add_grant_to_last_user(), calculate_initial_matchlist(), calculate_initial_matchlist_1(), check_access_conditions(), check_grant(), cl_corpus_charset(), cl_corpus_list_attributes(), cl_corpus_property(), cl_cpos2id(), cl_delete_attribute(), cl_delete_corpus(), cl_first_corpus_property(), cl_max_cpos(), cl_new_attribute(), cl_new_corpus(), combine_subcorpus_spec(), compose_kwic_line(), compressrdx_cleanup(), cqi_find_corpus(), describe_corpus(), describecorpus_show_attribute_names(), describecorpus_show_basic_info(), describecorpus_show_statistics(), do_cqi_cqp_list_subcorpora(), eval_constraint(), first_corpus_attribute(), GetVariableItems(), load_corpusnames(), main(), match_first_pattern(), RecomputeAL(), rs_cp_range(), setup_attribute(), split_attribute_spec(), split_subcorpus_spec(), SystemCorpusSize(), update_context_descriptor(), verify_context_descriptor(), VerifyList(), and VerifyVariable().
corpus_id
char* corpus_id = NULL
CWB id of the corpus we are working on.
Referenced by compress_reversed_index(), decompress_check_reversed_index(), and main().
debug
int debug = 0
debug level
Referenced by compress_reversed_index(), decompress_check_reversed_index(), and main().
debug_output
FILE* debug_output (void)
where debug messages are to be sent to (stderr)
Referenced by compress_reversed_index(), compressrdx_cleanup(), decompress_check_reversed_index(), and main().
progname
char* progname = NULL
Name of the program.
Name of the program (from the shell)
Referenced by compressrdx_usage(), and main().