CWB: utils/cwb-align-encode.c File Reference
cwb-align-encode.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/storage.h"
#include "../cl/attributes.h"
Functions
void alignencode_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
int alignencode_parse_args (int ac, char *av[], int min_args)
Parses the program's commandline arguments.
int main (int argc, char *argv[])
Main function for cwb-align-encode.
Variables
char * progname = ""
Name of the program (from the shell)
int compatibility = 0
create .alg file for backward compatibility ?
char * registry_dir = NULL
CL registry directory.
int reverse = 0
encode inverse alignment?
char * data_dir = NULL
where to store encoded alignment attribute
int data_dir_from_corpus = 0
determine data directory from registry entry?
int verbose = 0
print some information about what files are created
Function Documentation
alignencode_parse_args()
int alignencode_parse_args (int ac, char * av[], int min_args)
Parses the program's commandline arguments.
Usage:
optindex = alignencode_parse_args(argc, argv, required_arguments);
Parameters
ac The program's argc
av The program's argv
min_args Minimum number of arguments to be parsed.
Returns
The value of optind after parsing, ie the index of the first argument in argv[]
References alignencode_usage(), compatibility, data_dir, data_dir_from_corpus, progname, registry_dir, reverse, and verbose.
Referenced by main().
alignencode_usage()
void alignencode_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
References CWB_VERSION, and progname.
Referenced by alignencode_parse_args().
main()
int main (int argc, char * argv[])
Main function for cwb-align-encode.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References af, align_name, alignencode_parse_args(), ATT_ALIGN, ATT_POS, cl_close_stream(), cl_id_tolower(), cl_max_cpos(), CL_MAX_FILENAME_LENGTH, CL_MAX_LINE_LENGTH, cl_new_attribute(), cl_new_corpus(), cl_open_stream(), cl_startup(), cl_strdup(), CL_STREAM_MAGIC, CL_STREAM_READ, CompAlignData, compatibility, component_full_name(), CompXAlignData, corpus1, corpus1_name, corpus2, corpus2_name, data_dir, data_dir_from_corpus, line, NwriteInt(), progname, registry_dir, reverse, s1_name, s2_name, size1, size2, SUBDIR_SEP_STRING, verbose, w1, and w2.
Variable Documentation
compatibility
int compatibility = 0
create .alg file for backward compatibility ?
Referenced by alignencode_parse_args(), and main().
data_dir
char* data_dir = NULL
where to store encoded alignment attribute
Referenced by alignencode_parse_args(), and main().
data_dir_from_corpus
int data_dir_from_corpus = 0
determine data directory from registry entry?
Referenced by alignencode_parse_args(), and main().
progname
char* progname = ""
Name of the program (from the shell)
Referenced by alignencode_parse_args(), alignencode_usage(), and main().
registry_dir
char* registry_dir = NULL
CL registry directory.
Referenced by alignencode_parse_args(), cl_new_corpus(), find_corpus(), find_corpus_registry(), and main().
reverse
int reverse = 0
encode inverse alignment?
Referenced by alignencode_parse_args(), cl_string_qsort_compare(), and main().
verbose
int verbose = 0
print some information about what files are created
Referenced by alignencode_parse_args(), best_path(), and main().