CWB: utils/cwb-s-decode.c File Reference
cwb-s-decode.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
Functions
void sdecode_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
int main (int argc, char **argv)
Main function for cwb-s-decode.
Variables
char * progname
Name of the program (from the shell)
Function Documentation
main()
int main (int argc, char ** argv)
Main function for cwb-s-decode.
Prints information about each region in a given s-attribute in a specified corpus to STDOUT, optionally with their annotation values.
Parameters
argc Number of command-line arguments.
argv Command-line arguments.
References ATT_STRUC, cl_error(), cl_max_struc(), cl_new_attribute(), cl_new_corpus(), cl_standard_registry(), cl_startup(), cl_struc2cpos(), cl_struc2str(), cl_struc_values(), corpus, corpus_id, progname, registry_directory, and sdecode_usage().
sdecode_usage()
void sdecode_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
References CWB_VERSION, and progname.
Referenced by main().
Variable Documentation
progname
char* progname
Name of the program (from the shell)
Name of the program (from the shell)
Referenced by main(), and sdecode_usage().