CWB: utils/cwb-check-input.c File Reference
cwb-check-input.c File Reference
This was a temporary, experuimental "fiddle" with unicode programming.
#include <glib.h>
#include "../cl/globals.h"
#include "../cl/list.h"
Macros
#define MAX_INPUT_LINE_LENGTH 65536
Input buffer size: copied from cwb-encode.
Functions
void cwbci_file_write_abort (void)
convenience function with which to abort the program if file-write fails.
int cwbci_encoding_ok (char *str)
checks whether the encoding of a given string is OK.
int cwbci_is_wordchar (char c)
int cwbci_begins_with_blank (char *str)
Function for inner-loop in cwbci_check_lin().
void cwbci_report_error_fixable (char *msg)
void cwbci_report_error_unfixable (char *msg)
void cwbci_check_line (char *line)
void cwbci_usage (void)
void cwbci_parse_options (int argc, char **argv)
Parses commandline options for cwb-check-input and sets global variables accordingly.
int main (int argc, char **argv)
Main function for cwb-check-input.
Variables
int line_no = 0
line number of the line in the input file currently being checked; first == 1
int established_number_of_p_atts = 0
first p-att line established number of tags; anything that deviates then counts as an error
int silent = 0
hide messages
int verbose = 0
show messages about fixable errors in repair mode
int print_fixable_errors = 0
deduced from mode, silent & verbose
int print_unfixable_errors = 0
deduced from mode, silent & verbose
int errors_detected = 0
number of errors found so far
int xml_aware = 0
ignore <? and <! lines
int skip_empty_lines = 0
check for empty lines
int strip_blanks = 0
check for leading and trailing blanks in input and token annotations?
int check_nesting = 0
check perfect nesting of XML?
FILE * input_fd = NULL
file handle for the input file
char * input_file = NULL
filename of the input file
FILE * output_fd = NULL
file handle for the output file; also used for boolean tests on whether we are repairing or not
char * output_file = NULL
filename of the output file
char * charset_label = "ascii"
label of character set used for checking encoding
CorpusCharset charset
character set used for checking encoding
cl_string_list hierarchy = NULL
string list for keeping track of the XML hierarchy
char * progname = NULL
name of the currently running program
Detailed Description
This was a temporary, experuimental "fiddle" with unicode programming.
Macro Definition Documentation
MAX_INPUT_LINE_LENGTH
#define MAX_INPUT_LINE_LENGTH 65536
Input buffer size: copied from cwb-encode.
Function Documentation
cwbci_begins_with_blank()
int cwbci_begins_with_blank (char * str)
Function for inner-loop in cwbci_check_lin().
IMPORTANT NOTE: if to be used elsewhere will need adapting, because it assumes all utf8 is well-validated and that blanks will be deleted from the line, starting with the first character.
References charset, and utf8.
Referenced by cwbci_check_line().
cwbci_check_line()
void cwbci_check_line (char * line)
References check_nesting, cl_free, cl_strdup(), cl_string_list_append(), cl_string_list_get(), cl_string_list_size(), cwbci_begins_with_blank(), cwbci_encoding_ok(), cwbci_file_write_abort(), cwbci_is_wordchar(), cwbci_report_error_fixable(), cwbci_report_error_unfixable(), established_number_of_p_atts, hierarchy, line, MAX_INPUT_LINE_LENGTH, output_fd, _cl_string_list::size, skip_empty_lines, strip_blanks, and xml_aware.
Referenced by main().
cwbci_encoding_ok()
int cwbci_encoding_ok (char * str)
checks whether the encoding of a given string is OK.
(Maybe move to the CL later?? in which case the charset should be a parameter, as a global variable cannot be assumed in all programs.) Returns boolean.
References ascii, charset, latin1, and utf8.
Referenced by cwbci_check_line().
cwbci_file_write_abort()
void cwbci_file_write_abort (void)
convenience function with which to abort the program if file-write fails.
References input_fd, output_fd, and output_file.
Referenced by cwbci_check_line().
cwbci_is_wordchar()
int cwbci_is_wordchar (char c)
Referenced by cwbci_check_line().
cwbci_parse_options()
void cwbci_parse_options (int argc, char ** argv)
Parses commandline options for cwb-check-input and sets global variables accordingly.
References charset, charset_label, check_nesting, cl_charset_from_name(), cl_charset_name_canonical(), cl_new_string_list(), cl_strdup(), cwbci_usage(), hierarchy, input_file, output_file, print_fixable_errors, print_unfixable_errors, silent, skip_empty_lines, strip_blanks, verbose, and xml_aware.
Referenced by main().
cwbci_report_error_fixable()
void cwbci_report_error_fixable (char * msg)
References errors_detected, line_no, and print_fixable_errors.
Referenced by cwbci_check_line().
cwbci_report_error_unfixable()
void cwbci_report_error_unfixable (char * msg)
References errors_detected, line_no, and print_unfixable_errors.
Referenced by cwbci_check_line().
cwbci_usage()
void cwbci_usage (void)
References progname.
Referenced by cwbci_parse_options().
main()
int main (int argc, char ** argv)
Main function for cwb-check-input.
References cl_delete_string_list(), cl_free, cl_free_string_list(), cl_startup(), cwbci_check_line(), cwbci_parse_options(), errors_detected, hierarchy, input_fd, input_file, line, line_no, MAX_INPUT_LINE_LENGTH, output_fd, output_file, and progname.
Variable Documentation
charset
CorpusCharset charset
character set used for checking encoding
Referenced by cl_charset_strlen(), cl_iso_char_is_alphanumeric(), cl_new_regex(), cl_string_canonical(), cl_string_maptable(), cl_string_qsort_compare(), cl_string_reverse(), cl_string_validate_encoding(), create_feature_maps(), cwbci_begins_with_blank(), cwbci_encoding_ok(), cwbci_parse_options(), decode_print_xml_declaration(), open_pager(), and open_rd_output_stream().
charset_label
char* charset_label = "ascii"
label of character set used for checking encoding
Referenced by cwbci_parse_options().
check_nesting
int check_nesting = 0
check perfect nesting of XML?
Referenced by cwbci_check_line(), and cwbci_parse_options().
errors_detected
int errors_detected = 0
number of errors found so far
Referenced by cwbci_report_error_fixable(), cwbci_report_error_unfixable(), and main().
established_number_of_p_atts
int established_number_of_p_atts = 0
first p-att line established number of tags; anything that deviates then counts as an error
Referenced by cwbci_check_line().
hierarchy
cl_string_list hierarchy = NULL
string list for keeping track of the XML hierarchy
Referenced by cwbci_check_line(), cwbci_parse_options(), and main().
input_fd
FILE* input_fd = NULL
file handle for the input file
Referenced by cwbci_file_write_abort(), lexdecode_show(), and main().
input_file
char* input_file = NULL
filename of the input file
Referenced by cwbci_parse_options(), and main().
line_no
int line_no = 0
line number of the line in the input file currently being checked; first == 1
Referenced by cwbci_report_error_fixable(), cwbci_report_error_unfixable(), and main().
output_fd
FILE* output_fd = NULL
file handle for the output file; also used for boolean tests on whether we are repairing or not
Referenced by cwbci_check_line(), cwbci_file_write_abort(), and main().
output_file
char* output_file = NULL
filename of the output file
Referenced by cwbci_file_write_abort(), cwbci_parse_options(), and main().
print_fixable_errors
int print_fixable_errors = 0
deduced from mode, silent & verbose
Referenced by cwbci_parse_options(), and cwbci_report_error_fixable().
print_unfixable_errors
int print_unfixable_errors = 0
deduced from mode, silent & verbose
Referenced by cwbci_parse_options(), and cwbci_report_error_unfixable().
progname
char* progname = NULL
name of the currently running program
Name of the program (from the shell)
Referenced by cwbci_usage(), and main().
silent
int silent = 0
hide messages
Disables some messages & warnings (used rather inconsistently).
Referenced by cwbci_parse_options().
skip_empty_lines
int skip_empty_lines = 0
check for empty lines
Referenced by cwbci_check_line(), and cwbci_parse_options().
strip_blanks
int strip_blanks = 0
check for leading and trailing blanks in input and token annotations?
Referenced by cwbci_check_line(), and cwbci_parse_options().
verbose
int verbose = 0
show messages about fixable errors in repair mode
Referenced by cwbci_parse_options().
xml_aware
int xml_aware = 0
ignore <? and <! lines
Referenced by cwbci_check_line(), and cwbci_parse_options().