CWB: cqp/eval.h File Reference
eval.h File Reference
#include "regex2dfa.h"
#include "corpmanag.h"
#include "symtab.h"
#include "options.h"
Data Structures
union c_tree
Union of structures underlying the Constraint / Constrainttree objects.
struct _ActualParamList
The ActualParamList object: used to build a linked list of parameters, each one of which is a Constrainttree.
union e_tree
Underlying union for the Evaltree object.
union _avs
AVStructure: underlying data union for an AVS object representing an element of a finite-state query.
struct ctxtsp
The (ambiguously named) Context object.
struct MatchSelector
The MatchSelector structure defines which part of a (standard) query match is returned.
struct evalenv
The EvalEnvironment object: variables for the evaluation of a standard query.
Macros
#define repeat_inf -1
constant which indicates 'infinite repetition' (actually, repetition up to hard_boundary)
#define repeat_none -2
constant which indicates 'no repetition'
#define MAXPATTERNS 5000
Number of AVStructures each Patternlist can store.
#define MAXENVIRONMENT 10
maximum number of EvalEnvironments in the global array
Typedefs
typedef union c_tree Constraint
Union of structures underlying the Constraint / Constrainttree objects.
typedef Constraint * Constrainttree
The Constrainttree object.
typedef struct _ActualParamList ActualParamList
The ActualParamList object: used to build a linked list of parameters, each one of which is a Constrainttree.
typedef union e_tree * Evaltree
Evaltree object: structure for a compiled CQP query.
typedef enum _avstype AVSType
The AVS type: tells us what kind of query element an AVS holds.
typedef enum target_nature target_nature
typedef enum avs_region_op avs_region_op
typedef union _avs AVStructure
AVStructure: underlying data union for an AVS object representing an element of a finite-state query.
typedef AVStructure * AVS
AVS object: defined as a pointer type for AVStructure (it's not clear what "AV" stands for)
typedef AVStructure Patternlist[MAXPATTERNS]
A Patternlist is an array of AVS objects.
typedef enum ctxtdir ctxtdir
the direction of a Context (for expand ...)
typedef enum spacet spacet
used to record whether the "space type" of a Context is "word or structure"
typedef struct ctxtsp Context
The (ambiguously named) Context object.
typedef struct MatchSelector MatchSelector
The MatchSelector structure defines which part of a (standard) query match is returned.
typedef struct evalenv EvalEnvironment
The EvalEnvironment object: variables for the evaluation of a standard query.
typedef EvalEnvironment * EEP
EEPs are EvalEnvironment pointers.
Enumerations
enum b_ops {
b_and , b_or , b_implies , b_not ,
cmp_gt , cmp_lt , cmp_get , cmp_let ,
cmp_eq , cmp_neq , cmp_ex
}
Labels a boolean operation.
enum wf_type { NORMAL , REGEXP , CID }
Labels the type of a "wordform" comparison: normal, regular expression, or cpos id ref.
enum bnodetype {
bnode , cnode , func , sbound ,
pa_ref , sa_ref , string_leaf , int_leaf ,
float_leaf , id_list , var_ref
}
Labels the type of a boolean node.
enum tnodetype { node , leaf , meet_union , tabular }
Enumeration specifying different types of eval-tree node.
enum re_ops { re_od_concat , re_oi_concat , re_disj , re_repeat }
Enumeration of regular expression operations (for token-level regex)
enum cooc_op { cooc_meet , cooc_union }
Symbols for the two operations of meet-union queries, that is meet and union!
enum _avstype {
Pattern , Tag , MatchAll , Anchor ,
Region
}
The AVS type: tells us what kind of query element an AVS holds.
enum target_nature { IsNotTarget = 0 , IsTarget = 1 , IsKeyword = 2 }
enum avs_region_op { AVSRegionEnter = 1 , AVSRegionWait = 2 , AVSRegionEmit = 3 }
enum ctxtdir { ctxtdir_leftright , ctxtdir_left , ctxtdir_right }
the direction of a Context (for expand ...)
enum spacet { word , structure }
used to record whether the "space type" of a Context is "word or structure"
Functions
Boolean eval_bool (Constrainttree ctptr, RefTab rt, int corppos)
Evaluate a boolean constraint tree/node using recursion.
void cqp_run_query (int cut, int keep_old_ranges)
Run a standard CQP query.
void cqp_run_mu_query (int keep_old_ranges, int cut_value)
Run a CQP Meet-Union query.
void cqp_run_tab_query ()
Run a CQP Tabular query.
int next_environment (void)
Sets up a new environment in the global array, which then becomes the.
int free_environment (int thisenv)
Frees an evaluation environment.
void show_environment (int thisenv)
Prints the contents of an EvalEnvironment object to STDOUT.
void free_all_environments (void)
Frees all eval environments in the global array, and sets the ee_ix index to -1.
Variables
EvalEnvironment Environment [MAXENVIRONMENT]
A global array of EvalEnvironment structures.
int ee_ix
Global eval environment index; contains the index of the highest currently-occupied slot within Environment.
EEP CurEnv
Global pointer, address of the "highest" cell in Environment.
EEP evalenv
Global pointer, address of the cell in Environment that is being used for evaluation.
Macro Definition Documentation
MAXENVIRONMENT
#define MAXENVIRONMENT 10
maximum number of EvalEnvironments in the global array
MAXPATTERNS
#define MAXPATTERNS 5000
Number of AVStructures each Patternlist can store.
repeat_inf
#define repeat_inf -1
constant which indicates 'infinite repetition' (actually, repetition up to hard_boundary)
See also
hard_boundary
repeat_none
#define repeat_none -2
constant which indicates 'no repetition'
Typedef Documentation
ActualParamList
typedef struct _ActualParamList ActualParamList
The ActualParamList object: used to build a linked list of parameters, each one of which is a Constrainttree.
AVS
typedef AVStructure* AVS
AVS object: defined as a pointer type for AVStructure (it's not clear what "AV" stands for)
See also
AVStructure
avs_region_op
typedef enum avs_region_op avs_region_op
AVStructure
typedef union _avs AVStructure
AVStructure: underlying data union for an AVS object representing an element of a finite-state query.
Internal format: a union of structures (with the type member always accessible).
The Patternlist (i.e. the "symbol" vocabulary over which the regular expression of a finite-state query is formulated) is an array of AVS objects.
AVSType
typedef enum _avstype AVSType
The AVS type: tells us what kind of query element an AVS holds.
Constraint
typedef union c_tree Constraint
Union of structures underlying the Constraint / Constrainttree objects.
Each Constraint is a boolean node in the Constrainttree, i.e. a single element of a compiled CQP query.
Constrainttree
typedef Constraint* Constrainttree
The Constrainttree object.
Context
typedef struct ctxtsp Context
The (ambiguously named) Context object.
This stores information about context space.
"Context" here means the context for evaluation of a query result within a corpus. (???)
CUT TO THE CHASE: it's used for the "within..." clause, "expand", and for MUs.
ctxtdir
typedef enum ctxtdir ctxtdir
the direction of a Context (for expand ...)
EEP
typedef EvalEnvironment* EEP
EEPs are EvalEnvironment pointers.
EvalEnvironment
typedef struct evalenv EvalEnvironment
The EvalEnvironment object: variables for the evaluation of a standard query.
This includes the query itself, as an evaltree and compiled into a DFA; the corpus being queried; the match strategy; and other information.
Evaltree
typedef union e_tree* Evaltree
Evaltree object: structure for a compiled CQP query.
MatchSelector
typedef struct MatchSelector MatchSelector
The MatchSelector structure defines which part of a (standard) query match is returned.
The structure consists of labels defining the start and end of the part to be extracted (or NULL for match/matchend) and optional offsets to be applied.
It is used by the new "show a .. b" syntax introduced into standard queries by CQP v3.4.32, and does not apply to MU or TAB queries.
Patternlist
typedef AVStructure Patternlist[MAXPATTERNS]
A Patternlist is an array of AVS objects.
spacet
typedef enum spacet spacet
used to record whether the "space type" of a Context is "word or structure"
target_nature
typedef enum target_nature target_nature
Enumeration Type Documentation
_avstype
enum _avstype
The AVS type: tells us what kind of query element an AVS holds.
Enumerator
Pattern
a token expression, [...conditions...] in CQP syntax, represented as a constraint tree (tree of Boolean nodes)
Tag
an XML tag matching the start/end of an s-attribute region, possibly with regexp filter on the annotated value
MatchAll
a matchall item, i.e.
a token expression without any constraints, matching an arbitary token; [] or [::] in CQP syntax.
Anchor
an XML tag matching an anchor point in a subquery, e.g.
<match> or </target> in CQP syntax
Region
a region element, <<name>> in CQP syntax, matching an entire region of an s-attribute or named query result
avs_region_op
enum avs_region_op
Enumerator
AVSRegionEnter
AVSRegionWait
AVSRegionEmit
b_ops
enum b_ops
Labels a boolean operation.
Enumerator
b_and
boolean and operator
b_or
boolean or operator
b_implies
boolean implication (->) operator
b_not
boolean negation
cmp_gt
compare: greater than
cmp_lt
compare: less than
cmp_get
compare: greater or equal than
cmp_let
compare: less or equal than
cmp_eq
compare: equal
cmp_neq
compare: not equal
cmp_ex
is value present? bool exprs
bnodetype
enum bnodetype
Labels the type of a boolean node.
Enumerator
bnode
boolean evaluation node
cnode
constant node
func
function call
sbound
structure boundary (open or close)
pa_ref
reference to positional attribute
sa_ref
reference to structural attribute
string_leaf
string constant
int_leaf
integer constant
float_leaf
float constant
id_list
list of IDs
var_ref
variable reference
cooc_op
enum cooc_op
Symbols for the two operations of meet-union queries, that is meet and union!
Enumerator
cooc_meet
cooc_union
MU operation: meet.
MU operation: union
ctxtdir
enum ctxtdir
the direction of a Context (for expand ...)
Enumerator
ctxtdir_leftright
ctxtdir_left
ctxtdir_right
re_ops
enum re_ops
Enumeration of regular expression operations (for token-level regex)
Enumerator
re_od_concat
regex operation: order dependent concatenation
re_oi_concat
regex operation: order independent concatenation (unused)
re_disj
regex operation: disjunction
re_repeat
regex operation: repetition, i.e.
({n} and {n,k})
spacet
enum spacet
used to record whether the "space type" of a Context is "word or structure"
Enumerator
word
structure
target_nature
enum target_nature
Enumerator
IsNotTarget
IsTarget
IsKeyword
tnodetype
enum tnodetype
Enumeration specifying different types of eval-tree node.
Enumerator
node
This is a branching node in a "normal" (regex) query tree.
leaf
This is a terminal node in a "normal" (regex) query tree.
meet_union
This is a tree for a MU (meet-union) query.
tabular
This is a tree for a TAB (tabular) query.
wf_type
enum wf_type
Labels the type of a "wordform" comparison: normal, regular expression, or cpos id ref.
Enumerator
NORMAL
type of comparison = normal.
REGEXP
type of comparison = regex.
CID
type of comparison = compare as integer corpus ID refs.
Function Documentation
cqp_run_mu_query()
void cqp_run_mu_query (int keep_old_ranges, int cut_value)
Run a CQP Meet-Union query.
Parameters
keep_old_ranges Boolean
cut_value
References apply_setop_to_matchlist(), cl_malloc(), cqpmessage(), _Matchlist::end, Environment, Error, eval_mu_tree(), evalenv::evaltree, EvaluationIsRunning, free_matchlist(), init_matchlist(), mark_offrange_cells(), evalenv::query_corpus, Reduce, set_corpus_matchlists(), _Matchlist::start, and _Matchlist::tabsize.
Referenced by do_MUQuery().
cqp_run_query()
void cqp_run_query (int cut, int keep_old_ranges)
Run a standard CQP query.
This function wraps round run_standard_query_dfa (the only other thing it does is enforce the hard_cut limit).
See also
hard_cut
run_standard_query_dfa
Parameters
cut Integer value for "cut" command, clamped to hard_cut if one is set.
keep_old_ranges Boolean, passed to equivalent parameter to run_standard_query_dfa()
References ee_ix, hard_cut, and run_standard_query_dfa().
Referenced by do_StandardQuery().
cqp_run_tab_query()
void cqp_run_tab_query ()
Run a CQP Tabular query.
References apply_setop_to_matchlist(), calculate_initial_matchlist(), calculate_rightboundary(), cl_calloc(), cl_cpos_offset(), cl_free, cl_malloc(), cl_realloc(), cqpmessage(), _Matchlist::end, Environment, Error, evalenv::evaltree, EvaluationIsRunning, free_matchlist(), hard_boundary, init_matchlist(), mark_offrange_cells(), e_tree::max_dist, e_tree::min_dist, e_tree::next, e_tree::patindex, Pattern, evalenv::patternlist, evalenv::query_corpus, Reduce, repeat_inf, evalenv::search_context, set_corpus_matchlists(), _Matchlist::start, e_tree::tab_el, _Matchlist::tabsize, tabular, and e_tree::type.
Referenced by do_TABQuery().
eval_bool()
Boolean eval_bool (Constrainttree ctptr, RefTab rt, int curr_cpos)
Evaluate a boolean constraint tree/node using recursion.
Parameters
ctptr The constraint tree pointer.
rt The reference table object.
curr_cpos The current corpus position.
References ATTAT_FLOAT, ATTAT_INT, ATTAT_NONE, ATTAT_PAREF, ATTAT_POS, ATTAT_STRING, ATTAT_VAR, c_tree::attr, b_and, b_implies, b_not, b_or, bnode, CDA_OK, _DCR::charres, cl_all_ok, cl_cpos2id(), cl_cpos2struc2cpos(), cl_errno, cl_id2str(), cl_regex_match(), cl_str_is, cl_streq, cmp_eq, cmp_ex, cmp_get, cmp_gt, cmp_let, cmp_lt, cmp_neq, cnode, c_tree::constnode, cqpmessage(), c_tree::delete, Error, eval_debug, EvaluationIsRunning, False, float_leaf, _DCR::floatres, func, get_label_referenced_position(), get_leaf_value(), id_list, c_tree::idlist, int_leaf, intcompare(), _DCR::intres, c_tree::is_closing, c_tree::items, c_tree::label, c_tree::leaf, c_tree::left, _label_entry::name, c_tree::negated, c_tree::node, NORMAL, c_tree::nr_items, c_tree::op_id, pa_ref, _DCR::parefres, c_tree::pat_type, _label_entry::ref, REGEXP, c_tree::right, c_tree::rx, sa_ref, sbound, c_tree::sbound, set_reftab(), string_leaf, c_tree::strucattr, True, _DCR::type, c_tree::type, c_tree::val, and _DCR::value.
Referenced by calculate_initial_matchlist_1(), eval_constraint(), evaluate_subset(), evaluate_target(), and simulate().
free_all_environments()
void free_all_environments (void)
Frees all eval environments in the global array, and sets the ee_ix index to -1.
References ee_ix, and free_environment().
Referenced by in_UnnamedCorpusCommand(), and prepare_input().
free_environment()
int free_environment (int thisenv)
Frees an evaluation environment.
The environment must be one currently occupied within the global array.
See also
Environment
eep
Parameters
thisenv The eval environment to free (index in global array).
Returns
Boolean: true if the deletion went OK; false if the environment to be freed was not occupied (will print an error message).
References Anchor, ctxtsp::attrib, AVSRegionEnter, MatchSelector::begin, MatchSelector::begin_offset, cl_delete_regex(), cl_free, ctxtdir_leftright, delete_symbol_table(), ctxtsp::direction, ee_ix, MatchSelector::end, MatchSelector::end_offset, Environment, False, free_booltree(), free_dfa(), free_evaltree(), evalenv::gconstraint, evalenv::has_target_indicator, IsNotTarget, evalenv::labels, evalenv::match_selector, MatchAll, evalenv::MaxPatIndex, NoField, Pattern, evalenv::patternlist, evalenv::query_corpus, Region, evalenv::search_context, ctxtsp::size, ctxtsp::space_type, StateQueue_delete(), Tag, and word.
Referenced by free_all_environments().
next_environment()
int next_environment (void)
Sets up a new environment in the global array, which then becomes the.
(better name would be "add_environment" or "push_new_environment")
The next slot upwards is used (and ee_ix is incremented).
See also
ee_ix
Environment
Returns
True for all OK, false for an error (overflow of MAXENVIRONMENT).
References ctxtsp::attrib, ctxtdir_leftright, CurEnv, ctxtsp::direction, ee_ix, Environment, evalenv::evaltree, evalenv::gconstraint, evalenv::has_keyword_indicator, evalenv::has_target_indicator, init_dfa(), evalenv::keyword_label, evalenv::labels, evalenv::match_label, evalenv::matchend_label, evalenv::matching_strategy, matching_strategy, MAXENVIRONMENT, evalenv::MaxPatIndex, evalenv::negated, new_symbol_table(), evalenv::query_corpus, evalenv::search_context, ctxtsp::size, ctxtsp::space_type, evalenv::target_label, and word.
Referenced by ActivateCorpus(), after_CorpusSetExpr(), prepare_AlignmentConstraints(), and prepare_Query().
show_environment()
void show_environment (int thisenv)
Prints the contents of an EvalEnvironment object to STDOUT.
Which bits of information are printed depends on which of a group of debugging-variables are set to true.
The EvalEnvironment to print is specified as an index into the global array (Environment).
See also
Environment
Parameters
thisenv Index into Environment indicating which EvalEnvironment should be displayed.
References MatchSelector::begin, MatchSelector::begin_offset, ee_ix, MatchSelector::end, MatchSelector::end_offset, Environment, evalenv::match_selector, _label_entry::name, print_booltree(), print_evaltree(), show_compdfa, show_complete_dfa(), show_evaltree, show_gconstraints, show_patlist, and show_patternlist().
Referenced by debug_output().
Variable Documentation
CurEnv
EEP CurEnv extern
Global pointer, address of the "highest" cell in Environment.
Used largely in parse_actions.
See also
Environment
Referenced by ActivateCorpus(), after_CorpusSetExpr(), do_AnchorPoint(), do_IDReference(), do_LabelReference(), do_MatchSelector(), do_MUQuery(), do_NamedWfPattern(), do_RegionElement(), do_SearchPattern(), do_TABQuery(), do_WordformPattern(), do_XMLTag(), eval_mu_tree(), next_environment(), prepare_AlignmentConstraints(), and prepare_Query().
ee_ix
int ee_ix extern
Global eval environment index; contains the index of the highest currently-occupied slot within Environment.
See also
Environment
Referenced by check_alignment_constraints(), cqp_run_query(), debug_output(), do_SearchPattern(), free_all_environments(), free_environment(), initialize_cqp(), next_environment(), prepare_Query(), regex2dfa(), run_standard_query_dfa(), and show_environment().
Environment
EvalEnvironment Environment[MAXENVIRONMENT] extern
A global array of EvalEnvironment structures.
Each represents the environment for a different aligned corpus.
Referenced by check_alignment_constraints(), cqp_run_mu_query(), cqp_run_tab_query(), do_Description(), do_MUQuery(), do_StandardQuery(), do_TABQuery(), free_environment(), next_environment(), prepare_AlignmentConstraints(), prepare_Query(), print_evaltree(), print_pattern(), regex2dfa(), run_standard_query_dfa(), show_environment(), and show_patternlist().
evalenv
EEP evalenv extern
Global pointer, address of the cell in Environment that is being used for evaluation.
Used largely in files other than parse_actions.
See also
Environment.
Referenced by check_alignment_constraints().