CWB: cqp/eval.c File Reference
eval.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <limits.h>
#include <math.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cl/ui-helpers.h"
#include "cqp.h"
#include "ranges.h"
#include "options.h"
#include "tree.h"
#include "symtab.h"
#include "corpmanag.h"
#include "regex2dfa.h"
#include "eval.h"
#include "builtins.h"
#include "output.h"
#include "matchlist.h"
Macros
#define COMPILE_QUERY_OPTIMIZATION 0
#define no_match -1
Functions
static const char * get_b_operator_name (enum b_ops op)
To aid in building error messages: get const string with a printable name for an operation.
static void set_corpus_matchlists (CorpusList *cp, Matchlist *matchlist, int nr_lists, bool keep_old_ranges)
Set the appropriate values to the corpus id (given by its pointer to the symbol table).
static int get_corpus_positions (Attribute *attribute, char *wordform, Matchlist *matchlist)
Gets a list of corpus positions where the given p-attribute has the specified form (looked up directly in the attribute's lexicon).
static int get_matched_corpus_positions (Attribute *attribute, char *regstr, int regex_flags, Matchlist *matchlist, int *restrictor_list, int restrictor_size)
Get corpus positions matching a regular expression on a given p-attribute.
static int _find_range (Range *vec, int size, int start)
static void _add_to_queue (AVS avs, int start, int end, RefTab labels)
static Boolean eval_constraint (AVS avs, int corppos, RefTab labelrefs, RefTab target_labelrefs, int *out_cpos)
static int get_label_referenced_position (LabelEntry label, RefTab rt, int corppos)
static Boolean get_leaf_value (Constrainttree ctptr, RefTab rt, int corppos, DynCallResult *dcr, int deliver_strings)
static int intcompare (const void *i, const void *j)
Comparison function used when eval_bool() calls qsort().
Boolean eval_bool (Constrainttree ctptr, RefTab rt, int curr_cpos)
Evaluate a boolean constraint tree/node using recursion.
static int mark_offrange_cells (Matchlist *matchlist, CorpusList *subcorpus)
Alters a matchlist so that the start/end values of any match whose start point within the ranges of the given subcorpus are changed to the dummy -1 value.
static Boolean calculate_initial_matchlist_1 (Constrainttree ctptr, Matchlist *matchlist, CorpusList *corpus)
Gets the inital list of matches for a query.
static Boolean calculate_initial_matchlist (Constrainttree ctptr, Matchlist *matchlist, CorpusList *corpus)
Wrapper around calculate_initial_matchlist_1, qv.
static Boolean match_first_pattern (AVS pattern, Matchlist *matchlist, CorpusList *corpus)
try to match the given word form pattern and return success.
static int simulate (Matchlist *matchlist, int *cut, int *state_vector, int *target_vector, RefTab *reftab_vector, RefTab *reftab_target_vector, int start_transition)
Simulate the DFA in the global evalenv.
static int check_alignment_constraints (Matchlist *ml)
static void run_standard_query_dfa (int envidx, int cut, int keep_old_ranges)
Run the DFA that performs a standard CQP query (i.e.
static int meet_mu (Matchlist *list1, Matchlist *list2, int lw, int rw, Attribute *struc, int negated)
Does a "meet" operation within MU queries.
static int eval_mu_tree (Evaltree et, Matchlist *ml)
return is boolean (all OK? true => yes, false => no)
void cqp_run_query (int cut, int keep_old_ranges)
Run a standard CQP query.
void cqp_run_mu_query (int keep_old_ranges, int cut_value)
Run a CQP Meet-Union query.
void cqp_run_tab_query ()
Run a CQP Tabular query.
int next_environment (void)
Sets up a new environment in the global array, which then becomes the.
int free_environment (int thisenv)
Frees an evaluation environment.
void show_environment (int thisenv)
Prints the contents of an EvalEnvironment object to STDOUT.
void free_all_environments (void)
Frees all eval environments in the global array, and sets the ee_ix index to -1.
Variables
EvalEnvironment Environment [MAXENVIRONMENT]
A global array of EvalEnvironment structures.
int ee_ix
Global eval environment index; contains the index of the highest currently-occupied slot within Environment.
EEP CurEnv
Global pointer, address of the "highest" cell in Environment.
EEP evalenv
Global pointer, address of the cell in Environment that is being used for evaluation.
Macro Definition Documentation
COMPILE_QUERY_OPTIMIZATION
#define COMPILE_QUERY_OPTIMIZATION 0
no_match
#define no_match -1
Function Documentation
_add_to_queue()
static void _add_to_queue (AVS avs, int start, int end, RefTab labels) static
References _avs::end_label, _avs::end_target, IsKeyword, IsTarget, evalenv::keyword_label, evalenv::labels, _avs::name, print_label_values(), _avs::queue, _label_entry::ref, Region, _avs::region, set_reftab(), simulate_debug, _avs::start_label, _avs::start_target, StateQueue_length(), StateQueue_push(), symtab_debug, evalenv::target_label, and _avs::type.
Referenced by eval_constraint().
_find_range()
static int _find_range (Range * vec, int size, int start) static
Referenced by eval_constraint().
calculate_initial_matchlist()
static Boolean calculate_initial_matchlist (Constrainttree ctptr, Matchlist * matchlist, CorpusList * corpus) static
Wrapper around calculate_initial_matchlist_1, qv.
See also
calculate_initial_matchlist_1
References apply_setop_to_matchlist(), calculate_initial_matchlist_1(), Complement, corpus, _Matchlist::is_inverted, mark_offrange_cells(), and Reduce.
Referenced by cqp_run_tab_query(), eval_mu_tree(), and match_first_pattern().
calculate_initial_matchlist_1()
static Boolean calculate_initial_matchlist_1 (Constrainttree ctptr, Matchlist * matchlist, CorpusList * corpus) static
Gets the inital list of matches for a query.
NB. This function is called recursively.
Returns
False iff something has gone wrong.
References apply_setop_to_matchlist(), c_tree::attr, b_and, b_implies, b_not, b_or, bnode, c_tree::canon, CID, cl_id2cpos_oldstyle(), cl_idlist2cpos, cl_malloc(), cl_str_is, cmp_eq, cmp_ex, cmp_get, cmp_gt, cmp_let, cmp_lt, cmp_neq, cnode, Complement, c_tree::constnode, corpus, cqpmessage(), c_tree::ctype, _Matchlist::end, Error, eval_bool(), eval_debug, EvaluationIsRunning, False, free_matchlist(), func, get_b_operator_name(), get_corpus_positions(), get_matched_corpus_positions(), id_list, c_tree::idlist, init_matchlist(), int_leaf, Intersection, _Matchlist::is_inverted, c_tree::items, c_tree::label, c_tree::leaf, c_tree::left, mark_offrange_cells(), _Matchlist::matches_whole_corpus, _label_entry::name, c_tree::negated, c_tree::node, NORMAL, c_tree::nr_items, c_tree::op_id, pa_ref, c_tree::pa_ref, c_tree::pat_type, Reduce, REGEXP, c_tree::right, sa_ref, _Matchlist::start, string_leaf, _Matchlist::tabsize, True, c_tree::type, Union, and c_tree::val.
Referenced by calculate_initial_matchlist().
check_alignment_constraints()
static int check_alignment_constraints (Matchlist * ml) static
References CDA_OK, cl_alg2cpos(), cl_all_ok, cl_cpos2alg(), cl_errno, cl_free, cl_malloc(), cqp, cqpmessage(), delete_reftab(), evalenv::dfa, ee_ix, _Matchlist::end, Environment, evalenv, EvaluationIsRunning, free_matchlist(), Info, init_matchlist(), install_signal_handler(), evalenv::labels, dfa::Max_States, evalenv::negated, new_reftab(), no_match, simulate(), _Matchlist::start, and _Matchlist::tabsize.
Referenced by run_standard_query_dfa().
cqp_run_mu_query()
void cqp_run_mu_query (int keep_old_ranges, int cut_value)
Run a CQP Meet-Union query.
Parameters
keep_old_ranges Boolean
cut_value
References apply_setop_to_matchlist(), cl_malloc(), cqpmessage(), _Matchlist::end, Environment, Error, eval_mu_tree(), evalenv::evaltree, EvaluationIsRunning, free_matchlist(), init_matchlist(), mark_offrange_cells(), evalenv::query_corpus, Reduce, set_corpus_matchlists(), _Matchlist::start, and _Matchlist::tabsize.
Referenced by do_MUQuery().
cqp_run_query()
void cqp_run_query (int cut, int keep_old_ranges)
Run a standard CQP query.
This function wraps round run_standard_query_dfa (the only other thing it does is enforce the hard_cut limit).
See also
hard_cut
run_standard_query_dfa
Parameters
cut Integer value for "cut" command, clamped to hard_cut if one is set.
keep_old_ranges Boolean, passed to equivalent parameter to run_standard_query_dfa()
References ee_ix, hard_cut, and run_standard_query_dfa().
Referenced by do_StandardQuery().
cqp_run_tab_query()
void cqp_run_tab_query ()
Run a CQP Tabular query.
References apply_setop_to_matchlist(), calculate_initial_matchlist(), calculate_rightboundary(), cl_calloc(), cl_cpos_offset(), cl_free, cl_malloc(), cl_realloc(), cqpmessage(), _Matchlist::end, Environment, Error, evalenv::evaltree, EvaluationIsRunning, free_matchlist(), hard_boundary, init_matchlist(), mark_offrange_cells(), e_tree::max_dist, e_tree::min_dist, e_tree::next, e_tree::patindex, Pattern, evalenv::patternlist, evalenv::query_corpus, Reduce, repeat_inf, evalenv::search_context, set_corpus_matchlists(), _Matchlist::start, e_tree::tab_el, _Matchlist::tabsize, tabular, and e_tree::type.
Referenced by do_TABQuery().
eval_bool()
Boolean eval_bool (Constrainttree ctptr, RefTab rt, int curr_cpos)
Evaluate a boolean constraint tree/node using recursion.
Parameters
ctptr The constraint tree pointer.
rt The reference table object.
curr_cpos The current corpus position.
References ATTAT_FLOAT, ATTAT_INT, ATTAT_NONE, ATTAT_PAREF, ATTAT_POS, ATTAT_STRING, ATTAT_VAR, c_tree::attr, b_and, b_implies, b_not, b_or, bnode, CDA_OK, _DCR::charres, cl_all_ok, cl_cpos2id(), cl_cpos2struc2cpos(), cl_errno, cl_id2str(), cl_regex_match(), cl_str_is, cl_streq, cmp_eq, cmp_ex, cmp_get, cmp_gt, cmp_let, cmp_lt, cmp_neq, cnode, c_tree::constnode, cqpmessage(), c_tree::delete, Error, eval_debug, EvaluationIsRunning, False, float_leaf, _DCR::floatres, func, get_label_referenced_position(), get_leaf_value(), id_list, c_tree::idlist, int_leaf, intcompare(), _DCR::intres, c_tree::is_closing, c_tree::items, c_tree::label, c_tree::leaf, c_tree::left, _label_entry::name, c_tree::negated, c_tree::node, NORMAL, c_tree::nr_items, c_tree::op_id, pa_ref, _DCR::parefres, c_tree::pat_type, _label_entry::ref, REGEXP, c_tree::right, c_tree::rx, sa_ref, sbound, c_tree::sbound, set_reftab(), string_leaf, c_tree::strucattr, True, _DCR::type, c_tree::type, c_tree::val, and _DCR::value.
Referenced by calculate_initial_matchlist_1(), eval_constraint(), evaluate_subset(), evaluate_target(), and simulate().
eval_constraint()
static Boolean eval_constraint (AVS avs, int corppos, RefTab labelrefs, RefTab target_labelrefs, int * out_cpos) static
References _add_to_queue(), _find_range(), Anchor, _avs::anchor, _avs::attr, AVSRegionEmit, AVSRegionEnter, AVSRegionWait, cl_cpos2struc(), cl_regex_match(), cl_streq, cl_struc2cpos(), cl_struc2str(), _avs::con, _avs::constraint, corpus, _FSAState::cpos, dup_reftab(), Range::end, eval_bool(), False, _avs::field, get_reftab(), _StateQueue::head, _avs::is_closing, IsKeyword, IsTarget, evalenv::keyword_label, KeywordField, _avs::label, MatchAll, _avs::matchall, MatchEndField, MatchField, _avs::name, _avs::negated, _FSAState::next, _avs::nqr, _avs::opcode, Pattern, evalenv::query_corpus, _avs::queue, cl::range, _label_entry::ref, Region, _avs::region, _avs::right_boundary, evalenv::rp, _avs::rx, set_reftab(), simulate_debug, cl::size, _avs::start_label, _avs::start_target, StateQueue_length(), StateQueue_next_cpos(), StateQueue_pop(), strict_regions, Tag, _avs::tag, evalenv::target_label, TargetField, True, and _avs::type.
Referenced by simulate().
eval_mu_tree()
static int eval_mu_tree (Evaltree et, Matchlist * ml) static
return is boolean (all OK? true => yes, false => no)
References apply_setop_to_matchlist(), calculate_initial_matchlist(), e_tree::cooc, cooc_meet, cooc_union, CurEnv, EvaluationIsRunning, free_matchlist(), init_matchlist(), leaf, e_tree::leaf, e_tree::left, e_tree::lw, meet_mu(), meet_union, e_tree::negated, e_tree::op_id, e_tree::patindex, evalenv::patternlist, evalenv::query_corpus, e_tree::right, e_tree::rw, e_tree::struc, e_tree::type, and Union.
Referenced by cqp_run_mu_query().
free_all_environments()
void free_all_environments (void)
Frees all eval environments in the global array, and sets the ee_ix index to -1.
References ee_ix, and free_environment().
Referenced by in_UnnamedCorpusCommand(), and prepare_input().
free_environment()
int free_environment (int thisenv)
Frees an evaluation environment.
The environment must be one currently occupied within the global array.
See also
Environment
eep
Parameters
thisenv The eval environment to free (index in global array).
Returns
Boolean: true if the deletion went OK; false if the environment to be freed was not occupied (will print an error message).
References Anchor, ctxtsp::attrib, AVSRegionEnter, MatchSelector::begin, MatchSelector::begin_offset, cl_delete_regex(), cl_free, ctxtdir_leftright, delete_symbol_table(), ctxtsp::direction, ee_ix, MatchSelector::end, MatchSelector::end_offset, Environment, False, free_booltree(), free_dfa(), free_evaltree(), evalenv::gconstraint, evalenv::has_target_indicator, IsNotTarget, evalenv::labels, evalenv::match_selector, MatchAll, evalenv::MaxPatIndex, NoField, Pattern, evalenv::patternlist, evalenv::query_corpus, Region, evalenv::search_context, ctxtsp::size, ctxtsp::space_type, StateQueue_delete(), Tag, and word.
Referenced by free_all_environments().
get_b_operator_name()
static const char* get_b_operator_name (enum b_ops op) static
To aid in building error messages: get const string with a printable name for an operation.
References b_and, b_implies, b_not, b_or, cmp_eq, cmp_ex, cmp_get, cmp_gt, cmp_let, cmp_lt, and cmp_neq.
Referenced by calculate_initial_matchlist_1().
get_corpus_positions()
static int get_corpus_positions (Attribute * attribute, char * wordform, Matchlist * matchlist) static
Gets a list of corpus positions where the given p-attribute has the specified form (looked up directly in the attribute's lexicon).
This is done by wrapping cl_str2id() and cl_idlist2cpos(). Positions are placed into the "start" array of the matchlist.
Function is not NULL safe, the attribute and matchlist must be non-NULL. Similarly, the matchlist object must be empty; i.e. it cannot have memory allocated to its "start" array.
Parameters
attribute The p-attribute to search.
wordform The form to search for. (Should really be value_sought or similar.)
matchlist Where to put the results.
Returns
The size of the resulting matchlist table (also stored in its tabsize member).
References cl_all_ok, cl_idlist2cpos, cl_str2id(), initial_matchlist_debug, _Matchlist::matches_whole_corpus, silent, _Matchlist::start, and _Matchlist::tabsize.
Referenced by calculate_initial_matchlist_1().
get_label_referenced_position()
static int get_label_referenced_position (LabelEntry label, RefTab rt, int corppos) static
References eval_debug, get_reftab(), _label_entry::name, and _label_entry::ref.
Referenced by eval_bool(), and get_leaf_value().
get_leaf_value()
static Boolean get_leaf_value (Constrainttree ctptr, RefTab rt, int corppos, DynCallResult * dcr, int deliver_strings) static
References c_tree::args, ATTAT_FLOAT, ATTAT_INT, ATTAT_NONE, ATTAT_PAREF, ATTAT_POS, ATTAT_STRING, c_tree::attr, call_predefined_function(), CDA_EPOSORNG, CDA_ESTRUC, _DCR::charres, CID, cl_all_ok, cl_cpos2id(), cl_cpos2str(), cl_cpos2struc2cpos(), cl_cpos2struc2str(), cl_dynamic_call(), cl_errno, cl_free, cl_malloc(), cqpmessage(), c_tree::ctype, c_tree::delete, c_tree::dynattr, Error, eval_debug, EvaluationIsRunning, False, float_leaf, _DCR::floatres, func, c_tree::func, get_label_referenced_position(), int_leaf, _DCR::intres, c_tree::label, c_tree::leaf, _label_entry::name, _ActualParamList::next, c_tree::nr_args, pa_ref, c_tree::pa_ref, _ActualParamList::param, _DCR::parefres, c_tree::pat_type, c_tree::predef, _label_entry::ref, sa_ref, c_tree::sa_ref, set_reftab(), string_leaf, True, _DCR::type, c_tree::type, and _DCR::value.
Referenced by eval_bool().
get_matched_corpus_positions()
static int get_matched_corpus_positions (Attribute * attribute, char * regstr, int regex_flags, Matchlist * matchlist, int * restrictor_list, int restrictor_size) static
Get corpus positions matching a regular expression on a given p-attribute.
get_matched_corpus_positions looks in a corpus which is to be loaded for a regular expression 'regstr' of a given p-attribute and returns the table of matching start indices (start_table) and the tablesize (tabsize).
Parameters
attribute The attribute to search on. May be NULL, in which case DEFAULT_ATT_NAME is used.
regstr String containing the regular expression.
regex_flags Flags to be passed to the CL regex engine.
matchlist Location where the list of matches will be placed.
restrictor_list Passed to cl_idlist2cpos_oldstyle
restrictor_size Passed to cl_idlist2cpos_oldstyle
Returns
The number of matches found.
References ATT_POS, cl_free, cl_idlist2cpos_oldstyle(), cl_malloc(), cl_max_cpos(), cl_max_id(), cl_new_attribute(), cl_regex2id(), cl_str_is, cl::corpus, CWB_DEFAULT_ATT_NAME, eval_debug, initial_matchlist_debug, _Matchlist::is_inverted, _Matchlist::matches_whole_corpus, evalenv::query_corpus, silent, _Matchlist::start, and _Matchlist::tabsize.
Referenced by calculate_initial_matchlist_1(), and match_first_pattern().
intcompare()
static int intcompare (const void * i, const void * j) static
Comparison function used when eval_bool() calls qsort().
Referenced by eval_bool().
mark_offrange_cells()
static int mark_offrange_cells (Matchlist * matchlist, CorpusList * subcorpus) static
Alters a matchlist so that the start/end values of any match whose start point within the ranges of the given subcorpus are changed to the dummy -1 value.
Parameters
matchlist Matchlist to modify.
subcorpus Subcorpus to compare it to. (If some other kind of CorpusList is passed, it doesn't make sense).
Returns
Count of matches that were overwritten as -1.
References Range::end, _Matchlist::end, cl::mother_size, cl::range, cl::size, Range::start, and _Matchlist::start.
Referenced by calculate_initial_matchlist(), calculate_initial_matchlist_1(), cqp_run_mu_query(), and cqp_run_tab_query().
match_first_pattern()
static Boolean match_first_pattern (AVS pattern, Matchlist * matchlist, CorpusList * corpus) static
try to match the given word form pattern and return success.
References Anchor, _avs::anchor, apply_setop_to_matchlist(), _avs::attr, AVSRegionEnter, calculate_initial_matchlist(), cl_free, cl_malloc(), cl_max_struc(), cl_regex_match(), cl_struc2cpos(), cl_struc2str(), clear_all_bits(), _avs::con, _avs::constraint, corpus, cqpmessage(), create_bitfield(), destroy_bitfield(), _Matchlist::end, Error, EvaluationIsRunning, False, _avs::field, get_bit(), get_matched_corpus_positions(), _avs::is_closing, KeywordField, MatchAll, MatchEndField, _Matchlist::matches_whole_corpus, MatchField, _avs::name, _avs::negated, _avs::nqr, _avs::opcode, Pattern, query_optimize, cl::range, Reduce, Region, _avs::region, _avs::rx, set_all_bits(), set_bit(), silent, cl::size, Range::start, _Matchlist::start, _Matchlist::tabsize, Tag, _avs::tag, TargetField, True, and _avs::type.
Referenced by run_standard_query_dfa().
meet_mu()
static int meet_mu (Matchlist * list1, Matchlist * list2, int lw, int rw, Attribute * struc, int negated) static
Does a "meet" operation within MU queries.
NB: list1 will be modified in place, list2 remains unchanged and should be deallocated by the caller
Parameters
negated Boolean, true iff the "meet" operation contains the negation operator "not".
References cl_all_ok, cl_cpos2struc2cpos(), cl_cpos_offset(), cl_free, cl_realloc(), _Matchlist::end, _Matchlist::matches_whole_corpus, cl::mother_size, evalenv::query_corpus, _Matchlist::start, and _Matchlist::tabsize.
Referenced by eval_mu_tree().
next_environment()
int next_environment (void)
Sets up a new environment in the global array, which then becomes the.
(better name would be "add_environment" or "push_new_environment")
The next slot upwards is used (and ee_ix is incremented).
See also
ee_ix
Environment
Returns
True for all OK, false for an error (overflow of MAXENVIRONMENT).
References ctxtsp::attrib, ctxtdir_leftright, CurEnv, ctxtsp::direction, ee_ix, Environment, evalenv::evaltree, evalenv::gconstraint, evalenv::has_keyword_indicator, evalenv::has_target_indicator, init_dfa(), evalenv::keyword_label, evalenv::labels, evalenv::match_label, evalenv::matchend_label, evalenv::matching_strategy, matching_strategy, MAXENVIRONMENT, evalenv::MaxPatIndex, evalenv::negated, new_symbol_table(), evalenv::query_corpus, evalenv::search_context, ctxtsp::size, ctxtsp::space_type, evalenv::target_label, and word.
Referenced by ActivateCorpus(), after_CorpusSetExpr(), prepare_AlignmentConstraints(), and prepare_Query().
run_standard_query_dfa()
static void run_standard_query_dfa (int envidx, int cut, int keep_old_ranges) static
Run the DFA that performs a standard CQP query (i.e.
based on token-level regular expression).
Parameters
envidx Index into the global Environment array, specifiying which EvalEnvironment to use. The EvalEnvironment provides, inter alia, the corpus to search and the DFA itself.
cut The number specified as part of the "cut N" syntax. Any negative number = no limit.
keep_old_ranges Boolean. Passed through to set_corpus_matchlists.
References evalenv::aligned, apply_setop_to_matchlist(), check_alignment_constraints(), cl_free, cl_malloc(), cqp, cqpmessage(), delete_reftab(), evalenv::dfa, dfa::E_State, ee_ix, _Matchlist::end, Environment, Error, EvaluationIsRunning, dfa::Final, free_matchlist(), evalenv::has_keyword_indicator, evalenv::has_target_indicator, Info, init_matchlist(), initial_matchlist_debug, install_signal_handler(), _Matchlist::keyword_positions, evalenv::labels, match_first_pattern(), dfa::Max_Input, dfa::Max_States, new_reftab(), evalenv::patternlist, print_symbol_table(), progress_bar, progress_bar_clear_line(), progress_bar_message(), evalenv::query_corpus, Reduce, reset_reftab(), set_corpus_matchlists(), show_matchlist(), show_matchlist_firstelements(), simulate(), cl::size, sort_matchlist(), _Matchlist::start, _Matchlist::tabsize, _Matchlist::target_positions, dfa::TransTable, Union, Uniq, and Warning.
Referenced by cqp_run_query().
set_corpus_matchlists()
static void set_corpus_matchlists (CorpusList * cp, Matchlist * matchlist, int nr_lists, bool keep_old_ranges) static
Set the appropriate values to the corpus id (given by its pointer to the symbol table).
TODO what on earth does the above mean? seems not to relate to this function at all
Assigns the range data from a matchlist object (from running a query) to a CorpusList object that will represent the result as a NQR/subcorpus.
This includes the keyword/target data if present.
Parameters
cp (should be cl) The CorpusList object for the query result we are creating. In subquery filter mode (see below) it needs to contain the range data for the activated NQR being filtered.
matchlist Matchlist object array containing the actual query matches.
nr_lists Has no effect on anything, but it will cause an error if it's greater than 1.
keep_old_ranges Boolean. A somewhat opaquely named parameter which switches on/off "subquery filter mode". In SQ filter mode, the query result is a subset of the ranges in the activated query result (those which contain a match to the subquery). In non-filter mode, the query result is the expected set of match begin/end ranges. This implements the Keep operator (confusingly, an exclamation mark).
References apply_range_set_operation(), cl_free, cl_malloc(), Range::end, _Matchlist::end, _Matchlist::keyword_positions, cl::keywords, cl::range, RReduce, cl::size, cl::sortidx, Range::start, _Matchlist::start, _Matchlist::tabsize, _Matchlist::target_positions, and cl::targets.
Referenced by cqp_run_mu_query(), cqp_run_tab_query(), and run_standard_query_dfa().
show_environment()
void show_environment (int thisenv)
Prints the contents of an EvalEnvironment object to STDOUT.
Which bits of information are printed depends on which of a group of debugging-variables are set to true.
The EvalEnvironment to print is specified as an index into the global array (Environment).
See also
Environment
Parameters
thisenv Index into Environment indicating which EvalEnvironment should be displayed.
References MatchSelector::begin, MatchSelector::begin_offset, ee_ix, MatchSelector::end, MatchSelector::end_offset, Environment, evalenv::match_selector, _label_entry::name, print_booltree(), print_evaltree(), show_compdfa, show_complete_dfa(), show_evaltree, show_gconstraints, show_patlist, and show_patternlist().
Referenced by debug_output().
simulate()
static int simulate (Matchlist * matchlist, int * cut, int * state_vector, int * target_vector, RefTab * reftab_vector, RefTab * reftab_target_vector, int start_transition) static
Simulate the DFA in the global evalenv.
("Simulate", in technical Comp Sci terminology on finite state machines, basically means "run" - since CQP is, technically, only simulating the abstract machine described by the DFA!)
Returns True if the matching ranges may be out-of-order and need to be sorted.
References evalenv::aligned, Anchor, _avs::anchor, _avs::attr, AVSRegionEnter, MatchSelector::begin, MatchSelector::begin_offset, calculate_rightboundary(), CheckForInterrupts(), cl_cpos2struc2cpos(), _avs::con, cqpmessage(), evalenv::dfa, dup_reftab(), dfa::E_State, Range::end, MatchSelector::end, _Matchlist::end, MatchSelector::end_offset, Error, eval_bool(), eval_constraint(), EvaluationIsRunning, dfa::Final, free_matchlist(), evalenv::gconstraint, get_reftab(), evalenv::has_keyword_indicator, evalenv::has_target_indicator, _avs::is_closing, _avs::is_target, IsKeyword, IsNotTarget, IsTarget, evalenv::keyword_label, _Matchlist::keyword_positions, LAB_DEFINED, LAB_RDAT, LAB_USED, _avs::label, evalenv::labels, longest_match, _avs::lookahead, evalenv::match_label, evalenv::match_selector, MatchAll, _avs::matchall, evalenv::matchend_label, evalenv::matching_strategy, matching_strategy, dfa::Max_Input, dfa::Max_States, evalenv::MaxPatIndex, MIN, cl::mother_size, Pattern, evalenv::patternlist, print_label_values(), progress_bar, progress_bar_percentage(), evalenv::query_corpus, query_corpus, cl::range, _label_entry::ref, Region, reset_reftab(), _avs::right_boundary, evalenv::rp, evalenv::search_context, set_reftab(), simulate_debug, cl::size, Range::start, _Matchlist::start, StateQueue_clear(), strict_regions, symbol_table_iterator(), symbol_table_new_iterator(), symtab_debug, _Matchlist::tabsize, Tag, _avs::tag, evalenv::target_label, _Matchlist::target_positions, dfa::TransTable, and _avs::type.
Referenced by check_alignment_constraints(), and run_standard_query_dfa().
Variable Documentation
CurEnv
EEP CurEnv
Global pointer, address of the "highest" cell in Environment.
Used largely in parse_actions.
See also
Environment
Referenced by ActivateCorpus(), after_CorpusSetExpr(), do_AnchorPoint(), do_IDReference(), do_LabelReference(), do_MatchSelector(), do_MUQuery(), do_NamedWfPattern(), do_RegionElement(), do_SearchPattern(), do_TABQuery(), do_WordformPattern(), do_XMLTag(), eval_mu_tree(), next_environment(), prepare_AlignmentConstraints(), and prepare_Query().
ee_ix
int ee_ix
Global eval environment index; contains the index of the highest currently-occupied slot within Environment.
See also
Environment
Referenced by check_alignment_constraints(), cqp_run_query(), debug_output(), do_SearchPattern(), free_all_environments(), free_environment(), initialize_cqp(), next_environment(), prepare_Query(), regex2dfa(), run_standard_query_dfa(), and show_environment().
Environment
EvalEnvironment Environment[MAXENVIRONMENT]
A global array of EvalEnvironment structures.
Each represents the environment for a different aligned corpus.
Referenced by check_alignment_constraints(), cqp_run_mu_query(), cqp_run_tab_query(), do_Description(), do_MUQuery(), do_StandardQuery(), do_TABQuery(), free_environment(), next_environment(), prepare_AlignmentConstraints(), prepare_Query(), print_evaltree(), print_pattern(), regex2dfa(), run_standard_query_dfa(), show_environment(), and show_patternlist().
evalenv
EEP evalenv
Global pointer, address of the cell in Environment that is being used for evaluation.
Used largely in files other than parse_actions.
See also
Environment.
Referenced by check_alignment_constraints().