CWB: cl/fileutils.c File Reference
fileutils.c File Reference
#include <sys/stat.h>
#include <fcntl.h>
#include <glib.h>
#include "globals.h"
#include "fileutils.h"
Macros
#define STREAM_IS_PIPE(type) (type == CL_STREAM_PIPE || type == CL_STREAM_GZIP || type == CL_STREAM_BZIP2)
check whether stream type involves a pipe
Functions
off_t file_length (char *filename)
Gets the size of the specified file; returns EOF for error.
off_t fh_file_length (FILE *fh)
Gets the size of the specified file; returns EOF for error.
off_t fd_file_length (int fd)
Gets the size of the specified file; returns EOF for error.
long fprobe (char *fname)
Gets the size of the specified file; returns EOF for error.
int is_directory (char *path)
Checks whether the specified path indicates a directory.
int is_file (char *path)
Checks whether the specified path indicates a regular file.
int is_link (char *path)
Checks whether the specified path indicates a link.
static void cl_handle_sigpipe (int signum)
FILE * cl_open_stream (const char *filename, int mode, int type)
Open stream of specified (or guessed) type for reading or writing.
int cl_close_stream (FILE *handle)
Close I/O stream.
int cl_test_stream (FILE *handle)
Tests whether a file handle has been opened via cl_test_stream.
Variables
CLStream open_streams
Implementation of automagic I/O streams.
int cl_broken_pipe = 0
SIGPIPE handler and global status variable.
Macro Definition Documentation
STREAM_IS_PIPE
#define STREAM_IS_PIPE (type) (type == CL_STREAM_PIPE || type == CL_STREAM_GZIP || type == CL_STREAM_BZIP2)
check whether stream type involves a pipe
Function Documentation
cl_close_stream()
int cl_close_stream (FILE * handle)
Close I/O stream.
This function can only be used for FILE* objects opened with cl_open_stream()!
Parameters
handle An I/O stream that has been opened with cl_open_stream()
Returns
0 on success, otherwise the error code returned by fclose() or pclose()
References CDA_EATTTYPE, CDA_EPOSIX, CDA_OK, cl_broken_pipe, cl_errno, cl_free, CL_STREAM_BZIP2, CL_STREAM_FILE, CL_STREAM_GZIP, CL_STREAM_PIPE, CL_STREAM_STDIO, CLStream::handle, CLStream::next, open_streams, STREAM_IS_PIPE, and CLStream::type.
Referenced by addHistoryLine(), alignshow_goodbye(), attach_subcorpus(), close_rd_input_stream(), close_rd_output_stream(), corpus_info(), cqp_parse_file(), encode_get_input_line(), lexdecode_show(), main(), open_rd_input_stream(), open_rd_output_stream(), save_subcorpus(), and SetVariableValue().
cl_handle_sigpipe()
static void cl_handle_sigpipe (int signum) static
References cl_broken_pipe.
Referenced by cl_open_stream().
cl_open_stream()
FILE* cl_open_stream (const char * filename, int mode, int type)
Open stream of specified (or guessed) type for reading or writing.
I/O streams opened with this function must always be closed with cl_close_stream()!
Parameters
filename Filename or shell command
mode Open for reading (CL_STREAM_READ) or writing (CL_STREAM_WRITE)
type Type of stream (see above), or guess automagically from [filename] (CL_STREAM_MAGIC)
Returns
Standard C stream, or NULL on error (with details available via cl_errno or cl_error())
References CDA_EACCESS, CDA_EARGS, CDA_EBUFFER, CDA_EPOSIX, CDA_OK, cl_broken_pipe, cl_errno, cl_handle_sigpipe(), cl_malloc(), CL_MAX_FILENAME_LENGTH, cl_str_is, CL_STREAM_APPEND, CL_STREAM_APPEND_BIN, CL_STREAM_BZIP2, CL_STREAM_FILE, CL_STREAM_GZIP, CL_STREAM_MAGIC, CL_STREAM_MAGIC_NOPIPE, CL_STREAM_PIPE, CL_STREAM_READ, CL_STREAM_READ_BIN, CL_STREAM_STDIO, CL_STREAM_WRITE, CL_STREAM_WRITE_BIN, CLStream::handle, CLStream::mode, mode, CLStream::next, open_streams, STREAM_IS_PIPE, and CLStream::type.
Referenced by addHistoryLine(), attach_subcorpus(), corpus_info(), do_exec(), encode_get_input_line(), lexdecode_show(), main(), open_pager(), open_rd_input_stream(), open_rd_output_stream(), parse_options(), save_subcorpus(), sencode_parse_options(), and SetVariableValue().
cl_test_stream()
int cl_test_stream (FILE * handle)
Tests whether a file handle has been opened via cl_test_stream.
Parameters
handle The FILE pointer to check.
Returns
Boolean. True iff the "cl_stream" knows about this handle.
References CLStream::handle, CLStream::next, and open_streams.
Referenced by cqp_parse_file().
fd_file_length()
off_t fd_file_length (int fd)
Gets the size of the specified file; returns EOF for error.
As file_length, but the file is specified by number, not name.
See also
file_length
Parameters
fd The file to size up.
Returns
Size of file in bytes.
fh_file_length()
off_t fh_file_length (FILE * fh)
Gets the size of the specified file; returns EOF for error.
As file_length, but the file is specified by file handle, not name.
See also
file_length
Parameters
fh The file to size up.
Returns
Size of file in bytes.
file_length()
off_t file_length (char * filename)
Gets the size of the specified file; returns EOF for error.
Parameters
filename The file to size up.
Returns
Size of file in bytes (or EOF if call to stat() failed)
Referenced by attach_subcorpus(), and work_out_component_state().
fprobe()
long fprobe (char * fname)
Gets the size of the specified file; returns EOF for error.
Duplicates functionality of file_length, but return is long instead of off_t.
See also
file_length
Parameters
fname The file to size up.
Returns
Size of file in bytes.
is_directory()
int is_directory (char * path)
Checks whether the specified path indicates a directory.
Parameters
path Path to check.
Returns
Boolean. (Also false if there's an error.)
Referenced by makeall_do_attribute().
is_file()
int is_file (char * path)
Checks whether the specified path indicates a regular file.
Parameters
path Path to check.
Returns
Boolean. (Also false if there's an error.)
is_link()
int is_link (char * path)
Checks whether the specified path indicates a link.
Note this function always returns false in Windows, because Windows doesn't have Unix-style links. (.lnk files don't count.)
As of 2020: Windows 10 does have symlinks. They were added in Vista but required elevated permissions to work with. Windows 10 makes it possible to use symlinks without elevated permissions (but it might be necessary to dop some configuration twiddling to get that to work; it's not 100% clear). Even so, though, it's not clear whether stat() in MinGW will correctly report what is and is not a symlink.
See https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/
Parameters
path Path to check.
Returns
Boolean. (Also false if there's an error.)
Variable Documentation
cl_broken_pipe
int cl_broken_pipe = 0
SIGPIPE handler and global status variable.
This variable will be set to True if a SIGPIPE has been caught and ignored.
Referenced by ascii_print_group(), ascii_print_output(), cl_close_stream(), cl_handle_sigpipe(), cl_open_stream(), do_dump(), html_print_group(), html_print_output(), latex_print_group(), latex_print_output(), print_tabulation(), sgml_print_group(), sgml_print_output(), and SortSubcorpus().
open_streams
CLStream open_streams
Implementation of automagic I/O streams.
In order to make streams completely transparent to the caller and return them as standard FILE* objects, the CL keeps a list of all open streams with the necessary metadata information.
Referenced by cl_close_stream(), cl_open_stream(), and cl_test_stream().