CWB: cl/fileutils.h File Reference
fileutils.h File Reference
#include <sys/types.h>
#include "globals.h"
Data Structures
struct CLStream
Typedefs
typedef struct CLStream * CLStream
Functions
off_t file_length (char *filename)
Gets the size of the specified file; returns EOF for error.
off_t fh_file_length (FILE *fd)
Gets the size of the specified file; returns EOF for error.
off_t fd_file_length (int fileno)
Gets the size of the specified file; returns EOF for error.
long fprobe (char *fname)
Gets the size of the specified file; returns EOF for error.
int is_directory (char *path)
Checks whether the specified path indicates a directory.
int is_file (char *path)
Checks whether the specified path indicates a regular file.
int is_link (char *path)
Checks whether the specified path indicates a link.
Typedef Documentation
CLStream
typedef struct CLStream* CLStream
Function Documentation
fd_file_length()
off_t fd_file_length (int fd)
Gets the size of the specified file; returns EOF for error.
As file_length, but the file is specified by number, not name.
See also
file_length
Parameters
fd The file to size up.
Returns
Size of file in bytes.
fh_file_length()
off_t fh_file_length (FILE * fh)
Gets the size of the specified file; returns EOF for error.
As file_length, but the file is specified by file handle, not name.
See also
file_length
Parameters
fh The file to size up.
Returns
Size of file in bytes.
file_length()
off_t file_length (char * filename)
Gets the size of the specified file; returns EOF for error.
Parameters
filename The file to size up.
Returns
Size of file in bytes (or EOF if call to stat() failed)
Referenced by attach_subcorpus(), and work_out_component_state().
fprobe()
long fprobe (char * fname)
Gets the size of the specified file; returns EOF for error.
Duplicates functionality of file_length, but return is long instead of off_t.
See also
file_length
Parameters
fname The file to size up.
Returns
Size of file in bytes.
is_directory()
int is_directory (char * path)
Checks whether the specified path indicates a directory.
Parameters
path Path to check.
Returns
Boolean. (Also false if there's an error.)
Referenced by makeall_do_attribute().
is_file()
int is_file (char * path)
Checks whether the specified path indicates a regular file.
Parameters
path Path to check.
Returns
Boolean. (Also false if there's an error.)
is_link()
int is_link (char * path)
Checks whether the specified path indicates a link.
Note this function always returns false in Windows, because Windows doesn't have Unix-style links. (.lnk files don't count.)
As of 2020: Windows 10 does have symlinks. They were added in Vista but required elevated permissions to work with. Windows 10 makes it possible to use symlinks without elevated permissions (but it might be necessary to dop some configuration twiddling to get that to work; it's not 100% clear). Even so, though, it's not clear whether stat() in MinGW will correctly report what is and is not a symlink.
See https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/
Parameters
path Path to check.
Returns
Boolean. (Also false if there's an error.)