CWB: cl/globals.c File Reference
globals.c File Reference
This contains accessor functions for the CL global variables which are defined as "extern" in the include-it-everywhere "globals.h" header.
#include <locale.h>
#include "globals.h"
Functions
void cl_startup (void)
Startup function for the CL.
int cl_cpos_offset (int cpos, int offset, int corpus_size, int clamp)
Safely add an offset to a corpus position.
void cl_set_debug_level (int level)
Sets the debug level configuration variable.
void cl_set_optimize (int state)
Turns optimization on or off.
void cl_set_memory_limit (int megabytes)
Sets the memory limit respected by some CL functions.
int cl_get_debug_level (void)
int cl_get_optimize (void)
int cl_get_memory_limit (void)
Variables
int cl_debug = 0
Global configuration variable: debug level.
int cl_optimize = 0
Global configuration variable: optimisation.
size_t cl_memory_limit = 0
Global configuration variable: memory limit.
Detailed Description
This contains accessor functions for the CL global variables which are defined as "extern" in the include-it-everywhere "globals.h" header.
This allows CQP/CWB-utils to access these variables without including the extern declarations; while the CL can access them qua variables.
It also contains the must-always-be-called cl_startup() function and a couple of other utilities.
Function Documentation
cl_cpos_offset()
int cl_cpos_offset (int cpos, int offset, int corpus_size, int clamp)
Safely add an offset to a corpus position.
Return CDA_EPOSORNG if cpos + offset is outside the corpus (clamp = 0), or clamps the return value to the valid range (clamp = 1). Particular care is taken to avoid integer overflow if cpos is close to INT_MAX.
Parameters
cpos corpus position (must be in valid range)
offset positive or negative offset from corpus position
corpus_size corpus size as returned by cl_max_cpos()
clamp boolean: whether to clamp return value (1) or return an error (0)
Returns
cpos + offset (possibly clamped) or CDA_EPOSORNG
References CDA_EPOSORNG.
Referenced by cqp_run_tab_query(), and meet_mu().
cl_get_debug_level()
int cl_get_debug_level (void)
References cl_debug.
cl_get_memory_limit()
int cl_get_memory_limit (void)
References cl_memory_limit.
cl_get_optimize()
int cl_get_optimize (void)
References cl_optimize.
cl_set_debug_level()
void cl_set_debug_level (int level)
Sets the debug level configuration variable.
See also
cl_debug
References cl_debug.
Referenced by execute_side_effects(), impose_silent_options(), main(), parse_options(), and set_default_option_values().
cl_set_memory_limit()
void cl_set_memory_limit (int megabytes)
Sets the memory limit respected by some CL functions.
Parameters
megabytes The new limit. Zero or less means no limit.
See also
cl_memory_limit
References cl_memory_limit.
Referenced by main().
cl_set_optimize()
void cl_set_optimize (int state)
Turns optimization on or off.
See also
cl_optimize
Parameters
state Boolean (true turns it on, false turns it off).
References cl_optimize.
Referenced by execute_side_effects(), main(), and set_default_option_values().
cl_startup()
void cl_startup (void)
Startup function for the CL.
All programs that use CL should call this before doing anything else.
Currently, all it does is make sure that string case-insensitive comparison will work the same everywhere regardless of the locale set by the system or user.
Referenced by initialize_cqp(), and main().
Variable Documentation
cl_debug
int cl_debug = 0
Global configuration variable: debug level.
Controls how many debug messages are printed. 0 = none (default), 1 = some, 2 = heavy
Referenced by cl_dynamic_call(), cl_get_debug_level(), cl_lexhash_check_grow(), cl_new_regex(), cl_ngram_hash_check_grow(), cl_regex2id(), cl_regex_match(), cl_regopt_analyse(), cl_set_debug_level(), creat_rev_corpus(), create_component(), make_jump_table(), and regopt_data_copy_to_regex_object().
cl_memory_limit
size_t cl_memory_limit = 0
Global configuration variable: memory limit.
In megabytes; some functions will try to keep to this limit; 0 turns the limit off.
(ensure memory limit > 2GB is correctly converted to byte size or number of ints)
Referenced by cl_get_memory_limit(), cl_set_memory_limit(), and creat_rev_corpus().
cl_optimize
int cl_optimize = 0
Global configuration variable: optimisation.
0 = off, 1 = on (untested / expensive optimisations)
Referenced by cl_get_optimize(), cl_regex_match(), and cl_set_optimize().