CWB: cqp/groups.c File Reference
groups.c File Reference
#include <math.h>
#include "../cl/cl.h"
#include "../cl/ui-helpers.h"
#include "options.h"
#include "html-print.h"
#include "ascii-print.h"
#include "sgml-print.h"
#include "latex-print.h"
#include "corpmanag.h"
#include "groups.h"
#include "output.h"
Macros
#define GROUP_DEBUG 0
define this as 1 to prevent temporary file deletion & print additional messages
#define ANY_ID -2
integer identfier special value: = anything
#define GROUP_REALLOC 1024
Functions
static int compare_cells (const void *p1, const void *p2)
support function for qsort() of grouping cells, controlled by global variables
static int get_group_id (Group *group, int i, int target, int *cpos)
Get lexicon ID of grouping element target (1 = target, 0 = source) for item i in query result set.
const char * Group_id2str (Group *group, int id, int target)
static Group * ComputeGroupInternally (Group *group)
static Group * ComputeGroupExternally (Group *group)
This function is used for passing Groups to external tools for grouping.
Group * compute_grouping (CorpusList *cl, FieldType source_field, int source_offset, const char *source_attr_name, FieldType target_field, int target_offset, const char *target_attr_name, int cutoff_freq, int is_grouped, const char *within)
void free_group (Group **group)
Frees the Group object pointed to by the argument.
void print_group (Group *group, struct Redir *dst)
Prints a group in a style determined by GlobalPrintMode, to an output stream determined by argument rd (which gets both opened and closed here).
Variables
static Group * compare_cells_group = NULL
private variable in module: a global Group object.
Macro Definition Documentation
ANY_ID
#define ANY_ID -2
integer identfier special value: = anything
GROUP_DEBUG
#define GROUP_DEBUG 0
define this as 1 to prevent temporary file deletion & print additional messages
GROUP_REALLOC
#define GROUP_REALLOC 1024
Function Documentation
compare_cells()
static int compare_cells (const void * p1, const void * p2) static
support function for qsort() of grouping cells, controlled by global variables
References cl_strcmp(), compare_cells_group, _id_cnt_mapping::freq, Group_id2str(), _grouptable::is_grouped, _id_cnt_mapping::s, _id_cnt_mapping::s_freq, _id_cnt_mapping::t, w1, and w2.
Referenced by ComputeGroupInternally().
compute_grouping()
Group* compute_grouping (CorpusList * cl, FieldType source_field, int source_offset, const char * source_attr_name, FieldType target_field, int target_offset, const char * target_attr_name, int cutoff_freq, int is_grouped, const char * within)
References ATT_POS, ATT_STRUC, cl_malloc(), cl_new_attribute(), cl_struc2str(), cl_struc_values(), ComputeGroupExternally(), ComputeGroupInternally(), cl::corpus, _grouptable::count_cells, cqpmessage(), _grouptable::cutoff_frequency, Error, insecure, _grouptable::is_grouped, KeywordField, cl::keywords, MatchEndField, MatchField, _grouptable::my_corpus, cl::name, NoField, _grouptable::nr_cells, cl::range, cl::size, _grouptable::source_attribute, _grouptable::source_base, _grouptable::source_field, _grouptable::source_is_struc, _grouptable::source_offset, _grouptable::target_attribute, _grouptable::target_base, _grouptable::target_field, _grouptable::target_is_struc, _grouptable::target_offset, TargetField, cl::targets, UseExternalGroup, Warning, and _grouptable::within_attribute.
Referenced by do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), and do_group().
ComputeGroupExternally()
static Group* ComputeGroupExternally (Group * group) static
This function is used for passing Groups to external tools for grouping.
The Group object is modified in situ. The return is that Group again.
References cl_malloc(), CL_MAX_LINE_LENGTH, cl_realloc(), _grouptable::count_cells, cqpmessage(), _grouptable::cutoff_frequency, Error, ExternalGroupCommand, _id_cnt_mapping::freq, get_group_id(), GROUP_REALLOC, _grouptable::my_corpus, _grouptable::nr_cells, open_temporary_file(), _id_cnt_mapping::s, _id_cnt_mapping::s_freq, cl::size, _id_cnt_mapping::t, TEMP_FILENAME_BUFSIZE, Warning, and _grouptable::within_attribute.
Referenced by compute_grouping().
ComputeGroupInternally()
static Group* ComputeGroupInternally (Group * group) static
References ANY_ID, cl_cpos2struc(), cl_delete_ngram_hash(), cl_malloc(), cl_new_ngram_hash(), cl_ngram_hash_add(), cl_ngram_hash_freq(), cl_ngram_hash_iterator_next(), cl_ngram_hash_iterator_reset(), cl_ngram_hash_payload(), cl_ngram_hash_size(), cl_realloc(), compare_cells(), compare_cells_group, _grouptable::count_cells, cqp, cqpmessage(), _grouptable::cutoff_frequency, do_within, Error, EvaluationIsRunning, free_group(), _id_cnt_mapping::freq, get_group_id(), install_signal_handler(), _grouptable::my_corpus, _grouptable::nr_cells, progress_bar, progress_bar_clear_line(), progress_bar_message(), progress_bar_percentage(), _id_cnt_mapping::s, _id_cnt_mapping::s_freq, cl::size, _id_cnt_mapping::t, Warning, and _grouptable::within_attribute.
Referenced by compute_grouping().
free_group()
void free_group (Group ** group)
Frees the Group object pointed to by the argument.
References cl_free.
Referenced by ComputeGroupInternally(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), and do_group().
get_group_id()
static int get_group_id (Group * group, int i, int target, int * cpos) static
Get lexicon ID of grouping element target (1 = target, 0 = source) for item i in query result set.
Returns an integer ID to be used for frequency counts in an n-gram hash. This is either a lexicon ID (if the grouping element refers to a p-attribute) or a virtual ID computed from the offset of the annotation string (if the element refers to an s-attribute, relying on the fact that each unique annotation string is stored only once in the s-attribute).
If cpos is not NULL, the corresponding corpus position is written to *cpos.
The following special cases can occur:
A: The grouping element is unused (source in a simple group statement)
returns ANY_ID = -2 (which pretty-prints as (all) in the grouping output)
corpus position is set to ANY_ID
B: The anchor point is undefined (possible for target and keyword anchors)
returns -1 (which prints as (none) in the grouping output)
corpus position is set to ANY_ID
C: The anchor point with offset (= effective cpos) is outside the valid corpus range
returns -1 (either explicitly for cpos < 0, or implicitly as returned by cl_cpos2id)
corpus position is set to effective cpos, or to -1 for all negative values (to avoid confusion with ANY_ID)
D: The effective cpos is valid, but not inside a range of the referenced s-attribute
returns -1
corpus position is set to effective cpos
Parameters
group Pointer to a data structure describing the group operation (and holding results).
i The row of the query result to be accessed.
target Whether to return information for the source element (0) or the target element (1).
cpos If not NULL, the effective corpus position is returned in this location.
Returns
An integer ID to be used in frequency counts (see above for special cases)
References ANY_ID, cl_cpos2id(), cl_cpos2struc2str(), Range::end, KeywordField, cl::keywords, MatchEndField, MatchField, _grouptable::my_corpus, NoField, cl::range, _grouptable::source_attribute, _grouptable::source_base, _grouptable::source_field, _grouptable::source_is_struc, _grouptable::source_offset, Range::start, _grouptable::target_attribute, _grouptable::target_base, _grouptable::target_field, _grouptable::target_is_struc, _grouptable::target_offset, TargetField, and cl::targets.
Referenced by ComputeGroupExternally(), and ComputeGroupInternally().
Group_id2str()
const char* Group_id2str (Group * group, int id, int target)
References ANY_ID, cl_id2str(), _grouptable::source_attribute, _grouptable::source_base, _grouptable::source_is_struc, _grouptable::target_attribute, _grouptable::target_base, and _grouptable::target_is_struc.
Referenced by ascii_print_group(), compare_cells(), html_print_group(), latex_print_group(), and sgml_print_group().
print_group()
void print_group (Group * group, struct Redir * dst)
Prints a group in a style determined by GlobalPrintMode, to an output stream determined by argument rd (which gets both opened and closed here).
References ascii_print_group(), TCorpus::charset, close_rd_output_stream(), cl::corpus, cqpmessage(), Error, GlobalPrintMode, html_print_group(), latex_print_group(), _grouptable::my_corpus, open_rd_output_stream(), PrintASCII, PrintHTML, PrintLATEX, PrintSGML, sgml_print_group(), and Redir::stream.
Referenced by do_group().
Variable Documentation
compare_cells_group
Group* compare_cells_group = NULL static
private variable in module: a global Group object.
Referenced by compare_cells(), and ComputeGroupInternally().