CWB: cqp/html-print.c File Reference
html-print.c File Reference
#include "html-print.h"
#include <stdio.h>
#include <string.h>
#include "../cl/globals.h"
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include "cqp.h"
#include "options.h"
#include "corpmanag.h"
#include "concordance.h"
#include "attlist.h"
#include "print_align.h"
#include <sys/time.h>
#include <time.h>
#include <pwd.h>
Functions
char * html_print_field (FieldType field, int start)
static void html_puts (FILE *dst, const char *s, int flags)
const char * html_convert_string (const char *s)
Dis-entititifies lt, gt and amp entities in a string supplierd.
void html_print_aligned_line (FILE *dest, int highlighting, char *attribute_name, char *line)
Prints a line of text (which will have been previously extracted from a corpus linked to the present corpus by an a-attribute) within HTML markup.
void html_print_context (ContextDescriptor *cd, FILE *dest)
void html_print_corpus_header (CorpusList *cl, FILE *dest)
void html_print_output (CorpusList *cl, FILE *dest, int interactive, ContextDescriptor *cd, int first, int last)
void html_print_group (Group *group, FILE *dest)
Variables
PrintDescriptionRecord HTMLPrintDescriptionRecord
PrintDescriptionRecord HTMLTabularPrintDescriptionRecord
PrintDescriptionRecord HTMLTabularNowrapPrintDescriptionRecord
Function Documentation
html_convert_string()
const char* html_convert_string (const char * s)
Dis-entititifies lt, gt and amp entities in a string supplierd.
Returns
Pointer into an internal static buffer
References CL_MAX_LINE_LENGTH.
html_print_aligned_line()
void html_print_aligned_line (FILE * dest, int highlighting, char * attribute_name, char * line)
Prints a line of text (which will have been previously extracted from a corpus linked to the present corpus by an a-attribute) within HTML markup.
Parameters
dest Destination for the output.
highlighting DUMMY: only supported by ascii print.
attribute_name The name of the aligned corpus: printed in the leading indicator within the HTML.
line Character data of the line of aligned-corpus data to print. This is treated as opaque.
References GlobalPrintOptions, html_puts(), line, PrintOptions::print_tabular, PrintOptions::print_wrap, SUBST_ALL, and SUBST_NONE.
Referenced by print_all_aligned_lines().
html_print_context()
void html_print_context (ContextDescriptor * cd, FILE * dest)
References char_context, ContextDescriptor::left_structure_name, ContextDescriptor::left_type, ContextDescriptor::left_width, ContextDescriptor::right_structure_name, ContextDescriptor::right_type, ContextDescriptor::right_width, s_att_context, and word_context.
Referenced by html_print_corpus_header().
html_print_corpus_header()
void html_print_corpus_header (CorpusList * cl, FILE * dest)
References CD, cl::corpus, GlobalPrintOptions, html_print_context(), cl::mother_name, TCorpus::name, cl::name, passwd, PrintOptions::print_header, cl::query_corpus, cl::query_text, TCorpus::registry_name, and cl::size.
Referenced by print_corpus_info_header().
html_print_field()
char * html_print_field (FieldType field, int start)
References GlobalPrintOptions, KeywordField, MatchField, NoField, PrintOptions::print_tabular, PrintOptions::print_wrap, and TargetField.
html_print_group()
void html_print_group (Group * group, FILE * dest)
References cl_broken_pipe, _grouptable::count_cells, _id_cnt_mapping::freq, Group_id2str(), html_puts(), _grouptable::nr_cells, _id_cnt_mapping::s, SUBST_ALL, and _id_cnt_mapping::t.
Referenced by print_group().
html_print_output()
void html_print_output (CorpusList * cl, FILE * dest, int interactive, ContextDescriptor * cd, int first, int last)
References PrintDescriptionRecord::AfterConcordance, PrintDescriptionRecord::AfterLine, ContextDescriptor::alignedCorpora, PrintDescriptionRecord::BeforeLine, CD, cl_broken_pipe, cl_free, compose_kwic_line(), cl::corpus, Range::end, _ConcLineField::end_position, GlobalPrintOptions, HTMLPrintDescriptionRecord, HTMLTabularNowrapPrintDescriptionRecord, HTMLTabularPrintDescriptionRecord, KeywordField, cl::keywords, line, MatchEndField, MatchField, NoField, ParsePrintOptions(), print_all_aligned_lines(), PrintOptions::print_border, PrintOptions::print_tabular, PrintOptions::print_wrap, cl::range, cl::size, cl::sortidx, Range::start, _ConcLineField::start_position, TargetField, cl::targets, and _ConcLineField::type.
Referenced by print_concordance_body().
html_puts()
static void html_puts (FILE * dst, const char * s, int flags) static
References SUBST_AMP, SUBST_GT, SUBST_LT, and SUBST_QUOT.
Referenced by html_print_aligned_line(), and html_print_group().
Variable Documentation
HTMLPrintDescriptionRecord
PrintDescriptionRecord HTMLPrintDescriptionRecord
Referenced by html_print_output(), and print_all_aligned_lines().
HTMLTabularNowrapPrintDescriptionRecord
PrintDescriptionRecord HTMLTabularNowrapPrintDescriptionRecord
Initial value:
= {
  "<TD ALIGN=RIGHT nowrap>%d:</TD>",
  "<TD nowrap><EM>",
  " ",
  "</EM></TD>",
  "&lt;",
  "&gt;",
  " ",
  "&lt;/",
  "&gt;",
  NULL,
  " ",
  "/",
  NULL,
  "<TD nowrap ALIGN=RIGHT> ",
  "</TD>",
  "<TR>",
  "</TR>\n",
  "<HR>\n<TABLE>\n",
  "</TABLE>\n<HR>\n",
  html_convert_string,
  html_print_field
}
Referenced by html_print_output().
HTMLTabularPrintDescriptionRecord
PrintDescriptionRecord HTMLTabularPrintDescriptionRecord
Initial value:
= {
  "<TD ALIGN=RIGHT>%d:</TD>",
  "<TD><EM>",
  " ",
  "</EM></TD>",
  "&lt;",
  "&gt;",
  " ",
  "&lt;/",
  "&gt;",
  NULL,
  " ",
  "/",
  NULL,
  "<TD ALIGN=RIGHT> ",
  "</TD>",
  "<TR>",
  "</TR>\n",
  "<HR>\n<TABLE>\n",
  "</TABLE>\n<HR>\n",
  html_convert_string,
  html_print_field
}
Referenced by html_print_output().