CWB: cqp/latex-print.c File Reference
latex-print.c File Reference
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
#include <pwd.h>
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include "cqp.h"
#include "options.h"
#include "corpmanag.h"
#include "concordance.h"
#include "attlist.h"
#include "print_align.h"
#include "latex-print.h"
Functions
char * latex_print_field (FieldType field, int start)
const char * latex_convert_string (const char *s)
void latex_print_aligned_line (FILE *dest, int highlighting, char *attribute_name, char *line)
Does nothing: we don't support printing alignment data in LaTeX mode.
void latex_print_context (ContextDescriptor *cd, FILE *dest)
void latex_print_corpus_header (CorpusList *cl, FILE *dest)
Prints a concordance header in latex mode.
void latex_print_output (CorpusList *cl, FILE *dest, int interactive, ContextDescriptor *cd, int first, int last)
void latex_print_group (Group *group, FILE *dest)
Variables
PrintDescriptionRecord LaTeXPrintDescriptionRecord
PrintDescriptionRecord LaTeXTabularPrintDescriptionRecord
Function Documentation
latex_convert_string()
const char* latex_convert_string (const char * s)
References CL_MAX_LINE_LENGTH.
Referenced by latex_print_group().
latex_print_aligned_line()
void latex_print_aligned_line (FILE * dest, int highlighting, char * attribute_name, char * line)
Does nothing: we don't support printing alignment data in LaTeX mode.
Parameters
dest Destination for the output.
highlighting DUMMY: only supported by ascii print.
attribute_name The name of the aligned corpus.
line Character data of the line of aligned-corpus data to print.
Referenced by print_all_aligned_lines().
latex_print_context()
void latex_print_context (ContextDescriptor * cd, FILE * dest)
References char_context, ContextDescriptor::left_structure_name, ContextDescriptor::left_type, ContextDescriptor::left_width, ContextDescriptor::right_structure_name, ContextDescriptor::right_type, ContextDescriptor::right_width, s_att_context, and word_context.
Referenced by latex_print_corpus_header().
latex_print_corpus_header()
void latex_print_corpus_header (CorpusList * cl, FILE * dest)
Prints a concordance header in latex mode.
References CD, cl::corpus, latex_print_context(), cl::mother_name, TCorpus::name, cl::name, passwd, TCorpus::registry_name, and cl::size.
Referenced by print_corpus_info_header().
latex_print_field()
char * latex_print_field (FieldType field, int start)
References GlobalPrintOptions, KeywordField, MatchField, NoField, PrintOptions::print_tabular, and TargetField.
latex_print_group()
void latex_print_group (Group * group, FILE * dest)
References cl_broken_pipe, _grouptable::count_cells, _id_cnt_mapping::freq, Group_id2str(), latex_convert_string(), _grouptable::nr_cells, _id_cnt_mapping::s, and _id_cnt_mapping::t.
Referenced by print_group().
latex_print_output()
void latex_print_output (CorpusList * cl, FILE * dest, int interactive, ContextDescriptor * cd, int first, int last)
References PrintDescriptionRecord::AfterConcordance, PrintDescriptionRecord::AfterLine, ContextDescriptor::alignedCorpora, PrintDescriptionRecord::BeforeConcordance, PrintDescriptionRecord::BeforeLine, CD, cl_broken_pipe, cl_free, compose_kwic_line(), cl::corpus, Range::end, _ConcLineField::end_position, GlobalPrintOptions, KeywordField, cl::keywords, LaTeXPrintDescriptionRecord, LaTeXTabularPrintDescriptionRecord, line, _attlist::list, MatchEndField, MatchField, _attrbuf::next, NoField, ParsePrintOptions(), print_all_aligned_lines(), PrintOptions::print_border, ContextDescriptor::print_cpos, PrintOptions::print_tabular, ContextDescriptor::printStructureTags, cl::range, cl::size, cl::sortidx, Range::start, _ConcLineField::start_position, _attrbuf::status, TargetField, cl::targets, and _ConcLineField::type.
Referenced by print_concordance_body().
Variable Documentation
LaTeXPrintDescriptionRecord
PrintDescriptionRecord LaTeXPrintDescriptionRecord
Referenced by latex_print_output(), and print_all_aligned_lines().
LaTeXTabularPrintDescriptionRecord
PrintDescriptionRecord LaTeXTabularPrintDescriptionRecord
Referenced by latex_print_output().