CWB: cl/lexhash.c File Reference
lexhash.c File Reference
#include "globals.h"
#include <math.h>
Data Structures
struct _cl_lexhash
Underlying structure for the cl_lexhash object.
Macros
#define DEFAULT_NR_OF_BUCKETS 250000
Defines the default number of buckets in a lexhash.
#define DEFAULT_FILLRATE_LIMIT 2.0
Default parameters for auto-growing the table of buckets (.
#define DEFAULT_FILLRATE_TARGET 0.4
#define MAX_BUCKETS 1000000007 /* 1 billion (incremented to next prime number) */
Maximum number of buckets lexhash will try to allocate when auto-growing.
Typedefs
typedef void(* cl_lexhash_cleanup_func) (cl_lexhash_entry)
A function pointer type defining functions that can be used as the "cleanup" for a deleted cl_lexhash_entry.
Functions
int cl_is_prime (int n)
Returns True iff n is a prime.
int cl_find_prime (int n)
Returns smallest prime greater than or equal to n.
unsigned int cl_hash_string (const char *str)
Computes 32bit hash value for string.
unsigned int cl_hash_string_with_init (const char *str, unsigned int result_init)
Computes 32bit hash value for string, allowing the specification of an initial value for the result.
cl_lexhash cl_new_lexhash (int buckets)
Creates a new cl_lexhash object.
static void cl_delete_lexhash_entry (cl_lexhash hash, cl_lexhash_entry entry)
Deallocates a cl_lexhash_entry object and its key string.
void cl_delete_lexhash (cl_lexhash hash)
Deletes a cl_lexhash object.
void cl_lexhash_set_cleanup_function (cl_lexhash hash, cl_lexhash_cleanup_func func)
Sets the cleanup function for a cl_lexhash.
void cl_lexhash_auto_grow (cl_lexhash hash, int flag)
Turns a cl_lexhash's ability to auto-grow on or off.
void cl_lexhash_auto_grow_fillrate (cl_lexhash hash, double limit, double target)
Configure auto-grow parameters.
static int cl_lexhash_check_grow (cl_lexhash hash)
Grows a lexhash table, increasing the number of buckets, if necessary.
static cl_lexhash_entry cl_lexhash_find_i (cl_lexhash hash, char *token, unsigned int *ret_offset)
Finds the entry corresponding to a particular string in a cl_lexhash.
cl_lexhash_entry cl_lexhash_find (cl_lexhash hash, char *token)
Finds the entry corresponding to a particular string within a cl_lexhash.
cl_lexhash_entry cl_lexhash_add (cl_lexhash hash, char *token)
Adds a token to a cl_lexhash table.
int cl_lexhash_id (cl_lexhash hash, char *token)
Gets the ID of a particular string within a lexhash.
int cl_lexhash_freq (cl_lexhash hash, char *token)
Gets the frequency of a particular string within a lexhash.
int cl_lexhash_del (cl_lexhash hash, char *token)
Deletes a string from a hash.
int cl_lexhash_size (cl_lexhash hash)
Gets the number of different strings stored in a lexhash.
void cl_lexhash_iterator_reset (cl_lexhash hash)
Resets a lexhash's entry-iterator to the start of the hash.
cl_lexhash_entry cl_lexhash_iterator_next (cl_lexhash hash)
Gets the next entry from the hash's entry-iterator.
Macro Definition Documentation
DEFAULT_FILLRATE_LIMIT
#define DEFAULT_FILLRATE_LIMIT 2.0
Default parameters for auto-growing the table of buckets (.
See also
cl_lexhash_auto_grow_fillrate for details).
DEFAULT_FILLRATE_TARGET
#define DEFAULT_FILLRATE_TARGET 0.4
DEFAULT_NR_OF_BUCKETS
#define DEFAULT_NR_OF_BUCKETS 250000
Defines the default number of buckets in a lexhash.
MAX_BUCKETS
#define MAX_BUCKETS 1000000007 /* 1 billion (incremented to next prime number) */
Maximum number of buckets lexhash will try to allocate when auto-growing.
Typedef Documentation
cl_lexhash_cleanup_func
typedef void(* cl_lexhash_cleanup_func) (cl_lexhash_entry)
A function pointer type defining functions that can be used as the "cleanup" for a deleted cl_lexhash_entry.
See also
cl_lexhash_set_cleanup_function
Function Documentation
cl_delete_lexhash()
void cl_delete_lexhash (cl_lexhash hash)
Deletes a cl_lexhash object.
This deletes all the entries in all the buckets in the lexhash, plus the cl_lexhash itself.
Parameters
hash The cl_lexhash to delete.
References _cl_lexhash::buckets, cl_delete_lexhash_entry(), cl_free, _cl_lexhash_entry::next, and _cl_lexhash::table.
Referenced by main().
cl_delete_lexhash_entry()
static void cl_delete_lexhash_entry (cl_lexhash hash, cl_lexhash_entry entry) static
Deallocates a cl_lexhash_entry object and its key string.
Also, the cleanup function is run on the entry.
Usage: cl_delete_lexhash_entry(lexhash, entry);
See also
cl_lexhash_set_cleanup_function
Parameters
hash The lexhash this entry belongs to (needed to locate the cleanup function, if any).
entry The entry to delete.
References cl_free, and _cl_lexhash::cleanup_func.
Referenced by cl_delete_lexhash(), and cl_lexhash_del().
cl_find_prime()
int cl_find_prime (int n)
Returns smallest prime greater than or equal to n.
References cl_is_prime().
Referenced by cl_new_lexhash(), cl_new_ngram_hash(), InitialiseMacroHash(), and make_attribute_hash().
cl_hash_string()
unsigned int cl_hash_string (const char * str)
Computes 32bit hash value for string.
References cl_hash_string_with_init(), and init().
Referenced by att_hash_lookup(), cl_lexhash_check_grow(), and cl_lexhash_find_i().
cl_hash_string_with_init()
unsigned int cl_hash_string_with_init (const char * str, unsigned int result_init)
Computes 32bit hash value for string, allowing the specification of an initial value for the result.
Referenced by cl_hash_string().
cl_is_prime()
int cl_is_prime (int n)
Returns True iff n is a prime.
Referenced by cl_find_prime().
cl_lexhash_add()
cl_lexhash_entry cl_lexhash_add (cl_lexhash hash, char * token)
Adds a token to a cl_lexhash table.
If the string is already in the hash, its frequency count is increased by 1.
Otherwise, a new entry is created, with an auto-assigned ID; note that the string is duplicated, so the original string that is passed to this function does not need to be kept in memory.
Parameters
hash The hash table to add to.
token The string to add.
Returns
A pointer to a (new or existing) entry
References _cl_lexhash::auto_grow, _cl_lexhash::buckets, cl_lexhash_check_grow(), cl_lexhash_find_i(), cl_malloc(), _cl_lexhash_entry::data, _cl_lexhash::entries, _cl_lexhash::fillrate_limit, _cl_lexhash_entry::freq, _cl_lexhash_entry::id, _cl_lexhash_entry::_cl_lexhash_entry_data::integer, _cl_lexhash_entry::key, _cl_lexhash_entry::next, _cl_lexhash::next_id, _cl_lexhash_entry::_cl_lexhash_entry_data::numeric, _cl_lexhash_entry::_cl_lexhash_entry_data::pointer, _cl_lexhash::table, and token.
Referenced by encode_add_p_attr_line(), main(), s_att_close_range(), s_att_declare(), s_att_open_range(), and sencode_write_region().
cl_lexhash_auto_grow()
void cl_lexhash_auto_grow (cl_lexhash hash, int flag)
Turns a cl_lexhash's ability to auto-grow on or off.
When this setting is switched on, the lexhash will grow automatically to avoid performance degradation.
Note the default value for this setting is SWITCHED ON.
See also
cl_lexhash_check_grow
Parameters
hash The hash that will be affected.
flag New value for autogrow setting: boolean where true is on and false is off.
References _cl_lexhash::auto_grow.
cl_lexhash_auto_grow_fillrate()
void cl_lexhash_auto_grow_fillrate (cl_lexhash hash, double limit, double target)
Configure auto-grow parameters.
These settings are only relevant if auto-growing is enabled.
The decision to expand the bucket table of a lexhash is based on its fill rate, i.e. the average number of entries in each bucket. Under normal circumstances, this value corresponds to the average number of comparisons required to insert a new entry into the hash (locating an existing value should require roughly half as many comparisons).
Auto-growing is triggered if the fill rate exceeds a specified limit. The new number of buckets is chosen so that the fill rate after expansion corresponds to the specified target value.
The limit should not be set too low in order to reduce memory overhead and avoid frequent reallocation due to expansion in small increments. Good values seem to be in the range 2.0-5.0; depending on whether speed or memory efficiency is more important. A reasonable value for the target fill rate is 0.4, which corresponds to a 42% overhead over the storage required for entry data structures (48 bytes per entry vs. 8 bytes for each bucket).
See also
cl_lexhash_auto_grow, cl_lexhash_check_grow
Parameters
hash The hash that will be affected.
limit Fill rate limit, which triggers expansion of the lexhash
target Target fill rate after expansion (determines new number of buckets)
References _cl_lexhash::fillrate_limit, and _cl_lexhash::fillrate_target.
cl_lexhash_check_grow()
static int cl_lexhash_check_grow (cl_lexhash hash) static
Grows a lexhash table, increasing the number of buckets, if necessary.
This functions is called after inserting a new entry into the lexhash. If checks whether the current fill rate exceeds the specified limit. If this is the case, and auto_grow is enabled, then the hash is expanded by increasing the number of buckets, such that the new average fill rate corresponds to the specified target value. This gives the hash better performance and makes it capable of absorbing more keys.
If the bucket table would be expanded to more than MAX_BUCKETS entries, auto-grow is automatically disabled for this lexhash.
Note: this function also implements the hashing algorithm and must be consistent with cl_lexhash_find_i().
Usage: expanded = cl_lexhash_check_grow(cl_lexhash hash);
This is a non-exported function.
See also
cl_lexhash_auto_grow, cl_lexhash_auto_grow_fillrate
Parameters
hash The lexhash to autogrow.
Returns
Boolean: true for OK, false for error.
References _cl_lexhash::auto_grow, _cl_lexhash::buckets, cl_debug, cl_free, cl_hash_string(), cl_new_lexhash(), _cl_lexhash::entries, _cl_lexhash::fillrate_limit, _cl_lexhash::fillrate_target, _cl_lexhash_entry::key, MAX_BUCKETS, _cl_lexhash_entry::next, and _cl_lexhash::table.
Referenced by cl_lexhash_add().
cl_lexhash_del()
int cl_lexhash_del (cl_lexhash hash, char * token)
Deletes a string from a hash.
The entry corresponding to the specified string is removed from the lexhash. If the string is not in the lexhash to begin with, no action is taken.
Parameters
hash The hash to alter.
token The string to remove.
Returns
The frequency of the deleted entry (0 if the string was not found in the hash).
References cl_delete_lexhash_entry(), cl_lexhash_find_i(), _cl_lexhash::entries, _cl_lexhash_entry::freq, _cl_lexhash_entry::next, _cl_lexhash::table, and token.
cl_lexhash_find()
cl_lexhash_entry cl_lexhash_find (cl_lexhash hash, char * token)
Finds the entry corresponding to a particular string within a cl_lexhash.
This function is basically a wrapper around the internal function cl_lexhash_find_i.
See also
cl_lexhash_find_i
Parameters
hash The hash to search.
token The key-string to look for.
Returns
The entry that is found (or NULL if the string is not in the hash).
References cl_lexhash_find_i(), and token.
Referenced by main(), s_att_close_range(), s_att_open_range(), s_att_print_registry_line(), and sencode_write_region().
cl_lexhash_find_i()
static cl_lexhash_entry cl_lexhash_find_i (cl_lexhash hash, char * token, unsigned int * ret_offset) static
Finds the entry corresponding to a particular string in a cl_lexhash.
This function is the same as cl_lexhash_find(), but *ret_offset is set to the hashtable offset computed for token (i.e. the index of the bucket within the hashtable), unless *ret_offset == NULL.
Note that this function hides the hashing algorithm details from the rest of the lexhash implementation (except cl_lexhash_check_grow, which re-implements the hashing algorithm for performance reasons).
Usage: entry = cl_lexhash_find_i(cl_lexhash hash, char *token, unsigned int *ret_offset);
Parameters
hash The hash to search.
token The key-string to look for.
ret_offset This integer address will be filled with the token's hashtable offset (can be NULL, in which case, ignored).
Returns
The entry that is found (or NULL if the string is not in the hash).
References _cl_lexhash::buckets, cl_hash_string(), _cl_lexhash_entry::key, _cl_lexhash_entry::next, _cl_lexhash::table, and token.
Referenced by cl_lexhash_add(), cl_lexhash_del(), cl_lexhash_find(), cl_lexhash_freq(), and cl_lexhash_id().
cl_lexhash_freq()
int cl_lexhash_freq (cl_lexhash hash, char * token)
Gets the frequency of a particular string within a lexhash.
Parameters
hash The hash to look in.
token The string to look for.
Returns
The frequency of that string, or 0 if the string is not in the hash (whgich is, of course, actually its frequency).
References cl_lexhash_find_i(), _cl_lexhash_entry::freq, and token.
Referenced by main(), and s_att_open_range().
cl_lexhash_id()
int cl_lexhash_id (cl_lexhash hash, char * token)
Gets the ID of a particular string within a lexhash.
Note this is the ID integer that identifies THAT PARTICULAR STRING, not the hash value of that string - which only identifies the bucket the string is found in!
Parameters
hash The hash to look in.
token The string to look for.
Returns
The ID code of that string, or -1 if the string is not in the hash.
References cl_lexhash_find_i(), _cl_lexhash_entry::id, and token.
Referenced by encode_add_p_attr_line(), and s_att_declare().
cl_lexhash_iterator_next()
cl_lexhash_entry cl_lexhash_iterator_next (cl_lexhash hash)
Gets the next entry from the hash's entry-iterator.
This function returns the next entry from the hash, or NULL if there are no more entries. Keep in mind that the hash is traversed in an unspecified order.
The iterator allows access over all the entries in a lexhash.
Note that there is only a single iterator for each cl_lexhash object, so different parts of the application code must not try to iterate through the hash at the same time.
Parameters
hash The lexhash to iterate over.
References _cl_lexhash::buckets, _cl_lexhash::iter_bucket, _cl_lexhash::iter_point, _cl_lexhash_entry::next, and _cl_lexhash::table.
cl_lexhash_iterator_reset()
void cl_lexhash_iterator_reset (cl_lexhash hash)
Resets a lexhash's entry-iterator to the start of the hash.
The iterator allows access over all entries in a lexhash.
Note that there is only a single iterator for each cl_lexhash object, so different parts of the application code must not try to iterate through the hash at the same time.
Parameters
hash The lexhash to iterate over.
References _cl_lexhash::buckets, _cl_lexhash::iter_bucket, _cl_lexhash::iter_point, and _cl_lexhash::table.
cl_lexhash_set_cleanup_function()
void cl_lexhash_set_cleanup_function (cl_lexhash hash, cl_lexhash_cleanup_func func)
Sets the cleanup function for a cl_lexhash.
The cleanup function is called with a cl_lexhash_entry argument; it should delete any objects assocated with the entry's data field.
The cleanup function is initially set to NULL, i.e. run no function.
Parameters
hash The cl_lexhash to work with.
func Pointer to the function to use for cleanup.
References _cl_lexhash::cleanup_func, and func.
cl_lexhash_size()
int cl_lexhash_size (cl_lexhash hash)
Gets the number of different strings stored in a lexhash.
This returns the total number of entries in all the buckets in the whole hash table.
Parameters
hash The hash to size up.
References _cl_lexhash::entries.
cl_new_lexhash()
cl_lexhash cl_new_lexhash (int buckets)
Creates a new cl_lexhash object.
Parameters
buckets The number of buckets in the newly-created cl_lexhash; set to 0 to use the default number of buckets.
Returns
The new cl_lexhash.
References _cl_lexhash::auto_grow, _cl_lexhash::buckets, cl_calloc(), cl_find_prime(), cl_malloc(), _cl_lexhash::cleanup_func, DEFAULT_FILLRATE_LIMIT, DEFAULT_FILLRATE_TARGET, DEFAULT_NR_OF_BUCKETS, _cl_lexhash::entries, _cl_lexhash::fillrate_limit, _cl_lexhash::fillrate_target, _cl_lexhash::iter_bucket, _cl_lexhash::iter_point, _cl_lexhash::next_id, and _cl_lexhash::table.
Referenced by cl_lexhash_check_grow(), main(), p_att_declare(), s_att_declare(), and sencode_write_region().