CWB: cqp/llquery.c File Reference
llquery.c File Reference
This file contains the main function for CQP (interactive loop)
#include <stdio.h>
#include <signal.h>
#include "../cl/cl.h"
#include "cqp.h"
#include "eval.h"
#include "options.h"
#include "macro.h"
#include "variables.h"
#include "concordance.h"
#include "output.h"
#include "ascii-print.h"
Functions
int main (int argc, char *argv[])
Main function for the interactive CQP program.
Detailed Description
This file contains the main function for CQP (interactive loop)
In addition, it contains the functions that interactive CQP will need if command-line editing with GNU Readline is enabled.
Function Documentation
main()
int main (int argc, char * argv[])
Main function for the interactive CQP program.
Doesn't do much except call the initialisation function, and then one of the loop-and-parse-input functions.
Parameters
argc Number of commandline arguments.
argv Pointer to commandline arguments.
Returns
Return value to OS.
References batchfh, batchmode, child_process, cqp, cqp_cleanup_memory(), cqp_error_status, cqp_parse_file(), CWB_VERSION, get_colour_escape(), get_typeface_escape(), initialize_cqp(), install_signal_handler(), macro_debug, macro_statistics(), save_on_exit, save_unsaved_subcorpora(), use_colour, and use_readline.