CWB: CQi/log.c File Reference
log.c File Reference
Functions that encapsulate CQi / CQPserver logging and printing of debug messages.
#include <stdio.h>
#include <stdarg.h>
#include "../cl/cl.h"
#include "../cl/cwb-globals.h"
#include "../cqp/output.h"
#include "../cqp/options.h"
#include "cqi.h"
Functions
void cqiserver_welcome (void)
Prints the CQi server welcome and copyright message.
int cqiserver_log (MessageType msg_type, const char *msg,...)
Prints a message to log (if logging enabled); if the message is an error, or debugging is switched on, also prints to stderr.
void cqiserver_snoop (const char *format,...)
Print network communication snooping info on stderr (if global "snoop" option is true).
const char * cqiserver_debug_arglist (const char *arg_list, int n_args, int int_args)
Support function for calling cqiserver_debug_msg; stringifies a variable-length array of int/string arguments for presentation.
void cqiserver_debug_msg (const char *format,...)
Print server debug message on stderr (if global "server_debug" option is true).
Detailed Description
Functions that encapsulate CQi / CQPserver logging and printing of debug messages.
Function Documentation
cqiserver_debug_arglist()
const char* cqiserver_debug_arglist (const char * arg_list, int n_args, int int_args)
Support function for calling cqiserver_debug_msg; stringifies a variable-length array of int/string arguments for presentation.
Parameters
arg_list Array of char pointers or ints. The parameter is a pointer-to-byte, so a typecast may be needed in the call.
n_args Number of entries in arg_list.
int_args Boolean: if true, arguments are treted as integers; if false, as strings.
Returns
String with space-delimited argument list (internal buffer, do not alter or free). If the list is empty, the string returned is just a space.
References buf, CL_MAX_LINE_LENGTH, and server_debug.
Referenced by do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), do_cqi_cl_str2id(), and do_cqi_cl_struc2str().
cqiserver_debug_msg()
void cqiserver_debug_msg (const char * format, ...)
Print server debug message on stderr (if global "server_debug" option is true).
Parameters
format A printf-style formatting string. Must be followed by values to satisfy each specifier in the striong.
References server_debug.
Referenced by accept_connection(), cqi_activate_corpus(), cqi_lookup_attribute(), cqi_read_command(), do_cqi_cl_alg2cpos(), do_cqi_cl_attribute_size(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_drop_attribute(), do_cqi_cl_id2cpos(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), do_cqi_cl_lexicon_size(), do_cqi_cl_regex2id(), do_cqi_cl_str2id(), do_cqi_cl_struc2cpos(), do_cqi_cl_struc2str(), do_cqi_corpus_attributes(), do_cqi_corpus_charset(), do_cqi_corpus_full_name(), do_cqi_corpus_list_corpora(), do_cqi_corpus_properties(), do_cqi_corpus_structural_attribute_has_values(), do_cqi_cqp_drop_subcorpus(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), do_cqi_cqp_query(), do_cqi_cqp_subcorpus_has_field(), do_cqi_cqp_subcorpus_size(), interpreter(), and send_cl_error().
cqiserver_log()
int cqiserver_log (MessageType msg_type, const char * msg, ...)
Prints a message to log (if logging enabled); if the message is an error, or debugging is switched on, also prints to stderr.
Note that we only distinguish between "Error" and "anything else" in terms of MessageType; it's recommended to pass Info if the message is not an error.
Returns
Boolean. True if msg_type was Error, otherwise false (caller can use this as anexit() argument if none other is available)
References Error, server_debug, and server_log.
Referenced by accept_connection(), cqi_internal_error(), cqi_recv_error(), cqi_send_error(), cqiserver_internal_error(), cqiserver_unknown_command_error(), cqiserver_wrong_command_error(), do_cqi_cqp_query(), main(), and send_cl_error().
cqiserver_snoop()
void cqiserver_snoop (const char * format, ...)
Print network communication snooping info on stderr (if global "snoop" option is true).
Parameters
format A printf-style formatting string. Must be followed by values to satisfy each specifier in the striong.
References snoop.
Referenced by cqi_flush(), cqi_read_bool_list(), cqi_read_byte_list(), cqi_read_int(), cqi_read_int_list(), cqi_read_string(), cqi_read_string_list(), cqi_read_word(), cqi_recv_byte(), cqi_recv_bytes(), cqi_send_byte(), cqi_send_int(), cqi_send_string(), and cqi_send_word().
cqiserver_welcome()
void cqiserver_welcome (void)
Prints the CQi server welcome and copyright message.
References CQI_MAJOR_VERSION, CQI_MINOR_VERSION, CWB_VERSION, and server_log.
Referenced by main().