CWB: cqp/macro.h File Reference
macro.h File Reference
Macros
#define MACRO_FILE_MAX_LINE_LENGTH CL_MAX_LINE_LENGTH
The maximum length of a line in a macro definition file.
Typedefs
typedef struct InputBuffer * InputBuffer
Buffer which stores input strings while parsing a macro.
Functions
int yy_input_char (void)
Get a character for the lexer/parser.
void init_macros (void)
Initialises the macro database: creates the storage hash and defines built-in macros.
void drop_macros (void)
Cleanup the macro database.
int define_macro (char *name, int n_args, char *argstr, char *definition)
Define a new macro.
void load_macro_file (const char *name)
Loads the content of a macro definition file and creates the macros therein.
int expand_macro (const char *name)
Expand a macro.
int delete_macro_buffers (int trace)
Delete active macro input buffers created by macro expansion.
void macro_iterator_reset (void)
Initialise, or reset, the macro database iterator, by setting the tracking variables to the beginning of the database table.
char * macro_iterator_next_prototype (const char *prefix)
Get the next macro from the iterator (returned as formatted prototype in a string).
void list_macros (const char *prefix)
Print a list of all defined macros to stdout.
void print_macro_definition (const char *name, const int n_args)
Print the definition of a given macro on stdout.
void macro_statistics (void)
Prints macro hash statistics on stderr.
Variables
InputBuffer InputBufferList
Head of linked list of active input buffers (for the macro system).
Macro Definition Documentation
MACRO_FILE_MAX_LINE_LENGTH
#define MACRO_FILE_MAX_LINE_LENGTH CL_MAX_LINE_LENGTH
The maximum length of a line in a macro definition file.
As of 3.2.x, to simplify things, this is the same as CL_MAX_LINE_LENGTH.
Typedef Documentation
InputBuffer
typedef struct InputBuffer* InputBuffer
Buffer which stores input strings while parsing a macro.
Function Documentation
define_macro()
int define_macro (char * name, int n_args, char * argstr, char * definition)
Define a new macro.
Parameters
name macro name
n_args # of arguments (0 .. 9); alternatively, specify argstr.
argstr macro argument string (e.g. `‘$0=name $1=label’') (pass NULL to use args)
definition The macro definition ... this string is substituted for /name; $0 .. $9 refer to the macro's arguments and CANNOT be escaped
Returns
Boolean: true if macro definition was successful, false on syntax error.
References _MacroSegment::arg, _MacroEntry::argnames, cl_malloc(), cqpmessage(), Error, MACRO_MAX_ARGS, MacroAddSegment(), MacroHashAdd(), MacroHashDelete(), MacroHashLookup(), silent, and _MacroSegment::string.
Referenced by init_macros(), and load_macro_file().
delete_macro_buffers()
int delete_macro_buffers (int trace)
Delete active macro input buffers created by macro expansion.
This function is used when synchronizing after a parse error.
Parameters
trace Boolean: if true, a stack trace for the input buffers will be printed to stderr under the heading "MACRO STACK TRACE".
Returns
Number of input buffers that have been deleted.
References _MacroEntry::args, InputBuffer::data, InputBufferList, InputBuffer::macro, _MacroEntry::name, PopInputBuffer(), and InputBuffer::position.
Referenced by cqp_parse_file().
drop_macros()
void drop_macros (void)
Cleanup the macro database.
References cl_free, FreeMacroEntry(), MacroHashTable::hash, MacroHash, _MacroEntry::next, and MacroHashTable::size.
Referenced by cqp_cleanup_memory().
expand_macro()
int expand_macro (const char * name)
Expand a macro.
This function:
reads the macro argument list using yylex();
looks up the macro by its [name] and number of arguments;
pushes an input buffer containing the subsituted string onto the top of the input buffer list.
It's only called by the lexer (as the resulting macro string has to go through the parser).
Parameters
name The name of the macro to be looked up.
Returns
Boolean true for OK, false if macro is not defined or if there is a syntax error in the argument list.
References _MacroEntry::active, _MacroSegment::arg, buf, cl_free, cl_strcpy(), cl_strdup(), cqpmessage(), InputBuffer::data, Error, InputBufferList, InputBuffer::macro, macro_arg, macro_debug, macro_debug_newline_indent(), MACRO_MAX_ARGS, MacroHashLookup(), _MacroSegment::next, pseudo_arg_counter, PushInputBuffer(), _MacroEntry::replacement, _MacroSegment::string, token, yylex(), and yytext.
init_macros()
void init_macros (void)
Initialises the macro database: creates the storage hash and defines built-in macros.
References cqpmessage(), define_macro(), Error, InitialiseMacroHash(), and MACRO_HASH_BUCKETS.
Referenced by initialize_cqp().
list_macros()
void list_macros (const char * prefix)
Print a list of all defined macros to stdout.
Parameters
prefix If a prefix is passed, only macros whose name begins with that prefix will be printed. Pass NULL for no prefix.
References _MacroEntry::args, cl_free, cl_malloc(), enable_macros, MacroHashTable::hash, ilist_end(), ilist_print_break(), ilist_print_item(), ilist_start(), list_macros_sort(), MacroHash, _MacroEntry::name, _MacroEntry::next, pretty_print, and MacroHashTable::size.
load_macro_file()
void load_macro_file (const char * filename)
Loads the content of a macro definition file and creates the macros therein.
FORMAT: MACRO [name]([numargs]) [macro_definition] ; ... line comments starting with '#' are automatically removed, as is any whitespace at the start or end of a line; blanks are inserted between the lines of a multi-line macro definition
Parameters
filename File to process.
References cl_free, cl_realloc(), cl_str_is, cl_strdup(), cqpmessage(), define_macro(), Error, input_line, line, MACRO_FILE_MAX_LINE_LENGTH, parse_macro_name(), and preprocess_input_line().
macro_iterator_next_prototype()
char* macro_iterator_next_prototype (const char * prefix)
Get the next macro from the iterator (returned as formatted prototype in a string).
Parameters
prefix Optional macro-name-prefix; if specified, iterator will pass over non-matching macros; pass NULL to leave unspecified.
Returns
Prototype of the next macro (matching [prefix] if specified); or NULL at the end of the macro database, or if macros are disabled or not initialised. The returned string is newly allocated, and should be freed by the caller.
References _MacroEntry::argnames, _MacroEntry::args, cl_malloc(), macro_iterator_seek(), and _MacroEntry::name.
macro_iterator_reset()
void macro_iterator_reset (void)
Initialise, or reset, the macro database iterator, by setting the tracking variables to the beginning of the database table.
It does this by setting module-global tracking variables, iterator_bucket and iterator_entry, to their initial values (so the next call to the macro iterator will return the first macro).
References iterator_bucket, and iterator_entry.
macro_statistics()
void macro_statistics (void)
Prints macro hash statistics on stderr.
This function is called by CQP if MacroDebug is activated.
References MacroHashTable::hash, MacroHash, _MacroEntry::next, and MacroHashTable::size.
Referenced by main().
print_macro_definition()
void print_macro_definition (const char * name, const int n_args)
Print the definition of a given macro on stdout.
The macro is specified by its name and number of arguments.
Parameters
name Name of the macro to print.
n_args Number of arguments of the macro to print.
References _MacroSegment::arg, _MacroEntry::argnames, cqpmessage(), enable_macros, Error, MacroHashLookup(), _MacroSegment::next, _MacroEntry::replacement, and _MacroSegment::string.
yy_input_char()
int yy_input_char (void)
Get a character for the lexer/parser.
This function reads one character (byte) of input from InputBufferList[top], ... , InputBufferList[bottom], cqp_input_string, yyin in that order of precedence.
It adds the character to query buffer, and returns it.
Used by the lexer to get its characters; see parser.l where YY_INPUT() is defined to call this function.
This function is in this file because it accesses the variables associated with CQP-macro input buffering.
References buf, cqp_input_string, cqp_input_string_ix, cqpmessage(), InputBufferList, macro_debug, macro_debug_newline_indent(), PopInputBuffer(), QUERY_BUFFER_SIZE, QueryBuffer, QueryBufferOverflow, QueryBufferP, reading_cqprc, Warning, write_history_file, and yyin.
Variable Documentation
InputBufferList
InputBuffer InputBufferList extern
Head of linked list of active input buffers (for the macro system).
This is exported because cqp.c needs access to the InputBufferList, to make it possible to back up & suspend the macro expansion buffers while EXEC'ing another CQP script.
Referenced by cqp_parse_file(), delete_macro_buffers(), expand_macro(), macro_debug_newline_indent(), PopInputBuffer(), PushInputBuffer(), and yy_input_char().