CWB: cqp/macro.c File Reference
macro.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "../cl/cl.h"
#include "../cl/ui-helpers.h"
#include "macro.h"
#include "options.h"
#include "output.h"
#include "cqp.h"
#include "eval.h"
#include "ranges.h"
#include "targets.h"
#include "corpmanag.h"
#include "parser.tab.h"
Data Structures
struct InputBuffer
Buffer which stores input strings while parsing a macro.
struct _MacroSegment
The macro replacement string is stored as a sequence of segments:
struct _MacroEntry
An entry in the macro database.
struct MacroHashTable
The MacroHashTable is the type of the object which stores the macro database.
Macros
#define MACRO_HASH_BUCKETS 8000
#define MACRO_MAX_ARGS 10
#define hash_macro(macro_name, n_args) cl_hash_string_with_init(macro_name, n_args)
Creates a 32 bit hash value of a CQP macro (using both the macro name and its number of arguments, so that two macros with the same name but different parameter signatures will not hash the same).
Typedefs
typedef struct _MacroSegment * MacroSegment
The macro replacement string is stored as a sequence of segments:
typedef struct _MacroEntry * MacroEntry
An entry in the macro database.
typedef struct MacroHashTable * MacroHashTable
The MacroHashTable is the type of the object which stores the macro database.
Functions
int yylex (void)
flex caller function
static void macro_debug_newline_indent (void)
indent macro expansion debugging output (according to number of active input buffers)
static InputBuffer PushInputBuffer (int size)
push new input buffer (which can hold string of length [size]) onto the top of buffer list
static void PopInputBuffer (void)
delete input buffer from top of list
static void InitialiseMacroHash (int size)
Initialises the global macro hash; see init_macros() for how it's used.
static MacroEntry MacroHashLookup (const char *str, int args)
find hash entry; returns MacroEntry or NULL if not in hash
static MacroEntry MacroHashAdd (const char *str, int n_args)
Add a macro to the hash.
static void FreeMacroEntry (MacroEntry macro)
release memory from a MacroEntry object.
static void MacroHashDelete (MacroEntry macro)
remove macro from hash ...
static MacroSegment MacroAddSegment (MacroEntry macro)
append segment to macro replacement string, returns pointer to the new, initialised segment
int yy_input_char (void)
Get a character for the lexer/parser.
void init_macros (void)
Initialises the macro database: creates the storage hash and defines built-in macros.
void drop_macros (void)
Cleanup the macro database.
int expand_macro (const char *name)
Expand a macro.
int define_macro (char *name, int n_args, char *argstr, char *definition)
Define a new macro.
static char * preprocess_input_line (char *line)
internal function for load_macro_file(): remove whitespace & comments from input line
static char * parse_macro_name (char *text, int *nr_of_args, char **prototype)
Internal function for load_macro_file(): parse macro name & number of arguments.
void load_macro_file (const char *filename)
Loads the content of a macro definition file and creates the macros therein.
int delete_macro_buffers (int trace)
Delete active macro input buffers created by macro expansion.
void macro_iterator_reset (void)
Initialise, or reset, the macro database iterator, by setting the tracking variables to the beginning of the database table.
static MacroEntry macro_iterator_seek (const char *prefix)
Internal iterator function used by macro_iterator_next() and macro_iterator_next_prototype().
char * macro_iterator_next_prototype (const char *prefix)
Get the next macro from the iterator (returned as formatted prototype in a string).
static int list_macros_sort (const void *p1, const void *p2)
internal function comparing two macros to get their sort order for qsort()
void list_macros (const char *prefix)
Print a list of all defined macros to stdout.
void print_macro_definition (const char *name, const int n_args)
Print the definition of a given macro on stdout.
void macro_statistics (void)
Prints macro hash statistics on stderr.
Variables
FILE * yyin
flex input when parsing file
char * yytext
InputBuffer InputBufferList = NULL
Head of linked list of active input buffers (for the macro system).
static MacroHashTable MacroHash = NULL
Global macro database.
char * macro_arg [MACRO_MAX_ARGS] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
macro args are stored in a global array so we can always free() the memory
unsigned int pseudo_arg_counter = 0
unique number for pseudo argument in each macro call
static int iterator_bucket = -1
Current bucket in the macro iterator.
static MacroEntry iterator_entry = NULL
Current entry in the current bucket of the macro iterator (on iterator increment, if NULL, go to next bucket).
Macro Definition Documentation
hash_macro
#define hash_macro (macro_name, n_args) cl_hash_string_with_init(macro_name, n_args)
Creates a 32 bit hash value of a CQP macro (using both the macro name and its number of arguments, so that two macros with the same name but different parameter signatures will not hash the same).
MACRO_HASH_BUCKETS
#define MACRO_HASH_BUCKETS 8000
MACRO_MAX_ARGS
#define MACRO_MAX_ARGS 10
Typedef Documentation
MacroEntry
typedef struct _MacroEntry * MacroEntry
An entry in the macro database.
MacroHashTable
typedef struct MacroHashTable * MacroHashTable
The MacroHashTable is the type of the object which stores the macro database.
This hash implementation can hold multiple macro entries in a single bucket in order to avoid cache overflow when very many macros are defined. Since we don't need to store any other information in the buckets, a bucket is simply a pointer to a list of macro entries, i.e. a MacroEntry.
See also
MacroHash
MacroSegment
typedef struct _MacroSegment * MacroSegment
The macro replacement string is stored as a sequence of segments:
literal text ... string = "...", arg = -1 argument ... string = NULL, arg = 0 .. 9 pseudo arg ... string = NULL, arg = -1
A linked list of these defines the macro's replacement.
Function Documentation
define_macro()
int define_macro (char * name, int n_args, char * argstr, char * definition)
Define a new macro.
Parameters
name macro name
n_args # of arguments (0 .. 9); alternatively, specify argstr.
argstr macro argument string (e.g. `‘$0=name $1=label’') (pass NULL to use args)
definition The macro definition ... this string is substituted for /name; $0 .. $9 refer to the macro's arguments and CANNOT be escaped
Returns
Boolean: true if macro definition was successful, false on syntax error.
References _MacroSegment::arg, _MacroEntry::argnames, cl_malloc(), cqpmessage(), Error, MACRO_MAX_ARGS, MacroAddSegment(), MacroHashAdd(), MacroHashDelete(), MacroHashLookup(), silent, and _MacroSegment::string.
Referenced by init_macros(), and load_macro_file().
delete_macro_buffers()
int delete_macro_buffers (int trace)
Delete active macro input buffers created by macro expansion.
This function is used when synchronizing after a parse error.
Parameters
trace Boolean: if true, a stack trace for the input buffers will be printed to stderr under the heading "MACRO STACK TRACE".
Returns
Number of input buffers that have been deleted.
References _MacroEntry::args, InputBuffer::data, InputBufferList, InputBuffer::macro, _MacroEntry::name, PopInputBuffer(), and InputBuffer::position.
Referenced by cqp_parse_file().
drop_macros()
void drop_macros (void)
Cleanup the macro database.
References cl_free, FreeMacroEntry(), MacroHashTable::hash, MacroHash, _MacroEntry::next, and MacroHashTable::size.
Referenced by cqp_cleanup_memory().
expand_macro()
int expand_macro (const char * name)
Expand a macro.
This function:
reads the macro argument list using yylex();
looks up the macro by its [name] and number of arguments;
pushes an input buffer containing the subsituted string onto the top of the input buffer list.
It's only called by the lexer (as the resulting macro string has to go through the parser).
Parameters
name The name of the macro to be looked up.
Returns
Boolean true for OK, false if macro is not defined or if there is a syntax error in the argument list.
References _MacroEntry::active, _MacroSegment::arg, buf, cl_free, cl_strcpy(), cl_strdup(), cqpmessage(), InputBuffer::data, Error, InputBufferList, InputBuffer::macro, macro_arg, macro_debug, macro_debug_newline_indent(), MACRO_MAX_ARGS, MacroHashLookup(), _MacroSegment::next, pseudo_arg_counter, PushInputBuffer(), _MacroEntry::replacement, _MacroSegment::string, token, yylex(), and yytext.
FreeMacroEntry()
static void FreeMacroEntry (MacroEntry macro) static
release memory from a MacroEntry object.
References _MacroEntry::argnames, cl_free, MACRO_MAX_ARGS, _MacroEntry::name, _MacroSegment::next, _MacroEntry::replacement, and _MacroSegment::string.
Referenced by drop_macros(), and MacroHashDelete().
init_macros()
void init_macros (void)
Initialises the macro database: creates the storage hash and defines built-in macros.
References cqpmessage(), define_macro(), Error, InitialiseMacroHash(), and MACRO_HASH_BUCKETS.
Referenced by initialize_cqp().
InitialiseMacroHash()
static void InitialiseMacroHash (int size) static
Initialises the global macro hash; see init_macros() for how it's used.
References cl_find_prime(), cl_malloc(), MacroHashTable::hash, MacroHash, and MacroHashTable::size.
Referenced by init_macros().
list_macros()
void list_macros (const char * prefix)
Print a list of all defined macros to stdout.
Parameters
prefix If a prefix is passed, only macros whose name begins with that prefix will be printed. Pass NULL for no prefix.
References _MacroEntry::args, cl_free, cl_malloc(), enable_macros, MacroHashTable::hash, ilist_end(), ilist_print_break(), ilist_print_item(), ilist_start(), list_macros_sort(), MacroHash, _MacroEntry::name, _MacroEntry::next, pretty_print, and MacroHashTable::size.
list_macros_sort()
static int list_macros_sort (const void * p1, const void * p2) static
internal function comparing two macros to get their sort order for qsort()
Referenced by list_macros().
load_macro_file()
void load_macro_file (const char * filename)
Loads the content of a macro definition file and creates the macros therein.
FORMAT: MACRO [name]([numargs]) [macro_definition] ; ... line comments starting with '#' are automatically removed, as is any whitespace at the start or end of a line; blanks are inserted between the lines of a multi-line macro definition
Parameters
filename File to process.
References cl_free, cl_realloc(), cl_str_is, cl_strdup(), cqpmessage(), define_macro(), Error, input_line, line, MACRO_FILE_MAX_LINE_LENGTH, parse_macro_name(), and preprocess_input_line().
macro_debug_newline_indent()
static void macro_debug_newline_indent (void) static
indent macro expansion debugging output (according to number of active input buffers)
References buf, and InputBufferList.
Referenced by expand_macro(), and yy_input_char().
macro_iterator_next_prototype()
char* macro_iterator_next_prototype (const char * prefix)
Get the next macro from the iterator (returned as formatted prototype in a string).
Parameters
prefix Optional macro-name-prefix; if specified, iterator will pass over non-matching macros; pass NULL to leave unspecified.
Returns
Prototype of the next macro (matching [prefix] if specified); or NULL at the end of the macro database, or if macros are disabled or not initialised. The returned string is newly allocated, and should be freed by the caller.
References _MacroEntry::argnames, _MacroEntry::args, cl_malloc(), macro_iterator_seek(), and _MacroEntry::name.
macro_iterator_reset()
void macro_iterator_reset (void)
Initialise, or reset, the macro database iterator, by setting the tracking variables to the beginning of the database table.
It does this by setting module-global tracking variables, iterator_bucket and iterator_entry, to their initial values (so the next call to the macro iterator will return the first macro).
References iterator_bucket, and iterator_entry.
macro_iterator_seek()
static MacroEntry macro_iterator_seek (const char * prefix) static
Internal iterator function used by macro_iterator_next() and macro_iterator_next_prototype().
Parameters
prefix A string prefix; if not NULL, macros that don't match will be skipped.
Returns
Next MacroEntry; if macros are disabled or not initialised, NULL; NULL will also be returned if the iterator gets to the end of the table of macros.
References enable_macros, MacroHashTable::hash, iterator_bucket, iterator_entry, MacroHash, _MacroEntry::name, _MacroEntry::next, and MacroHashTable::size.
Referenced by macro_iterator_next_prototype().
macro_statistics()
void macro_statistics (void)
Prints macro hash statistics on stderr.
This function is called by CQP if MacroDebug is activated.
References MacroHashTable::hash, MacroHash, _MacroEntry::next, and MacroHashTable::size.
Referenced by main().
MacroAddSegment()
static MacroSegment MacroAddSegment (MacroEntry macro) static
append segment to macro replacement string, returns pointer to the new, initialised segment
References _MacroSegment::arg, cl_malloc(), _MacroSegment::next, _MacroEntry::replacement, and _MacroSegment::string.
Referenced by define_macro().
MacroHashAdd()
static MacroEntry MacroHashAdd (const char * str, int n_args) static
Add a macro to the hash.
NB if you add a macro key that is already in the hash, the new entry will hide the old one, in accordance with the macro redefinition strategy.
(Macro keys are defined deterministically from the macro's name and number of arguments.)
Parameters
str The string for the macro's name.
n_args The number of arguments the macro has.
Returns
The new MacroEntry.
References _MacroEntry::active, _MacroEntry::argnames, _MacroEntry::args, cl_malloc(), cl_strdup(), cqpmessage(), Error, MacroHashTable::hash, hash_macro, MACRO_MAX_ARGS, MacroHash, _MacroEntry::name, _MacroEntry::next, _MacroEntry::replacement, and MacroHashTable::size.
Referenced by define_macro().
MacroHashDelete()
static void MacroHashDelete (MacroEntry macro) static
remove macro from hash ...
this is worse than you'd think at first
References _MacroEntry::args, cqp_error_status, cqpmessage(), Error, FreeMacroEntry(), MacroHashTable::hash, hash_macro, MacroHash, _MacroEntry::name, _MacroEntry::next, and MacroHashTable::size.
Referenced by define_macro().
MacroHashLookup()
static MacroEntry MacroHashLookup (const char * str, int args) static
find hash entry; returns MacroEntry or NULL if not in hash
References _MacroEntry::args, cl_streq, cqpmessage(), Error, MacroHashTable::hash, hash_macro, MacroHash, _MacroEntry::name, _MacroEntry::next, and MacroHashTable::size.
Referenced by define_macro(), expand_macro(), and print_macro_definition().
parse_macro_name()
static char* parse_macro_name (char * text, int * nr_of_args, char ** prototype) static
Internal function for load_macro_file(): parse macro name & number of arguments.
expected format: [whitespace] [identifier] '(' [digit] ')' -> sets nr_of_args, prototype = NULL or: [whitespace] [identfifier] '(' [prototype] ')' -> nr_of_args = 0, prototype = copy of [prototype]
Returns
Pointer to copy of [identifier] or NULL on parse error
References cl_malloc().
Referenced by load_macro_file().
PopInputBuffer()
static void PopInputBuffer (void) static
delete input buffer from top of list
References _MacroEntry::active, cl_free, InputBuffer::data, InputBufferList, InputBuffer::macro, and InputBuffer::next.
Referenced by delete_macro_buffers(), and yy_input_char().
preprocess_input_line()
static char* preprocess_input_line (char * line) static
internal function for load_macro_file(): remove whitespace & comments from input line
References cl_string_chomp(), and line.
Referenced by load_macro_file().
print_macro_definition()
void print_macro_definition (const char * name, const int n_args)
Print the definition of a given macro on stdout.
The macro is specified by its name and number of arguments.
Parameters
name Name of the macro to print.
n_args Number of arguments of the macro to print.
References _MacroSegment::arg, _MacroEntry::argnames, cqpmessage(), enable_macros, Error, MacroHashLookup(), _MacroSegment::next, _MacroEntry::replacement, and _MacroSegment::string.
PushInputBuffer()
static InputBuffer PushInputBuffer (int size) static
push new input buffer (which can hold string of length [size]) onto the top of buffer list
References cl_malloc(), InputBuffer::data, InputBufferList, InputBuffer::macro, InputBuffer::next, and InputBuffer::position.
Referenced by expand_macro().
yy_input_char()
int yy_input_char (void)
Get a character for the lexer/parser.
This function reads one character (byte) of input from InputBufferList[top], ... , InputBufferList[bottom], cqp_input_string, yyin in that order of precedence.
It adds the character to query buffer, and returns it.
Used by the lexer to get its characters; see parser.l where YY_INPUT() is defined to call this function.
This function is in this file because it accesses the variables associated with CQP-macro input buffering.
References buf, cqp_input_string, cqp_input_string_ix, cqpmessage(), InputBufferList, macro_debug, macro_debug_newline_indent(), PopInputBuffer(), QUERY_BUFFER_SIZE, QueryBuffer, QueryBufferOverflow, QueryBufferP, reading_cqprc, Warning, write_history_file, and yyin.
yylex()
int yylex (void)
flex caller function
Referenced by expand_macro().
Variable Documentation
InputBufferList
InputBuffer InputBufferList = NULL
Head of linked list of active input buffers (for the macro system).
This is exported because cqp.c needs access to the InputBufferList, to make it possible to back up & suspend the macro expansion buffers while EXEC'ing another CQP script.
Referenced by cqp_parse_file(), delete_macro_buffers(), expand_macro(), macro_debug_newline_indent(), PopInputBuffer(), PushInputBuffer(), and yy_input_char().
iterator_bucket
int iterator_bucket = -1 static
Current bucket in the macro iterator.
-1 indicates we are right at the start.
See also
iterator_entry
macro_iterator_reset
Referenced by macro_iterator_reset(), and macro_iterator_seek().
iterator_entry
MacroEntry iterator_entry = NULL static
Current entry in the current bucket of the macro iterator (on iterator increment, if NULL, go to next bucket).
See also
iterator_bucket
macro_iterator_reset
Referenced by macro_iterator_reset(), and macro_iterator_seek().
macro_arg
char* macro_arg[MACRO_MAX_ARGS] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
macro args are stored in a global array so we can always free() the memory
Referenced by expand_macro().
MacroHash
MacroHashTable MacroHash = NULL static
Global macro database.
Referenced by drop_macros(), InitialiseMacroHash(), list_macros(), macro_iterator_seek(), macro_statistics(), MacroHashAdd(), MacroHashDelete(), and MacroHashLookup().
pseudo_arg_counter
unsigned int pseudo_arg_counter = 0
unique number for pseudo argument in each macro call
Referenced by expand_macro().
yyin
FILE* yyin extern
flex input when parsing file
Referenced by yy_input_char().
yytext
char* yytext extern
Referenced by expand_macro().