CWB: cqp/matchlist.c File Reference
matchlist.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "../cl/cl.h"
#include "../cl/attributes.h"
#include "matchlist.h"
#include "output.h"
#include "eval.h"
Functions
void init_matchlist (Matchlist *matchlist)
Initialise the memebrs of the given Matchlist object.
void show_matchlist (Matchlist matchlist)
Prints the entire contents of a Matchlist to stdout.
void show_matchlist_firstelements (Matchlist matchlist)
Prints the first few elements of a matchlist to stderr.
void free_matchlist (Matchlist *matchlist)
Frees all the memory used within a matchlist, and re-initialises all its variables; null-safe.
static void _swap_items (int *v, int a, int b)
int sort_matchlist (Matchlist *ml)
Sort a matchlist in canonical order, i.e.
int apply_setop_to_matchlist (Matchlist *list1, MLSetOp operation, Matchlist *list2)
Perform a "set operation" on the two match lists (can be initial).
Function Documentation
_swap_items()
static void _swap_items (int * v, int a, int b) static
Referenced by sort_matchlist().
apply_setop_to_matchlist()
int apply_setop_to_matchlist (Matchlist * list1, MLSetOp operation, Matchlist * list2)
Perform a "set operation" on the two match lists (can be initial).
This is the main functionality provided for Matchlist object. The result of the operation is written to list1, which is modified destructively and may be reallocated.
Parameters
list1 first or only argument of the operation, will be overwritten with the result
operation operation to apply; only Union, Reduce and Complement are properly supported and used by other CQP code so far
list2 optional second argument of the operation
Here Be Dragons
implementation of Intersection and Unique is dubious and likely buggy (and will produce wrong results for inverted matchlists)
Union, Intersection and Unique assume that the matchlists are sorted (by increasing start position, then increasing end position) and will produce incorrect results otherwise; this was not documented anywhere in the source code!
this sort order is different from the one used by RangeSort() (which sorts longer matches first given the same start point); it is quite unclear what the expected canonical sort order thus is for named query results, and which parts of the CQP code rely on a particular sort order
Union is used by CQP to combine results from multiple evaluation passes with different starting points (in finite-state queries); for each pass the matchlist is sorted appropriately (with start = match anchor increasing by definition, and only a single match possible for each start position, hence sorting by end = matchend anchor is irrelevant); building up the joint matchlist with Union ensures that it is also sorted correctly
if the FSA simulation is changed so that start points of matches can be out of order or there can be multiple matches with the same start point, the matchlist has to be sorted before further processing; if there could be duplicate matches (with identical start and end points) they should be discarded by an additional Uniq operation (as they might confuse other operations)
TODO: implement a suitable Sort operation and revise Uniq, or implement a join SortUniq operation, possibly as a separate function rather than yet another set operator; this should be relatively straightforward if we don't mind allocating new vectors rather than modifying the existing ones in place (at the cost of considerable memory overhead)
Some old notes:
TODO: this whole code is WRONG when one of the matchlists is inverted TODO: many operations expect that the matchlist(s) is/are consistently sorted, but don't specify the expected sort order
Fortunately, CQP only uses the operations Union, Reduce and Complement (only sensible for initial matchlists) so far, while Identity is used internally. Other operations may have been intended for matching the first pattern of a finite-state query with a MU-style algorithm, but clearly haven't been thought through at all.
References access_corpus(), ATT_POS, CDA_OK, cl_errno, cl_free, cl_malloc(), cl_max_cpos(), cl_new_attribute(), cl_realloc(), Complement, cl::corpus, CWB_DEFAULT_ATT_NAME, _Matchlist::end, free_matchlist(), Identity, Intersection, _Matchlist::is_inverted, _Matchlist::keyword_positions, _Matchlist::matches_whole_corpus, MIN, evalenv::query_corpus, Reduce, _Matchlist::start, _Matchlist::tabsize, _Matchlist::target_positions, Union, and Uniq.
Referenced by calculate_initial_matchlist(), calculate_initial_matchlist_1(), cqp_run_mu_query(), cqp_run_tab_query(), eval_mu_tree(), match_first_pattern(), run_standard_query_dfa(), and try_optimization().
free_matchlist()
void free_matchlist (Matchlist * matchlist)
Frees all the memory used within a matchlist, and re-initialises all its variables; null-safe.
References cl_free, _Matchlist::end, init_matchlist(), _Matchlist::keyword_positions, _Matchlist::start, and _Matchlist::target_positions.
Referenced by apply_setop_to_matchlist(), calculate_initial_matchlist_1(), check_alignment_constraints(), cqp_run_mu_query(), cqp_run_tab_query(), eval_mu_tree(), run_standard_query_dfa(), simulate(), and try_optimization().
init_matchlist()
void init_matchlist (Matchlist * matchlist)
Initialise the memebrs of the given Matchlist object.
References _Matchlist::end, _Matchlist::is_inverted, _Matchlist::keyword_positions, _Matchlist::matches_whole_corpus, _Matchlist::start, _Matchlist::tabsize, and _Matchlist::target_positions.
Referenced by calculate_initial_matchlist_1(), check_alignment_constraints(), cqp_run_mu_query(), cqp_run_tab_query(), eval_mu_tree(), free_matchlist(), run_standard_query_dfa(), and try_optimization().
show_matchlist()
void show_matchlist (Matchlist matchlist)
Prints the entire contents of a Matchlist to stdout.
References _Matchlist::end, _Matchlist::is_inverted, _Matchlist::keyword_positions, _Matchlist::start, _Matchlist::tabsize, and _Matchlist::target_positions.
Referenced by run_standard_query_dfa().
show_matchlist_firstelements()
void show_matchlist_firstelements (Matchlist matchlist)
Prints the first few elements of a matchlist to stderr.
"First few" equals up to 1000.
Only the start positions are printed.
References _Matchlist::start, and _Matchlist::tabsize.
Referenced by run_standard_query_dfa().
sort_matchlist()
int sort_matchlist (Matchlist * ml)
Sort a matchlist in canonical order, i.e.
by increasing start and end position.
The sort operation is carried out in-place, modifying the function argument. Currently, a bubblesort algorithm is used which doesn't need to allocate scratch memory. While it has bad worst-case complexity, the typical use case (reordering matches from a single pass of a finite-state query) will only contain a small number of local inversions (if any) and allows the bubblesort to stop early.
"Special" matchlist (i.e. initial matchlist without end positions, ml->is_inverted, ml->matches_while_corpus) are not allowed.
Parameters
ml matchlist to be sorted (must not be initial or inverted)
Returns
True if the sort operation was successful
References _swap_items(), cqpmessage(), _Matchlist::end, Error, False, _Matchlist::is_inverted, _Matchlist::keyword_positions, _Matchlist::matches_whole_corpus, _Matchlist::start, _Matchlist::tabsize, _Matchlist::target_positions, and True.
Referenced by run_standard_query_dfa().