CWB: cqp/output.h File Reference
output.h File Reference
#include <stdio.h>
#include "corpmanag.h"
#include "context_descriptor.h"
#include "print-modes.h"
Data Structures
struct Redir
The Redir structure: contains information about redirecting output to a file or pipe.
struct InputRedir
The InputRedir structure: contains information about redirecting input so it reads from a file or pipe.
struct _TabulationItem
TabulationItem object: contains the data structures needed by CQP's "tabulate" command.
Typedefs
typedef struct _TabulationItem * TabulationItem
TabulationItem object: contains the data structures needed by CQP's "tabulate" command.
typedef enum _msgtype MessageType
Enumeration specifying different types of redirectable (error) messages & warnings.
Enumerations
enum _msgtype { Error , Warning , Message , Info }
Enumeration specifying different types of redirectable (error) messages & warnings.
Functions
FILE * open_temporary_file (char *tmp_name_buffer)
Creates, and opens for text-mode write, a temporary file.
int open_rd_output_stream (struct Redir *rd, CorpusCharset charset)
Open the (output) stream within a Redir(ection) structure.
int close_rd_output_stream (struct Redir *rd)
Closes the (output) stream within a Redir structure.
int open_rd_input_stream (struct InputRedir *rd)
Opens the input stream within a InputRedir structure.
int close_rd_input_stream (struct InputRedir *rd)
Closes the input stream within a InputRedir structure.
void cat_listed_corpus (CorpusList *cl, struct Redir *dst, int first, int last, PrintMode mode)
Prints a "corpus", typically (some of) the matches of a query.
void print_concordance_body (CorpusList *cl, FILE *fd, int interactive, ContextDescriptor *cd, int first, int last, PrintMode mode)
Prints a concordance (with no header) based on the subcorpus supplied (as a CorpusList object called cl) onto the stream supplied.
void corpus_info (CorpusList *cl)
Outputs a blob of information on the specified cl, or its mother-corpus if it's a SUB.
void cqpmessage (MessageType type, const char *format,...)
Print a message to output (for instance a debug message).
void print_corpus_info_header (CorpusList *cl, FILE *stream, PrintMode mode, int force)
Prints something like a header for a concordance.
void free_tabulation_list (void)
Free the global list of tabulation items (before building a new one).
TabulationItem new_tabulation_item (void)
allocate and initialize new tabulation item
void append_tabulation_item (TabulationItem item)
append tabulation item to end of current list
int print_tabulation (CorpusList *cl, int first, int last, struct Redir *rd)
Tabulate specified query result, using settings from global list of tabulation items.
Variables
TabulationItem TabulationList
Global list of tabulation items for use with the "tabulate" operator.
Typedef Documentation
MessageType
typedef enum _msgtype MessageType
Enumeration specifying different types of redirectable (error) messages & warnings.
TabulationItem
typedef struct _TabulationItem * TabulationItem
TabulationItem object: contains the data structures needed by CQP's "tabulate" command.
Each TabulationItem defines a single column in the tabulation output. A since global linked-list of TabulationItems, whose head is stored as TabulationList, is used to hold the tabulation specification requested by the user.
Note that TabulationItem is typedefed as a pointer-to-structure.
See also
TabulationList
Enumeration Type Documentation
_msgtype
enum _msgtype
Enumeration specifying different types of redirectable (error) messages & warnings.
Enumerator
Error
error message (always displayed)
Warning
warning (not shown in silent mode)
Message
used for "-d VerboseParser" output only
Info
user information (not shown in silent mode)
Function Documentation
append_tabulation_item()
void append_tabulation_item (TabulationItem item)
append tabulation item to end of current list
References _TabulationItem::next, and TabulationList.
cat_listed_corpus()
void cat_listed_corpus (CorpusList * cl, struct Redir * dst, int first, int last, PrintMode mode)
Prints a "corpus", typically (some of) the matches of a query.
This function supports the "cat" command, i.e. it is the main "please print concordance" function.
(Not sure why it's called "catalog"; is this a pun on the cat keyword? – AH 2012-07-17) (I suspect that it's a misinterpretation of what "cat" stands for. – SE 2016-07-20) (I finally bit the bullet and renamed it from "catalog_corpus" to "cat_listed_corpus". – AH 2020-05-26)
The query is represented by a subcorpus (cl); only results [first]..[last]; will be printed; use (0,-1) for entire corpus.
See also
do_cat
Parameters
cl The record of the corpus/subcorpus/query to output.
dst Block of output redirection info; if NULL, default settings will be used.
first Offset of first match to print.
last Offset of last match to print.
mode Print mode to use.
References access_corpus(), CD, TCorpus::charset, close_rd_output_stream(), cl::corpus, cqpmessage(), Range::end, Error, False, GlobalPrintMode, GlobalPrintOptions, Redir::is_paging, Redir::mode, mode, Redir::name, open_rd_output_stream(), output_binary_ranges, print_concordance_body(), print_corpus_info_header(), PrintOptions::print_header, PrintASCII, PrintHTML, printNrMatches, cl::range, cl::size, Range::start, Redir::stream, True, and verify_context_descriptor().
Referenced by after_CorpusCommand(), and do_cat().
close_rd_input_stream()
int close_rd_input_stream (struct InputRedir * rd)
Closes the input stream within a InputRedir structure.
Parameters
rd The InputRedir stream to close.
Returns
True for all OK, false if closing did not work. If rd does not actually have an open stream, nothing is done, and that counts as a success.
References cl_close_stream(), and InputRedir::stream.
Referenced by do_undump().
close_rd_output_stream()
int close_rd_output_stream (struct Redir * rd)
Closes the (output) stream within a Redir structure.
If output was being sent to a pipe, SIGPIPE is set back to the SIG_IGN handler.
Parameters
rd The Redir stream to close.
Returns
True for all OK, false if closing did not work. If rd does not actually have an open stream, nothing is done, and that counts as a success.
References cl_close_stream(), Redir::is_paging, and Redir::stream.
Referenced by cat_listed_corpus(), corpus_info(), do_catString(), do_dump(), print_context_descriptor(), print_group(), print_tabulation(), and SortSubcorpus().
corpus_info()
void corpus_info (CorpusList * cl)
Outputs a blob of information on the specified cl, or its mother-corpus if it's a SUB.
References ascii, buf, TCorpus::charset, child_process, cl_charset_name(), cl_close_stream(), cl_corpus_property(), cl_first_corpus_property(), CL_MAX_LINE_LENGTH, cl_next_corpus_property(), cl_open_stream(), CL_STREAM_MAGIC, CL_STREAM_READ_BIN, close_rd_output_stream(), cl::corpus, cqpmessage(), findcorpus(), Info, TCorpus::info_file, cl::mother_name, cl::mother_size, cl::name, open_rd_output_stream(), TCorpusProperty::property, Redir::stream, SYSTEM, cl::type, unknown_charset, TCorpusProperty::value, and Warning.
Referenced by do_info().
cqpmessage()
void cqpmessage (MessageType type, const char * format, ...)
Print a message to output (for instance a debug message).
See also
MessageType
Parameters
type Specifies what type of message (messages of some types are not always printed)
format Format string (and ...) are passed as arguments to vfprintf().
References Error, Info, Message, silent, verbose_parser, and Warning.
Referenced by ActivateCorpus(), add_host_to_list(), add_hosts_in_subnet_to_list(), add_user_to_list(), addHistoryLine(), after_CorpusSetExpr(), ascii_print_concordance_line(), attach_subcorpus(), calculate_initial_matchlist_1(), call_predefined_function(), cat_listed_corpus(), check_alignment_constraints(), check_labels(), compute_grouping(), ComputeGroupExternally(), ComputeGroupInternally(), ComputePrintStructures(), corpus_info(), cqp_parse_string(), cqp_run_mu_query(), cqp_run_tab_query(), define_macro(), do_AddSubVariables(), do_AnchorPoint(), do_attribute_show(), do_cat(), do_catString(), do_cut(), do_delete_lines(), do_delete_lines_num(), do_Description(), do_dump(), do_exec(), do_flagged_re_variable(), do_flagged_string(), do_FunctionCall(), do_group(), do_IDReference(), do_LabelReference(), do_MatchSelector(), do_MUQuery(), do_mval_string(), do_NamedWfPattern(), do_OptDistance(), do_printVariableSize(), do_PrintVariableValue(), do_reduce(), do_RegionElement(), do_RelExpr(), do_save(), do_SearchPattern(), do_setop(), do_SetVariableValue(), do_SimpleVariableReference(), do_StandardQuery(), do_StringConstraint(), do_StructuralContext(), do_timing(), do_translate(), do_undump(), do_WordformPattern(), do_XMLTag(), duplicate_corpus(), ensure_corpus_size(), eval_bool(), evaluate_subset(), evaluate_target(), execute_side_effects(), expand_dataspace(), expand_macro(), field_type_to_name(), findcorpus(), get_leaf_value(), in_CorpusCommand(), in_UnnamedCorpusCommand(), init_macros(), initialize_cqp(), install_signal_handler(), load_corpusnames(), load_macro_file(), MacroHashAdd(), MacroHashDelete(), MacroHashLookup(), match_first_pattern(), mval_string_conversion(), open_rd_input_stream(), open_rd_output_stream(), OptimizeStringConstraint(), prepare_AlignmentConstraints(), prepare_do_subset(), prepare_parse(), prepare_Query(), print_concordance_body(), print_group(), print_macro_definition(), print_tabulation(), pt_validate_anchor(), RangeSort(), run_standard_query_dfa(), save_subcorpus(), save_unsaved_subcorpora(), set_reftab(), set_target(), SetVariableValue(), simulate(), sort_matchlist(), SortExternally(), SortSubcorpus(), SortSubcorpusRandomize(), string_to_strategy(), validate_integer_option_value(), Varref2IDList(), verify_context_descriptor(), VerifyVariable(), and yy_input_char().
free_tabulation_list()
void free_tabulation_list (void)
Free the global list of tabulation items (before building a new one).
References cl_free, and TabulationList.
Referenced by print_tabulation().
new_tabulation_item()
TabulationItem new_tabulation_item (void)
allocate and initialize new tabulation item
References ATT_NONE, cl_malloc(), and NoField.
open_rd_input_stream()
int open_rd_input_stream (struct InputRedir * rd)
Opens the input stream within a InputRedir structure.
Parameters
rd The Redir stream to open for input.
Returns
True for all OK, false if opening did not work.
References cl_close_stream(), cl_errno, cl_error_string(), cl_free, cl_malloc(), cl_open_stream(), CL_STREAM_MAGIC, CL_STREAM_MAGIC_NOPIPE, CL_STREAM_PIPE, CL_STREAM_READ, CL_STREAM_STDIO, cqpmessage(), Error, insecure, InputRedir::name, and InputRedir::stream.
Referenced by do_undump().
open_rd_output_stream()
int open_rd_output_stream (struct Redir * rd, CorpusCharset charset)
Open the (output) stream within a Redir(ection) structure.
If output is sent to a pipe, a signal handler for SIGPIPE is automatically installed and configured to set the global variable broken_pipe to True. Output functions should check this variable and abort if it is set. The signal handler is uninstalled when close_pipe is called, which may lead to undesired behaviour if multiple streams are open at the same time.
See also
CLStream
Parameters
rd Redir structure to be opened.
charset The charset to be used. Only has an effect if the stream to be opened is to an output pager.
Returns
True for success, false for failure.
References charset, cl_close_stream(), cl_errno, cl_error_string(), cl_open_stream(), cl_str_is, cl_strdup(), CL_STREAM_APPEND, CL_STREAM_MAGIC, CL_STREAM_MAGIC_NOPIPE, CL_STREAM_STDIO, CL_STREAM_WRITE, CQP_FALLBACK_PAGER, cqpmessage(), Error, False, insecure, Redir::is_paging, Redir::mode, mode, Redir::name, open_pager(), pager, paging, set_integer_option_value(), set_string_option_value(), Redir::stream, True, and Warning.
Referenced by cat_listed_corpus(), corpus_info(), do_catString(), do_dump(), print_context_descriptor(), print_group(), print_tabulation(), and SortSubcorpus().
open_temporary_file()
FILE* open_temporary_file (char * tmp_name_buffer)
Creates, and opens for text-mode write, a temporary file.
Temporary files have the form "cqp-tempfile.XXXXXX" (where XXXXXX = distinguishing letters) and are placed in the directory defined as TEMPDIR_PATH.
See also
TEMPDIR_PATH
TEMP_FILENAME_BUFSIZE
Parameters
tmp_name_buffer A pre-allocated buffer which will be overwritten with the name of the temporary file. This should be at least (strlen(TEMPDIR_PATH) + 20) bytes in size. If opening is unsuccessful, this buffer will be set to "".
Returns
A stream (FILE *) to the opened temporary file, or NULL if unsuccessful.
References cl_strcpy(), SUBDIR_SEP_STRING, and TEMPDIR_PATH.
Referenced by ComputeGroupExternally(), and SortExternally().
print_concordance_body()
void print_concordance_body (CorpusList * cl, FILE * stream, int interactive, ContextDescriptor * cd, int first, int last, PrintMode mode)
Prints a concordance (with no header) based on the subcorpus supplied (as a CorpusList object called cl) onto the stream supplied.
This function does not do much itself - it dispatches to another specialised function based on the mode argument.
It's also that delegate function which checks the validity of the range of ranges within the subcorpus specified by7
See also
PrintMode
Parameters
cl
stream
interactive
cd
first
last
mode
References ascii_print_output(), cqpmessage(), Error, html_print_output(), latex_print_output(), mode, PrintASCII, PrintHTML, PrintLATEX, PrintSGML, and sgml_print_output().
Referenced by cat_listed_corpus().
print_corpus_info_header()
void print_corpus_info_header (CorpusList * cl, FILE * stream, PrintMode mode, int force)
Prints something like a header for a concordance.
Parameters
cl CorpusList object for the subcorpus representing the query to print out.
stream Where to print to.
mode The print mode to use (ascii, html etc.)
force Boolean: if true, the header will print even if headers are disabled in the global print options.
References ascii_print_corpus_header(), GlobalPrintOptions, html_print_corpus_header(), latex_print_corpus_header(), mode, PrintOptions::print_header, PrintASCII, PrintHTML, PrintLATEX, PrintSGML, and sgml_print_corpus_header().
Referenced by cat_listed_corpus().
print_tabulation()
int print_tabulation (CorpusList * cl, int first, int last, struct Redir * dst)
Tabulate specified query result, using settings from global list of tabulation items.
Parameters
cl CorpusList for the query result
first first/last = range of hits to tabulate
last
dst Stream to print to.
Returns
Boolean: true indicates that tabulation was successful (otherwise, generates error message)
References ATT_NONE, ATT_POS, ATT_STRUC, CDA_CPOSUNDEF, TCorpus::charset, cl_broken_pipe, cl_cpos2str(), cl_cpos2struc2str(), cl_free, cl_new_attribute(), cl_string_canonical(), CL_STRING_CANONICAL_STRDUP, cl_struc_values(), close_rd_output_stream(), cl::corpus, cqpmessage(), Error, free_tabulation_list(), cl::name, open_rd_output_stream(), pt_get_anchor_cpos(), pt_validate_anchor(), cl::size, Redir::stream, and TabulationList.
Variable Documentation
TabulationList
TabulationItem TabulationList extern
Global list of tabulation items for use with the "tabulate" operator.
Referenced by append_tabulation_item(), free_tabulation_list(), and print_tabulation().