CWB: cqp/parse_actions.h File Reference
parse_actions.h File Reference
#include <stdio.h>
#include <sys/time.h>
#include <sys/resource.h>
#include "cqp.h"
#include "corpmanag.h"
#include "targets.h"
#include "eval.h"
#include "output.h"
#include "ranges.h"
Macros
#define OP_EQUAL 0
grammar constant: =
#define OP_NOT 1
grammar constant: != or 'not'
#define OP_NOT_MASK 0xfe
grammar constant: mask used to reset OP_NOT bit
#define OP_CONTAINS 2
grammar constant: contains
#define OP_MATCHES 4
grammar constant: matches
Functions
void addHistoryLine (void)
Add a line of CQP input to the history file.
void resetQueryBuffer (void)
Empties the query buffer and sets to 0 the pointer.
void prepare_parse (void)
Misc steps before parsing a query: turn on generate code, and restore old_query_corpus to query_corpus if there is one.
CorpusList * in_CorpusCommand (char *id, CorpusList *cl)
Function that handles subcorpus / NQR assignments, that is "SomeNqr = SomeOtherCorpusOrNqr".
void after_CorpusCommand (CorpusList *cl)
Set the current corpus and do the output if it was a query.
CorpusList * in_UnnamedCorpusCommand (CorpusList *cl)
This function is called after an UnnamedCorpusCommand rule is parsed.
CorpusList * ActivateCorpus (CorpusList *cl)
CorpusList * after_CorpusSetExpr (CorpusList *cl)
void prepare_Query (void)
This function sets things up to run a query.
CorpusList * after_Query (CorpusList *cl)
void do_cat (CorpusList *cl, struct Redir *dst, int first, int last)
Function that implements the "cat" command.
void do_catString (const char *str, struct Redir *dst)
Implements cat "..." > "somewhere" : writes arbitrary string to a redirected output, the way do_cat() does for a CorpusList.
void do_save (CorpusList *cl, struct Redir *dst)
Implements the save command, saving the specified query (in the cl) to the file specified within the redirection info (the r).
void do_attribute_show (char *name, int status)
Display info on an attribute - in respone to the "show...." commmand.
CorpusList * do_translate (CorpusList *source, char *target_name)
CorpusList * do_setop (RangeSetOp op, CorpusList *c1, CorpusList *c2)
Implements set operation commands; returns the CorpusList of the output.
void prepare_do_subset (CorpusList *cl, FieldType field)
CorpusList * do_subset (FieldType field, Constrainttree boolt)
void do_set_target (CorpusList *cl, FieldType goal, FieldType source, int source_offset, int overwrite)
Action for "set $Nqr (match) (matchend)" etc.
void do_set_complex_target (CorpusList *cl, FieldType goal, SearchStrategy search_strategy, Constrainttree boolt, enum ctxtdir direction, int number, char *id, FieldType field, int inclusive)
void do_sleep (int duration)
Puts the program to sleep.
void do_exec (char *fname)
Execute the commands contained in a CQP script file (CQP "source FILENAME;".
void do_delete_lines_num (CorpusList *cl, int start, int end)
Deletes lines from a subcorpus/NQR as specified by a range (start index to end index)
void do_delete_lines (CorpusList *cl, FieldType f, int mode)
void do_reduce (CorpusList *cl, int number, int percent)
Function implementing the "reduce" command - making an NQR smaller.
void do_cut (CorpusList *cl, int first, int last)
void do_info (CorpusList *cl)
void do_group (CorpusList *cl, FieldType target, int target_offset, char *t_att, FieldType source, int source_offset, char *s_att, int cut, int expand, int is_grouped, struct Redir *dst, char *within)
void do_group_nosource (CorpusList *cl, FieldType target, int target_offset, char *t_att, int cut, int expand, struct Redir *dst, char *within)
Like do_group, but with no source anchor; compute_grouping() is therefore called with empty arguments.
CorpusList * do_StandardQuery (int cut_value, int keep_flag, char *modifier)
Implements the running of a standard query, that is, a token-level regex query.
CorpusList * do_MUQuery (Evaltree evalt, int keep_flag, int cut_value)
Implements the running of a Meet-Union query.
void do_SearchPattern (Evaltree expr, Constrainttree constraint)
Populates the global CurEnv with compiled data regarding the query part of a StandardQuery, that is, the "search pattern" part that contains the token-level regular expression, global constraint, and within clause (and not any leading modifiers or trailing alignment contraints, cut commands, etc.)
Evaltree reg_disj (Evaltree left, Evaltree right)
Links two evaltrees into a new node using disjunction (implements '|')
Evaltree reg_seq (Evaltree left, Evaltree right)
Links two evaltrees into a new node using order dependent concatenation (implements sequencing)
int do_AnchorPoint (FieldType field, int is_closing)
Adds an anchor to CurEnv's pattern list.
int do_XMLTag (char *s_name, int is_closing, int op, char *regex, int flags)
Implements mastching an s-attribute boundary (open tag, open tag with constraint on annotation value, or close tag) within a standard query.
Evaltree do_RegionElement (char *name, target_nature start_target, char *start_label, target_nature end_target, char *end_label, int zero_width)
Implements the CQP-syntax rule for a region element (i.e.
int do_NamedWfPattern (target_nature is_target, char *label, int pat_idx)
Implements the CQP-syntax rule for a named wordform pattern.
int do_WordformPattern (Constrainttree boolt, int lookahead)
Implements the grammar rule that matches a token pattern in a CQP query, by adding a tree of compiled Boolean statements as the next entry in the CurEnv's patternlist, which is of type Patternlist, i.e.
Constrainttree do_StringConstraint (char *s, int flags)
Implements a token expression which consists only of a string (regex pattern) and its flags, outside the usual token-square-brackets with no attribute specified, so the default p-attribute, generally "word", is matched.
Constrainttree do_VariableReference (char *s)
Constrainttree do_SimpleVariableReference (char *varName)
void do_MatchSelector (char *start, int start_offset, char *end, int end_offset)
void prepare_AlignmentConstraints (char *id)
Constrainttree bool_or (Constrainttree left, Constrainttree right)
Creates a constraint tree node by linking two other nodes into a boolean OR relationship.
Constrainttree bool_implies (Constrainttree left, Constrainttree right)
Constrainttree bool_and (Constrainttree left, Constrainttree right)
Creates a constraint tree node by linking two other nodes into a boolean AND relationship.
Constrainttree bool_not (Constrainttree left)
Creates a constraint tree node by applying the Boolean NOT operator to the outcome of an existing node (representing whatever is leftward of the !).
Constrainttree do_RelExpr (Constrainttree left, enum b_ops op, Constrainttree right)
Constrainttree do_RelExExpr (Constrainttree left)
Constrainttree do_LabelReference (char *label_name, int auto_delete)
Constrainttree do_IDReference (char *id_name, int auto_delete)
Constrainttree do_flagged_re_variable (char *varname, int flags)
Implements expansion of a variable within the RE() operator.
Constrainttree do_flagged_string (char *s, int flags)
Creates a constraint tree node for a flagged regular expression.
Constrainttree do_mval_string (char *s, int op, int flags)
do_mval_string() replaces do_flagged_string() for 'contains' and 'matches' operators that operate on multi-valued attributes
Constrainttree do_FunctionCall (char *f_name, ActualParamList *apl)
Create a constraint tree node that contains a function call.
void do_Description (Context *context, int nr, char *name)
Evaltree do_MeetStatement (Evaltree left, Evaltree right, Context *context, int negated)
Evaltree do_UnionStatement (Evaltree left, Evaltree right)
void do_StructuralContext (Context *context, char *name)
CorpusList * do_TABQuery (Evaltree patterns)
Evaltree make_first_tabular_pattern (int pattern_index, Evaltree next)
Evaltree add_tabular_pattern (Evaltree patterns, Context *context, int pattern_index)
Add new tab pattern to end of a linked list of such "patterns"; returns new head of list or NULL if not generate_code.
void do_OptDistance (Context *context, int l_bound, int u_bound)
void do_PrintAllVariables ()
Prints settings of all Variables as an indented list.
void do_PrintVariableValue (char *varName)
Prints values of a Variable.
void do_printVariableSize (char *varName)
void do_SetVariableValue (char *varName, char operator, char *varValues)
Implments CQP 'define $var = "aaa bbb ccc"'.
void do_AddSubVariables (char *var1Name, int add, char *var2Name)
Implements addition or subtraction of strings in word-list variables (the CQP command 'define $some_var += $some_other_var', or, likewise '-='.
void prepare_input (void)
Get ready to parse a command.
void expand_dataspace (CorpusList *ds)
Expand the dataspace of a subcorpus.
void debug_output (void)
where debug messages are to be sent to (stderr)
void do_start_timer (void)
Starts the timer running.
void do_timing (char *msg)
Shows the period since the timer started running.
void do_size (CorpusList *cl, FieldType field)
Prints to stdout the size of a CorpusList (corpus/subcorpus/NQP).
void do_dump (CorpusList *cl, int first, int last, struct Redir *rd)
Dump subcorpus/NQR (or part of it) as TAB-delimited table of corpus positions.
int do_undump (char *corpname, int extension_fields, int sort_ranges, struct InputRedir *src)
Read TAB-delimited table of corpus positions and create named query result from it.
Variables
int generate_code
A boolean; indicates whether the code trees for query execution should actually be built or not when the query input is parsed.
int within_gc
A boolean; seems to be about whether or not we are within a global constraint.
CYCtype last_cyc
Type of last corpus yielding command.
CorpusList * query_corpus
The corpus (or subcorpus) which is "active" in the sense that the query will be executed within it.
CorpusList * old_query_corpus
Used for preserving former values of query_corpus (.
FieldType field_to_set
SearchStrategy strategy
int catch_unknown_ids
FILE * yyin
Context expansion
This is used by the parser in response to CQP's "expand" operator, which incorporates context around the query hit into the match itself.
char regex_string []
Buffer for storing regex strings.
int regex_string_pos
index into the regex string buffer, storing a current position.
int sslen
Macro Definition Documentation
OP_CONTAINS
#define OP_CONTAINS 2
grammar constant: contains
OP_EQUAL
#define OP_EQUAL 0
grammar constant: =
OP_MATCHES
#define OP_MATCHES 4
grammar constant: matches
OP_NOT
#define OP_NOT 1
grammar constant: != or 'not'
OP_NOT_MASK
#define OP_NOT_MASK 0xfe
grammar constant: mask used to reset OP_NOT bit
Function Documentation
ActivateCorpus()
CorpusList* ActivateCorpus (CorpusList * cl)
References Activation, cqp_error_status, cqpmessage(), CurEnv, Error, generate_code, inhibit_activation, last_cyc, Message, next_environment(), evalenv::query_corpus, and query_corpus.
add_tabular_pattern()
Evaltree add_tabular_pattern (Evaltree patterns, Context * context, int pattern_index)
Add new tab pattern to end of a linked list of such "patterns"; returns new head of list or NULL if not generate_code.
References cl_malloc(), generate_code, e_tree::next, node, ctxtsp::size, ctxtsp::size2, e_tree::tab_el, and tabular.
addHistoryLine()
void addHistoryLine (void)
Add a line of CQP input to the history file.
Supports parser rule: line -> command
The line that is added comes from QueryBuffer; the file it is written to is that named in cqp_history_file.
See also
QueryBuffer
cqp_history_file
References cl_close_stream(), cl_open_stream(), CL_STREAM_APPEND, CL_STREAM_FILE, cqp_history_file, cqpmessage(), Error, QueryBuffer, reading_cqprc, silent, and write_history_file.
after_CorpusCommand()
void after_CorpusCommand (CorpusList * cl)
Set the current corpus and do the output if it was a query.
References Activation, auto_save, auto_subquery, autoshow, cat_listed_corpus(), GlobalPrintMode, last_cyc, LastExpression, NoExpression, Query, query_corpus, QueryBuffer, QueryBufferOverflow, save_subcorpus(), cl::saved, set_current_corpus(), SetOperation, silent, cl::size, SUB, and cl::type.
after_CorpusSetExpr()
CorpusList* after_CorpusSetExpr (CorpusList * cl)
References cqpmessage(), CurEnv, Error, generate_code, last_cyc, next_environment(), evalenv::query_corpus, and SetOperation.
after_Query()
CorpusList* after_Query (CorpusList * cl)
References cl_free, cl_strdup(), generate_code, last_cyc, cl::name, Query, cl::query_corpus, query_corpus, cl::query_text, QueryBuffer, QueryBufferOverflow, QueryBufferP, and within_gc.
bool_and()
Constrainttree bool_and (Constrainttree left, Constrainttree right)
Creates a constraint tree node by linking two other nodes into a boolean AND relationship.
References b_and, bnode, cnode, c_tree::constnode, free_booltree(), generate_code, c_tree::left, NEW_BNODE, c_tree::node, c_tree::op_id, c_tree::right, c_tree::type, and c_tree::val.
bool_implies()
Constrainttree bool_implies (Constrainttree left, Constrainttree right)
References b_implies, bnode, bool_not(), cnode, c_tree::constnode, free_booltree(), generate_code, c_tree::left, NEW_BNODE, c_tree::node, c_tree::op_id, c_tree::right, try_optimization(), c_tree::type, and c_tree::val.
bool_not()
Constrainttree bool_not (Constrainttree left)
Creates a constraint tree node by applying the Boolean NOT operator to the outcome of an existing node (representing whatever is leftward of the !).
References b_not, bnode, cnode, c_tree::constnode, free_booltree(), generate_code, id_list, c_tree::idlist, c_tree::left, c_tree::negated, NEW_BNODE, c_tree::node, c_tree::op_id, c_tree::right, c_tree::type, and c_tree::val.
Referenced by bool_implies().
bool_or()
Constrainttree bool_or (Constrainttree left, Constrainttree right)
Creates a constraint tree node by linking two other nodes into a boolean OR relationship.
References b_or, bnode, cnode, c_tree::constnode, free_booltree(), generate_code, c_tree::left, NEW_BNODE, c_tree::node, c_tree::op_id, c_tree::right, try_optimization(), c_tree::type, and c_tree::val.
debug_output()
void debug_output (void)
where debug messages are to be sent to (stderr)
where debug messages are to be sent to (stderr)
See also
Environment
References ee_ix, and show_environment().
Referenced by compress_reversed_index(), compressrdx_cleanup(), decompress_check_reversed_index(), do_MUQuery(), do_StandardQuery(), do_TABQuery(), and main().
do_AddSubVariables()
void do_AddSubVariables (char * var1Name, int add, char * var2Name)
Implements addition or subtraction of strings in word-list variables (the CQP command 'define $some_var += $some_other_var', or, likewise '-='.
)
Parameters
var1Name Name of variable we're changing.
add If true, add strings in 2 to 1. If false, remove strings in 2 from 1.
var2Name Name of the variable containing te lsit of things to add/remove.
References cl_free, cqpmessage(), Error, FindVariable(), GetVariableStrings(), VariableAddItem(), and VariableSubtractItem().
do_AnchorPoint()
int do_AnchorPoint (FieldType field, int is_closing)
Adds an anchor to CurEnv's pattern list.
Returns -1 if something wrong; otherwise, the pattern index of the new anchor in CurEnv
References Anchor, cqpmessage(), CurEnv, Error, field_type_to_name(), generate_code, KeywordField, cl::keywords, MatchEndField, MatchField, evalenv::MaxPatIndex, MAXPATTERNS, Message, cl::name, evalenv::patternlist, query_corpus, TargetField, and cl::targets.
do_attribute_show()
void do_attribute_show (char * name, int status)
Display info on an attribute - in respone to the "show...." commmand.
References ContextDescriptor::alignedCorpora, ATT_STRUC, ContextDescriptor::attributes, CD, cl_new_attribute(), cl_streq_ci, cl::corpus, cqpmessage(), current_corpus, CWB_DEFAULT_ATT_NAME, Error, FindInAL(), generate_code, _attlist::list, _attrbuf::next, ContextDescriptor::print_cpos, show_targets, _attrbuf::status, and ContextDescriptor::strucAttributes.
do_cat()
void do_cat (CorpusList * cl, struct Redir * dst, int first, int last)
Function that implements the "cat" command.
References cat_listed_corpus(), cqpmessage(), GlobalPrintMode, Message, and cl::name.
do_catString()
void do_catString (const char * str, struct Redir * dst)
Implements cat "..." > "somewhere" : writes arbitrary string to a redirected output, the way do_cat() does for a CorpusList.
It also implements the \t, \n, \r escape sequences.
Parameters
str String to print
dst Redirection specifier.
References cl_free, cl_strdup(), close_rd_output_stream(), cqpmessage(), Error, open_rd_output_stream(), Redir::stream, and unknown_charset.
do_cut()
void do_cut (CorpusList * cl, int first, int last)
References apply_range_set_operation(), cqpmessage(), Range::end, Error, generate_code, cl::range, RReduce, cl::size, cl::sortidx, Range::start, SUB, touch_corpus(), cl::type, and Warning.
do_delete_lines()
void do_delete_lines (CorpusList * cl, FieldType f, int mode)
References cqpmessage(), create_bitfield(), delete_intervals(), destroy_bitfield(), Error, generate_code, KeywordField, cl::keywords, MatchEndField, MatchField, mode, NoField, set_bit(), cl::size, SUB, TargetField, cl::targets, cl::type, and Warning.
do_delete_lines_num()
void do_delete_lines_num (CorpusList * cl, int start, int end)
Deletes lines from a subcorpus/NQR as specified by a range (start index to end index)
References cqpmessage(), create_bitfield(), delete_intervals(), destroy_bitfield(), Error, generate_code, nr_bits_set(), SELECTED_LINES, set_bit(), cl::size, SUB, and cl::type.
do_Description()
void do_Description (Context * context, int nr, char * name)
References ATT_STRUC, ctxtsp::attrib, cl_new_attribute(), cl_str_is, cl::corpus, cqpmessage(), Environment, Error, generate_code, cl::name, query_corpus, ctxtsp::size, ctxtsp::space_type, structure, and word.
do_dump()
void do_dump (CorpusList * cl, int first, int last, struct Redir * dst)
Dump subcorpus/NQR (or part of it) as TAB-delimited table of corpus positions.
Parameters
cl The result (as a subcorpus, naturally)
first Where in the result to begin dumping (index of cl->range)
last Where in the result to end dumping (index of cl->range)
dst Pointer to a Redir structure which contains information about where to dump to.
References TCorpus::charset, cl_broken_pipe, close_rd_output_stream(), cl::corpus, cqpmessage(), Range::end, Error, cl::keywords, open_rd_output_stream(), cl::range, cl::size, cl::sortidx, Range::start, Redir::stream, and cl::targets.
do_exec()
void do_exec (char * fname)
Execute the commands contained in a CQP script file (CQP "source FILENAME;".
The tricky part is to suspend execution of the parser and ongoing macro expansions, then return safely to the current state when the file has been read.
References cl_open_stream(), CL_STREAM_MAGIC_NOPIPE, CL_STREAM_READ, cqp_parse_file(), cqpmessage(), Error, generate_code, and Message.
do_flagged_re_variable()
Constrainttree do_flagged_re_variable (char * varname, int flags)
Implements expansion of a variable within the RE() operator.
References TCorpus::charset, cl_free, cl_malloc(), cl_string_validate_encoding(), cl::corpus, cqpmessage(), do_flagged_string(), Error, FindVariable(), generate_code, GetVariableStrings(), IGNORE_REGEX, TCorpus::name, query_corpus, and Warning.
do_flagged_string()
Constrainttree do_flagged_string (char * s, int flags)
Creates a constraint tree node for a flagged regular expression.
Parameters
s The constraint stringh (regex, or literal with IGNORE_REGEX).
flags IGNORE_REGEX, or either or both of IGNORE_CASE/IGNORE_DIAC (bitwise-OR'd).
Returns
The new node, ort NULL in case of error.
References c_tree::canon, TCorpus::charset, cl_new_regex(), cl_string_latex2iso(), cl::corpus, cqpmessage(), c_tree::ctype, Error, generate_code, IGNORE_REGEX, c_tree::leaf, NEW_BNODE, NORMAL, c_tree::pat_type, query_corpus, REGEXP, c_tree::rx, string_leaf, and c_tree::type.
Referenced by do_flagged_re_variable(), do_mval_string(), and do_StringConstraint().
do_FunctionCall()
Constrainttree do_FunctionCall (char * f_name, ActualParamList * apl)
Create a constraint tree node that contains a function call.
Parameters
f_name Name of the function.
apl Argument list for the function.
Returns
New Constrainttree object, of type function, with the supplied argument list.
References c_tree::args, ATT_DYN, builtin_function, cl_new_attribute(), cl::corpus, cqpmessage(), c_tree::dynattr, Error, find_predefined_function(), func, c_tree::func, generate_code, Message, NEW_BNODE, _ActualParamList::next, c_tree::nr_args, c_tree::predef, query_corpus, and c_tree::type.
do_group()
void do_group (CorpusList * cl, FieldType target, int target_offset, char * t_att, FieldType source, int source_offset, char * s_att, int cut, int expand, int is_grouped, struct Redir * dst, char * within)
References compute_grouping(), cqpmessage(), do_start_timer(), do_timing(), Error, free_group(), generate_code, and print_group().
Referenced by do_group_nosource().
do_group_nosource()
void do_group_nosource (CorpusList * cl, FieldType target, int target_offset, char * t_att, int cut, int expand, struct Redir * dst, char * within)
Like do_group, but with no source anchor; compute_grouping() is therefore called with empty arguments.
References do_group(), and NoField.
do_IDReference()
Constrainttree do_IDReference (char * id_name, int auto_delete)
References ATT_POS, ATT_STRUC, c_tree::attr, cl_free, cl_new_attribute(), cl::corpus, cqpmessage(), CurEnv, c_tree::delete, Error, _label_entry::flags, generate_code, LAB_SPECIAL, LAB_USED, c_tree::label, label_lookup(), evalenv::labels, NEW_BNODE, pa_ref, c_tree::pa_ref, query_corpus, sa_ref, c_tree::sa_ref, c_tree::type, Warning, and within_gc.
do_info()
void do_info (CorpusList * cl)
References corpus_info().
do_LabelReference()
Constrainttree do_LabelReference (char * label_name, int auto_delete)
References ATT_POS, ATT_STRUC, c_tree::attr, cl_free, cl_new_attribute(), cl_struc_values(), cl::corpus, cqpmessage(), CurEnv, c_tree::delete, Error, _label_entry::flags, generate_code, LAB_SPECIAL, LAB_USED, c_tree::label, label_lookup(), evalenv::labels, NEW_BNODE, pa_ref, c_tree::pa_ref, query_corpus, sa_ref, c_tree::sa_ref, c_tree::type, and Warning.
do_MatchSelector()
void do_MatchSelector (char * start, int start_offset, char * end, int end_offset)
References MatchSelector::begin, MatchSelector::begin_offset, cqpmessage(), CurEnv, MatchSelector::end, MatchSelector::end_offset, Error, _label_entry::flags, generate_code, LAB_SPECIAL, LAB_USED, label_lookup(), evalenv::labels, and evalenv::match_selector.
do_MeetStatement()
Evaltree do_MeetStatement (Evaltree left, Evaltree right, Context * context, int negated)
References ctxtsp::attrib, cl_malloc(), e_tree::cooc, cooc_meet, generate_code, e_tree::left, e_tree::lw, meet_union, e_tree::negated, e_tree::op_id, e_tree::right, e_tree::rw, ctxtsp::size, ctxtsp::size2, e_tree::struc, and e_tree::type.
do_MUQuery()
CorpusList* do_MUQuery (Evaltree evalt, int keep_flag, int cut_value)
Implements the running of a Meet-Union query.
See also
cqp_run_mu_query
Parameters
evalt evaltree on which to run the query.
keep_flag Boolean: contain thew "keep ranges" setting. Passed to cqp_run_mu_query.
cut_value Passed to cqp_run_mu_query.
References cqp_run_mu_query(), cqpmessage(), CurEnv, current_corpus, debug_output(), do_start_timer(), Environment, evalenv::evaltree, generate_code, leaf, meet_union, Message, parse_only, evalenv::query_corpus, SUB, cl::type, e_tree::type, and Warning.
do_mval_string()
Constrainttree do_mval_string (char * s, int op, int flags)
do_mval_string() replaces do_flagged_string() for 'contains' and 'matches' operators that operate on multi-valued attributes
References cl_free, cl_malloc(), cqpmessage(), do_flagged_string(), Error, generate_code, IGNORE_REGEX, mval_string_conversion(), OP_CONTAINS, OP_MATCHES, and OP_NOT_MASK.
do_NamedWfPattern()
int do_NamedWfPattern (target_nature is_target, char * label_str, int pat_idx)
Implements the CQP-syntax rule for a named wordform pattern.
Parameters
is_target Int flag: 0 (no marker), 1 (marked as target), or 2 (marked as keyword)
label_str Label string, will be looked up in the symbol table.
pat_idx Pattern list index (which pattern to work with).
Returns
An output pattern list index (or 0 or -1)
References cqpmessage(), CurEnv, Error, _label_entry::flags, generate_code, evalenv::has_keyword_indicator, evalenv::has_target_indicator, IsKeyword, IsTarget, evalenv::keyword_label, LAB_DEFINED, LAB_SPECIAL, LAB_USED, label_lookup(), evalenv::labels, MatchAll, Message, Pattern, evalenv::patternlist, and evalenv::target_label.
do_OptDistance()
void do_OptDistance (Context * context, int l_bound, int u_bound)
References ctxtsp::attrib, cqpmessage(), repeat_inf, ctxtsp::size, ctxtsp::size2, ctxtsp::space_type, Warning, and word.
do_PrintAllVariables()
void do_PrintAllVariables ()
Prints settings of all Variables as an indented list.
Implements CQP "show variables".
References printSingleVariableValue(), variables_iterator_new(), and variables_iterator_next().
do_printVariableSize()
void do_printVariableSize (char * varName)
References cqpmessage(), Error, FindVariable(), _variable_item::free, _variable_buf::items, _variable_buf::my_name, and _variable_buf::nr_items.
do_PrintVariableValue()
void do_PrintVariableValue (char * varName)
Prints values of a Variable.
Implements CQP "show (name of var)".
References cqpmessage(), Error, FindVariable(), and printSingleVariableValue().
do_reduce()
void do_reduce (CorpusList * cl, int number, int percent)
Function implementing the "reduce" command - making an NQR smaller.
The matches removed are selected randomly.
Parameters
cl The NQR's CorpusList entry.
number Number of matches to retain in reduced query. Or, a percentage, if the "percent" parameter is true
percent Boolean determining whether "number" is to be treated as a count, or as a percerntage of existing matches.
References cl_random_fraction(), cqpmessage(), create_bitfield(), delete_intervals(), destroy_bitfield(), Error, generate_code, set_bit(), cl::size, SUB, cl::type, UNSELECTED_LINES, and Warning.
do_RegionElement()
Evaltree do_RegionElement (char * name, target_nature start_target, char * start_label, target_nature end_target, char * end_label, int zero_width)
Implements the CQP-syntax rule for a region element (i.e.
<<att>> or <<NamedQuery>>).
Parameters
name unqualified name of the query result, or name of the s-attribute
start_target whether start of range should be marked as target or keyword
start_label label to set on start of range
end_target whether end of range should be marked as target or keyword
end_label label to set on end of range
zero_width if True, only test whether current position is the start of a suitable range
Returns
new Evaltree object representing the query fragment that implements a region element
References ATT_STRUC, AVSRegionEmit, AVSRegionEnter, AVSRegionWait, cl_free, cl_malloc(), cl_new_attribute(), cl_strdup(), cl::corpus, cqpmessage(), CurEnv, Error, findcorpus(), _label_entry::flags, generate_code, evalenv::has_keyword_indicator, evalenv::has_target_indicator, IsKeyword, IsNotTarget, IsTarget, evalenv::keyword_label, LAB_DEFINED, LAB_SPECIAL, LAB_USED, label_lookup(), evalenv::labels, evalenv::MaxPatIndex, MAXPATTERNS, cl::mother_name, cl::name, NEW_EVALLEAF, NEW_EVALNODE, evalenv::patternlist, query_corpus, re_repeat, reg_seq(), Region, repeat_inf, StateQueue_new(), SUB, evalenv::target_label, and cl::type.
do_RelExExpr()
Constrainttree do_RelExExpr (Constrainttree left)
References bnode, cmp_ex, generate_code, c_tree::left, NEW_BNODE, c_tree::node, c_tree::op_id, c_tree::right, try_optimization(), and c_tree::type.
do_RelExpr()
Constrainttree do_RelExpr (Constrainttree left, enum b_ops op, Constrainttree right)
References c_tree::attr, bnode, cmp_eq, cmp_neq, cqpmessage(), c_tree::delete, Error, free_booltree(), generate_code, id_list, c_tree::idlist, c_tree::label, c_tree::left, NEW_BNODE, c_tree::node, c_tree::op_id, OptimizeStringConstraint(), pa_ref, c_tree::pa_ref, c_tree::right, string_leaf, try_optimization(), c_tree::type, var_ref, c_tree::varName, c_tree::varref, and Varref2IDList().
do_save()
void do_save (CorpusList * cl, struct Redir * dst)
Implements the save command, saving the specified query (in the cl) to the file specified within the redirection info (the r).
References cqpmessage(), data_directory, Message, cl::name, Redir::name, save_subcorpus(), and Warning.
do_SearchPattern()
void do_SearchPattern (Evaltree expr, Constrainttree constraint)
Populates the global CurEnv with compiled data regarding the query part of a StandardQuery, that is, the "search pattern" part that contains the token-level regular expression, global constraint, and within clause (and not any leading modifiers or trailing alignment contraints, cut commands, etc.)
It takes the expr Evaltree and compiles it to a DFA, and stores that, plus the two arguments, in the global Environment pointed to by CurEnv.
Parameters
expr The eval tree representing the token-level regular expression. Parameter $2 when the rule is parsed. Gets stored as CurEnv->evaltree.
constraint The constraint tree representing any global constraint. Parameter $4 when the rule is parsed.
References check_labels(), cl_free, cqpmessage(), CurEnv, evalenv::dfa, ee_ix, Error, evalenv::evaltree, evaltree2searchstr(), evalenv::gconstraint, generate_code, evalenv::labels, Message, print_evaltree(), regex2dfa(), search_debug, and searchstr.
do_set_complex_target()
void do_set_complex_target (CorpusList * cl, FieldType goal, SearchStrategy search_strategy, Constrainttree boolt, enum ctxtdir direction, int number, char * id, FieldType field, int inclusive)
References evaluate_target(), field_to_set, free_booltree(), generate_code, old_query_corpus, query_corpus, and strategy.
do_set_target()
void do_set_target (CorpusList * cl, FieldType goal, FieldType source, int source_offset, int overwrite)
Action for "set $Nqr (match) (matchend)" etc.
References NoField, and set_target().
do_setop()
CorpusList* do_setop (RangeSetOp op, CorpusList * c1, CorpusList * c2)
Implements set operation commands; returns the CorpusList of the output.
References apply_range_set_operation(), cl::corpus, cqpmessage(), make_temp_corpus(), Message, cl::mother_name, cl::name, and Warning.
do_SetVariableValue()
void do_SetVariableValue (char * varName, char operator, char * varValues)
Implments CQP 'define $var = "aaa bbb ccc"'.
References cl_string_latex2iso(), cqpmessage(), Error, FindVariable(), NewVariable(), SetVariableValue(), and Warning.
do_SimpleVariableReference()
Constrainttree do_SimpleVariableReference (char * varName)
References ATT_POS, cl_new_attribute(), cmp_eq, cl::corpus, cqpmessage(), CWB_DEFAULT_ATT_NAME, def_unbr_attr, Error, generate_code, cl::name, query_corpus, set_string_option_value(), and Varref2IDList().
do_size()
void do_size (CorpusList * cl, FieldType field)
Prints to stdout the size of a CorpusList (corpus/subcorpus/NQP).
Implements the "size Something" command.
Parameters
cl The (sub)corpus.
field If this is TargetField or KeywordField, then the count of targets/keywords is printed. Otherwise the CL size is printed.
References KeywordField, cl::keywords, NoField, cl::size, TargetField, and cl::targets.
do_sleep()
void do_sleep (int duration)
Puts the program to sleep.
A wrapper round the standard sleep() function (or Sleep() in Windows).
Parameters
duration How many seconds to sleep for.
do_StandardQuery()
CorpusList* do_StandardQuery (int cut_value, int keep_flag, char * modifier)
Implements the running of a standard query, that is, a token-level regex query.
See also
cqp_run_query
Parameters
cut_value Passed to cqp_run_query.
keep_flag Boolean: contain the "keep ranges" setting. Passed to cqp_run_query.
modifer String with intial embedded-modifier, if there was one. Or NULL.
Returns
CorpusList object for the result.
References apply_range_set_operation(), cl_free, cqp_run_query(), cqpmessage(), create_bitfield(), current_corpus, debug_output(), delete_intervals(), destroy_bitfield(), do_start_timer(), Environment, Error, find_matching_strategy(), generate_code, longest_match, evalenv::matching_strategy, matching_strategy, Message, parse_only, evalenv::query_corpus, RLeftMaximalMatches, RMaximalMatches, RMinimalMatches, searchstr, set_bit(), shortest_match, cl::size, standard_match, SUB, traditional, cl::type, UNSELECTED_LINES, and Warning.
do_start_timer()
void do_start_timer (void)
Starts the timer running.
References timer_start_time, and timing.
Referenced by do_group(), do_MUQuery(), do_StandardQuery(), and do_TABQuery().
do_StringConstraint()
Constrainttree do_StringConstraint (char * s, int flags)
Implements a token expression which consists only of a string (regex pattern) and its flags, outside the usual token-square-brackets with no attribute specified, so the default p-attribute, generally "word", is matched.
Parameters
s String to be matched.
flags IGNORE_CASE and/or IGNORE_DIAC (bitwise-OR'd); or, IGNORE_REGEX.
Returns
Newly-created Constrainttree node for this token expression. NULL in case of error.
References ATT_POS, cl_new_attribute(), cmp_eq, cnode, cl::corpus, cqpmessage(), CWB_DEFAULT_ATT_NAME, def_unbr_attr, do_flagged_string(), Error, generate_code, cl::name, NEW_BNODE, OptimizeStringConstraint(), pa_ref, query_corpus, and set_string_option_value().
do_StructuralContext()
void do_StructuralContext (Context * context, char * name)
References ATT_STRUC, ctxtsp::attrib, cl_new_attribute(), cl::corpus, cqpmessage(), Error, generate_code, TCorpus::id, query_corpus, ctxtsp::size, ctxtsp::size2, ctxtsp::space_type, structure, and word.
do_subset()
CorpusList* do_subset (FieldType field, Constrainttree boolt)
References evaluate_subset(), free_booltree(), generate_code, progress_bar, progress_bar_clear_line(), and query_corpus.
do_TABQuery()
CorpusList* do_TABQuery (Evaltree patterns)
References cqp_run_tab_query(), CurEnv, debug_output(), do_start_timer(), Environment, evalenv::evaltree, generate_code, parse_only, evalenv::query_corpus, tabular, and e_tree::type.
do_timing()
void do_timing (char * msg)
Shows the period since the timer started running.
Parameters
msg A message to print along with the reading from the timer.
References cqpmessage(), Info, timer_start_time, and timing.
Referenced by do_group(), and in_UnnamedCorpusCommand().
do_translate()
CorpusList* do_translate (CorpusList * source, char * target_name)
References apply_range_set_operation(), ATT_ALIGN, cl_alg2cpos(), cl_all_ok, cl_calloc(), cl_cpos2alg(), cl_free, cl_new_attribute(), cl::corpus, cqpmessage(), Range::end, Error, findcorpus(), generate_code, cl::keywords, make_temp_corpus(), cl::mother_name, cl::range, RangeSort(), TCorpus::registry_name, RReduce, s1, s2, cl::size, Range::start, SYSTEM, cl::targets, and Warning.
do_undump()
int do_undump (char * corpname, int extension_fields, int sort_ranges, struct InputRedir * src)
Read TAB-delimited table of corpus positions and create named query result from it.
acceptable values for extension_fields and corresponding row formats: 0 = match [tab] matchend 1 = match [tab] matchend [tab] target 2 = match [tab] matchend [tab] target [tab] keyword
References assign_temp_to_sub(), cl_free, cl_malloc(), CL_MAX_LINE_LENGTH, close_rd_input_stream(), corpname, cqpmessage(), current_corpus, drop_temp_corpora(), Error, findcorpus(), line, make_temp_corpus(), cl::mother_name, cl::mother_size, open_rd_input_stream(), RangeSort(), split_subcorpus_name(), InputRedir::stream, subcorpus_name_is_qualified(), SYSTEM, cl::type, valid_subcorpus_name(), and Warning.
do_UnionStatement()
Evaltree do_UnionStatement (Evaltree left, Evaltree right)
References cl_malloc(), e_tree::cooc, cooc_union, generate_code, e_tree::left, e_tree::lw, meet_union, e_tree::negated, e_tree::op_id, e_tree::right, e_tree::rw, e_tree::struc, and e_tree::type.
do_VariableReference()
Constrainttree do_VariableReference (char * s)
do_WordformPattern()
int do_WordformPattern (Constrainttree boolt, int lookahead)
Implements the grammar rule that matches a token pattern in a CQP query, by adding a tree of compiled Boolean statements as the next entry in the CurEnv's patternlist, which is of type Patternlist, i.e.
an array of AVStructure objects.
See also
AVStructure
Patternlist
Parameters
boolt The tree of boolean constraints which will be added to the patternlist.
lookahead Value to insert for the lookahead variable in the new entry in the patternlist.
Returns
The index of the patternlist entry that boolt has been added to. -1 for error (which arises only if we have run out of patternlist slots, or there was an error before this function was called).
References cl_free, cnode, c_tree::constnode, cqpmessage(), CurEnv, Error, generate_code, IsNotTarget, MatchAll, evalenv::MaxPatIndex, MAXPATTERNS, Pattern, evalenv::patternlist, c_tree::type, and c_tree::val.
do_XMLTag()
int do_XMLTag (char * s_name, int is_closing, int op, char * regex, int flags)
Implements mastching an s-attribute boundary (open tag, open tag with constraint on annotation value, or close tag) within a standard query.
Parameters
s_name The tag for the XML element (i.e. the s-attribute name).
is_closing Boolean: are we looking for a closing tag? False for opening tag.
op Constant for the comparison operator: OP_EQUAL, OP_MATCHES, or OP_CONTAINS. OP_NOT may be bit-OR'ed.
regex Query term for the annotation value to match (if there is one).
flags Flag constant: IGNORE_REGEX, or one or both of IGNORE_CASE and IGNORE_DIAC, bit-OR'ed together.
Returns
-1 for error; otherwise the number of patterns in the eval environment after this part of the query is complete.
References ATT_STRUC, TCorpus::charset, cl_free, cl_malloc(), cl_new_attribute(), cl_new_regex(), cl_strdup(), cl_string_latex2iso(), cl_struc_values(), cl::corpus, cqpmessage(), CurEnv, Error, find_label(), _label_entry::flags, generate_code, IGNORE_REGEX, LAB_DEFINED, LAB_RDAT, LAB_USED, label_lookup(), evalenv::labels, evalenv::MaxPatIndex, MAXPATTERNS, Message, mval_string_conversion(), cl::name, OP_CONTAINS, OP_EQUAL, OP_MATCHES, OP_NOT, OP_NOT_MASK, evalenv::patternlist, query_corpus, s_name, strict_regions, and Tag.
expand_dataspace()
void expand_dataspace (CorpusList * cl)
Expand the dataspace of a subcorpus.
This is done, e.g., by the CQP-syntax "expand" command, to include context into the matches found by a query.
Each corpus interval stored in the CorpusList is extended by an amount, and in a direction, dependant on the information in the global variable "expansion", a Context object (information which has been put there by the parser).
See also
expansion
Parameters
cl The subcorpus to expand.
References apply_range_set_operation(), calculate_leftboundary(), calculate_rightboundary(), cqpmessage(), ctxtdir_left, ctxtdir_leftright, ctxtdir_right, ctxtsp::direction, Range::end, expansion, False, cl::needs_update, cl::range, RUniq, cl::saved, cl::size, ctxtsp::size, Range::start, SYSTEM, True, cl::type, and Warning.
Referenced by in_UnnamedCorpusCommand().
in_CorpusCommand()
CorpusList* in_CorpusCommand (char * id, CorpusList * cl)
Function that handles subcorpus / NQR assignments, that is "SomeNqr = SomeOtherCorpusOrNqr".
Parameters
id String of the name of the NQR to be created/overwritten.
cl The CorpusList entry for the source subcorpus/NQR.
Returns
Value of global "current_corpus" if the assignment was succesful; otherwise NULL.
References Assignment, cqpmessage(), current_corpus, duplicate_corpus(), last_cyc, subcorpus_name_is_qualified(), SYSTEM, True, cl::type, and Warning.
in_UnnamedCorpusCommand()
CorpusList* in_UnnamedCorpusCommand (CorpusList * cl)
This function is called after an UnnamedCorpusCommand rule is parsed.
Seems to be a tidying-up function.
Parameters
cl The result of the corpus-yielding command (first component of this syntax rule).
Returns
Modified valuse of cl. May be NULL.
References Activation, assign_temp_to_sub(), cqpmessage(), do_timing(), drop_temp_corpora(), expand_dataspace(), expansion, free_all_environments(), generate_code, last_cyc, make_temp_corpus(), Message, Query, SetOperation, ctxtsp::size, SYSTEM, TEMP, cl::type, and Warning.
make_first_tabular_pattern()
Evaltree make_first_tabular_pattern (int pattern_index, Evaltree next)
References cl_malloc(), generate_code, node, and tabular.
prepare_AlignmentConstraints()
void prepare_AlignmentConstraints (char * id)
References access_corpus(), evalenv::aligned, ATT_ALIGN, cl_new_attribute(), cl::corpus, cqpmessage(), CurEnv, Environment, Error, findcorpus(), generate_code, cl::mother_name, next_environment(), evalenv::query_corpus, query_corpus, TCorpus::registry_name, SYSTEM, and Warning.
prepare_do_subset()
void prepare_do_subset (CorpusList * cl, FieldType field)
References cqpmessage(), Error, field_type_to_name(), generate_code, KeywordField, cl::keywords, make_temp_corpus(), MatchEndField, MatchField, progress_bar, progress_bar_clear_line(), progress_bar_message(), query_corpus, cl::size, SUB, TargetField, cl::targets, cl::type, and Warning.
prepare_input()
void prepare_input (void)
Get ready to parse a command.
This function is called before the processing of each parsed line that is recognised as a command.
Mostly it involves setting the global variables to their starting-state values.
References free_all_environments(), generate_code, last_cyc, LastExpression, NoExpression, regex_string_pos, and searchstr.
prepare_parse()
void prepare_parse (void)
Misc steps before parsing a query: turn on generate code, and restore old_query_corpus to query_corpus if there is one.
References cqpmessage(), generate_code, old_query_corpus, query_corpus, and Warning.
prepare_Query()
void prepare_Query (void)
This function sets things up to run a query.
It is called as an "action" before any detected Query in the parser.
[AH 2010/8/2: I have added the code checking input character encoding. Anything that is not part of a query should be plain ASCII - if not, then the lexer/parser should pick it up as bad. Filenames, etc. are obvious exceptions - but we can't check the encoding of those, because there's no guarantee it will be the same as that of the corpus, which is the only thing whose encoding we know. So it's up to the user to type filenames in an encoding their OS will accept! Canonicalisation is done within the CL_Regex, not here.]
References access_corpus(), apply_range_set_operation(), TCorpus::charset, cl_string_validate_encoding(), cl::corpus, cqpmessage(), CurEnv, current_corpus, ee_ix, Environment, Error, generate_code, make_temp_corpus(), cl::mother_name, cl::name, next_environment(), evalenv::query_corpus, query_corpus, QueryBuffer, RNonOverlapping, searchstr, cl::size, Warning, and within_gc.
reg_disj()
Evaltree reg_disj (Evaltree left, Evaltree right)
Links two evaltrees into a new node using disjunction (implements '|')
References generate_code, NEW_EVALNODE, re_disj, and repeat_none.
reg_seq()
Evaltree reg_seq (Evaltree left, Evaltree right)
Links two evaltrees into a new node using order dependent concatenation (implements sequencing)
References generate_code, NEW_EVALNODE, re_od_concat, and repeat_none.
Referenced by do_RegionElement().
resetQueryBuffer()
void resetQueryBuffer (void)
Empties the query buffer and sets to 0 the pointer.
Supports parser rule: line -> command
See also
QueryBuffer
QueryBufferP
References QueryBuffer, QueryBufferOverflow, and QueryBufferP.
Variable Documentation
catch_unknown_ids
int catch_unknown_ids extern
Referenced by OptimizeStringConstraint().
expansion
Context expansion extern
This is used by the parser in response to CQP's "expand" operator, which incorporates context around the query hit into the match itself.
Functions involved in carrying this out utilise info stored here by the parser.
Referenced by expand_dataspace(), findcorpus(), and in_UnnamedCorpusCommand().
field_to_set
FieldType field_to_set extern
Referenced by do_set_complex_target().
generate_code
int generate_code extern
A boolean; indicates whether the code trees for query execution should actually be built or not when the query input is parsed.
When it is false, many actions simply have no effect, because they are set to only actually do anything "if (generate_code)".
It's only referenced in this file and in the Yacc grammar.
Responses to errors usually involve switching this off - since when there's been an error, the query won't ever run, so no point malloc'ing massive object trees.
Referenced by ActivateCorpus(), add_tabular_pattern(), after_CorpusSetExpr(), after_Query(), bool_and(), bool_implies(), bool_not(), bool_or(), do_AnchorPoint(), do_attribute_show(), do_cut(), do_delete_lines(), do_delete_lines_num(), do_Description(), do_exec(), do_flagged_re_variable(), do_flagged_string(), do_FunctionCall(), do_group(), do_IDReference(), do_LabelReference(), do_MatchSelector(), do_MeetStatement(), do_MUQuery(), do_mval_string(), do_NamedWfPattern(), do_reduce(), do_RegionElement(), do_RelExExpr(), do_RelExpr(), do_SearchPattern(), do_set_complex_target(), do_SimpleVariableReference(), do_StandardQuery(), do_StringConstraint(), do_StructuralContext(), do_subset(), do_TABQuery(), do_translate(), do_UnionStatement(), do_WordformPattern(), do_XMLTag(), in_UnnamedCorpusCommand(), make_first_tabular_pattern(), mval_string_conversion(), OptimizeStringConstraint(), prepare_AlignmentConstraints(), prepare_do_subset(), prepare_input(), prepare_parse(), prepare_Query(), reg_disj(), reg_seq(), and Varref2IDList().
last_cyc
CYCtype last_cyc extern
Type of last corpus yielding command.
Referenced by ActivateCorpus(), after_CorpusCommand(), after_CorpusSetExpr(), after_Query(), in_CorpusCommand(), in_UnnamedCorpusCommand(), and prepare_input().
old_query_corpus
CorpusList* old_query_corpus extern
Used for preserving former values of query_corpus (.
See also
query_corpus), so it can be reset to a former value).
Referenced by do_set_complex_target(), and prepare_parse().
query_corpus
CorpusList* query_corpus extern
The corpus (or subcorpus) which is "active" in the sense that the query will be executed within it.
Referenced by ActivateCorpus(), after_CorpusCommand(), after_Query(), do_AnchorPoint(), do_Description(), do_flagged_re_variable(), do_flagged_string(), do_FunctionCall(), do_IDReference(), do_LabelReference(), do_RegionElement(), do_set_complex_target(), do_SimpleVariableReference(), do_StringConstraint(), do_StructuralContext(), do_subset(), do_XMLTag(), prepare_AlignmentConstraints(), prepare_do_subset(), prepare_parse(), prepare_Query(), simulate(), and Varref2IDList().
regex_string
char regex_string[] extern
Buffer for storing regex strings.
As it says on the tin.
regex_string_pos
int regex_string_pos extern
index into the regex string buffer, storing a current position.
@ see regex_string
Referenced by prepare_input().
sslen
int sslen extern
strategy
SearchStrategy strategy extern
Referenced by do_set_complex_target(), and evaluate_target().
within_gc
int within_gc extern
A boolean; seems to be about whether or not we are within a global constraint.
It's switched on in the SearchPattern parser rule when it gets to RegWordfExpr and then switched off when it gets to GlobalConstraint.
It can also be turned off by do_Query / prepare_Query.
It's referenced as a test within do_IDReference.
Referenced by after_Query(), do_IDReference(), and prepare_Query().
yyin
FILE* yyin extern