CWB: cqp/print-modes.h File Reference
print-modes.h File Reference
#include "corpmanag.h"
#include "attlist.h"
Data Structures
struct PrintOptions
PrintOptions: records a set of print options.
struct PrintDescriptionRecord
The PrintDescriptionRecord object.
Typedefs
typedef void(* print_aligned_line_func) (FILE *, int, char *, char *)
Enumerations
enum PrintMode {
PrintASCII , PrintSGML , PrintHTML , PrintLATEX ,
PrintUNKNOWN
}
Print mode: specifies output formats for CQP.
Functions
AttributeList * ComputePrintStructures (CorpusList *cl)
Computes a list of s-attributes to print from the PrintStructure global option setting.
void ParsePrintOptions (void)
Reads the global string printModeOptions and parses it to update the GlobalPrintOptions.
Variables
PrintMode GlobalPrintMode
Global print-mode setting.
PrintOptions GlobalPrintOptions
Global print-options: all booleans initially set to false.
Typedef Documentation
print_aligned_line_func
typedef void(* print_aligned_line_func) (FILE *, int, char *, char *)
Enumeration Type Documentation
PrintMode
enum PrintMode
Print mode: specifies output formats for CQP.
Enumerator
PrintASCII
PrintSGML
PrintHTML
PrintLATEX
PrintUNKNOWN
Function Documentation
ComputePrintStructures()
AttributeList* ComputePrintStructures (CorpusList * cl)
Computes a list of s-attributes to print from the PrintStructure global option setting.
PrintStructure is itself updated.
Parameters
cl The corpus from which to find the attributes.
Returns
An attribute list containing the attributes to be printed.
References AddNameToAL(), _Attribute::any, ATT_STRUC, _attrbuf::attribute, cl_new_attribute(), cl_struc_values(), cl::corpus, cqpmessage(), DestroyAttributeList(), Error, _attlist::list, NewAttributeList(), _attrbuf::next, PRINT_STRUC_SEP, printStructure, TCorpus::registry_name, token, VerifyList(), and Warning.
Referenced by execute_side_effects().
ParsePrintOptions()
void ParsePrintOptions (void)
Reads the global string printModeOptions and parses it to update the GlobalPrintOptions.
See also
printModeOptions
GlobalPrintOptions
References CL_MAX_LINE_LENGTH, cl_strcpy(), cl_streq_ci, GlobalPrintOptions, PrintOptions::number_lines, PrintOptions::print_border, PrintOptions::print_header, PrintOptions::print_tabular, PrintOptions::print_wrap, printModeOptions, silent, and token.
Referenced by execute_side_effects(), html_print_output(), and latex_print_output().
Variable Documentation
GlobalPrintMode
PrintMode GlobalPrintMode extern
Global print-mode setting.
Referenced by after_CorpusCommand(), cat_listed_corpus(), do_cat(), execute_side_effects(), print_all_aligned_lines(), and print_group().
GlobalPrintOptions
PrintOptions GlobalPrintOptions extern
Global print-options: all booleans initially set to false.
Referenced by ascii_print_output(), cat_listed_corpus(), html_print_aligned_line(), html_print_corpus_header(), html_print_field(), html_print_output(), latex_print_field(), latex_print_output(), ParsePrintOptions(), print_corpus_info_header(), and print_option_value().