CWB: cqp/print_align.c File Reference
print_align.c File Reference
#include <stdio.h>
#include "../cl/cl.h"
#include "concordance.h"
#include "cqp.h"
#include "options.h"
#include "corpmanag.h"
#include "print-modes.h"
#include "context_descriptor.h"
#include "ascii-print.h"
#include "html-print.h"
#include "sgml-print.h"
#include "latex-print.h"
Functions
void init_align_module ()
Initialises the alignment-printing module by setting up the static global ContextDescriptor (internal to print_align module).
void print_all_aligned_lines (Corpus *sourceCorpus, ContextDescriptor *cd, int begin_target, int end_target, int highlighting, FILE *stream)
For a given query result, prints the corresponding section of the aligned corpus (if any).
Variables
static ContextDescriptor AlignedCorpusCD
Global context descriptor used solely for printing corresponding strings from an aligned corpus.
Function Documentation
init_align_module()
void init_align_module ()
Initialises the alignment-printing module by setting up the static global ContextDescriptor (internal to print_align module).
If module initialisation has already run, does nothing.
See also
AlignedCorpusCD
References AlignedCorpusCD, initialize_context_descriptor(), ContextDescriptor::left_type, ContextDescriptor::right_type, and word_context.
Referenced by print_all_aligned_lines().
print_all_aligned_lines()
void print_all_aligned_lines (Corpus * sourceCorpus, ContextDescriptor * cd, int begin_target, int end_target, int highlighting, FILE * stream)
For a given query result, prints the corresponding section of the aligned corpus (if any).
This function is the business-end of the "print_align" module.
Parameters
sourceCorpus The corpus the query was run on.
cd ContextDescriptor containing data on how the concordance is to be printed.
begin_target Starting cpos of the result being printed.
end_target Ending cpos of the result being printed.
highlighting Boolean: Iff true, highlighting will be used (applies only in ASCII print mode; see "ascii_print_aligned_line").
stream Output destination stream (will be printed to).
References ContextDescriptor::alignedCorpora, AlignedCorpusCD, ascii, ascii_print_aligned_line(), ASCIIPrintDescriptionRecord, ATT_ALIGN, ContextDescriptor::attributes, TCorpus::charset, cl_alg2cpos(), cl_cpos2alg(), cl_free, cl_new_attribute(), cl_new_corpus(), cl_strdup(), cl_string_validate_encoding(), compose_kwic_line(), FindInAL(), GlobalPrintMode, highlighting, html_print_aligned_line(), HTMLPrintDescriptionRecord, init_align_module(), initialize_context_descriptor(), latex_print_aligned_line(), LaTeXPrintDescriptionRecord, _attlist::list, _attrbuf::name, _attrbuf::next, PrintASCII, PrintHTML, PrintLATEX, PrintSGML, PrintUNKNOWN, registry, sgml_print_aligned_line(), SGMLPrintDescriptionRecord, _attrbuf::status, ContextDescriptor::strucAttributes, update_context_descriptor(), and utf8.
Referenced by ascii_print_concordance_line(), html_print_output(), latex_print_output(), and sgml_print_output().
Variable Documentation
AlignedCorpusCD
ContextDescriptor AlignedCorpusCD static
Global context descriptor used solely for printing corresponding strings from an aligned corpus.
(It exists because the amount fo left/right context to print is not unlikely to be different for the aligned line than for the main KWIC line.)
Referenced by init_align_module(), and print_all_aligned_lines().