CWB: cqp/print_align.h File Reference
print_align.h File Reference
#include <stdio.h>
#include "../cl/corpus.h"
#include "context_descriptor.h"
Functions
void print_all_aligned_lines (Corpus *sourceCorpus, ContextDescriptor *cd, int begin_target, int end_target, int highlighting, FILE *stream)
For a given query result, prints the corresponding section of the aligned corpus (if any).
Function Documentation
print_all_aligned_lines()
void print_all_aligned_lines (Corpus * sourceCorpus, ContextDescriptor * cd, int begin_target, int end_target, int highlighting, FILE * stream)
For a given query result, prints the corresponding section of the aligned corpus (if any).
This function is the business-end of the "print_align" module.
Parameters
sourceCorpus The corpus the query was run on.
cd ContextDescriptor containing data on how the concordance is to be printed.
begin_target Starting cpos of the result being printed.
end_target Ending cpos of the result being printed.
highlighting Boolean: Iff true, highlighting will be used (applies only in ASCII print mode; see "ascii_print_aligned_line").
stream Output destination stream (will be printed to).
References ContextDescriptor::alignedCorpora, AlignedCorpusCD, ascii, ascii_print_aligned_line(), ASCIIPrintDescriptionRecord, ATT_ALIGN, ContextDescriptor::attributes, TCorpus::charset, cl_alg2cpos(), cl_cpos2alg(), cl_free, cl_new_attribute(), cl_new_corpus(), cl_strdup(), cl_string_validate_encoding(), compose_kwic_line(), FindInAL(), GlobalPrintMode, highlighting, html_print_aligned_line(), HTMLPrintDescriptionRecord, init_align_module(), initialize_context_descriptor(), latex_print_aligned_line(), LaTeXPrintDescriptionRecord, _attlist::list, _attrbuf::name, _attrbuf::next, PrintASCII, PrintHTML, PrintLATEX, PrintSGML, PrintUNKNOWN, registry, sgml_print_aligned_line(), SGMLPrintDescriptionRecord, _attrbuf::status, ContextDescriptor::strucAttributes, update_context_descriptor(), and utf8.
Referenced by ascii_print_concordance_line(), html_print_output(), latex_print_output(), and sgml_print_output().