CWB: cqp/ranges.c File Reference
ranges.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <limits.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include "../cl/cl.h"
#include "cqp.h"
#include "corpmanag.h"
#include "eval.h"
#include "output.h"
#include "matchlist.h"
#include "options.h"
#include "ranges.h"
Macros
#define SORT_DEBUG 0
#define USE_SORT_CACHE
Defined if a sort cache is to be used in sorting concordance lines.
#define spaceship(A, B) ((A) > (B)) ? 1 : ((A) < (B)) ? -1 : 0
Functions
int delete_intervals (CorpusList *cp, Bitfield intervals, int mode)
Delete a whole bunch of concordance hits from a query-generated subcorpus.
int calculate_ranges (CorpusList *cl, int cpos, Context spc, int *left, int *right)
int calculate_rightboundary (CorpusList *cl, int cpos, Context spc)
Returns -1 if there is no rightboundary found.
int calculate_leftboundary (CorpusList *cl, int cpos, Context spc)
Returns -1 if there is no leftboundary found.
static void rs_cp_range (Range *rng, int *target, int *keyword, int ins, CorpusList *corpus, int j)
this is a rather specialised utility function for the UNION part of RangeSetop() (copies range + keyword/target (if defined) in corpus into temporary lists)
static int _RS_compare_ranges (const void *pa, const void *pb)
qsort() helper function for RangeSort() below
void RangeSort (CorpusList *c, int mk_sortidx)
Make sure that ranges are sorted in 'natural' order (i.e.
int apply_range_set_operation (CorpusList *corpus1, RangeSetOp operation, CorpusList *corpus2, Bitfield restrictor)
Carries out one of a set of operations on corpus1.
static int SortExternally (void)
Use an external program to sort a query.
static int i2compare (const void *vidx1, const void *vidx2)
Compare two matches according to current sort settings in static variables (qsort callback used in query result sorting).
static int group2compare (const void *vidx1, const void *vidx2)
Compares two groups of equivalent matches by group sizes (descending), breaking ties through i2compare.
static int random_compare (const void *vidx1, const void *vidx2)
Sorts hits in random order by comparing random numbers in the vector random_sort_keys[], breaking ties by start and end positions of matches (from *srt_cl) in order to ensure stable sorting.
int SortSubcorpusRandomize (CorpusList *cl, int seed)
Sorts a query result in random order.
int SortSubcorpus (CorpusList *cl, SortClause sc, int count_mode, struct Redir *redir)
Sort the (query) subcorpus specified by cl, or count frequencies of matching strings.
void FreeSortClause (SortClause sc)
Frees a SortClause object.
Variables
static Range * _RS_range = NULL
Variable used by _RS_compare_ranges; global so data can be passed in without going through that function's parameter list!
static CorpusList * srt_cl
The CorpusList object representing a query to be sorted.
static Attribute * srt_attribute
The)p-)Attribute on which a query is to be sorted.
static int * srt_start
When sorting a query, this contains start positions of intervals to be sorted.
static int * srt_end
When sorting a query, this contains end positions of intervals to be sorted.
static FieldType srt_anchor1
In a query sort, indicates the field type of the start of sort region.
static int srt_offset1
In a query sort, indicates the offset of the start of sort region.
static FieldType srt_anchor2
In a query sort, indicates the field type of the end of sort region.
static int srt_offset2
In a query sort, indicates the offset of the end of sort region.
static int srt_flags
Whether to use the c and/or d flags when sorting a query.
static int srt_ascending
boolean: sort query into ascending order or not
static int srt_reverse
boolean: sort query on reversed-character-sequence strings (and reversed sequences OF strings) or not
static int text_size
When sorting a query - this represents the size of the corpus the query belongs to.
static int break_ties
whether to break ties (by comparison without cd flags, and by line number in the last instance)
static unsigned int * random_sort_keys
random keys for randomized sort order (ties are broken by cpos of matches)
static int * group_first
first match for each group of identical (or equivalent) sort strings
static int * group_size
number of matches for each group of identical (or equivalent) sort strings
static int * current_sortidx
alias to newly created sortidx, so it can be accessed by the callback function
static int * sort_id_cache = NULL
Pointer to the sort cache.
Macro Definition Documentation
SORT_DEBUG
#define SORT_DEBUG 0
spaceship
#define spaceship (A, B) ((A) > (B)) ? 1 : ((A) < (B)) ? -1 : 0
USE_SORT_CACHE
#define USE_SORT_CACHE
Defined if a sort cache is to be used in sorting concordance lines.
The sort cache (caching the lexicon IDs of the first two tokens to be compared in each line) is indispensable for the internal sorting algorithm since random accesses to a compressed corpus are painfully slow; when sorting variable length matches such as German NPs on word forms, the current implementation has a hit rate of around 99%.
Function Documentation
_RS_compare_ranges()
static int _RS_compare_ranges (const void * pa, const void * pb) static
qsort() helper function for RangeSort() below
References _RS_range, Range::end, and Range::start.
Referenced by RangeSort().
apply_range_set_operation()
int apply_range_set_operation (CorpusList * corpus1, RangeSetOp operation, CorpusList * corpus2, Bitfield restrictor)
Carries out one of a set of operations on corpus1.
The operations that can be carried out are as follows:
RUnion - copy intervals from corpus2 to corpus1 (no duplicates); RIntersection - remove from corpus1 any intervals that are not also in corpus2; RDiff RMaximalMatches - remove spurious matches according to "longest" strategy; RMinimalMatches - remove spurious matches according to "shortest" strategy; RLeftMaximalMatches - remove spurious matches according to "standard" strategy; RNonOverlapping RUniq - remove duplicate intervals from corpus1; RReduce - remove intervals marked for deletion (by having the start member set to -1).
Parameters
corpus1 The corpus to be changed.
operation Specifies which operation is to be carried out.
corpus2 The corpus that is the second argument for this operation. Can be NULL if no corpus2 is required for operation.
restrictor Specifies which intervals in corpus2 are to be taken notice of versus ignored. Can be NULL.
Returns
Boolean, true for all OK, otherwise false.
References cl_free, cl_malloc(), cl_realloc(), corpus1, corpus2, get_bit(), RDiff, RIntersection, RLeftMaximalMatches, RMaximalMatches, RMinimalMatches, RNonOverlapping, RReduce, rs_cp_range(), RUnion, RUniq, and touch_corpus().
Referenced by delete_intervals(), do_cut(), do_setop(), do_StandardQuery(), do_translate(), evaluate_subset(), expand_dataspace(), findcorpus(), prepare_Query(), set_corpus_matchlists(), and set_target().
calculate_leftboundary()
int calculate_leftboundary (CorpusList * cl, int cpos, Context spc)
Returns -1 if there is no leftboundary found.
References calculate_ranges().
Referenced by expand_dataspace(), and findcorpus().
calculate_ranges()
int calculate_ranges (CorpusList * cl, int cpos, Context spc, int * left, int * right)
References ctxtsp::attrib, cl_cpos2struc(), cl_cpos2struc2cpos(), cl_max_struc(), cl_struc2cpos(), cqp_error_status, MAX, MIN, cl::mother_size, ctxtsp::size, ctxtsp::space_type, structure, and word.
Referenced by calculate_leftboundary(), calculate_rightboundary(), and evaluate_target().
calculate_rightboundary()
int calculate_rightboundary (CorpusList * cl, int cpos, Context spc)
Returns -1 if there is no rightboundary found.
References calculate_ranges().
Referenced by cqp_run_tab_query(), expand_dataspace(), findcorpus(), and simulate().
delete_intervals()
int delete_intervals (CorpusList * cp, Bitfield intervals, int mode)
Delete a whole bunch of concordance hits from a query-generated subcorpus.
Parameters
cp The CorpusList indicating the query to delete from.
intervals A Bitfield containing a bit for each query hit, which is true if the hit is "selected", false if not.
mode ALL_LINES, SELECTED_LINES or UNSELECTED_LINES (indicating which lines to delete).
Returns
Boolean: true for success, false for failure.
References ALL_LINES, apply_range_set_operation(), auto_save, cl_free, BFBuf::elements, Range::end, get_bit(), cl::keywords, mode, cl::range, RReduce, save_subcorpus(), SELECTED_LINES, cl::size, cl::sortidx, Range::start, SUB, cl::targets, TEMP, touch_corpus(), cl::type, and UNSELECTED_LINES.
Referenced by do_delete_lines(), do_delete_lines_num(), do_reduce(), and do_StandardQuery().
FreeSortClause()
void FreeSortClause (SortClause sc)
Frees a SortClause object.
Used only in the parser.
References _sort_clause::attribute_name, and cl_free.
group2compare()
static int group2compare (const void * vidx1, const void * vidx2) static
Compares two groups of equivalent matches by group sizes (descending), breaking ties through i2compare.
References current_sortidx, EvaluationIsRunning, group_first, group_size, i2compare(), s1, and s2.
Referenced by SortSubcorpus().
i2compare()
static int i2compare (const void * vidx1, const void * vidx2) static
Compare two matches according to current sort settings in static variables (qsort callback used in query result sorting).
This is the primary query-hit-comparison function. It wraps cl_string_qsort_compare for string comparison, but does much more as well, because we are not just comparing individual strings but rather, potentially, whole bundles of strings from various different positions.
Parameters
vidx1 Pointer to the integer index of the first of the intervals to be compared (ie an index into an array of start/end positions).
vidx2 Pointer to the integer index of the second of the intervals to be compared.
Returns
Usual returns for qsort callbacks.
References break_ties, TCorpus::charset, cl_cpos2id(), cl_id2str(), cl_string_qsort_compare(), cl::corpus, EvaluationIsRunning, MIN, s1, s2, SORT_DEBUG, sort_id_cache, srt_ascending, srt_attribute, srt_cl, srt_end, srt_flags, srt_reverse, and srt_start.
Referenced by group2compare(), and SortSubcorpus().
random_compare()
static int random_compare (const void * vidx1, const void * vidx2) static
Sorts hits in random order by comparing random numbers in the vector random_sort_keys[], breaking ties by start and end positions of matches (from *srt_cl) in order to ensure stable sorting.
This is another qsort callback function.
References Range::end, random_sort_keys, cl::range, spaceship, srt_cl, and Range::start.
Referenced by SortSubcorpusRandomize().
RangeSort()
void RangeSort (CorpusList * c, int mk_sortidx)
Make sure that ranges are sorted in 'natural' order (i.e.
by start and end cpos).
This function has to be called when matching ranges are modified and may be needed when loading a query result (with "undump") that is not sorted in ascending order; with optional "mk_sortidx" flag, a sortidx corresponding to the original ordering is created.
Parameters
c The corpus (ie subcorpus/query) whose intervals ('ranges') are to be sorted.
mk_sortidx Boolean flag: if true a sortidx is created.
References _RS_compare_ranges(), _RS_range, cl_free, cl_malloc(), cqpmessage(), Error, cl::keywords, cl::name, cl::range, cl::size, cl::sortidx, SUB, cl::targets, TEMP, cl::type, and Warning.
Referenced by do_translate(), do_undump(), evaluate_target(), and set_target().
rs_cp_range()
static void rs_cp_range (Range * rng, int * target, int * keyword, int ins, CorpusList * corpus, int j) static
this is a rather specialised utility function for the UNION part of RangeSetop() (copies range + keyword/target (if defined) in corpus into temporary lists)
References corpus, Range::end, and Range::start.
Referenced by apply_range_set_operation().
SortExternally()
static int SortExternally (void) static
Use an external program to sort a query.
No parameters - the assumption is that everything is set up already by the SortSubCorpus function which calls this one.
References TCorpus::charset, cl_cpos2str(), cl_free, cl_malloc(), CL_MAX_LINE_LENGTH, cl_string_canonical(), CL_STRING_CANONICAL_STRDUP, cl_string_reverse(), cl::corpus, cqpmessage(), Range::end, Error, ExternalSortCommand, KeywordField, cl::keywords, line, MatchEndField, MatchField, open_temporary_file(), cl::range, cl::size, SORT_DEBUG, cl::sortidx, srt_anchor1, srt_anchor2, srt_ascending, srt_attribute, srt_cl, srt_flags, srt_offset1, srt_offset2, srt_reverse, Range::start, TargetField, cl::targets, TEMP_FILENAME_BUFSIZE, text_size, token, and Warning.
Referenced by SortSubcorpus().
SortSubcorpus()
int SortSubcorpus (CorpusList * cl, SortClause sc, int count_mode, struct Redir * redir)
Sort the (query) subcorpus specified by cl, or count frequencies of matching strings.
(Note that frequency counting and query result sorting are done via the same sorting algorithm.)
If the sort was not performed successfully, the sort index is reset to the default sort order, and the function returns false.
Parameters
cl Subcorpus designating the query to sort.
sc A sort clause. sc = NULL resets the sort index to the default sort order (i.e. sorted by corpus position).
count_mode Boolean: run the function in count frequency mode?
redir Redir object for where the output of string-counting is to be displayed.
Returns
Boolean: true for successful sort, false for unsuccessful.
References access_corpus(), _sort_clause::anchor1, _sort_clause::anchor2, ATT_POS, _sort_clause::attribute_name, break_ties, TCorpus::charset, cl_broken_pipe, cl_cpos2id(), cl_cpos2str(), cl_free, cl_malloc(), cl_max_cpos(), cl_new_attribute(), cl_string_canonical(), CL_STRING_CANONICAL_STRDUP, cl_string_reverse(), close_rd_output_stream(), cl::corpus, cqp, cqpmessage(), current_sortidx, CWB_DEFAULT_ATT_NAME, Range::end, Error, EvaluationIsRunning, _sort_clause::flags, group2compare(), group_first, group_size, i2compare(), Info, insecure, install_signal_handler(), KeywordField, cl::keywords, MatchEndField, MatchField, cl::name, NoField, _sort_clause::offset1, _sort_clause::offset2, open_rd_output_stream(), pretty_print, cl::range, cl::size, _sort_clause::sort_ascending, sort_id_cache, _sort_clause::sort_reverse, SortExternally(), cl::sortidx, srt_anchor1, srt_anchor2, srt_ascending, srt_attribute, srt_cl, srt_end, srt_flags, srt_offset1, srt_offset2, srt_reverse, srt_start, Range::start, Redir::stream, TargetField, cl::targets, text_size, token, touch_corpus(), USE_SORT_CACHE, UseExternalSort, and Warning.
SortSubcorpusRandomize()
int SortSubcorpusRandomize (CorpusList * cl, int seed)
Sorts a query result in random order.
This function is only used by the parser.
If seed > 0, a reproducible and stable ordering is generated based on the start and end corpus positions of matches (i.e. two given matches will always be sorted in the same order).
Parameters
cl Corpus-list object representing the query to sort.
seed Seed for the randomiser; should ideally be a prime number (2^31 is a particularly bad choice); if it is 0, then the internal RNG's standard random order is used.
References access_corpus(), cl_free, cl_malloc(), cl_random(), cl_set_rng_state(), cqp, cqpmessage(), Range::end, Error, EvaluationIsRunning, Info, install_signal_handler(), cl::name, random_compare(), random_sort_keys, cl::range, cl::size, cl::sortidx, srt_cl, Range::start, touch_corpus(), and Warning.
Variable Documentation
_RS_range
Range* _RS_range = NULL static
Variable used by _RS_compare_ranges; global so data can be passed in without going through that function's parameter list!
Referenced by _RS_compare_ranges(), and RangeSort().
break_ties
int break_ties static
whether to break ties (by comparison without cd flags, and by line number in the last instance)
Referenced by i2compare(), and SortSubcorpus().
current_sortidx
int* current_sortidx static
alias to newly created sortidx, so it can be accessed by the callback function
Referenced by group2compare(), and SortSubcorpus().
group_first
int* group_first static
first match for each group of identical (or equivalent) sort strings
Referenced by group2compare(), and SortSubcorpus().
group_size
int* group_size static
number of matches for each group of identical (or equivalent) sort strings
Referenced by group2compare(), and SortSubcorpus().
random_sort_keys
unsigned int* random_sort_keys static
random keys for randomized sort order (ties are broken by cpos of matches)
Referenced by random_compare(), and SortSubcorpusRandomize().
sort_id_cache
int* sort_id_cache = NULL static
Pointer to the sort cache.
See also
USE_SORT_CACHE
Referenced by i2compare(), and SortSubcorpus().
srt_anchor1
FieldType srt_anchor1 static
In a query sort, indicates the field type of the start of sort region.
Referenced by SortExternally(), and SortSubcorpus().
srt_anchor2
FieldType srt_anchor2 static
In a query sort, indicates the field type of the end of sort region.
Referenced by SortExternally(), and SortSubcorpus().
srt_ascending
int srt_ascending static
boolean: sort query into ascending order or not
Referenced by i2compare(), SortExternally(), and SortSubcorpus().
srt_attribute
Attribute* srt_attribute static
The)p-)Attribute on which a query is to be sorted.
Referenced by i2compare(), SortExternally(), and SortSubcorpus().
srt_cl
CorpusList* srt_cl static
The CorpusList object representing a query to be sorted.
Referenced by i2compare(), random_compare(), SortExternally(), SortSubcorpus(), and SortSubcorpusRandomize().
srt_end
int* srt_end static
When sorting a query, this contains end positions of intervals to be sorted.
Referenced by i2compare(), and SortSubcorpus().
srt_flags
int srt_flags static
Whether to use the c and/or d flags when sorting a query.
Referenced by i2compare(), SortExternally(), and SortSubcorpus().
srt_offset1
int srt_offset1 static
In a query sort, indicates the offset of the start of sort region.
Referenced by SortExternally(), and SortSubcorpus().
srt_offset2
int srt_offset2 static
In a query sort, indicates the offset of the end of sort region.
Referenced by SortExternally(), and SortSubcorpus().
srt_reverse
int srt_reverse static
boolean: sort query on reversed-character-sequence strings (and reversed sequences OF strings) or not
Referenced by i2compare(), SortExternally(), and SortSubcorpus().
srt_start
int* srt_start static
When sorting a query, this contains start positions of intervals to be sorted.
Referenced by i2compare(), and SortSubcorpus().
text_size
int text_size static
When sorting a query - this represents the size of the corpus the query belongs to.
Referenced by compose_kwic_line(), SortExternally(), and SortSubcorpus().