CWB: cqp/regex2dfa.c File Reference
regex2dfa.c File Reference
Regular expression to DFA converter – originally written by markh.nosp@m.@csd.nosp@m.4.csd.nosp@m..uwm.nosp@m..edu.
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdarg.h>
#include <stdlib.h>
#include <assert.h>
#include "../cl/cl.h"
#include "cqp.h"
#include "eval.h"
#include "options.h"
#include "regex2dfa.h"
Data Structures
struct StackCard
A StackCard combines a StackTag with a Q integer.
struct state
A State object.
struct item
Item object: combines an LHS symbol with an RHS integer array (tracked by Size).
struct exp
content for Expression object
struct symbol
struct equation
struct Equiv
The Equiv Table or ETab: array of Equiv structs (each of which links an L State to an R State).
Macros
#define MAX_CHAR 0x4000
16kb length of this module's "character space" buffer.
#define MAX_ERRORS 25
The maximum number of errors that the regex2dfa module will allow before killing the program.
#define HASH_MAX 0x200
Maximum size of the symbol hash array (number of buckets)
#define NN 0x200
Size of the expression hash array (number of buckets).
#define EQU_EXTEND 0x200
number of slots added to the EquTab when it is reallocated.
#define STACK_MAX 200
Size of the Stack of StackCards.
#define X_EXTEND 4
number of slots added to the XStack when it is reallocated.
#define ETAB_EXTEND 8
Number of slots added to the ETab when it is reallocated.
#define TOP ((SP - 1)->Tag)
Evals to the Tag of the card at the top of the stack.
#define POP() (unused_junk_value = ((--SP)->Q))
Moves the tracker pointer backwards by one, then returns the Q value of the stack card it is now pointing to.
Typedefs
typedef unsigned char byte
typedef struct symbol * Symbol
Symbol object: a particular string, living in a hash table, which can thus be referenced.
typedef struct exp * Exp
typedef struct equation * Equation
typedef struct state * State
A State object.
typedef struct item * Item
Item object: combines an LHS symbol with an RHS integer array (tracked by Size).
Enumerations
enum ExpTag {
SymX , ZeroX , OneX , AndX ,
OrX , StarX , PlusX , OptX
}
Expression (X) tag: one of Sym, Zero, One, And, Or, Star, Plus, Opt.
enum StackTag {
RULE , EQU , PAR , OPT ,
OR , AND
}
Stack tag: one of RULE, EQU, PAR, OPT, OR, AND.
enum Lexical {
EndT , CommaT , RParT , RBrT ,
EqualT , BarT , ZeroT , OneT ,
IdenT , LParT , LBrT , PlusT ,
StarT
}
Lexer symbols.
Functions
static int GET (void)
Gets the next character from the searchstr, and increments its pointer; returns EOF if we are at the end of the string.
static void UNGET (int Ch)
Ungets a character from the search string (by decrementing the index into the search string; the actual string itself isn't modified).
static void REGEX2DFA_ERROR (char *Format,...)
Prints an error message to stdout, and exits the program if there are now just too many errors.
static Lexical LEX (void)
Gets the Lexical symbol corresponding to the next non-whitespace character in the searchstr (lexer function)
static byte Hash (char *S)
Creates a one-byte hash of the string S.
static Symbol LookUp (char *S)
Get the Symbol corresponding to the string argument S.
static int DUP (int A, int B)
static void Store (Symbol S, int Q)
Finds or creates the Expression whose Leaf is the given Symbol, and sets its Class to the Q integer.
static int MakeExp (int Q, ExpTag Tag,...)
static void PUSH (StackTag Tag, int Q)
Pushes a Tag / Q combination onto the stack of cards.
static int Parse (void)
the regex parser proper
static void PushQ (int Q)
static void PopQ (void)
static int AddState (int States, int *SList)
Adds a State with the given SList into STab (or finds one that already exists); returns the index of that State in STab.
static void AddBuf (Symbol LHS, int Q)
Adds to the item buffer: looks up (or creates) an Item with the LHS Symbol, and adds the Q to its RHS array if it's not already there.
static void FormState (int Q)
NB.
static void AddEquiv (int L, int R)
static void MergeStates (void)
static void WriteStates (void)
Write states to stdout.
void init_dfa (DFA *dfa)
Initialises the members of the argument DFA object.
void free_dfa (DFA *dfa)
Frees all the memory associated with the argument DFA.
void show_complete_dfa (DFA dfa)
Prints the contents of a DFA to stdout.
static void init (void)
Initialises the global variables in the regex2dfa module, also freeing any previously-allocated memory.
void regex2dfa (char *rxs, DFA *automaton)
Converts a regular expression to a DFA.
Variables
char * searchstr
Global variable containing a search string that is to be converted to a DFA.
State STab = (State)NULL
Table of state objects.
int Ss
Index into the STab table of state objects.
Item IBuf = (Item)NULL
Buffer for item objects.
int Is
Index for the next available slot in the buffer of Items (.
int IMax
Number of currently available slots in the item buffer (.
char * Action [7]
Block of lookup data.
char * LastW
pointer to "last word" within the character space (tracks a marked point when ChP is incremented further along).
static char ChArr [MAX_CHAR]
char * ChP
int LINE
Tracks the current line number within the input string (starting from 1).
int ERRORS
The number of errors enocuntered while parsing a regex to a DFA.
Symbol HashTab [HASH_MAX]
Global hash table containing Symbols (particular strings).
Symbol FirstB
Pointer to the list in the first-created bucket of HashTab.
Symbol LastB
Pointer to the list in the most recently created bucket of HashTab.
Exp ExpHash [NN]
Expression hash table : array of pointers, where each pointer = head of a bucket linked list.
Equation EquTab = (Equation)NULL
Equation table : array of Equation objects.
int Equs
Index of the next unfilled "slot" in the EquTab.
int EquMax
Current number of slots in the.
StackCard Stack [STACK_MAX]
Stack (of stack cards)
StackCard * SP
Tracking pointer into the Stack (of stack cards)
int * XStack = NULL
The XStack array of integers.
int Xs
Index of next unfilled "slot" in the XStack.
int XMax
Current maximum size of the XStack.
struct Equiv * ETab = NULL
int Es
Index of next unfilled "slot" in the ETab.
int EMax
Current maximum size of the ETab.
int currpos
Index into searchstr showing the next character that will be read.
static int unused_junk_value
Detailed Description
Regular expression to DFA converter – originally written by markh.nosp@m.@csd.nosp@m.4.csd.nosp@m..uwm.nosp@m..edu.
Derived from the syntax:
Rule = (ID "=" Ex ",")* Ex.
Ex = "0" | "1" | ID | "(" Ex ")" | "[" Ex "]" | Ex "+" | Ex "*" | Ex Ex | Ex "|" Ex.
with the usual precedence rules.
(Note, this is the token-sequence regex = not the string-level regex!
Macro Definition Documentation
EQU_EXTEND
#define EQU_EXTEND 0x200
number of slots added to the EquTab when it is reallocated.
ETAB_EXTEND
#define ETAB_EXTEND 8
Number of slots added to the ETab when it is reallocated.
HASH_MAX
#define HASH_MAX 0x200
Maximum size of the symbol hash array (number of buckets)
MAX_CHAR
#define MAX_CHAR 0x4000
16kb length of this module's "character space" buffer.
MAX_ERRORS
#define MAX_ERRORS 25
The maximum number of errors that the regex2dfa module will allow before killing the program.
NN
#define NN 0x200
Size of the expression hash array (number of buckets).
See also
ExpHash
POP
#define POP () (unused_junk_value = ((--SP)->Q))
Moves the tracker pointer backwards by one, then returns the Q value of the stack card it is now pointing to.
STACK_MAX
#define STACK_MAX 200
Size of the Stack of StackCards.
TOP
#define TOP ((SP - 1)->Tag)
Evals to the Tag of the card at the top of the stack.
X_EXTEND
#define X_EXTEND 4
number of slots added to the XStack when it is reallocated.
Typedef Documentation
byte
typedef unsigned char byte
Equation
typedef struct equation* Equation
Exp
typedef struct exp* Exp
Item
typedef struct item * Item
Item object: combines an LHS symbol with an RHS integer array (tracked by Size).
State
typedef struct state * State
A State object.
Symbol
typedef struct symbol* Symbol
Symbol object: a particular string, living in a hash table, which can thus be referenced.
Enumeration Type Documentation
ExpTag
enum ExpTag
Expression (X) tag: one of Sym, Zero, One, And, Or, Star, Plus, Opt.
Enumerator
SymX
ZeroX
OneX
AndX
OrX
StarX
PlusX
OptX
Lexical
enum Lexical
Lexer symbols.
Enumerator
EndT
CommaT
RParT
RBrT
EqualT
BarT
ZeroT
OneT
IdenT
LParT
LBrT
PlusT
StarT
StackTag
enum StackTag
Stack tag: one of RULE, EQU, PAR, OPT, OR, AND.
Enumerator
RULE
EQU
PAR
OPT
OR
AND
Function Documentation
AddBuf()
static void AddBuf (Symbol LHS, int Q) static
Adds to the item buffer: looks up (or creates) an Item with the LHS Symbol, and adds the Q to its RHS array if it's not already there.
References cl_realloc(), IBuf, IMax, Is, item::LHS, symbol::Name, item::RHS, and item::Size.
Referenced by FormState().
AddEquiv()
static void AddEquiv (int L, int R) static
References cl_realloc(), state::Class, EMax, Es, ETab, ETAB_EXTEND, Equiv::L, Equiv::R, and STab.
Referenced by MergeStates().
AddState()
static int AddState (int States, int * SList) static
Adds a State with the given SList into STab (or finds one that already exists); returns the index of that State in STab.
References cl_free, cl_realloc(), state::Class, state::SList, Ss, STab, and state::States.
Referenced by FormState().
DUP()
static int DUP (int A, int B) static
References NN.
Referenced by MakeExp().
FormState()
static void FormState (int Q) static
NB.
As used in regex2dfa, qv, Q is the return value from Parse()
References AddBuf(), AddState(), AndX, exp::Arg, exp::Body, cl_free, cl_malloc(), EquTab, IBuf, IMax, Is, exp::Leaf, item::LHS, MakeExp(), OneX, OptX, OrX, PlusX, PopQ(), PushQ(), SP, Ss, STab, StarX, SymX, exp::Tag, equation::Value, Xs, XStack, and ZeroX.
Referenced by regex2dfa().
free_dfa()
void free_dfa (DFA * dfa)
Frees all the memory associated with the argument DFA.
References cl_free, dfa::Final, dfa::Max_Input, dfa::Max_States, and dfa::TransTable.
Referenced by free_environment().
GET()
static int GET (void) static
Gets the next character from the searchstr, and increments its pointer; returns EOF if we are at the end of the string.
See also
searchstr
currpos
References currpos, and searchstr.
Referenced by LEX().
Hash()
static byte Hash (char * S) static
Creates a one-byte hash of the string S.
Referenced by LookUp(), and MakeExp().
init()
static void init (void) static
Initialises the global variables in the regex2dfa module, also freeing any previously-allocated memory.
References ChArr, ChP, cl_free, currpos, EquMax, Equs, EquTab, ERRORS, ETab, ExpHash, FirstB, HASH_MAX, HashTab, IBuf, LINE, NN, Ss, STab, XMax, Xs, and XStack.
Referenced by cl_hash_string(), and regex2dfa().
init_dfa()
void init_dfa (DFA * dfa)
Initialises the members of the argument DFA object.
References dfa::Final, dfa::Max_Input, dfa::Max_States, and dfa::TransTable.
Referenced by next_environment().
LEX()
static Lexical LEX (void) static
Gets the Lexical symbol corresponding to the next non-whitespace character in the searchstr (lexer function)
References BarT, ChArr, ChP, CommaT, cqp_error_status, EndT, EqualT, GET(), IdenT, LastW, LBrT, LParT, MAX_CHAR, OneT, PlusT, RBrT, REGEX2DFA_ERROR(), RParT, StarT, UNGET(), and ZeroT.
Referenced by Parse().
LookUp()
static Symbol LookUp (char * S) static
Get the Symbol corresponding to the string argument S.
How it works: (1) Look up the symbol contained in string S in the Symbol table, and return if found. If not found, (2) a new Symbol object is added to the correct bucket of the table and returned. In the latter case, the new Symbol's pointer will be stored in LastB/FirstB as necessary.
Returns
Symbol object for the string in question.
References cl_malloc(), cl_strdup(), FirstB, symbol::Hash, Hash(), HashTab, LastB, symbol::Name, symbol::Next, and symbol::Tail.
Referenced by Parse().
MakeExp()
static int MakeExp (int Q, ExpTag Tag, ...) static
References AndX, exp::Arg, exp::Body, cl_malloc(), cl_realloc(), exp::Class, DUP(), EQU_EXTEND, EquMax, Equs, EquTab, ExpHash, exp::Hash, symbol::Hash, equation::Hash, Hash(), exp::Leaf, OneX, OptX, OrX, PlusX, equation::Stack, StarX, SymX, Tag, exp::Tag, exp::Tail, equation::Value, and ZeroX.
Referenced by FormState(), and Parse().
MergeStates()
static void MergeStates (void) static
References AddEquiv(), state::Class, EMax, state::Empty, Es, ETab, Equiv::L, state::LHS, Equiv::R, state::RHS, state::Shifts, state::ShList, SP, Ss, and STab.
Referenced by regex2dfa().
Parse()
static int Parse (void) static
the regex parser proper
References Action, AND, AndX, cqp_error_status, EQU, EqualT, IdenT, LastW, LBrT, LEX(), LookUp(), LParT, MakeExp(), OneT, OneX, OPT, OptX, OR, OrX, PAR, PlusX, POP, PUSH(), REGEX2DFA_ERROR(), RULE, SP, Stack, StarX, Store(), SymX, TOP, ZeroT, and ZeroX.
Referenced by regex2dfa().
PopQ()
static void PopQ (void) static
References EquTab, equation::Stack, Xs, and XStack.
Referenced by FormState().
PUSH()
static void PUSH (StackTag Tag, int Q) static
Pushes a Tag / Q combination onto the stack of cards.
References cqp_error_status, StackCard::Q, REGEX2DFA_ERROR(), SP, Stack, STACK_MAX, Tag, and StackCard::Tag.
Referenced by Parse().
PushQ()
static void PushQ (int Q) static
References cl_realloc(), EquTab, equation::Stack, Stack, X_EXTEND, XMax, Xs, and XStack.
Referenced by FormState().
regex2dfa()
void regex2dfa (char * rxs, DFA * automaton)
Converts a regular expression to a DFA.
Public function.
Parameters
rxs The regular expression.
automaton Pointer to the DFA object to write to.
References C, cl_malloc(), state::Class, cqp_error_status, dfa::E_State, ee_ix, Environment, ERRORS, False, dfa::Final, FormState(), init(), dfa::Max_Input, dfa::Max_States, evalenv::MaxPatIndex, MergeStates(), Parse(), searchstr, show_dfa, SP, Ss, STab, dfa::TransTable, True, and WriteStates().
Referenced by do_SearchPattern().
REGEX2DFA_ERROR()
static void REGEX2DFA_ERROR (char * Format, ...) static
Prints an error message to stdout, and exits the program if there are now just too many errors.
(In almost every case, exit() will be called straight after this function anyway.)
References cqp_error_status, ERRORS, LINE, and MAX_ERRORS.
Referenced by LEX(), Parse(), and PUSH().
show_complete_dfa()
void show_complete_dfa (DFA dfa)
Prints the contents of a DFA to stdout.
References dfa::E_State, dfa::Final, dfa::Max_Input, dfa::Max_States, and dfa::TransTable.
Referenced by show_environment().
Store()
static void Store (Symbol S, int Q) static
Finds or creates the Expression whose Leaf is the given Symbol, and sets its Class to the Q integer.
References exp::Body, cl_malloc(), exp::Class, ExpHash, exp::Hash, symbol::Hash, exp::Leaf, SymX, exp::Tag, and exp::Tail.
Referenced by Parse().
UNGET()
static void UNGET (int Ch) static
Ungets a character from the search string (by decrementing the index into the search string; the actual string itself isn't modified).
Parameters
Ch Ignored.
References currpos.
Referenced by LEX().
WriteStates()
static void WriteStates (void) static
Write states to stdout.
References C, state::Class, SP, Ss, and STab.
Referenced by regex2dfa().
Variable Documentation
Action
char* Action[7]
Initial value:
=
{
  ".ABCH|&&&&&+*",
  "I=BCH|&&&&&+*",
  "DD)FH|&&&&&+*",
  "EEG]H|&&&&&+*",
  "vvvvv|&&&&&+*",
  "xxxxxx&&&&&+*"
}
Block of lookup data.
Referenced by Parse().
ChArr
char ChArr[MAX_CHAR] static
Referenced by init(), and LEX().
ChP
char* ChP
Referenced by init(), and LEX().
currpos
int currpos
Index into searchstr showing the next character that will be read.
Referenced by GET(), init(), and UNGET().
EMax
int EMax
Current maximum size of the ETab.
Referenced by AddEquiv(), and MergeStates().
EquMax
int EquMax
Current number of slots in the.
See also
EquTab
Referenced by init(), and MakeExp().
Equs
int Equs
Index of the next unfilled "slot" in the EquTab.
Referenced by init(), and MakeExp().
EquTab
Equation EquTab = (Equation)NULL
Equation table : array of Equation objects.
Referenced by FormState(), init(), MakeExp(), PopQ(), and PushQ().
ERRORS
int ERRORS
The number of errors enocuntered while parsing a regex to a DFA.
Referenced by init(), regex2dfa(), and REGEX2DFA_ERROR().
Es
int Es
Index of next unfilled "slot" in the ETab.
Referenced by AddEquiv(), and MergeStates().
ETab
struct Equiv * ETab = NULL
Referenced by AddEquiv(), init(), and MergeStates().
ExpHash
Exp ExpHash[NN]
Expression hash table : array of pointers, where each pointer = head of a bucket linked list.
Referenced by init(), MakeExp(), and Store().
FirstB
Symbol FirstB
Pointer to the list in the first-created bucket of HashTab.
Referenced by init(), and LookUp().
HashTab
Symbol HashTab[HASH_MAX]
Global hash table containing Symbols (particular strings).
Referenced by init(), and LookUp().
IBuf
Item IBuf = (Item)NULL
Buffer for item objects.
Referenced by AddBuf(), FormState(), and init().
IMax
int IMax
Number of currently available slots in the item buffer (.
See also
IBuf).
Referenced by AddBuf(), and FormState().
Is
int Is
Index for the next available slot in the buffer of Items (.
See also
IBuf).
Referenced by AddBuf(), and FormState().
LastB
Symbol LastB
Pointer to the list in the most recently created bucket of HashTab.
Referenced by LookUp().
LastW
char* LastW
pointer to "last word" within the character space (tracks a marked point when ChP is incremented further along).
Referenced by LEX(), and Parse().
LINE
int LINE
Tracks the current line number within the input string (starting from 1).
Referenced by init(), and REGEX2DFA_ERROR().
searchstr
char* searchstr
Global variable containing a search string that is to be converted to a DFA.
(Needs to be global; functions using the DFA write to it, and then the DFA parser reads from it. Declared as an external global in cqp.h so other parts of CQP can access it. The actual space is not allocated here, rather a pointer, passed as an argument to regex2dfa(), is copied here.)
Referenced by do_SearchPattern(), do_StandardQuery(), GET(), prepare_input(), prepare_Query(), and regex2dfa().
SP
StackCard* SP
Tracking pointer into the Stack (of stack cards)
See also
Stack
Referenced by FormState(), MergeStates(), Parse(), PUSH(), regex2dfa(), and WriteStates().
Ss
int Ss
Index into the STab table of state objects.
Referenced by AddState(), FormState(), init(), MergeStates(), regex2dfa(), and WriteStates().
STab
State STab = (State)NULL
Table of state objects.
Referenced by AddEquiv(), AddState(), FormState(), init(), MergeStates(), regex2dfa(), and WriteStates().
Stack
StackCard Stack[STACK_MAX]
Stack (of stack cards)
Referenced by Parse(), PUSH(), and PushQ().
unused_junk_value
int unused_junk_value static
XMax
int XMax
Current maximum size of the XStack.
Referenced by init(), and PushQ().
Xs
int Xs
Index of next unfilled "slot" in the XStack.
Referenced by FormState(), init(), PopQ(), and PushQ().
XStack
int* XStack = NULL
The XStack array of integers.
This is where "Q" integers are pushed to/popped from.
Referenced by FormState(), init(), PopQ(), and PushQ().