CWB: cqp/regex2dfa.h File Reference
regex2dfa.h File Reference
#include "cqp.h"
Data Structures
struct dfa
The DFA object.
Typedefs
typedef struct dfa DFA
The DFA object.
Functions
void regex2dfa (char *rxs, DFA *dfa)
Converts a regular expression to a DFA.
void init_dfa (DFA *dfa)
Initialises the members of the argument DFA object.
void free_dfa (DFA *dfa)
Frees all the memory associated with the argument DFA.
void show_complete_dfa (DFA dfa)
Prints the contents of a DFA to stdout.
Typedef Documentation
DFA
typedef struct dfa DFA
The DFA object.
A Deterministic Finite Automaton: into which a regular expression can be converted.
(Note this is regular expression across tokens, not single-string regexes, which are dealt with by functions in the corpus library.)
The RX-to-DFA parser is not in keeping with the rest of the CWB code in terms of style etc., reflecting its origins. So this object does not behave much like others. In particular, all the info to make a DFA has to be passed in via global variables.
Function Documentation
free_dfa()
void free_dfa (DFA * dfa)
Frees all the memory associated with the argument DFA.
References cl_free, dfa::Final, dfa::Max_Input, dfa::Max_States, and dfa::TransTable.
Referenced by free_environment().
init_dfa()
void init_dfa (DFA * dfa)
Initialises the members of the argument DFA object.
References dfa::Final, dfa::Max_Input, dfa::Max_States, and dfa::TransTable.
Referenced by next_environment().
regex2dfa()
void regex2dfa (char * rxs, DFA * automaton)
Converts a regular expression to a DFA.
Public function.
Parameters
rxs The regular expression.
automaton Pointer to the DFA object to write to.
References C, cl_malloc(), state::Class, cqp_error_status, dfa::E_State, ee_ix, Environment, ERRORS, False, dfa::Final, FormState(), init(), dfa::Max_Input, dfa::Max_States, evalenv::MaxPatIndex, MergeStates(), Parse(), searchstr, show_dfa, SP, Ss, STab, dfa::TransTable, True, and WriteStates().
Referenced by do_SearchPattern().
show_complete_dfa()
void show_complete_dfa (DFA dfa)
Prints the contents of a DFA to stdout.
References dfa::E_State, dfa::Final, dfa::Max_Input, dfa::Max_States, and dfa::TransTable.
Referenced by show_environment().