CWB: CQi/server.h File Reference
server.h File Reference
#include "../cl/cl.h"
#include "../cqp/corpmanag.h"
Macros
#define check_corpus_name(name) (check_identifier_convention((name), 1, 1, 0))
Checks a corpus name for validity of format (not whether or not it actually exists!), i.e.
#define check_attribute_name(name) (check_identifier_convention((name), 0, 0, 0))
Checks an attribute name for validity of format (not whether or not it actually exists!), i.e.
#define check_subcorpus_name(name) (check_identifier_convention((name), 1, 0, 1))
Checks a subcorpus/NQR name for validity of format (not whether or not it actually exists!), i.e.
Typedefs
typedef unsigned char cqi_byte
Functions
void cqi_general_error (char *errstring)
General error reporting function.
void cqiserver_snoop (const char *format,...)
Print network communication snooping info on stderr (if global "snoop" option is true).
void cqiserver_debug_msg (const char *format,...)
Print server debug message on stderr (if global "server_debug" option is true).
int accept_connection (int port)
Wait for, and then process, an attempt by a client to initiate a connection to cqpserver via TCP/IP.
int cqi_flush (void)
Flushes the stream from the CQP server to the client program, emptying its buffer.
int cqi_send_byte (int n, int nosnoop)
Sends a BYTE to the client.
int cqi_send_word (int n)
Sends a WORD to the client.
int cqi_send_int (int n)
Sends an INT to the client.
int cqi_send_string (const char *str)
Sends a STRING to the client.
int cqi_send_byte_list (cqi_byte *list, int length, int as_boolean)
Sends a BYTE[] (byte list) to the client.
int cqi_send_int_list (int *list, int length)
Sends an INT[] (integer list) to the client.
int cqi_send_string_list (char **list, int length)
Sends a STRING[] (string list) to the client.
void cqi_command (int command)
Sends a general CQi command, without any arguments.
void cqi_data_byte (int n)
Sends a byte of data to the client.
void cqi_data_bool (int n)
Sends a boolean to the client.
void cqi_data_int (int n)
Sends an integer to the client.
void cqi_data_string (const char *str)
Sends a string to the client.
void cqi_data_byte_list (cqi_byte *list, int length)
Sends a byte list to the client.
void cqi_data_bool_list (cqi_byte *list, int length)
Sends a list of booleans to the client.
void cqi_data_int_list (int *list, int length)
Sends a list of integers to the client.
void cqi_data_string_list (char **list, int length)
Sends a list of strings to the client.
void cqi_data_int_int (int n1, int n2)
Sends a sequence of two integers to the client.
void cqi_data_int_int_int_int (int n1, int n2, int n3, int n4)
Sends a sequence of four integers to the client.
int cqi_recv_bytes (cqi_byte *buf, int n)
int cqi_recv_byte (void)
int cqi_read_byte (void)
int cqi_read_bool (void)
int cqi_read_word (void)
int cqi_read_int (void)
char * cqi_read_string (void)
int cqi_read_byte_list (cqi_byte **list)
int cqi_read_bool_list (cqi_byte **list)
int cqi_read_int_list (int **list)
int cqi_read_string_list (char ***list)
int cqi_read_command (void)
int check_identifier_convention (char *name, int init_cap, int rest_cap, int rest_any)
Makes sure that an identifier complies with the specified convention regarding its initial and subsequent characters.
int split_attribute_spec (char *spec, char **corpus_name, char **attribute_name)
new strings are allocated for the output arguments
int split_subcorpus_spec (char *spec, char **corpus_name, char **subcorpus_name)
char * combine_subcorpus_spec (char *corpus_name, char *subcorpus_name)
void make_attribute_hash (int size)
This function has to be called once to initialise the global attribute hash.
void free_attribute_hash (void)
Frees the global AttHash object and the space that it points to.
Attribute * cqi_lookup_attribute (char *name, int type)
int cqi_drop_attribute (char *name)
Drops the named attribute from memory.
CorpusList * cqi_find_corpus (char *name)
Gets a pointer to the corpus with the given name.
int cqi_activate_corpus (char *name)
Activates the named corpus.
Variables
int cqi_errno
CQi last error.
char cqi_error_string []
String describing the last CQi error.
Macro Definition Documentation
check_attribute_name
#define check_attribute_name (name) (check_identifier_convention((name), 0, 0, 0))
Checks an attribute name for validity of format (not whether or not it actually exists!), i.e.
all-lower_case
check_corpus_name
#define check_corpus_name (name) (check_identifier_convention((name), 1, 1, 0))
Checks a corpus name for validity of format (not whether or not it actually exists!), i.e.
ALL-UPPER_CASE
check_subcorpus_name
#define check_subcorpus_name (name) (check_identifier_convention((name), 1, 0, 1))
Checks a subcorpus/NQR name for validity of format (not whether or not it actually exists!), i.e.
First_upper-rest_EiThEr
Typedef Documentation
cqi_byte
typedef unsigned char cqi_byte
Function Documentation
accept_connection()
int accept_connection (int port)
Wait for, and then process, an attempt by a client to initiate a connection to cqpserver via TCP/IP.
Note that this function may or may not fork the cqpserver process.
If forking happens, then the child handles the connection, whereas the parent carries on waiting for further connections.
On Windows, forking never happens (since Windows doesn't support it).
On *nix, forking happens UNLESS the global private_server is true. (Actually, if private_server is true, then forking still happens, but the parent process immeidately exits.)
Parameters
port The integer identifier of the port to listen on.
Returns
A > 0 value (the socket ID of the incoming connection) if all is OK; otherwise -1.
References ATTHASHSIZE, check_host(), client_addr, conn_out, connfd, CQI_PORT, cqiserver_debug_msg(), cqiserver_log(), cqp_error_status, Error, Info, localhost, make_attribute_hash(), private_server, remote_address, remote_host, server_quit, and sockfd.
Referenced by main().
check_identifier_convention()
int check_identifier_convention (char * name, int init_cap, int rest_cap, int rest_any)
Makes sure that an identifier complies with the specified convention regarding its initial and subsequent characters.
If the identifier does not conform, cqi_errno is set and the function returns false.
Parameters
name The identifier to check.
init_cap If true, the initial char must be uppercase or underscore. If false, it can be lowercase or underscore.
rest_cap If true, subsequent chars must be uppercase or underscore. If false, they must be lowercase or underscore or hyphen.
rest_any If true, rest_cap is overridden: any valid identifier char is accepted. If false, the value given as rest_cap is enforced.
Returns
Boolean: is the identifier in accordance with convention?
References cqi_errno, CQI_ERROR_SYNTAX_ERROR, cqi_id_all, cqi_id_lc, cqi_id_lc_first, cqi_id_uc, cqi_id_uc_first, and CQI_STATUS_OK.
combine_subcorpus_spec()
char* combine_subcorpus_spec (char * corpus_name, char * subcorpus_name)
References cl_malloc(), cl_strdup(), and corpus.
Referenced by do_cqi_cqp_query().
cqi_activate_corpus()
int cqi_activate_corpus (char * name)
Activates the named corpus.
References cqi_find_corpus(), cqiserver_debug_msg(), and set_current_corpus().
Referenced by do_cqi_cqp_query().
cqi_command()
void cqi_command (int command)
Sends a general CQi command, without any arguments.
References cqi_flush(), cqi_send_error(), and cqi_send_word().
Referenced by cqi_general_error(), do_cqi_cl_alg2cpos(), do_cqi_cl_attribute_size(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_id2cpos(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), do_cqi_cl_lexicon_size(), do_cqi_cl_regex2id(), do_cqi_cl_str2id(), do_cqi_cl_struc2cpos(), do_cqi_cl_struc2str(), do_cqi_corpus_attributes(), do_cqi_corpus_charset(), do_cqi_corpus_full_name(), do_cqi_corpus_structural_attribute_has_values(), do_cqi_cqp_drop_subcorpus(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), do_cqi_cqp_query(), do_cqi_cqp_subcorpus_has_field(), do_cqi_cqp_subcorpus_size(), interpreter(), main(), and send_cl_error().
cqi_data_bool()
void cqi_data_bool (int n)
Sends a boolean to the client.
References CQI_CONST_FALSE, CQI_CONST_TRUE, CQI_DATA_BOOL, cqi_flush(), cqi_send_byte(), cqi_send_error(), and cqi_send_word().
Referenced by do_cqi_corpus_structural_attribute_has_values(), do_cqi_cqp_subcorpus_has_field(), and interpreter().
cqi_data_bool_list()
void cqi_data_bool_list (cqi_byte * list, int l)
Sends a list of booleans to the client.
Parameters
list pointer to a block of booleans (each occupying one byte) to send.
l the number of bytes to send.
References CQI_DATA_BOOL_LIST, cqi_flush(), cqi_send_byte_list(), cqi_send_error(), and cqi_send_word().
cqi_data_byte()
void cqi_data_byte (int n)
Sends a byte of data to the client.
References CQI_CONST_FALSE, CQI_CONST_TRUE, CQI_DATA_BYTE, cqi_flush(), cqi_send_byte(), cqi_send_error(), and cqi_send_word().
cqi_data_byte_list()
void cqi_data_byte_list (cqi_byte * list, int l)
Sends a byte list to the client.
Parameters
list pointer to a block of bytes to send.
l the number of bytes to send.
References CQI_DATA_BYTE_LIST, cqi_flush(), cqi_send_byte_list(), cqi_send_error(), and cqi_send_word().
cqi_data_int()
void cqi_data_int (int n)
Sends an integer to the client.
References CQI_DATA_INT, cqi_flush(), cqi_send_error(), cqi_send_int(), and cqi_send_word().
Referenced by do_cqi_cl_attribute_size(), do_cqi_cl_lexicon_size(), and do_cqi_cqp_subcorpus_size().
cqi_data_int_int()
void cqi_data_int_int (int n1, int n2)
Sends a sequence of two integers to the client.
Parameters
n1 The first integer sent
n2 The second integer sent
References CQI_DATA_INT_INT, cqi_flush(), cqi_send_error(), cqi_send_int(), and cqi_send_word().
Referenced by do_cqi_cl_struc2cpos().
cqi_data_int_int_int_int()
void cqi_data_int_int_int_int (int n1, int n2, int n3, int n4)
Sends a sequence of four integers to the client.
Parameters
n1 The first integer sent
n2 The second integer sent
n3 The third integer sent
n4 The fourth integer sent
References CQI_DATA_INT_INT_INT_INT, cqi_flush(), cqi_send_error(), cqi_send_int(), and cqi_send_word().
Referenced by do_cqi_cl_alg2cpos().
cqi_data_int_list()
void cqi_data_int_list (int * list, int l)
Sends a list of integers to the client.
Parameters
list pointer to a block of integers to send.
l the number of integers to send.
References CQI_DATA_INT_LIST, cqi_flush(), cqi_send_error(), cqi_send_int_list(), and cqi_send_word().
Referenced by do_cqi_cl_id2cpos(), do_cqi_cl_idlist2cpos(), and do_cqi_cl_regex2id().
cqi_data_string()
void cqi_data_string (const char * str)
Sends a string to the client.
References CQI_DATA_STRING, cqi_flush(), cqi_send_error(), cqi_send_string(), and cqi_send_word().
Referenced by do_cqi_corpus_charset(), do_cqi_corpus_full_name(), and interpreter().
cqi_data_string_list()
void cqi_data_string_list (char ** list, int l)
Sends a list of strings to the client.
Parameters
list pointer to a block of pointers-to-strings; the strings will be sent.
l the number of strings to send.
References CQI_DATA_STRING_LIST, cqi_flush(), cqi_send_error(), cqi_send_string_list(), and cqi_send_word().
Referenced by do_cqi_corpus_properties().
cqi_drop_attribute()
int cqi_drop_attribute (char * name)
Drops the named attribute from memory.
The attribute name is looked up in the global hash, and then cl_delete_attribute() is called on the result.
See also
cl_delete_attribute
Parameters
name Name of the attribute to be deleted
Returns
Boolean: true for all OK, otherwise false
References att_hash_lookup(), ATT_NONE, att_bucket::attribute, cl_delete_attribute(), and att_bucket::type.
cqi_find_corpus()
CorpusList* cqi_find_corpus (char * name)
Gets a pointer to the corpus with the given name.
References access_corpus(), check_corpus_name, cl_free, corpus, CQI_CQP_ERROR_NO_SUCH_CORPUS, cqi_errno, CQI_STATUS_OK, findcorpus(), split_subcorpus_spec(), SUB, and SYSTEM.
Referenced by cqi_activate_corpus(), do_cqi_cqp_drop_subcorpus(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), do_cqi_cqp_query(), do_cqi_cqp_subcorpus_has_field(), and do_cqi_cqp_subcorpus_size().
cqi_flush()
int cqi_flush (void)
Flushes the stream from the CQP server to the client program, emptying its buffer.
Note that under windows, buffered output is not possible, so this function does nothing.
Returns
Boolean: true if everything OK, otherwise false.
References conn_out, and cqiserver_snoop().
Referenced by cqi_command(), cqi_data_bool(), cqi_data_bool_list(), cqi_data_byte(), cqi_data_byte_list(), cqi_data_int(), cqi_data_int_int(), cqi_data_int_int_int_int(), cqi_data_int_list(), cqi_data_string(), cqi_data_string_list(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), do_cqi_cl_str2id(), do_cqi_cl_struc2str(), do_cqi_corpus_list_corpora(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), do_cqi_cqp_subcorpus_has_field(), and send_cqi_corpus_attributes().
cqi_general_error()
void cqi_general_error (char * errstring)
General error reporting function.
Note that unlike other CQi error functions, this function sends an error message to the outgoing connection, rather than printing to the server's STDERR. Also note that the program doesn't exit!
The error message is placed into the global variable cqi_error_string, whence it can be accessed by the client if the CQI_CTRL_LAST_GENERAL_ERROR is sent to the server.
Parameters
errstring String containing the error message.
References cqi_command(), CQI_ERROR_GENERAL_ERROR, cqi_error_string, cqi_internal_error(), and GENERAL_ERROR_SIZE.
Referenced by do_cqi_cl_drop_attribute(), and do_cqi_corpus_attributes().
cqi_lookup_attribute()
Attribute* cqi_lookup_attribute (char * name, int type)
References access_corpus(), att_hash_lookup(), att_bucket::attribute, cl_new_attribute(), cl::corpus, CQI_CL_ERROR_NO_SUCH_ATTRIBUTE, CQI_CL_ERROR_WRONG_ATTRIBUTE_TYPE, CQI_CQP_ERROR_NO_SUCH_CORPUS, cqi_errno, CQI_STATUS_OK, cqiserver_debug_msg(), findcorpus(), split_attribute_spec(), SYSTEM, and att_bucket::type.
Referenced by do_cqi_cl_alg2cpos(), do_cqi_cl_attribute_size(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_id2cpos(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), do_cqi_cl_lexicon_size(), do_cqi_cl_regex2id(), do_cqi_cl_str2id(), do_cqi_cl_struc2cpos(), do_cqi_cl_struc2str(), and do_cqi_corpus_structural_attribute_has_values().
cqi_read_bool()
int cqi_read_bool (void)
References CQI_CONST_FALSE, CQI_CONST_TRUE, cqi_recv_byte(), and cqi_recv_error().
cqi_read_bool_list()
int cqi_read_bool_list (cqi_byte ** list)
References cl_malloc(), CQI_CONST_FALSE, CQI_CONST_TRUE, cqi_read_byte(), cqi_read_int(), and cqiserver_snoop().
cqi_read_byte()
int cqi_read_byte (void)
References cqi_recv_byte(), and cqi_recv_error().
Referenced by cqi_read_bool_list(), cqi_read_byte_list(), cqi_read_command(), cqi_read_int(), cqi_read_word(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), and do_cqi_cqp_subcorpus_has_field().
cqi_read_byte_list()
int cqi_read_byte_list (cqi_byte ** list)
References cl_malloc(), cqi_read_byte(), cqi_read_int(), and cqiserver_snoop().
cqi_read_command()
int cqi_read_command (void)
References CQI_PAD, cqi_read_byte(), and cqiserver_debug_msg().
Referenced by interpreter(), and main().
cqi_read_int()
int cqi_read_int (void)
References cqi_read_byte(), and cqiserver_snoop().
Referenced by cqi_read_bool_list(), cqi_read_byte_list(), cqi_read_int_list(), cqi_read_string_list(), do_cqi_cl_alg2cpos(), do_cqi_cl_id2cpos(), do_cqi_cl_struc2cpos(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), and do_cqi_cqp_fdist_2().
cqi_read_int_list()
int cqi_read_int_list (int ** list)
References cl_malloc(), cqi_read_int(), and cqiserver_snoop().
Referenced by do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), and do_cqi_cl_struc2str().
cqi_read_string()
char* cqi_read_string (void)
References cl_malloc(), cqi_read_word(), cqi_recv_bytes(), cqi_recv_error(), and cqiserver_snoop().
Referenced by cqi_read_string_list(), do_cqi_cl_alg2cpos(), do_cqi_cl_attribute_size(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_id2cpos(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), do_cqi_cl_lexicon_size(), do_cqi_cl_regex2id(), do_cqi_cl_str2id(), do_cqi_cl_struc2cpos(), do_cqi_cl_struc2str(), do_cqi_corpus_attributes(), do_cqi_corpus_charset(), do_cqi_corpus_full_name(), do_cqi_corpus_properties(), do_cqi_corpus_structural_attribute_has_values(), do_cqi_cqp_drop_subcorpus(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), do_cqi_cqp_query(), do_cqi_cqp_subcorpus_has_field(), do_cqi_cqp_subcorpus_size(), and main().
cqi_read_string_list()
int cqi_read_string_list (char *** list)
References cl_malloc(), cqi_read_int(), cqi_read_string(), and cqiserver_snoop().
Referenced by do_cqi_cl_str2id().
cqi_read_word()
int cqi_read_word (void)
References cqi_read_byte(), and cqiserver_snoop().
Referenced by cqi_read_string().
cqi_recv_byte()
int cqi_recv_byte (void)
References connfd, cqiserver_snoop(), and MSG_WAITALL.
Referenced by cqi_read_bool(), and cqi_read_byte().
cqi_recv_bytes()
int cqi_recv_bytes (cqi_byte * buf, int n)
References buf, connfd, cqiserver_snoop(), and MSG_WAITALL.
Referenced by cqi_read_string().
cqi_send_byte()
int cqi_send_byte (int n, int nosnoop)
Sends a BYTE to the client.
This function should be called via one of the cqi_data_* functions and not on its own.
This is the fundamental "sending" function, and the only one that calls the underlying OS-specific file stream/socket functions.
Parameters
n The byte to send. NOTE that as the parameter is an int, numbers bigger than 0xff can be passed. BUT all content except the lowest-order 8-bits are discarded (0xff is used as a mask with bitwise-and).
nosnoop Boolean: if true, snoop functionality is overridden (to allow for non-repetition of messages when called from a function that has already printed a message)
References conn_out, connfd, cqiserver_snoop(), and MSG_WAITALL.
Referenced by cqi_data_bool(), cqi_data_byte(), cqi_send_byte_list(), cqi_send_int(), cqi_send_string(), and cqi_send_word().
cqi_send_byte_list()
int cqi_send_byte_list (cqi_byte * list, int l, int as_boolean)
Sends a BYTE[] (byte list) to the client.
This function should be called via one of the cqi_data_* functions and not on its own.
Parameters
list pointer to a block of bytes to send.
l the number of bytes to send.
as_boolean if true, send 1 for any true byte, 0 for 0.
Returns
Boolean: true if everything OK, otherwise false.
References CQI_CONST_FALSE, CQI_CONST_TRUE, cqi_send_byte(), and cqi_send_int().
Referenced by cqi_data_bool_list(), and cqi_data_byte_list().
cqi_send_int()
int cqi_send_int (int n)
Sends an INT to the client.
An int consists of four bytes in network order.
This function should be called via one of the cqi_data_* functions and not on its own.
Returns
Boolean: true if everything OK, otherwise false.
References cqi_send_byte(), and cqiserver_snoop().
Referenced by cqi_data_int(), cqi_data_int_int(), cqi_data_int_int_int_int(), cqi_send_byte_list(), cqi_send_int_list(), cqi_send_string_list(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_str2id(), do_cqi_cl_struc2str(), do_cqi_corpus_list_corpora(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), do_cqi_send_minus_one_list(), and send_cqi_corpus_attributes().
cqi_send_int_list()
int cqi_send_int_list (int * list, int l)
Sends an INT[] (integer list) to the client.
This function should be called via one of the cqi_data_* functions and not on its own.
Parameters
list pointer to a block of integers to send.
l the number of integers to send.
Returns
Boolean: true if everything OK, otherwise false.
References cqi_send_int().
Referenced by cqi_data_int_list().
cqi_send_string()
int cqi_send_string (const char * str)
Sends a STRING to the client.
CQi strings are NOT null-terminated – so while the argument to this function needs to be a null-terminated string, the string that actually gets sent across the network will not be.
This function should be called via one of the cqi_data_* functions and not on its own.
Returns
Boolean: true if everything OK, otherwise false.
References cqi_send_byte(), cqi_send_word(), and cqiserver_snoop().
Referenced by cqi_data_string(), cqi_send_string_list(), do_cqi_cl_cpos2str(), do_cqi_cl_id2str(), do_cqi_cl_struc2str(), do_cqi_corpus_list_corpora(), do_cqi_cqp_list_subcorpora(), and send_cqi_corpus_attributes().
cqi_send_string_list()
int cqi_send_string_list (char ** list, int l)
Sends a STRING[] (string list) to the client.
This function should be called via one of the cqi_data_* functions and not on its own.
Parameters
list pointer to a block of pointers-to-strings; the strings will be sent.
l the number of strings to send.
References cqi_send_int(), and cqi_send_string().
Referenced by cqi_data_string_list().
cqi_send_word()
int cqi_send_word (int n)
Sends a WORD to the client.
A word consists of two bytes in network order. Since CQi commands are two bytes, this function can be used to send commands.
This function should be called via one of the cqi_data_* functions and not on its own.
References cqi_send_byte(), and cqiserver_snoop().
Referenced by cqi_command(), cqi_data_bool(), cqi_data_bool_list(), cqi_data_byte(), cqi_data_byte_list(), cqi_data_int(), cqi_data_int_int(), cqi_data_int_int_int_int(), cqi_data_int_list(), cqi_data_string(), cqi_data_string_list(), cqi_send_string(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_str2id(), do_cqi_cl_struc2str(), do_cqi_corpus_list_corpora(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), and send_cqi_corpus_attributes().
cqiserver_debug_msg()
void cqiserver_debug_msg (const char * format, ...)
Print server debug message on stderr (if global "server_debug" option is true).
Parameters
format A printf-style formatting string. Must be followed by values to satisfy each specifier in the striong.
References server_debug.
Referenced by accept_connection(), cqi_activate_corpus(), cqi_lookup_attribute(), cqi_read_command(), do_cqi_cl_alg2cpos(), do_cqi_cl_attribute_size(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_drop_attribute(), do_cqi_cl_id2cpos(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), do_cqi_cl_lexicon_size(), do_cqi_cl_regex2id(), do_cqi_cl_str2id(), do_cqi_cl_struc2cpos(), do_cqi_cl_struc2str(), do_cqi_corpus_attributes(), do_cqi_corpus_charset(), do_cqi_corpus_full_name(), do_cqi_corpus_list_corpora(), do_cqi_corpus_properties(), do_cqi_corpus_structural_attribute_has_values(), do_cqi_cqp_drop_subcorpus(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), do_cqi_cqp_query(), do_cqi_cqp_subcorpus_has_field(), do_cqi_cqp_subcorpus_size(), interpreter(), and send_cl_error().
cqiserver_snoop()
void cqiserver_snoop (const char * format, ...)
Print network communication snooping info on stderr (if global "snoop" option is true).
Parameters
format A printf-style formatting string. Must be followed by values to satisfy each specifier in the striong.
References snoop.
Referenced by cqi_flush(), cqi_read_bool_list(), cqi_read_byte_list(), cqi_read_int(), cqi_read_int_list(), cqi_read_string(), cqi_read_string_list(), cqi_read_word(), cqi_recv_byte(), cqi_recv_bytes(), cqi_send_byte(), cqi_send_int(), cqi_send_string(), and cqi_send_word().
free_attribute_hash()
void free_attribute_hash (void)
Frees the global AttHash object and the space that it points to.
See also
AttHash
References AttHash, cl_free, and att_hashtable::space.
make_attribute_hash()
void make_attribute_hash (int size)
This function has to be called once to initialise the global attribute hash.
See also
AttHash
References AttHash, cl_find_prime(), cl_malloc(), att_hashtable::code, att_hashtable::size, and att_hashtable::space.
Referenced by accept_connection().
split_attribute_spec()
int split_attribute_spec (char * spec, char ** corpus_name, char ** attribute_name)
new strings are allocated for the output arguments
References check_attribute_name, check_corpus_name, cl_free, cl_strdup(), cl_strdup_to(), corpus, cqi_errno, CQI_ERROR_SYNTAX_ERROR, and CQI_STATUS_OK.
Referenced by cqi_lookup_attribute().
split_subcorpus_spec()
int split_subcorpus_spec (char * spec, char ** corpus_name, char ** subcorpus_name)
References check_corpus_name, check_subcorpus_name, cl_free, cl_strdup(), cl_strdup_to(), corpus, cqi_errno, and CQI_STATUS_OK.
Referenced by cqi_find_corpus(), do_cqi_cqp_drop_subcorpus(), and do_cqi_cqp_query().
Variable Documentation
cqi_errno
int cqi_errno extern
CQi last error.
Referenced by check_identifier_convention(), cqi_find_corpus(), cqi_lookup_attribute(), do_cqi_cl_alg2cpos(), do_cqi_cl_attribute_size(), do_cqi_cl_cpos2alg(), do_cqi_cl_cpos2id(), do_cqi_cl_cpos2lbound(), do_cqi_cl_cpos2rbound(), do_cqi_cl_cpos2str(), do_cqi_cl_cpos2struc(), do_cqi_cl_id2cpos(), do_cqi_cl_id2freq(), do_cqi_cl_id2str(), do_cqi_cl_idlist2cpos(), do_cqi_cl_lexicon_size(), do_cqi_cl_regex2id(), do_cqi_cl_str2id(), do_cqi_cl_struc2cpos(), do_cqi_cl_struc2str(), do_cqi_corpus_structural_attribute_has_values(), do_cqi_cqp_drop_subcorpus(), do_cqi_cqp_dump_subcorpus(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_cqi_cqp_list_subcorpora(), do_cqi_cqp_query(), do_cqi_cqp_subcorpus_has_field(), do_cqi_cqp_subcorpus_size(), split_attribute_spec(), and split_subcorpus_spec().
cqi_error_string
char cqi_error_string[] extern
String describing the last CQi error.
This can be queried by the client.
Referenced by cqi_general_error(), and interpreter().