CWB: cqp/sgml-print.c File Reference
sgml-print.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/time.h>
#include <time.h>
#include <pwd.h>
#include "../cl/cl.h"
#include "cqp.h"
#include "options.h"
#include "corpmanag.h"
#include "concordance.h"
#include "attlist.h"
#include "print_align.h"
#include "sgml-print.h"
Macros
#define SUBST_NONE 0
#define SUBST_LT 1
#define SUBST_GT 2
#define SUBST_AMP 4
#define SUBST_QUOT 8
#define SUBST_ALL (SUBST_LT | SUBST_GT | SUBST_AMP | SUBST_QUOT)
Functions
static const char * sgml_convert_string (const char *s)
static char * sgml_print_field (FieldType field, int start)
static void sgml_puts (FILE *dest, const char *s, int flags)
like "puts" but with escaping of LT/GT/AMP/QUOT depending on the flags.
void sgml_print_aligned_line (FILE *dest, int highlighting, char *attribute_name, char *line)
Prints a line of text (which will have been previously exrtracted from a corfpus linked to the present corpus by an a-attribute) following an SGML open-tag.
static void sgml_print_context (ContextDescriptor *cd, FILE *dest)
void sgml_print_corpus_header (CorpusList *cl, FILE *dest)
void sgml_print_output (CorpusList *cl, FILE *dest, int interactive, ContextDescriptor *cd, int first, int last)
void sgml_print_group (Group *group, FILE *dest)
Variables
PrintDescriptionRecord SGMLPrintDescriptionRecord
Macro Definition Documentation
SUBST_ALL
#define SUBST_ALL (SUBST_LT | SUBST_GT | SUBST_AMP | SUBST_QUOT)
SUBST_AMP
#define SUBST_AMP 4
SUBST_GT
#define SUBST_GT 2
SUBST_LT
#define SUBST_LT 1
SUBST_NONE
#define SUBST_NONE 0
SUBST_QUOT
#define SUBST_QUOT 8
Function Documentation
sgml_convert_string()
static const char * sgml_convert_string (const char * s) static
References CL_MAX_LINE_LENGTH.
sgml_print_aligned_line()
void sgml_print_aligned_line (FILE * dest, int highlighting, char * attribute_name, char * line)
Prints a line of text (which will have been previously exrtracted from a corfpus linked to the present corpus by an a-attribute) following an SGML open-tag.
The structure is
<align name="$attribute_name">$line_data
And the whole thing is terminated by EOL (note, no close tag as we'd have in XML!)
Parameters
dest Destination for the output.
highlighting DUMMY: only supported by ascii print.
attribute_name The name of the aligned corpus: printed in the "align" tag as an SGML attribute.
line Character data of the line of aligned-corpus data to print. This is treated as opaque.
References line, sgml_puts(), and SUBST_NONE.
Referenced by print_all_aligned_lines().
sgml_print_context()
static void sgml_print_context (ContextDescriptor * cd, FILE * dest) static
References char_context, ContextDescriptor::left_structure_name, ContextDescriptor::left_type, ContextDescriptor::left_width, ContextDescriptor::right_structure_name, ContextDescriptor::right_type, ContextDescriptor::right_width, s_att_context, and word_context.
Referenced by sgml_print_corpus_header().
sgml_print_corpus_header()
void sgml_print_corpus_header (CorpusList * cl, FILE * dest)
References CD, cl::corpus, cl::mother_name, TCorpus::name, cl::name, passwd, TCorpus::registry_name, sgml_print_context(), and cl::size.
Referenced by print_corpus_info_header().
sgml_print_field()
static char * sgml_print_field (FieldType field, int start) static
References KeywordField, MatchField, NoField, and TargetField.
sgml_print_group()
void sgml_print_group (Group * group, FILE * dest)
References cl_broken_pipe, _grouptable::count_cells, _id_cnt_mapping::freq, Group_id2str(), _grouptable::nr_cells, _id_cnt_mapping::s, sgml_puts(), SUBST_ALL, and _id_cnt_mapping::t.
Referenced by print_group().
sgml_print_output()
void sgml_print_output (CorpusList * cl, FILE * dest, int interactive, ContextDescriptor * cd, int first, int last)
References PrintDescriptionRecord::AfterConcordance, PrintDescriptionRecord::AfterLine, ContextDescriptor::alignedCorpora, _Attribute::any, _attrbuf::attribute, ContextDescriptor::attributes, PrintDescriptionRecord::BeforeConcordance, PrintDescriptionRecord::BeforeLine, CD, cl_broken_pipe, cl_free, compose_kwic_line(), cl::corpus, Range::end, _ConcLineField::end_position, KeywordField, cl::keywords, line, _attlist::list, MatchEndField, MatchField, _attrbuf::next, NoField, print_all_aligned_lines(), cl::range, SGMLPrintDescriptionRecord, cl::size, cl::sortidx, Range::start, _ConcLineField::start_position, _attrbuf::status, TargetField, cl::targets, and _ConcLineField::type.
Referenced by print_concordance_body().
sgml_puts()
static void sgml_puts (FILE * dest, const char * s, int flags) static
like "puts" but with escaping of LT/GT/AMP/QUOT depending on the flags.
References SUBST_AMP, SUBST_GT, SUBST_LT, and SUBST_QUOT.
Referenced by sgml_print_aligned_line(), and sgml_print_group().
Variable Documentation
SGMLPrintDescriptionRecord
PrintDescriptionRecord SGMLPrintDescriptionRecord
Referenced by print_all_aligned_lines(), and sgml_print_output().