CWB: cqp/symtab.c File Reference
symtab.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "../cl/cl.h"
#include "symtab.h"
#include "output.h"
#include "cqp.h"
Functions
void free_labellist (LabelEntry label)
Frees the whole of a linked list of label entries.
SymbolTable new_symbol_table (void)
create new symbol table
void delete_symbol_table (SymbolTable st)
delete symbol table (free all entries)
LabelEntry find_label (SymbolTable st, char *s, int flags)
Returns label entry, or NULL if undefined (flags are used only to determine namespace)
LabelEntry label_lookup (SymbolTable st, char *s, int flags, int create)
Look up a label, add flags, and return label entry (NULL if undefined).
int check_labels (SymbolTable st)
Checks whether all used labels are defined (and vice versa); only non-special labels in the user namespace of the argument symbol table will be checked.
void print_symbol_table (SymbolTable st)
print symbol table contents (for debugging purposes)
LabelEntry symbol_table_new_iterator (SymbolTable st, int flags)
LabelEntry symbol_table_iterator (LabelEntry prev, int flags)
RefTab new_reftab (SymbolTable st)
Create new reference table of required size for the given symbol table.
void delete_reftab (RefTab rt)
Deletes (and frees) a reference table.
void dup_reftab (RefTab rt1, RefTab rt2)
Copies rt1 to rt2; doesn't allocate new reftab for efficiency reasons.
void reset_reftab (RefTab rt)
resets all referenced corpus position to -1 -> undefine all references
void set_reftab (RefTab rt, int index, int value)
set references (cpos value in get_reftab is returned for 'this' label (_), set to -1 if n/a)
int get_reftab (RefTab rt, int index, int cpos)
read references (cpos value in get_reftab is returned for 'this' label (_), set to -1 if n/a)
void print_label_values (SymbolTable st, RefTab rt, int cpos)
Prints the current label values (for debugging).
FSAState FSAState_new (SymbolTable st)
Allocate a new FSA simulation state object based on the specified symbol table.
void FSAState_delete (FSAState *self_ref)
Deallocate FSAState object, freeing all associated memory.
StateQueue StateQueue_new (SymbolTable st)
Allocate a new StateQueue object, i.e.
void StateQueue_delete (StateQueue *self_ref)
Deallocate StateQueue object, freeing all remaining FSAState objects in the wait list.
void StateQueue_clear (StateQueue self)
Clear the StateQueue, i.e.
RefTab StateQueue_push (StateQueue self, int cpos, RefTab rt)
Enter FSA state into the wait list, sorted by increasing cpos.
int StateQueue_pop (StateQueue self, RefTab output_rt)
Remove next FSA state to be emitted from the wait list.
int StateQueue_next_cpos (StateQueue self)
Return cpos of next FSA state waiting in the queue (or -1 if there are no waiting states).
int StateQueue_length (StateQueue self)
Return number of FSA states currently waiting in the queue.
Function Documentation
check_labels()
int check_labels (SymbolTable st)
Checks whether all used labels are defined (and vice versa); only non-special labels in the user namespace of the argument symbol table will be checked.
Result is boolean.
References cqpmessage(), _label_entry::flags, LAB_DEFINED, LAB_SPECIAL, LAB_USED, _label_entry::name, _label_entry::next, _symbol_table::user, and Warning.
Referenced by do_SearchPattern().
delete_reftab()
void delete_reftab (RefTab rt)
Deletes (and frees) a reference table.
References cl_free, and _RefTab::data.
Referenced by check_alignment_constraints(), FSAState_delete(), and run_standard_query_dfa().
delete_symbol_table()
void delete_symbol_table (SymbolTable st)
delete symbol table (free all entries)
References cl_free, free_labellist(), _symbol_table::rdat, and _symbol_table::user.
Referenced by free_environment().
dup_reftab()
void dup_reftab (RefTab rt1, RefTab rt2)
Copies rt1 to rt2; doesn't allocate new reftab for efficiency reasons.
References cqp_error_status, _RefTab::data, and _RefTab::size.
Referenced by eval_constraint(), simulate(), StateQueue_pop(), and StateQueue_push().
find_label()
LabelEntry find_label (SymbolTable st, char * s, int flags)
Returns label entry, or NULL if undefined (flags are used only to determine namespace)
References cl_streq, LAB_RDAT, _label_entry::name, _label_entry::next, _symbol_table::rdat, and _symbol_table::user.
Referenced by do_XMLTag(), and label_lookup().
free_labellist()
void free_labellist (LabelEntry label)
Frees the whole of a linked list of label entries.
References cl_free, _label_entry::name, and _label_entry::next.
Referenced by delete_symbol_table().
FSAState_delete()
void FSAState_delete (FSAState * self_ref)
Deallocate FSAState object, freeing all associated memory.
Parameters
self_ref reference to an FSAState object, i.e. a pointer to a variable of type FSAState
*self_ref will be set to NULL after deallocation. It is valid to pass a reference to a NULL value (i.e. *self_ref == NULL), in which case the function is a no-op.
References cl_free, and delete_reftab().
Referenced by StateQueue_clear(), StateQueue_delete(), and StateQueue_pop().
FSAState_new()
FSAState FSAState_new (SymbolTable st)
Allocate a new FSA simulation state object based on the specified symbol table.
Parameters
st a SymbolTable object, determines the label references stored in the FSA state
Returns
a newly allocated FSAState object, must be deallocated by user code with FSAState_delete
References cl_malloc(), and new_reftab().
Referenced by StateQueue_push().
get_reftab()
int get_reftab (RefTab rt, int index, int cpos)
read references (cpos value in get_reftab is returned for 'this' label (_), set to -1 if n/a)
References _RefTab::data, and _RefTab::size.
Referenced by eval_constraint(), get_label_referenced_position(), print_label_values(), and simulate().
label_lookup()
LabelEntry label_lookup (SymbolTable st, char * s, int flags, int create)
Look up a label, add flags, and return label entry (NULL if undefined).
if create is set and label does not exist, it is added to the symbol table.
References cl_malloc(), cl_str_is, cl_strdup(), field_name_to_type(), find_label(), _label_entry::flags, LAB_RDAT, LAB_SPECIAL, _label_entry::name, _label_entry::next, _symbol_table::next_index, NoField, _symbol_table::rdat, _label_entry::ref, and _symbol_table::user.
Referenced by do_IDReference(), do_LabelReference(), do_MatchSelector(), do_NamedWfPattern(), do_RegionElement(), and do_XMLTag().
new_reftab()
RefTab new_reftab (SymbolTable st)
Create new reference table of required size for the given symbol table.
NB If further labels are added to st, you must reallocate the reference table to make room for the new reference indices
References cl_malloc(), _RefTab::data, _symbol_table::next_index, and _RefTab::size.
Referenced by check_alignment_constraints(), FSAState_new(), and run_standard_query_dfa().
new_symbol_table()
SymbolTable new_symbol_table (void)
create new symbol table
References cl_malloc(), _symbol_table::next_index, _symbol_table::rdat, and _symbol_table::user.
Referenced by next_environment().
print_label_values()
void print_label_values (SymbolTable st, RefTab rt, int cpos)
Prints the current label values (for debugging).
Parameters
st The SymbolTable
rt The reference table
cpos The corpus position
References get_reftab(), _label_entry::name, _label_entry::next, _symbol_table::next_index, _symbol_table::rdat, _label_entry::ref, _RefTab::size, and _symbol_table::user.
Referenced by _add_to_queue(), and simulate().
print_symbol_table()
void print_symbol_table (SymbolTable st)
print symbol table contents (for debugging purposes)
References _label_entry::flags, _label_entry::name, _label_entry::next, _symbol_table::rdat, _label_entry::ref, and _symbol_table::user.
Referenced by run_standard_query_dfa().
reset_reftab()
void reset_reftab (RefTab rt)
resets all referenced corpus position to -1 -> undefine all references
References _RefTab::data, and _RefTab::size.
Referenced by run_standard_query_dfa(), and simulate().
set_reftab()
void set_reftab (RefTab rt, int index, int value)
set references (cpos value in get_reftab is returned for 'this' label (_), set to -1 if n/a)
References cqp_error_status, cqpmessage(), _RefTab::data, Error, and _RefTab::size.
Referenced by _add_to_queue(), eval_bool(), eval_constraint(), get_leaf_value(), and simulate().
StateQueue_clear()
void StateQueue_clear (StateQueue self)
Clear the StateQueue, i.e.
remove all remaining FSAState objects from the wait list.
Parameters
self a StateQueue object
References FSAState_delete().
Referenced by simulate().
StateQueue_delete()
void StateQueue_delete (StateQueue * self_ref)
Deallocate StateQueue object, freeing all remaining FSAState objects in the wait list.
Parameters
self_ref reference to a StateQueue object, i.e. a pointer to a variable of type StateQueue
*self_ref will be set to NULL after deallocation. It is valid to pass a reference to a NULL value (i.e. *self_ref == NULL), in which case the function is a no-op.
References cl_free, and FSAState_delete().
Referenced by free_environment().
StateQueue_length()
int StateQueue_length (StateQueue self)
Return number of FSA states currently waiting in the queue.
Parameters
self a StateQueue object
Returns
the number of waiting FSA states (0 if the queue is empty)
Referenced by _add_to_queue(), and eval_constraint().
StateQueue_new()
StateQueue StateQueue_new (SymbolTable st)
Allocate a new StateQueue object, i.e.
a wait list of FSA simulation states based on the same symbol table.
Parameters
st a SymbolTable object, determines the label references stored in the FSA state waiting in the queue; note that the symbol table need not be complete when StateQueue_new is called, only when the first state enters the queue
Returns
a newly allocated StateQueue object, must be deallocated by user code with StateQueue_delete
References cl_malloc().
Referenced by do_RegionElement().
StateQueue_next_cpos()
int StateQueue_next_cpos (StateQueue self)
Return cpos of next FSA state waiting in the queue (or -1 if there are no waiting states).
Parameters
self a StateQueue object
Returns
the cpos of the next waiting FSA state, or -1 if the queue is empty
Referenced by eval_constraint().
StateQueue_pop()
int StateQueue_pop (StateQueue self, RefTab output_rt)
Remove next FSA state to be emitted from the wait list.
Parameters
self a StateQueue object
output_rt a RefTab object to be overwritten with the label references of the waiting FSA state; must be based on the same SymbolTable as the StateQueue
Returns
cpos the cpos of the FSA state to be emitted; -1 if the queue was already empty
References dup_reftab(), and FSAState_delete().
Referenced by eval_constraint().
StateQueue_push()
RefTab StateQueue_push (StateQueue self, int cpos, RefTab rt)
Enter FSA state into the wait list, sorted by increasing cpos.
Parameters
self a StateQueue object
cpos corpus position of the FSA state entering the queue, determining when it will be emitted
rt a RefTab object containing the label references of the FSA state; must be based on the same SymbolTable as the StateQueue object
Returns
pointer to the RefTab object inside the state in the wait list, which contains a copy of rt
If there are already one or more states with the same cpos in the list, the new state will be inserted after them (so a competing state that has entered the queue earlier will also be emitted first.
References _FSAState::cpos, dup_reftab(), and FSAState_new().
Referenced by _add_to_queue().
symbol_table_iterator()
LabelEntry symbol_table_iterator (LabelEntry prev, int flags)
References _label_entry::flags, and _label_entry::next.
Referenced by simulate(), and symbol_table_new_iterator().
symbol_table_new_iterator()
LabelEntry symbol_table_new_iterator (SymbolTable st, int flags)
References _label_entry::flags, LAB_RDAT, _symbol_table::rdat, symbol_table_iterator(), and _symbol_table::user.
Referenced by simulate().