CWB: cqp/targets.c File Reference
targets.c File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "../cl/cl.h"
#include "../cl/ui-helpers.h"
#include "corpmanag.h"
#include "eval.h"
#include "options.h"
#include "output.h"
#include "ranges.h"
#include "cqp.h"
#include "targets.h"
Functions
SearchStrategy string_to_strategy (const char *s)
int set_target (CorpusList *corp, FieldType dest, FieldType source, int source_offset, int overwrite)
Sets one of the anchors (aka fields) of the NQR/subcorpus to the value of one of the others, optionally adding an token offset.
int evaluate_target (CorpusList *corp, FieldType t_id, FieldType base, int inclusive, SearchStrategy strategy, Constrainttree constr, enum ctxtdir direction, int units, char *attr_name)
int evaluate_subset (CorpusList *cl, FieldType the_field, Constrainttree constr)
Function Documentation
evaluate_subset()
int evaluate_subset (CorpusList * cl, FieldType the_field, Constrainttree constr)
Parameters
cl the corpus
the_field the field to scan
constr
Returns
References apply_range_set_operation(), cqp, cqpmessage(), Range::end, eval_bool(), EvaluationIsRunning, install_signal_handler(), KeywordField, cl::keywords, line, MatchEndField, MatchField, NoField, progress_bar, progress_bar_message(), progress_bar_percentage(), cl::range, RReduce, cl::size, Range::start, SUB, TargetField, cl::targets, TEMP, cl::type, and Warning.
Referenced by do_subset().
evaluate_target()
int evaluate_target (CorpusList * corp, FieldType t_id, FieldType base, int inclusive, SearchStrategy strategy, Constrainttree constr, enum ctxtdir direction, int units, char * attr_name)
References ATT_POS, ATT_STRUC, ctxtsp::attrib, calculate_ranges(), CheckForInterrupts(), cl_calloc(), cl_free, cl_new_attribute(), cl_streq_ci, cl::corpus, cqp, cqpmessage(), ctxtdir_left, ctxtdir_right, CWB_DEFAULT_ATT_NAME, ctxtsp::direction, Range::end, Error, eval_bool(), EvaluationIsRunning, install_signal_handler(), KeywordField, cl::keywords, line, MatchEndField, MatchField, MAX, cl::mother_name, progress_bar, progress_bar_clear_line(), progress_bar_message(), progress_bar_percentage(), cl::range, RangeSort(), SearchFarthest, SearchLeftmost, SearchNearest, SearchRightmost, cl::size, ctxtsp::size, ctxtsp::space_type, Range::start, strategy, structure, TargetField, cl::targets, touch_corpus(), Warning, and word.
Referenced by do_set_complex_target().
set_target()
int set_target (CorpusList * corp, FieldType dest, FieldType source, int source_offset, int overwrite)
Sets one of the anchors (aka fields) of the NQR/subcorpus to the value of one of the others, optionally adding an token offset.
It implements the CQP commands set NQR <anchor> <anchor>[<offset>]; set NQR <anchor> NULL;
There are several special cases to be considered:
if source anchor has an undefined value (-1), the destination will either be unchanged (overwrite=0) or become undefined, too (overwrite=1)
if source anchor's offset puts it outside the valid cpos range, it is treated as undefined (and the rule above applies)
if destination is MatchField or MatchendField, the matching range is modified and may become invalid (either because the destination anchor is set to undefined or because matchend ends up to the left of match); in this case, the modification is either ignored (overwrite=0) or the match is discarded from the query (overwrite=1)
Parameters
corp CorpusList entry for the subcorpus or NQR to modify.
dest Which anchor to modify (MatchField, MatchEndField, TargetField, KeywordField). If this is MatchField or MatchendField, the modified query will be re-sorted and some matches may be discarded. If this is NoField, CQP dies, since that's a logic error.
source Which anchor to get the data from. If NoField, the destination TargetField or KeywordField is deleted.
source_offset Token offset to add to the source anchor(to shift anchor to the left or right).
overwrite Whether undefined or invalid source anchor should overwrite destination or be ignored (see above). In other words, overwrite=0 performs a conditional update while overwrite=1 performs a forced update.
Returns
True if successful, False (with a CQP error message) otherwise.
References apply_range_set_operation(), cl_free, cl_malloc(), cqpmessage(), Range::end, Error, KeywordField, cl::keywords, MatchEndField, MatchField, cl::mother_size, cl::name, NoField, cl::range, RangeSort(), RReduce, cl::size, Range::start, TargetField, cl::targets, touch_corpus(), and Warning.
Referenced by do_set_target().
string_to_strategy()
SearchStrategy string_to_strategy (const char * s)
References cl_streq_ci, cqpmessage(), SearchFarthest, SearchLeftmost, SearchNearest, SearchNone, SearchRightmost, and Warning.