CWB: cqp/tree.c File Reference
tree.c File Reference
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "../cl/cl.h"
#include "cqp.h"
#include "eval.h"
#include "treemacros.h"
#include "tree.h"
#include "options.h"
#include "symtab.h"
#include "builtins.h"
#include "matchlist.h"
Functions
void print_indent (int indent)
static void print_pattern (int envidx, int index, int indent)
Pretty-prints a single query element (i.e.
static void print_rep_factor (int i)
Translates the symbolic value for the repetition arguments.
void print_evaltree (int envidx, Evaltree etptr, int indent)
Pretty-prints an evaluation tree.
void free_booltree (Constrainttree ctptr)
Deletes a boolean constraint tree node (recursive with depth-first).
void free_evaltree (Evaltree *tree_ptr)
Deletes an evaluation tree node, and every node under it, with the depth-first method.
void print_booltree (Constrainttree ctptr, int indent)
Prints a boolean evaluation tree.
void show_patternlist (int eidx)
Shows the contents of the patternlist.
char * evaltree2searchstr (Evaltree etptr, int *length)
Converts an evaluation tree to a string.
Constraint * try_optimization (Constraint *tree)
Function Documentation
evaltree2searchstr()
char* evaltree2searchstr (Evaltree etptr, int * length)
Converts an evaluation tree to a string.
This is done by traversing the tree in infix order, calling this function recursively.
Parameters
etptr The evaluation tree to convert.
length Out paramter: length of the resulting string is placed here. Can be NULL if the length is unwanted.
Returns
The resulting string.
References cl_free, cl_malloc(), cl_strdup(), leaf, e_tree::leaf, e_tree::left, e_tree::max, e_tree::min, node, e_tree::node, e_tree::op_id, e_tree::patindex, re_disj, re_od_concat, re_oi_concat, re_repeat, repeat_inf, repeat_none, e_tree::right, and e_tree::type.
Referenced by do_SearchPattern().
free_booltree()
void free_booltree (Constrainttree ctptr)
Deletes a boolean constraint tree node (recursive with depth-first).
Parameters
ctptr The Constrainttree to delete. Null-safe.
References c_tree::args, bnode, CID, cl_delete_regex(), cl_free, cnode, c_tree::ctype, float_leaf, func, c_tree::func, id_list, c_tree::idlist, int_leaf, c_tree::items, c_tree::leaf, c_tree::left, _ActualParamList::next, c_tree::node, NORMAL, pa_ref, _ActualParamList::param, c_tree::pat_type, REGEXP, c_tree::right, c_tree::rx, sa_ref, sbound, string_leaf, c_tree::type, var_ref, c_tree::varName, and c_tree::varref.
Referenced by bool_and(), bool_implies(), bool_not(), bool_or(), do_RelExpr(), do_set_complex_target(), do_subset(), free_environment(), and try_optimization().
free_evaltree()
void free_evaltree (Evaltree * tree_ptr)
Deletes an evaluation tree node, and every node under it, with the depth-first method.
Parameters
tree_ptr The evaluation tree to delete. This is a pointer to a pointer since Evaltree is itself a pointer type.
References cl_free, leaf, meet_union, node, re_disj, re_od_concat, re_oi_concat, re_repeat, and tabular.
Referenced by free_environment().
print_booltree()
void print_booltree (Constrainttree ctptr, int indent)
Prints a boolean evaluation tree.
This function is a pretty-printer for the Constrainttree data type. It traverses a boolean evaluation tree and prints its contents. An indentation level must be specified.
(The indentation is needed because this function calls itself recursively for sub-branches.)
Parameters
ctptr Constrainttree to print.
indent Number of indent levels at which to start printing. Each indent level is realised as two spaces.
References _Attribute::any, c_tree::args, c_tree::attr, b_and, b_implies, b_not, b_or, bnode, builtin_function, CID, cmp_eq, cmp_ex, cmp_get, cmp_gt, cmp_let, cmp_lt, cmp_neq, cnode, c_tree::constnode, c_tree::ctype, c_tree::dynattr, float_leaf, func, c_tree::func, id_list, c_tree::idlist, int_leaf, c_tree::items, c_tree::label, c_tree::leaf, c_tree::left, _builtinf::name, _label_entry::name, c_tree::negated, _ActualParamList::next, c_tree::node, NORMAL, c_tree::nr_items, c_tree::op_id, pa_ref, c_tree::pa_ref, _ActualParamList::param, c_tree::pat_type, c_tree::predef, print_indent(), REGEXP, c_tree::right, sa_ref, sbound, string_leaf, tree_debug, c_tree::type, c_tree::val, var_ref, c_tree::varName, and c_tree::varref.
Referenced by print_pattern(), and show_environment().
print_evaltree()
void print_evaltree (int envidx, Evaltree etptr, int indent)
Pretty-prints an evaluation tree.
This function traverses the evaluation tree in infix order and prints it appropriately indented.
Parameters
envidx Index into the Environment global array.
etptr The evaluation tree to print.
indent The indent level to start printing at.
References _Attribute::any, e_tree::cooc, cooc_meet, cooc_union, Environment, leaf, e_tree::leaf, e_tree::left, e_tree::lw, e_tree::max, e_tree::max_dist, evalenv::MaxPatIndex, meet_union, e_tree::min, e_tree::min_dist, e_tree::next, node, e_tree::node, e_tree::op_id, e_tree::patindex, print_indent(), print_pattern(), print_rep_factor(), re_disj, re_od_concat, re_oi_concat, re_repeat, repeat_none, e_tree::right, e_tree::rw, e_tree::struc, e_tree::tab_el, tabular, and e_tree::type.
Referenced by do_SearchPattern(), and show_environment().
print_indent()
void print_indent (int indent)
Referenced by print_booltree(), print_evaltree(), and print_pattern().
print_pattern()
static void print_pattern (int envidx, int index, int indent) static
Pretty-prints a single query element (i.e.
a transition of the FSA)
Parameters
envidx Index into the Environment global array.
index Index into the patternlist element of that element of environment.
indent The indent level to start printing at.
References AVSRegionEmit, AVSRegionEnter, AVSRegionWait, Environment, IGNORE_CASE, IGNORE_DIAC, IGNORE_REGEX, MatchAll, Pattern, evalenv::patternlist, print_booltree(), print_indent(), Region, and Tag.
Referenced by print_evaltree(), and show_patternlist().
print_rep_factor()
static void print_rep_factor (int i) static
Translates the symbolic value for the repetition arguments.
(The translated value is printed as a string to STDOUT.)
Parameters
i The repetition argument symbol to translate.
References repeat_inf, and repeat_none.
Referenced by print_evaltree().
show_patternlist()
void show_patternlist (int eidx)
Shows the contents of the patternlist.
(Prints to STDOUT.)
Parameters
eidx Index into the global Environment array, identifying the EvalEnvironment whose patternlist is to be printed.
References Environment, evalenv::MaxPatIndex, and print_pattern().
Referenced by show_environment().
try_optimization()
Constraint* try_optimization (Constraint * tree)
References apply_setop_to_matchlist(), c_tree::attr, b_or, bnode, CID, cl_malloc(), cmp_eq, cmp_neq, cnode, c_tree::constnode, c_tree::ctype, free_booltree(), free_matchlist(), id_list, c_tree::idlist, init_matchlist(), c_tree::items, c_tree::label, c_tree::leaf, c_tree::left, c_tree::negated, NEW_BNODE, c_tree::node, NORMAL, c_tree::nr_items, c_tree::op_id, pa_ref, c_tree::pa_ref, c_tree::pat_type, c_tree::right, _Matchlist::start, string_leaf, _Matchlist::tabsize, c_tree::type, Union, and c_tree::val.
Referenced by bool_implies(), bool_or(), do_RelExExpr(), and do_RelExpr().