CWB: cl/ui-helpers.h File Reference
ui-helpers.h File Reference
Functions
void progress_bar_child_mode (int on_off)
Activates or deactivates child (simple) mode for progress_bar.
void progress_bar_clear_line (void)
Clears the progress bar currently displayed on the terminal.
void progress_bar_message (int pass, int total, char *message)
Prints a new progress bar (passes-plus-message format).
void progress_bar_percentage (int pass, int total, int percentage)
Prints a new progress bar (passes-plus-percentage-done format).
void ilist_start (int linewidth, int tabsize, int indent)
Begins the printing of a line in an indented 'tabularised' list.
void ilist_print_break (char *label)
Starts a new line in an indented 'tabularised' list.
void ilist_print_item (char *string)
Prints an item into an ongoing indented list.
void ilist_end (void)
Ends the printing of a line in an indented 'tabularised' list.
Function Documentation
ilist_end()
void ilist_end (void)
Ends the printing of a line in an indented 'tabularised' list.
References ilist_cursor.
Referenced by list_macros(), printSingleVariableValue(), and show_corpora_backend().
ilist_print_break()
void ilist_print_break (char * label)
Starts a new line in an indented 'tabularised' list.
Used when a line break is needed within an indented list; this function starts a new line (as
in HTML), an showing optional label in indentation.
Parameters
label The optional label, if this is NULL, no label is used; if it is a string, then the string appears on the far left hand side.
References ilist_cursor, ilist_indent, and ilist_print_blanks().
Referenced by ilist_print_item(), list_macros(), and show_corpora_backend().
ilist_print_item()
void ilist_print_item (char * string)
Prints an item into an ongoing indented list.
Parameters
string The string to print as a list item.
References ilist_cursor, ilist_linewidth, ilist_print_break(), and ilist_tab.
Referenced by describecorpus_show_attribute_names(), list_macros(), printSingleVariableValue(), and show_corpora_backend().
ilist_start()
void ilist_start (int linewidth, int tabsize, int indent)
Begins the printing of a line in an indented 'tabularised' list.
If any of the three parameters are zero, this function uses the internal default value for that parameter instead (ILIST macro constants).
Parameters
linewidth Width of the line (in characters)
tabsize Tabulator steps (in characters)
indent Indentation of the list from left margin (in characters)
References ilist_cursor, ILIST_INDENT, ilist_indent, ILIST_LINEWIDTH, ilist_linewidth, ilist_print_blanks(), ILIST_TAB, and ilist_tab.
Referenced by describecorpus_show_attribute_names(), list_macros(), printSingleVariableValue(), and show_corpora_backend().
progress_bar_child_mode()
void progress_bar_child_mode (int on_off)
Activates or deactivates child (simple) mode for progress_bar.
Parameters
on_off The new setting for the progress bar mode, where 1 = simple messages ON STDOUT, 0 = pretty-printed messages with carriage returns ON STDERR
References progress_bar_simple.
Referenced by parse_options().
progress_bar_clear_line()
void progress_bar_clear_line (void)
Clears the progress bar currently displayed on the terminal.
Note: assumes line width of 60 characters.
References progress_bar_simple.
Referenced by ComputeGroupInternally(), do_subset(), evaluate_target(), prepare_do_subset(), and run_standard_query_dfa().
progress_bar_message()
void progress_bar_message (int pass, int total, char * message)
Prints a new progress bar (passes-plus-message format).
The progress bar printed is as follows:
[pass {pass} of {total}: {message}]
If total is equal to zero, the function uses the pass and total values from the last call of this function.
References progress_bar_pass, progress_bar_simple, and progress_bar_total.
Referenced by ComputeGroupInternally(), evaluate_subset(), evaluate_target(), prepare_do_subset(), progress_bar_percentage(), and run_standard_query_dfa().
progress_bar_percentage()
void progress_bar_percentage (int pass, int total, int percentage)
Prints a new progress bar (passes-plus-percentage-done format).
The progress bar printed is as follows:
[pass {pass} of {total}: {percentage}% complete]
If total is equal to zero, the function uses the pass and total values from the last call of this function.
References progress_bar_message().
Referenced by ComputeGroupInternally(), evaluate_subset(), evaluate_target(), and simulate().