CWB: cqp/variables.h File Reference
variables.h File Reference
#include "../cl/cl.h"
Data Structures
struct _variable_item
VariableItem object: an item within a variable.
struct _variable_buf
The Variable object: a list of strings that can be used as a variable within a query (to match all tokens whose type is identical to one of the strings on the list).
Typedefs
typedef struct _variable_item VariableItem
VariableItem object: an item within a variable.
typedef struct _variable_buf VariableBuffer
The Variable object: a list of strings that can be used as a variable within a query (to match all tokens whose type is identical to one of the strings on the list).
typedef struct _variable_buf * Variable
Functions
Variable FindVariable (const char *varname)
Finds the Variable object of the given name, if it exists in VariableSpace.
int VariableItemMember (Variable v, const char *item)
Tests whether a given string exists within the variable.
int VariableAddItem (Variable v, const char *item)
Adds a string to the variable.
int VariableSubtractItem (Variable v, const char *item)
Remove a string from a defined Variable.
int VariableDeleteItems (Variable v)
Deletes and frees up all memory associated with the strings contained by this variable.
Variable NewVariable (const char *varname)
Creates a new Variable (set of strings) with the specified name within the global VariableSpace.
int SetVariableValue (const char *varname, char operator, char *values)
Alters the value of a Variable according to one of four possible operations.
void variables_iterator_new (void)
Resets the global variables iterator to the beginning of the global VariableSpace array.
Variable variables_iterator_next (void)
Gets the next Variable object from the variables iterator.
int VerifyVariable (Variable v, Corpus *corpus, Attribute *attribute)
Verify a variable for use with a given p-attribute of a given corpus.
int * GetVariableItems (Variable v, Corpus *corpus, Attribute *attribute, int *nr_items)
Get array of lexicon IDs of those of the Variable's strings that are found in the lexicon of the given corpus/attribute.
char ** GetVariableStrings (Variable v, int *nr_items)
Returns an array of pointers to a Variable's strings.
Variables
int nr_variables
Number of variables in VariableArray (exported)
Variable * VariableSpace
Global array of Variables (exported)
Typedef Documentation
Variable
typedef struct _variable_buf * Variable
VariableBuffer
typedef struct _variable_buf VariableBuffer
The Variable object: a list of strings that can be used as a variable within a query (to match all tokens whose type is identical to one of the strings on the list).
(Plus also VariableBuffer: the former is a pointer to the latter.)
VariableItem
typedef struct _variable_item VariableItem
VariableItem object: an item within a variable.
Function Documentation
FindVariable()
Variable FindVariable (const char * varname)
Finds the Variable object of the given name, if it exists in VariableSpace.
Parameters
varname The name of the variable required.
Returns
The Variable requested, or NULL if no Variable by that name could be found.
References cl_streq, nr_variables, and VariableSpace.
Referenced by do_AddSubVariables(), do_flagged_re_variable(), do_printVariableSize(), do_PrintVariableValue(), do_SetVariableValue(), SetVariableValue(), and Varref2IDList().
GetVariableItems()
int* GetVariableItems (Variable v, Corpus * corpus, Attribute * attribute, int * nr_items)
Get array of lexicon IDs of those of the Variable's strings that are found in the lexicon of the given corpus/attribute.
Parameters
v The Variable object.
corpus The corpus we are working with.
attribute The attribute against which to verify the Variable's items
nr_items Out parameter: will be set to the number of integers in the returned array (likewise, to 0 if the return value is NULL).
Returns
Pointer to sorted block of integers based on valid items from the variable; NULL if there were no valid items (i.e. items found in the attribute's lexicon). Caller has responsibiltiy to free this block as it is newly allocated.
References cl_malloc(), corpus, _variable_item::free, intcompare(), _variable_buf::items, _variable_item::ival, _variable_buf::nr_items, _variable_buf::nr_valid_items, and VerifyVariable().
Referenced by Varref2IDList().
GetVariableStrings()
char** GetVariableStrings (Variable v, int * nr_items)
Returns an array of pointers to a Variable's strings.
Return value is NULL if there were no strings stored in the variable. The number of strings that were found is inserted into nr_items.
The array that is returned must be freed by the caller.
Parameters
v The Variable whose strings you want.
nr_items The number of strings found will be put here.
Returns
Table of pointers to the Variable's strings. Or NULL if there weren't any. The table is newly allocated but the string data isn't.
References cl_malloc(), _variable_item::free, _variable_buf::items, _variable_buf::nr_items, and _variable_item::sval.
Referenced by do_AddSubVariables(), and do_flagged_re_variable().
NewVariable()
Variable NewVariable (const char * varname)
Creates a new Variable (set of strings) with the specified name within the global VariableSpace.
Returns NULL only if the variable string name was NULL.
References cl_malloc(), cl_realloc(), cl_strdup(), _variable_buf::items, _variable_buf::my_attribute, _variable_buf::my_corpus, _variable_buf::my_name, _variable_buf::nr_items, nr_variables, _variable_buf::valid, VARIABLE_REALLOC, and VariableSpace.
Referenced by do_SetVariableValue(), and SetVariableValue().
SetVariableValue()
int SetVariableValue (const char * varname, char operator, char * values)
Alters the value of a Variable according to one of four possible operations.
Parameters
varname Variable to act on.
operator One of + (add), - (remove), = (set ie overwrite), or < (add from file).
values Whitespace delimited list of items to set/add/remove; or, a filename from which to read items, one per line. The string storage may be destructively modified.
Returns
True for success, false for problem.
References cl_close_stream(), CL_MAX_LINE_LENGTH, cl_open_stream(), CL_STREAM_MAGIC, CL_STREAM_MAGIC_NOPIPE, CL_STREAM_READ, cl_string_chomp(), cqpmessage(), Error, FindVariable(), insecure, NewVariable(), VariableAddItem(), VariableDeleteItems(), VariableSubtractItem(), and Warning.
Referenced by do_SetVariableValue().
VariableAddItem()
int VariableAddItem (Variable v, const char * item)
Adds a string to the variable.
Returns
Always 1.
References cl_malloc(), cl_realloc(), cl_strdup(), _variable_item::free, ITEM_REALLOC, _variable_buf::items, _variable_item::ival, _variable_buf::nr_items, _variable_item::sval, _variable_buf::valid, and VariableItemMember().
Referenced by do_AddSubVariables(), and SetVariableValue().
VariableDeleteItems()
int VariableDeleteItems (Variable v)
Deletes and frees up all memory associated with the strings contained by this variable.
The variable continues to exist, but is now empty.
References cl_free, _variable_buf::items, _variable_buf::nr_invalid_items, _variable_buf::nr_items, _variable_buf::nr_valid_items, _variable_item::sval, and _variable_buf::valid.
Referenced by SetVariableValue().
VariableItemMember()
int VariableItemMember (Variable v, const char * item)
Tests whether a given string exists within the variable.
Returns
Boolean: true if the variable contains the string.
References cl_streq, _variable_item::free, _variable_buf::items, _variable_buf::nr_items, and _variable_item::sval.
Referenced by VariableAddItem().
variables_iterator_new()
void variables_iterator_new (void)
Resets the global variables iterator to the beginning of the global VariableSpace array.
References variables_iterator_idx.
Referenced by do_PrintAllVariables().
variables_iterator_next()
Variable variables_iterator_next (void)
Gets the next Variable object from the variables iterator.
Returns NULL if the iterator has reached the end of the global VariableSpace array.
See also
VariableSpace
Returns
The next Variable object from the iterator.
References nr_variables, variables_iterator_idx, and VariableSpace.
Referenced by do_PrintAllVariables().
VariableSubtractItem()
int VariableSubtractItem (Variable v, const char * item)
Remove a string from a defined Variable.
Identification of the string to remove is by bytewise identity.
Parameters
v The variable.
item The string to take out of the variable.
Returns
Always 1
References cl_free, cl_streq, _variable_item::free, _variable_buf::items, _variable_item::ival, _variable_buf::nr_items, _variable_item::sval, and _variable_buf::valid.
Referenced by do_AddSubVariables(), and SetVariableValue().
VerifyVariable()
int VerifyVariable (Variable v, Corpus * corpus, Attribute * attribute)
Verify a variable for use with a given p-attribute of a given corpus.
This associates the variable with the supplied corpus/attribute, plus checks the variable's strings against the relevant attribute lexicon.
Returns
Boolean: true for all OK, false if something went wrong (problem with the arguments, or if none of the variable's strings match the lexicon). Same as the value of the Variable's "valid" flag after this function has run.
References _Attribute::any, ATT_POS, TCorpus::charset, cl_free, cl_str2id(), cl_strdup(), cl_string_canonical(), CL_STRING_CANONICAL_STRDUP, cl_string_validate_encoding(), corpus, cqpmessage(), Error, _variable_item::free, _variable_buf::items, _variable_item::ival, _variable_buf::my_attribute, _variable_buf::my_corpus, _variable_buf::my_name, _variable_buf::nr_invalid_items, _variable_buf::nr_items, _variable_buf::nr_valid_items, TCorpus::registry_name, REQUIRE_NFC, _variable_item::sval, utf8, and _variable_buf::valid.
Referenced by GetVariableItems().
Variable Documentation
nr_variables
int nr_variables extern
Number of variables in VariableArray (exported)
Referenced by FindVariable(), NewVariable(), and variables_iterator_next().
VariableSpace
Variable* VariableSpace extern
Global array of Variables (exported)
Referenced by FindVariable(), NewVariable(), and variables_iterator_next().