/*
 generated by:
 tools::package_native_routine_registration_skeleton(dir = "~/Lab/github/polmineR.Rcpp", con = "~/Lab/github/polmineR.Rcpp/src/polmineR.Rcpp_init.c")
 see: https://stackoverflow.com/questions/42313373/r-cmd-check-note-found-no-calls-to-r-registerroutines-r-usedynamicsymbols
 cange in NAMESPACE: useDynLib(polmineR.Rcpp, .registration = TRUE)
*/

/*

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

 */
 
/* FIXME: 
   Check these declarations against the C/Fortran source code.
*/

/* .Call calls */

/*

extern SEXP _polmineR_Rcpp_attribute_size(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_cpos2id(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_cpos2lbound(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_cpos2rbound(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_cpos2str(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_cpos2struc(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_decode_s_attribute(SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_get_cbow_matrix(SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_get_count_vector(SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_get_region_matrix(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_id2cpos(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_id2freq(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_id2str(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_lexicon_size(SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_regex2id(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_regions_to_count_matrix(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_regions_to_ids(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_str2id(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_struc2cpos(SEXP, SEXP, SEXP, SEXP);
extern SEXP _polmineR_Rcpp_struc2str(SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_polmineR_Rcpp_attribute_size",          (DL_FUNC) &_polmineR_Rcpp_attribute_size,          4},
    {"_polmineR_Rcpp_cpos2id",                 (DL_FUNC) &_polmineR_Rcpp_cpos2id,                 4},
    {"_polmineR_Rcpp_cpos2lbound",             (DL_FUNC) &_polmineR_Rcpp_cpos2lbound,             4},
    {"_polmineR_Rcpp_cpos2rbound",             (DL_FUNC) &_polmineR_Rcpp_cpos2rbound,             4},
    {"_polmineR_Rcpp_cpos2str",                (DL_FUNC) &_polmineR_Rcpp_cpos2str,                4},
    {"_polmineR_Rcpp_cpos2struc",              (DL_FUNC) &_polmineR_Rcpp_cpos2struc,              4},
    {"_polmineR_Rcpp_decode_s_attribute",      (DL_FUNC) &_polmineR_Rcpp_decode_s_attribute,      3},
    {"_polmineR_Rcpp_get_cbow_matrix",         (DL_FUNC) &_polmineR_Rcpp_get_cbow_matrix,         5},
    {"_polmineR_Rcpp_get_count_vector",        (DL_FUNC) &_polmineR_Rcpp_get_count_vector,        3},
    {"_polmineR_Rcpp_get_region_matrix",       (DL_FUNC) &_polmineR_Rcpp_get_region_matrix,       4},
    {"_polmineR_Rcpp_id2cpos",                 (DL_FUNC) &_polmineR_Rcpp_id2cpos,                 4},
    {"_polmineR_Rcpp_id2freq",                 (DL_FUNC) &_polmineR_Rcpp_id2freq,                 4},
    {"_polmineR_Rcpp_id2str",                  (DL_FUNC) &_polmineR_Rcpp_id2str,                  4},
    {"_polmineR_Rcpp_lexicon_size",            (DL_FUNC) &_polmineR_Rcpp_lexicon_size,            3},
    {"_polmineR_Rcpp_regex2id",                (DL_FUNC) &_polmineR_Rcpp_regex2id,                4},
    {"_polmineR_Rcpp_regions_to_count_matrix", (DL_FUNC) &_polmineR_Rcpp_regions_to_count_matrix, 4},
    {"_polmineR_Rcpp_regions_to_ids",          (DL_FUNC) &_polmineR_Rcpp_regions_to_ids,          4},
    {"_polmineR_Rcpp_str2id",                  (DL_FUNC) &_polmineR_Rcpp_str2id,                  4},
    {"_polmineR_Rcpp_struc2cpos",              (DL_FUNC) &_polmineR_Rcpp_struc2cpos,              4},
    {"_polmineR_Rcpp_struc2str",               (DL_FUNC) &_polmineR_Rcpp_struc2str,               4},
    {NULL, NULL, 0}
};

void R_init_polmineR_Rcpp(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}


*/
