# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decode_s_attribute <- function(corpus, s_attribute, registry) {
    .Call(`_RcppCWB_decode_s_attribute`, corpus, s_attribute, registry)
}

get_count_vector <- function(corpus, p_attribute, registry) {
    .Call(`_RcppCWB_get_count_vector`, corpus, p_attribute, registry)
}

get_region_matrix <- function(corpus, s_attribute, strucs, registry) {
    .Call(`_RcppCWB_get_region_matrix`, corpus, s_attribute, strucs, registry)
}

get_cbow_matrix <- function(corpus, p_attribute, registry, matrix, window) {
    .Call(`_RcppCWB_get_cbow_matrix`, corpus, p_attribute, registry, matrix, window)
}

regions_to_ids <- function(corpus, p_attribute, registry, matrix) {
    .Call(`_RcppCWB_regions_to_ids`, corpus, p_attribute, registry, matrix)
}

regions_to_count_matrix <- function(corpus, p_attribute, registry, matrix) {
    .Call(`_RcppCWB_regions_to_count_matrix`, corpus, p_attribute, registry, matrix)
}

cwb_attribute_size <- function(corpus, attribute, attribute_type, registry) {
    .Call(`_RcppCWB_cwb_attribute_size`, corpus, attribute, attribute_type, registry)
}

cwb_lexicon_size <- function(corpus, p_attribute, registry) {
    .Call(`_RcppCWB_cwb_lexicon_size`, corpus, p_attribute, registry)
}

cwb_cpos2struc <- function(corpus, s_attribute, cpos, registry) {
    .Call(`_RcppCWB_cwb_cpos2struc`, corpus, s_attribute, cpos, registry)
}

cwb_cpos2str <- function(corpus, p_attribute, registry, cpos) {
    .Call(`_RcppCWB_cwb_cpos2str`, corpus, p_attribute, registry, cpos)
}

cwb_cpos2id <- function(corpus, p_attribute, registry, cpos) {
    .Call(`_RcppCWB_cwb_cpos2id`, corpus, p_attribute, registry, cpos)
}

cwb_struc2cpos <- function(corpus, s_attribute, registry, struc) {
    .Call(`_RcppCWB_cwb_struc2cpos`, corpus, s_attribute, registry, struc)
}

cwb_id2str <- function(corpus, p_attribute, registry, id) {
    .Call(`_RcppCWB_cwb_id2str`, corpus, p_attribute, registry, id)
}

cwb_struc2str <- function(corpus, s_attribute, struc, registry) {
    .Call(`_RcppCWB_cwb_struc2str`, corpus, s_attribute, struc, registry)
}

cwb_regex2id <- function(corpus, p_attribute, regex, registry) {
    .Call(`_RcppCWB_cwb_regex2id`, corpus, p_attribute, regex, registry)
}

cwb_str2id <- function(corpus, p_attribute, str, registry) {
    .Call(`_RcppCWB_cwb_str2id`, corpus, p_attribute, str, registry)
}

cwb_id2freq <- function(corpus, p_attribute, id, registry) {
    .Call(`_RcppCWB_cwb_id2freq`, corpus, p_attribute, id, registry)
}

cwb_id2cpos <- function(corpus, p_attribute, id, registry) {
    .Call(`_RcppCWB_cwb_id2cpos`, corpus, p_attribute, id, registry)
}

cwb_cpos2lbound <- function(corpus, s_attribute, cpos, registry) {
    .Call(`_RcppCWB_cwb_cpos2lbound`, corpus, s_attribute, cpos, registry)
}

cwb_cpos2rbound <- function(corpus, s_attribute, cpos, registry) {
    .Call(`_RcppCWB_cwb_cpos2rbound`, corpus, s_attribute, cpos, registry)
}

